Repository ihhub/fheroes2, pull requests merged in 2019-10, with the labels that each got.

#81 Remove duplicated header file inclusion
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/world.cpp
  src/fheroes2/monster/monster.cpp
Labels: enhancement

#83 Remove src/tools/palette_h2.h file
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/palette_h2.h
Labels: enhancement

#85 Sorted headers in alphabetic order in few files #82
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_bar.h
  src/fheroes2/army/army_troop.cpp
Labels: enhancement

#89 Sorting Headers in alphabetical order in src/fheroes2/objects
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/objcrck.cpp
  src/fheroes2/objects/objdirt.cpp
  src/fheroes2/objects/objdsrt.cpp
  src/fheroes2/objects/objgras.cpp
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/objects/objsnow.cpp
  src/fheroes2/objects/objswmp.cpp
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/objects/objxloc.cpp
  src/fheroes2/objects/trees.cpp
Labels: enhancement

#96 Modify Luck::String() and Luck::Description() functions to do not recreate objects for every call
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/kingdom/luck.h
Labels: enhancement

#100 Renamed 'Free Heroes II' to 'Free Heroes of Might and Magic II'
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/pocketpc/pocketpc_mainmenu.cpp
Labels: enhancement

#86 Remove all inline word usage
  editor/engine.cpp
  src/xmlccwrap/tinyxml.h
Labels: enhancement

#94 Sorted headers in alphabetic order
  src/fheroes2/army/army_troop.cpp
Labels: enhancement

#104 Added screenshots to readme
  README.md
  files/images/screenshots/screenshot_game1.png
  files/images/screenshots/screenshot_game2.png
Labels: documentation, enhancement

#105 Fix compilation warnings
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_list.h
Labels: enhancement

#113 Fix incorrect image for Captains Quarters (#109)
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, gui

#119 Changes to building dialog (#110)
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, gui

#137 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#139 Do not populate GitHub releases with new versions for Travis-CI
  .travis.yml
Labels: Travis-CI, script

#140 Travis deployment fix
  .travis.yml
Labels: Travis-CI, script

#141 AppVeyor deployment fix
  appveyor.yml
Labels: AppVeyor, script

#136 Required buildings are listed in separate lines
  src/fheroes2/castle/buildinginfo.cpp
Labels: enhancement, gui

#125 Disabled Continue Movement button
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: bug, gui

#135 Display error window if no original data detected
  src/fheroes2/agg/agg.cpp
Labels: enhancement, gui

#118 Change LastLoseHero structure
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: enhancement

#142 Fixed redrawing grid during battle
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, gui

#148 Change AI state from empty to simple in makefile
  Makefile
Labels: enhancement

#157 Add code style check for all pull requests
  .clang-format
  .travis.yml
  script/tools/check_code_format.sh
Labels: enhancement

#156 Incorrect message for Shipyard by right click
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, gui

#138 Unchecked array access leading to potential corruption
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug

#159 Hide dismiss button
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, gui

#163 fix: increase view distance for observation tower
  src/fheroes2/game/game_static.cpp
Labels: bug, gui

#164 fix: use euclidean distance calculation for map reveal
  src/fheroes2/maps/maps.cpp
Labels: bug, gui

#167 Fix font color for creature name
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, gui

#168 Fix application execution after unpacking demo
  script/demo/demo_linux.sh
Labels: Linux, bug

#165 Disable cast a spell for castles
  src/fheroes2/gui/interface_buttons.cpp
Labels: bug, gui

#169 Fix shadow for hexes in the battle
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#174 Try to fix Travis-CI build for MacOS
  .travis.yml
Labels: Travis-CI

#170 Remove third component of app's version
  src/dist/Makefile
  src/fheroes2/system/settings.cpp
Labels: enhancement

#172 Fix interface buttons in hero dialog
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, gui

#155 Add missing text in battle options dialog
  fheroes2.key
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/gui/button.cpp
  src/fheroes2/gui/button.h
  src/fheroes2/gui/text.cpp
Labels: bug, gui

#162 Change battle cells net
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#197 make installation scripts readable at completion
  script/demo/demo.bat
  script/windows/install_packages.bat
Labels: AppVeyor, script

#205 Fix save loading
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug

#206 Make found resources message amount show below resource icon
  src/fheroes2/gui/interface_status.cpp
Labels: bug, gui

#195 Remove Dismiss button for unhired hero in town
  src/fheroes2/gui/button.cpp
  src/fheroes2/gui/button.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, gui

#212 Tavern info updated
  src/fheroes2/kingdom/world_loadmap.cpp
Labels: enhancement

#196 Added setup instructions for win system in README.md
  README.md
  script/demo/demo.bat
  script/windows/install_packages.bat
Labels: enhancement, script

#213 Updating .gitignore file
  .gitignore
Labels: Windows

#207 Fix #158 shadowing of variables
  src/fheroes2/agg/agg.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/resource/artifact.cpp
Labels: enhancement
