Repository ihhub/fheroes2, pull requests merged in 2019-11, with the labels that each got.

#198 SDL2 windows build
  .gitignore
  VisualStudio/Debug.props
  VisualStudio/Release.props
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  VisualStudio/common.props
  appveyor.yml
  fheroes2.vcxproj
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/system.cpp
Labels: AppVeyor, Windows

#222 Add configuration file into deployment packages
  .travis.yml
  appveyor.yml
Labels: AppVeyor, Travis-CI, deployment

#183 Split settings labels above and below icon
  src/fheroes2/dialog/dialog_system.cpp
Labels: enhancement, gui

#225 Change logic for AI castle development
  src/fheroes2/ai/simple/ai_castle.cpp
  src/fheroes2/castle/castle.cpp
Labels: AI, enhancement

#230 Fix shadows in SDL 2
  src/engine/surface.cpp
Labels: bug, gui

#229 Do not put all scripts into deployed package
  .travis.yml
Labels: Travis-CI, deployment

#228 No sound win sdl1
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  VisualStudio/common.props
  src/fheroes2/dialog/dialog_system.cpp
Labels: SDL 1, sound

#231 Save configuration file is none is present
  src/fheroes2/game/fheroes2.cpp
Labels: enhancement

#233 Add monster information dialog by right mouse click
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: enhancement, gui

#214 Recalculate hero path each time player chooses the hero
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_icons.cpp
Labels: enhancement, logic

#241 Fix transparency for Spellbook
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/sprite.cpp
Labels: bug, gui

#240 Fix window position in SDL 2 for Windows
  src/engine/display.cpp
Labels: bug, gui

#244 AI speed, Hero speed and Battle speed must take values from 1 to 10
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/system/settings.cpp
Labels: logic

#247 Fix credits
  src/fheroes2/game/game.cpp
Labels: enhancement

#246 Make "Buy from well" as default option
  src/fheroes2/system/settings.cpp
Labels: enhancement
