Repository ihhub/fheroes2, pull requests merged in 2019-12, with the labels that each got.

#242 Add WITH_DEBUG macro for debug builds on VS
  VisualStudio/Debug.props
Labels: Windows

#258 Fix compilation for missing zlib library
  VisualStudio/packages/zlib1.2.11.zip
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
Labels: AppVeyor, Windows, bug

#259 Fix dwelling info dialog position
  src/engine/sprites.cpp
  src/engine/sprites.h
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: bug, gui

#263 Fix shadowing in hero's option dialog
  src/fheroes2/battle/battle_dialogs.cpp
Labels: SDL 2, bug, gui

#260 Fix missing window title after starting new game
  src/engine/display.cpp
Labels: bug, gui

#269 Fix resource displaying popup
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, gui

#270 Fix battle option missing titles
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, gui

#272 Fix hero path cursor display
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#280 Fix crystal resource position
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: bug, gui

#281 Add initial campaign button
  src/fheroes2/game/game_newgame.cpp
Labels: campaign, gui

#282 Make Roland campaign UI appear for New Campaign option
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/interface_border.cpp
Labels: campaign, enhancement, gui

#283 Rename demo.bat to demo_windows.bat to be more explicit for users
  README.md
  appveyor.yml
  script/demo/demo_windows.bat
Labels: Windows, script

#284 Warning fixes
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/system/bitmodes.h
Labels: enhancement

#285 Fix campaign crash on OKAY button press
  src/fheroes2/game/game_newgame.cpp
Labels: bug, campaign
