Repository ihhub/fheroes2, pull requests merged in 2020-05, with the labels that each got.

#428 Add quit dialog popup window and change File Options dialog behavior
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: enhancement, gui

#447 Fix a crash for hot seat game start
  src/fheroes2/game/game_startgame.cpp
Labels: crash

#449 Update bin2txt tool
  src/tools/bin2txt.cpp
Labels: enhancement, gui

#446 Flying movement animation is shifted during battle
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#456 Make Army order window during battle optional
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, gui

#430 *nix case insensitive file access
  src/engine/dir.cpp
  src/engine/system.cpp
  src/engine/system.h
Labels: Linux, MacOS, logic

#465 Fix morale and luck events
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#464 Fix unit damage formula
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/game/game_static.cpp
Labels: enhancement, logic

#440 Battle animation rework: using AGG/BIN files to fix wrong frames
  fheroes2.vcxproj
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/monster/monster_info.h
Labels: enhancement, gui

#474 Update well animation based on latest BIN file changes
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/monster/monster_info.h
Labels: enhancement, gui

#476 Add movement animation in Well
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: enhancement, gui

#478 Add monster animation in army's info dialog
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: enhancement, gui

#479 Correct hero position in battle
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#480 Fix hero animation in battle
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#472 GUI: Fix value input selectors
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, gui

#489 Fix surrender action during battle
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, logic

#473 Battle logic: fix Genie special ability
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#490 Set a correct position for buttons in Configuration dialog
  src/fheroes2/dialog/dialog_settings.cpp
Labels: bug, gui

#491 Fix EXIT button position in casle options
  src/fheroes2/castle/castle_town.cpp
Labels: bug, gui

#493 Fix Phoenixes naming
  src/fheroes2/monster/monster.cpp
Labels: bug

#477 Not destroyed castle gate remains opened after a troop from a castle crossed the bridge during battle
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#492 Anim rework: fix flying animation using new structures
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/monster/monster_info.h
Labels: bug, enhancement, gui

#502 Music: Loop battle music and switch to main tune when loading
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/game/game_loadgame.cpp
Labels: bug, sound

#513 Fix Golem and Swordsman animation shift
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/monster/monster.cpp
Labels: bug, gui

#514 Draw main menu as a background for High Score window
  src/fheroes2/game/game_highscores.cpp
Labels: enhancement, gui

#498 Unit animation is freezed during its turn
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
Labels: bug, gui

#521 Music: xmi2mid rework
  src/engine/xmi2mid.cpp
Labels: enhancement, sound

#499 AI rework: prepare for the future changes and pick AI at runtime
  Makefile
  fheroes2.vcxproj
  src/dist/Makefile
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_action.cpp
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/empty/ai_empty.cpp
  src/fheroes2/ai/empty/ai_empty.h
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/simple/ai_heroes.cpp
  src/fheroes2/ai/simple/ai_kingdom.cpp
  src/fheroes2/ai/simple/ai_simple.cpp
  src/fheroes2/ai/simple/ai_simple.h
  src/fheroes2/ai/simple/ai_simple_battle.cpp
  src/fheroes2/ai/simple/ai_simple_castle.cpp
  src/fheroes2/ai/simple/ai_simple_heroes.cpp
  src/fheroes2/ai/simple/ai_simple_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/route_pathfind.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: AI, enhancement

#524 Fix negative resources in kingdom posession
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: bug, logic

#527 Fix shifted monster position in recruit window
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: bug, gui

#529 Fix alignment of text in monster info dialog
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, gui

#530 Fix a crash for unhired hero
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: crash, gui

#419 Add optional aspect ratio correction in fullscreen mode.
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, gui

#539 Fix memory leak for arena
  src/fheroes2/battle/battle_arena.cpp
Labels: bug

#540 Fix spell sorting crash and mage guild positioning
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: bug, gui

#547 Fix display info of resources with scouting
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, gui, logic

#548 Fix hero movement at low speeds
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
Labels: bug, gui

#558 Ignore expansion and visual studio files
  .gitignore
Labels: Windows

#431 Add support for swapping palettes
  fheroes2.vcxproj
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/pal.cpp
  src/fheroes2/agg/pal.h
  src/fheroes2/agg/sprite.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/tools/palette_h2.h
Labels: enhancement, gui

#549 Fix hero, castle and status army info
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/gui/interface_status.cpp
Labels: enhancement, gui

#563 Fix incorrect map object naming
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: bug, gui

#523 Music: switch music type in settings
  fheroes2.cfg
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/xmi.cpp
  src/fheroes2/agg/xmi.h
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/tools/cdinfo.py
Labels: enhancement, sound

#565 Fix minimap colors
  src/fheroes2/gui/interface_radar.cpp
Labels: enhancement, gui

#564 Set correct position of monster in dwelling info
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: enhancement, gui

#559 Idle animation update: correct speed and frequency
  VisualStudio/Release.props
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
Labels: enhancement, gui, logic

#567 Fix bugs and warnings caught by lgtm
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/system/settings.cpp
  src/xmlccwrap/tinyxml.h
  src/xmlccwrap/tinyxmlparser.cpp
Labels: bug

#520 Add GitHub Actions builds
  .github/workflows/github_actions.yml
  appveyor.yml
  script/tools/check_code_format.sh
Labels: script

#568 Remove clang-format from Travis-CI
  .travis.yml
Labels: Travis-CI, script

#569 Fix cursor behavior beyond world edge
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps.cpp
Labels: bug, gui

#570 Fix speel icon size and position for monster's info
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, gui

#571 Fix Mass Cure spell icon
  src/fheroes2/spell/spell.cpp
Labels: bug, gui

#572 Fix incorrect mixed spells for hero's book
  src/fheroes2/spell/spell_book.cpp
Labels: bug, gui

#573 Attack a monster after landing from a ship
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#574 Fix invisible hero's path after Dimension Door spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, gui

#576 Limit Dimension Door spell range
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/game/game_interface.cpp
Labels: enhancement, gui

#575 Add fading animation after battle
  src/engine/display.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#577 Fixed a monster attrack an the start of a new game
  src/fheroes2/system/settings.cpp
Labels: bug, logic

#578 Show a message if not enough points for digging
  src/fheroes2/gui/interface_events.cpp
Labels: bug, gui

#579 Fix inability to move artifacts
  src/fheroes2/resource/artifact.cpp
Labels: bug, gui, logic

#580 Use shadowing for end movement cell
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#557 Movement interruption by left click
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
Labels: enhancement, gui

#582 Do not move a hero over a portal above another hero
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#581 Remove tiny ship icon
  src/fheroes2/heroes/heroes.cpp
Labels: enhancement, gui

#583 Do not auto disable dimension door spell
  src/fheroes2/game/game_interface.cpp
Labels: bug, logic

#586 Show reflected monster animation in a dialog
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, enhancement, gui

#589 Calculate properly quick info window position
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: enhancement, gui

#591 Fix an ability to continue movement after Town portal spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, gui, logic

#594 Fix building a new dwelling animation
  src/fheroes2/castle/castle_building.cpp
Labels: bug, gui

#595 Remove red cross over town's icon
  src/fheroes2/gui/interface_icons.cpp
Labels: enhancement, gui

#596 Fix incorrect position of a stunned monster
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#597 Play animation of treasure chest after collection
  src/fheroes2/heroes/heroes_action.cpp
Labels: enhancement, gui, logic

#598 Add shadows to most of dialogs
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: enhancement, gui

#599 Fix Haunt spell incorrect behavior
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, gui, logic

#601 Fix incremental growth of shadows of dialogs
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: bug, gui

#602 Fix gradual shadowing in SDL2
  src/engine/surface.cpp
Labels: SDL 2, bug, gui

#603 Do not shift window while loading a map for SDL 2
  src/engine/display.cpp
Labels: SDL 2, bug, gui

#604 Give a control to an opponent over a hypnotized monster
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic

#541 Animations: correct attacks and timing
  src/engine/rect.h
  src/engine/types.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
Labels: enhancement, gui

#607 Fix idling condition check
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#609 Show disable Dismiss button for a hero in a castle
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, gui

#611 Battle speed adjustment formula
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/system/gamedefs.h
Labels: enhancement, gui

#626 Fix 0 monster count for Visions spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, logic

#624 Fix Identify Hero spell behavior
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, gui, logic

#629 Fix the logic for Summon Boat spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, logic

#628 Animation: Tower and Magic Arrow
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/game/game.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: enhancement, gui

#631 Fix Archmage dispel post attack effect
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, gui

#632 Fix monster count window position during battle
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#617 Fix many warnings
  src/fheroes2/gui/interface_list.h
Labels: enhancement

#639 Fix Lich animation
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic

#641 Fix multiple spell frame jumps
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#566 Try SonarCloud integration
  .travis.yml
  appveyor.yml
  sonar-project.properties
Labels: script

#646 Speed up Travis-CI
  .travis.yml
Labels: Travis-CI, script

#648 Remove an ability to add an artifact for a hero
  src/fheroes2/resource/artifact.cpp
Labels: bug, logic

#652 Move static analysis job to GitHub Actions
  .github/workflows/clang_format.yml
  .github/workflows/static_analysis.yml
  .travis.yml
Labels: GitHub Actions, Travis-CI, enhancement

#650 Fix hero position in battle
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#651 Play resource collection and sound after reading a dialog
  src/fheroes2/heroes/heroes_action.cpp
Labels: enhancement, gui, sound

#655 Fix inability to cast another spell upon cancellation teleport spell
  src/fheroes2/battle/battle_interface.cpp
Labels: gui, logic

#656 Fix hero's flag position in battle
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: enhancement, gui

#630 Speed up rendering
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/sprite.cpp
  src/fheroes2/agg/sprite.h
Labels: enhancement

#658 Fix few bugs found by SonarCloud
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/pocketpc/pocketpc_selectscenario.cpp
Labels: bug

#663 Fix hero's offset in battle for high resolutions
  src/fheroes2/agg/agg.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, gui

#664 Add min and max buttons for troop separation dialog
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: enhancement, gui

#666 Fix hot seat no info situation
  src/fheroes2/game/game_startgame.cpp
Labels: bug, gui, logic

#668 Fix incorrect dialog display for non-hot seat mode
  src/fheroes2/game/game_startgame.cpp
Labels: bug, gui

#667 Fix hero fading animation
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, gui

#669 Set correct post battle video sequence
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/game/game_delays.cpp
Labels: enhancement, gui

#672 Ignore bad spell status for Archmage attack
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic

#673 Fix application exiting behavior
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_icons.cpp
Labels: bug

#674 Fix defence formula for monster during battle
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#675 Sort spell icons by duration in monster statistics window
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, gui

#676 Fix teleport delay in animation
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#678 Fix blurred buttons in Adventure Panel
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/gui/interface_cpanel.cpp
Labels: bug, gui

#679 Add a monster location to path route
  src/fheroes2/heroes/route.cpp
Labels: bug, gui, logic

#680 Add bad luck animation
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#681 Update sounds and music upon teleport spell usage
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, sound
