Repository ihhub/fheroes2, pull requests merged in 2020-10, with the labels that each got.

#1854 Replace Simple AI and bugfixes for the new one
  fheroes2.vcxproj
  src/dist/Makefile
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/empty/ai_empty.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/ai/simple/ai_simple.cpp
  src/fheroes2/ai/simple/ai_simple.h
  src/fheroes2/ai/simple/ai_simple_battle.cpp
  src/fheroes2/ai/simple/ai_simple_castle.cpp
  src/fheroes2/ai/simple/ai_simple_heroes.cpp
  src/fheroes2/ai/simple/ai_simple_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: AI, enhancement

#1855 Strategic AI: build up castle defenses
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, enhancement

#1857 Fix second attack for blinded creatures
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic

#1856 Don't show journal scrollbar when it's not open
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#1862 Fix price of loyalty map objects
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: Regression, ui

#1863 Fix missing dialog box in some rare cases
  src/fheroes2/dialog/dialog_box.cpp
Labels: bug, ui

#1865 Fix monthly monster placement
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, ui

#1868 Fix monster shadows
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, ui

#1867 Fix tents/barriers from Price of Loyalty
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
Labels: bug, logic, ui

#1873 Fix price of loyalty artifact selection
  src/fheroes2/resource/artifact.cpp
Labels: logic

#1874 Add missing const modifier to lambda function
  src/fheroes2/world/world_regions.cpp
Labels: enhancement

#1894 Fix heroes movement animation
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
Labels: enhancement, ui

#1879 Kingdom Overview screen, Towns/Castles Overview screen, wrong window displayed when right-clicking on creatures
  src/fheroes2/castle/buildinginfo.cpp
Labels: Hacktoberfest, bug, ui

#1872 Bring neutral armies in line with original logic
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: enhancement, logic

#1881 Strategic AI: better heuristics and boat handling
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: AI, enhancement

#1895 Fix event cursor type
  src/fheroes2/maps/mp2.cpp
Labels: bug, ui

#1896 Fix hero's movement speed
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, ui

#1899 Make boarding/off-boarding boat animation dependent
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
Labels: enhancement, ui

#1900 Center Adventure Options window
  src/fheroes2/dialog/dialog_adventure.cpp
Labels: Hacktoberfest, bug, ui

#1904 Fix monster dwelling unit count
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: Regression, logic

#1905 Fix the clipped boat sprite
  src/fheroes2/gui/interface_gamearea.cpp
Labels: Regression, ui

#1901 Modify messages for splitting army window - fixed issue #1887
  files/lang/cs.po
  files/lang/es.po
  files/lang/fheroes2.pot
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: Hacktoberfest, bug, ui

#1898 Fix some text issues
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/resource/artifact.cpp
Labels: Hacktoberfest, bug, enhancement, ui

#1902 I1858 fix CanMove method
  src/fheroes2/heroes/heroes.cpp
Labels: Hacktoberfest, bug, logic

#1906 Source code cleanup
  src/engine/image.cpp
  src/engine/rect.cpp
  src/engine/rect.h
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/engine/surface.cpp
  src/engine/surface.h
  src/engine/thread.cpp
  src/engine/thread.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/ai/ai.h
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/splitter.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world_regions.cpp
Labels: enhancement

#1814 Delete SDL logo related information
  image/sdl_logo.png
  src/fheroes2/game/fheroes2.cpp
Labels: enhancement

#1915 Battle AI: fix target adjacency
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
Labels: AI, bug, logic

#1916 Fix multiple compilation warnings
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement

#1914 Reset pathfinder cache on a map change
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#1907 added how to install SDL on Arch based Linux distros
  README.md
Labels: Hacktoberfest, Linux

#1917 Remove unused test mode in game
  VisualStudio/common.props
  fheroes2.vcxproj
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/test/test.cpp
  src/fheroes2/test/test.h
  src/fheroes2/test/test_monstersprite.cpp
Labels: Hacktoberfest, enhancement

#1903 FreeBSD: iconv build fixes
  src/Makefile.bsd
  src/engine/tools.cpp
Labels: Hacktoberfest, Linux, bug, script

#1920 Fix time loss conditions in Info window
  src/fheroes2/game/game_over.cpp
Labels: bug, ui

#1921 Remove "allow pickup objects for patrol"
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: enhancement

#1923 Usual code cleanup
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/pocketpc/pocketpc_dialog.cpp
Labels: enhancement

#1930 Source code cleanup
  src/engine/image.h
  src/engine/rect.cpp
  src/engine/rect.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_resourceinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_skillinfo.cpp
  src/fheroes2/dialog/dialog_spellinfo.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/splitter.cpp
  src/fheroes2/gui/splitter.h
  src/fheroes2/gui/statusbar.cpp
  src/fheroes2/gui/statusbar.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/system/settings.cpp
Labels: enhancement

#1931 Code cleanup
  src/engine/math_base.h
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: enhancement

#1934 fix -Wreorder warns
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/settings.cpp
Labels: Hacktoberfest, enhancement

#1937 Another compilation warning reduction
  src/fheroes2/agg/agg.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/system/players.cpp
Labels: enhancement

#1938 Fix many compilation warnings
  src/engine/localevent.cpp
  src/engine/rect.cpp
  src/engine/rect.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/heroes/direction.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/pocketpc/pocketpc_dialog.cpp
Labels: enhancement

#1943 Add fading animation for defeated AI hero
  src/fheroes2/ai/ai_hero_action.cpp
Labels: enhancement, ui

#1945 Remove scrollbars from interface in battle only mode
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, ui

#1947 Fix system options dialog
  src/fheroes2/dialog/dialog_system.cpp
Labels: enhancement, ui

#1949 Honour player count for Hot Seat mode
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/player_info.h
Labels: bug, logic

#1953 Fix incorrect resurrected troops after battle
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#1958 Allow to cast a spell with no move points
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, logic

#1957 Show skip turn message during AI turns
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: bug, logic

#1959 Limit text within given input box
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
Labels: bug, ui

#1960 Fix visibility of AI hero moving close to fog
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#1961 Fix multiple compilation warnings
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/splitter.cpp
  src/fheroes2/gui/splitter.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement

#1962 Fix Theves Guild background
  src/fheroes2/dialog/dialog_thievesguild.cpp
Labels: bug, ui

#1963 Combat screen, logs list, quantity text "one" instead of "1"
  src/fheroes2/battle/battle_interface.cpp
Labels: Hacktoberfest, enhancement, ui

#1952 Battle doesn't stop, after AI kills the last creature
  src/fheroes2/battle/battle_arena.cpp
Labels: Hacktoberfest, bug, logic

#1935 When retreating, give the hero its default army instead of 1 T1 unit
  src/fheroes2/heroes/heroes.cpp
Labels: Hacktoberfest, bug, logic

#1966 Use 1 instead of 'one' in battle log
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, ui

#1968 Fix income window drawings
  src/fheroes2/resource/resource.cpp
Labels: bug, ui

#1978 Fix multiple compilation warnings
  src/engine/dir.cpp
  src/engine/rand.cpp
  src/engine/system.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_box.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_resourceinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_skillinfo.cpp
  src/fheroes2/dialog/dialog_spellinfo.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/payment.h
  src/fheroes2/kingdom/profit.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/resource/artifact.cpp
Labels: enhancement

#1972 Play flotsam disappearing sound after closing the window
  src/fheroes2/heroes/heroes_action.cpp
Labels: Hacktoberfest, bug, hacktoberfest-accepted, sound

#1993 Code cleanup
  Makefile
  README.md
  src/engine/font.cpp
  src/engine/font.h
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_cpanel.h
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/maps/maps_actions.cpp
  src/fheroes2/maps/maps_actions.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: enhancement

#1982 Set starting XP for starting heroes
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, logic

#2000 replace "Ship Wreck" with "Shipwreck"
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/mp2.cpp
Labels: Hacktoberfest, bug, ui

#2001 Battle AI: make it more agressive when dealing with archers
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: AI, enhancement

#2011 1970 - Sea Bottle - Getting bottle message in the same manner as Acti…
  src/fheroes2/heroes/heroes_action.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, ui

#2002 Fix the artifact spell damage modifiers
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/resource/artifact.cpp
Labels: bug, logic

#2005 Code cleanup
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#2017 Strategic AI: fix hero paths
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: AI, Regression, bug, enhancement

#2003 The growth of ghosts after battle
  src/fheroes2/battle/battle_army.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, logic, question

#2015 Fix non-necro undead units decreasing morale in an all-undead army
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#2018 Revert back some cleanup changes
  src/engine/thread.cpp
  src/engine/thread.h
Labels: Regression

#2020 Remove mud pool from obstacle list
  src/fheroes2/battle/battle_board.cpp
Labels: ui

#2019 Check armies for validity before starting the battle
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#2033 Use original difficulty bonuses for the game
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps.cpp
Labels: enhancement, logic

#2032 Fix potential infinite loop when AI is stuck on teleporters
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, logic

#2022 All parts of wide objects have to be flagged as visited
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#2030 Save boat direction when disembarking
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
Labels: bug, ui

#2031 Disable spell animation after mine was cleared
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic, ui

#1991 some improvements for make process
  Makefile
  fheroes2.vcxproj
  src/Makefile
  src/dist/Makefile
  src/engine/image.cpp
  src/engine/pal.cpp
  src/engine/palette_h2.h
  src/engine/screen.cpp
  src/fheroes2/agg/agg.cpp
  src/thirdparty/tinyxml/Makefile
  src/thirdparty/tinyxml/tinystr.cpp
  src/thirdparty/tinyxml/tinystr.h
  src/thirdparty/tinyxml/tinyxml.cpp
  src/thirdparty/tinyxml/tinyxml.h
  src/thirdparty/tinyxml/tinyxmlerror.cpp
  src/thirdparty/tinyxml/tinyxmlparser.cpp
Labels: Hacktoberfest, Linux, enhancement

#2021 Speed up map processing functions
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/world/world.cpp
Labels: optimisation

#2035 Make autosave with capital letters
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, ui

#2025 Hero AI: Support patrol mode set in scenario
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, bug, logic

#2036 Change main menu popup window descriptions
  src/fheroes2/dialog/dialog_file.cpp
Labels: enhancement, ui

#2037 Make small code optimizations
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: enhancement

#2038 Make small speedups for drawings
  src/fheroes2/agg/agg.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: enhancement

#2039 Fix boat sprite on older saves
  src/fheroes2/maps/maps_tiles.cpp
Labels: Regression, ui

#2041 Make some performance improvements
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
Labels: enhancement

#2034 Cache hero bonus when calculating army strength
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/world/world_pathfinding.h
Labels: optimisation

#2043 Adjust post battle shadowing
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, ui

#2044 Fix battle option text overlapping
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#2045 Adjust few elements in resolution window
  src/fheroes2/dialog/dialog_resolution.cpp
Labels: enhancement, ui

#2040 Use map region tools in AI code
  fheroes2.vcxproj
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_regions.cpp
  src/fheroes2/world/world_regions.h
Labels: AI, enhancement

#2053 Hero AI: value objects on the way to target
  src/engine/pathfinding.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: AI, enhancement

#2057 Fix OK button in joining army window
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, logic, ui

#2042 Give every magic guild a guaranteed damage and non-damage spell
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/spell/spell_storage.cpp
  src/fheroes2/spell/spell_storage.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, logic

#2058 Fix Knowledge message in arena
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/gui/text.cpp
Labels: bug, ui

#2066 Always show building requirements even if the building is already built
  src/fheroes2/castle/buildinginfo.cpp
Labels: Hacktoberfest, logic, ui

#2063 Spelling in castle dialog
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
Labels: Hacktoberfest, enhancement, ui

#2067 Add game resolution popup window
  src/fheroes2/game/game_mainmenu.cpp
Labels: enhancement, ui

#2065 Change Hut of the Magi behavior
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, ui

#2062 fix(world): lighthouse doesn't reveal additional squares
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_static.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/world/world.cpp
Labels: Hacktoberfest, bug, hacktoberfest-accepted, logic

#2061 Use hero spell power when applying Earthquake
  .gitignore
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, logic

#2064 Fix redraw order for unit count
  src/fheroes2/battle/battle_interface.cpp
Labels: Hacktoberfest, bug, ui

#2068 Add after play animation
  src/fheroes2/game/game_over.cpp
Labels: enhancement, ui

#2069 Add an ability to save images
  fheroes2.vcxproj
  src/engine/image_tool.cpp
  src/engine/image_tool.h
Labels: enhancement, ui

#2074 Fix adjacent monsters when removing one
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#2077 Fix troop counter window position
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2078 Fix boat animation and castle building rendering
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
Labels: bug, ui

#2080 Fix town population status text position
  src/fheroes2/castle/castle_well.cpp
Labels: enhancement, ui

#2081 Fix Hero's portrait in hiring window
  src/fheroes2/castle/castle_town.cpp
Labels: bug, ui

#2079 Fix a crash while loading another second map of the same size
  src/fheroes2/world/world_regions.cpp
Labels: bug, logic

#2082 Change Pyramid Bad Luck message
  src/fheroes2/heroes/heroes.cpp
Labels: enhancement, ui

#2083 Fix Hero meeting screen title position
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: enhancement, ui

#2084 Fix Hero screen status bar message position
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, ui

#2085 Give at least 1 skeleton via necromancy after victory
  src/fheroes2/battle/battle_main.cpp
Labels: Hacktoberfest, enhancement, logic

#2086 Fix pass image position on the world map
  src/fheroes2/gui/interface_gamearea.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, ui

#2088 Speed up drawings for World Map
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/maps/maps_tiles.cpp
Labels: enhancement, ui

#2089 Small optimizations by caching some data
  src/fheroes2/agg/agg.cpp
  src/fheroes2/gui/interface_gamearea.cpp
Labels: enhancement, ui

#2087 Fix boat and hero position
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, ui

#2099 Fix lighthouse missing movement bonus
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/world/world.cpp
Labels: bug, logic

#2092 Army merge logic improvement
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, enhancement, logic

#2103 Fix battle only mode
  src/fheroes2/battle/battle_only.cpp
Labels: bug

#2104 Fix mine guardians sprites
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/mp2.cpp
Labels: bug, ui

#2117 MacOS GitHub Actions fix for PRs
  .github/workflows/osx_pull_request.yml
  .github/workflows/osx_release.yml
Labels: bug, script

#2116 Code speedup and Blit function correction
  src/engine/image.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: enhancement, logic, ui

#2113 Fixes for MinGW Build
  src/Makefile.mingw
  src/engine/tools.cpp
Labels: Hacktoberfest, Regression, hacktoberfest-accepted

#2102 Show boat froth sprite when stationary
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, ui

#2096 Battle AI: teach units to block enemy archers
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
Labels: AI, enhancement

#1929 RPM Linux Distros
  README.md
  script/linux/SDL_mixer.ymp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#2107 1882 dialog alignment
  src/fheroes2/dialog/dialog_box.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, ui

#2112 Do not show teleport animation in some AI cases
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, enhancement, logic

#2115 Fix castle defense trigger condition
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, bug

#2114 AI: apply logarithmic growth to distance scaling
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, enhancement

#2124 Add road connection drawings for Barbarian castle
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
Labels: enhancement, ui

#2108 Strategic AI: cooperating heroes and improved estimates
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/castle/mageguild.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: AI, enhancement

#2131 Fix boat summoning animation
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: Regression, ui

#2106 Troops assigned to a slot of the same type which would result in an e…
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, logic

#2134 Fix mage guild dialog message
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
Labels: bug, ui

#2136 Fix Cavalry sprite
  src/fheroes2/agg/agg.cpp
Labels: enhancement, ui

#2132 2101 upgrading troops
  src/fheroes2/heroes/heroes_action.cpp
Labels: Hacktoberfest, bug, ui

#2127 Play sound on shipwreck pickup
  src/fheroes2/heroes/heroes_action.cpp
Labels: Hacktoberfest, enhancement, sound

#2139 Speed up video loading
  src/engine/smk_decoder.cpp
  src/fheroes2/game/game_video.cpp
Labels: enhancement, ui

#2142 Fix few castle icons
  src/fheroes2/agg/agg.cpp
Labels: enhancement, ui

#2143 Fix Monster Info dialog in evil interface
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, ui
