Repository ihhub/fheroes2, pull requests merged in 2020-11, with the labels that each got.

#2105 A creature blinded by Unicorn, with triggered moral is still able to attack
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: Hacktoberfest, bug, logic

#2110 One rumor per week
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: Hacktoberfest, logic

#2145 Fix glitched flying animation when unit has to turn to attack
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2140 Update Town Portal dialog
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes_spell.cpp
Labels: enhancement, ui

#2148 2130 Fix so that boarding a boat does not change the direction of the…
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: enhancement, logic

#2160 fix building with external tinyxml
  src/Makefile
Labels: bug

#2146 Fix slowed flying creature movemnt
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic, ui

#2161 Improvements for castle monster recruitment
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
Labels: enhancement, logic

#2155 Strategic AI: general improvements
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_regions.cpp
  src/fheroes2/world/world_regions.h
Labels: AI, enhancement

#2166 Fix class inheritance warnings
  src/engine/pathfinding.h
  src/fheroes2/world/world_pathfinding.h
Labels: enhancement

#2165 remove obsolete __GNUC__ checks
  src/fheroes2/objects/objdsrt.cpp
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/objects/objwatr.cpp
  src/fheroes2/objects/objxloc.cpp
Labels: Linux, enhancement

#2176 Fix missing spell point digits
  src/fheroes2/spell/spell_book.cpp
Labels: Regression, bug

#2177 Fix Sorceress castle background image
  src/fheroes2/agg/agg.cpp
Labels: enhancement, ui

#2178 fix changing boat direction by AI at boarding
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, ui

#2182 Fix enemy army threat check
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, Regression

#2183 Fix normal moral icon
  src/fheroes2/agg/agg.cpp
Labels: enhancement, ui

#2150 Fix portraits/hero information display in battle only mode
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#2123 2070 scenario selection
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: Hacktoberfest, bug, logic

#2194 Show hero's name in magic book related windows
  src/engine/pal.cpp
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: enhancement, ui

#2209 Update hero availability pool after hero purchase
  src/fheroes2/castle/castle.cpp
Labels: bug, logic

#2206 Fix map loading typo
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: enhancement, ui

#2203 #1084 Upgrade SDL2 to 2.0.12 for Windows platform
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
Labels: enhancement

#2210 Fix drawings for meeting hero dialog
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#2215 Fix battle false hex shadow
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2214 Add a title for joining army dialog
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, ui

#2213 Fix primary skill frame color in hero meering dialog
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: enhancement, ui

#2218 Change map size popup window text
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: enhancement, ui

#2217 Place a hero into castle at the start of game
  src/fheroes2/kingdom/kingdom.cpp
Labels: enhancement, logic

#2220 Assemble Battle Garb of Anduran artifact for hero meeting
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, logic

#2221 Fix Alchemist Tower artifact manipulation logic
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#2222 Artesian spring logic
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, logic

#2224 Fix spell order in magic book
  src/fheroes2/spell/spell_book.cpp
Labels: bug, ui

#2225 Increase Meteor Shower spell animation
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: enhancement, ui

#2226 Remove last occurence of std::mem_fun_ref
  src/engine/audio_mixer.cpp
Labels: enhancement

#2228 Remove "pocketpc: low memory" option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement

#2229 Remove "world: no in-built requirements or guardians for placed artif…
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world_loadmap.cpp
Labels: enhancement

#2223 fix next hero focusing the first hero if used when the focus is on a castle
  src/fheroes2/gui/interface_events.cpp
Labels: bug, logic

#2233 Crossing barrier (#2232)
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic, ui

#2239 fix stack overflow when using armageddon spell
  src/fheroes2/battle/battle_interface.cpp
Labels: crash

#2242 Don't show army formation with no captain
  src/fheroes2/castle/castle_town.cpp
Labels: bug, ui

#2227 Draw boat shadow (#1290)
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: enhancement, ui

#2230 Reset buttons when cursor move out (#387)
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_buttons.h
Labels: bug, ui

#2231 Mine info dialog near hero (#2170)
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#2208 Correctly reduce hero army after whirlpool (#1054)
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#1880 Add captain portraits in Kingdom Overview
  src/fheroes2/castle/captain.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: Hacktoberfest, enhancement, ui

#2098 Mixer::isPlaying returns false if music is disabled
  src/engine/audio_mixer.cpp
Labels: Hacktoberfest, bug, sound

#2256 Don't reset army while moving a hero to castle
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#2257 Fix post game conditions
  src/fheroes2/game/game_over.cpp
Labels: bug, logic

#2147 2137 - Fixed Bug: File to Save window, use of the Delete key on the k…
  src/engine/tools.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: bug, ui

#2255 fix battle log text layout
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, ui

#2253 Adventure map, Freeman's Foundry window, wrong title and wrong text
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/mp2.cpp
Labels: enhancement, ui

#2258 fix layout for campaign selection window
  src/fheroes2/game/game_newgame.cpp
Labels: enhancement, ui

#2187 Enemy castle view based on Thieves Guild count
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: bug, logic, ui

#2272 "Town portal" spell window should have evil UI elements
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/heroes/heroes_spell.cpp
Labels: enhancement, ui

#2281 Added magic book sprite to popup window #2185
  src/fheroes2/heroes/heroes.cpp
Labels: enhancement, ui

#2284 Use keypad Enter as a normal one
  src/engine/localevent.cpp
Labels: enhancement, logic

#2287 Add popup messages for next/previous pages
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement, ui

#2288 Add missing Info word for artifact status bar
  src/fheroes2/resource/artifact.cpp
Labels: enhancement, ui

#2283 Clear message log for retreat case
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_main.cpp
Labels: enhancement, ui

#2290 Remove spaces for Level messages
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, ui

#2291 Add a popup message for View Hero button
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: enhancement, ui

#2285 Remove unused code for old Win32 CE platform
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: enhancement

#2292 Correct few sprites of mini-monsters
  src/fheroes2/agg/agg.cpp
  src/fheroes2/army/army.cpp
Labels: enhancement, ui

#2286 Fix Pyramid bad luck position
  src/fheroes2/heroes/heroes_action.cpp
Labels: enhancement, ui

#2279 Fix lambda capture in AllHeroes
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: enhancement

#1990 Game windows, changes to title, yellow color and colon
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted, ui

#2267 Adventure map, no sound should be played until the hero gets the artifact
  src/fheroes2/heroes/heroes_action.cpp
Labels: enhancement, sound

#2296 Rename CI job to be more user friendly
  .github/workflows/clang_format.yml
Labels: enhancement, script
