Repository ihhub/fheroes2, pull requests merged in 2020-07, with the labels that each got.

#933 Adjust flags animation with battle speed
  src/fheroes2/game/game_delays.cpp
Labels: enhancement, gui

#935 Fix incorrect hero's interaction with objects during movement
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, logic

#941 Update README to reflect more accurate information
  README.md
Labels: enhancement

#938 Add base code for contour color cycling
  src/engine/surface.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: enhancement, gui

#943 Update README.md
  README.md
Labels: enhancement

#925 Add simplified lightning animation
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#947 Add Chain Lightning animation
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: enhancement, gui

#951 Add a partial support for disabled buttons
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/agg/pal.cpp
  src/fheroes2/agg/pal.h
  src/fheroes2/gui/button.cpp
  src/fheroes2/gui/button.h
Labels: enhancement, gui

#948 Shift battle log window by 1 pixel up
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#960 Build with clang on Linux
  src/engine/system.cpp
Labels: Linux, enhancement

#815 Refactor battle interface to add a dedicated surface
  src/engine/rect.cpp
  src/engine/rect.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, gui

#961 Fix hero's status bar item locations
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, gui

#962 Fix mage guild background
  src/fheroes2/castle/castle_mageguild.cpp
Labels: bug, gui

#963 Set monster to static state after receiving a hit
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#932 Adjust arena dialog
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, gui

#967 Add small palette adjustments
  src/fheroes2/agg/pal.cpp
  src/fheroes2/gui/button.cpp
Labels: enhancement, gui

#965 Reuse SDL2 texture for display flip
  src/engine/display.cpp
  src/engine/display.h
Labels: SDL 2, optimisation

#966 Add frame border to highscore screen
  src/fheroes2/game/game_highscores.cpp
Labels: enhancement, gui

#976 Change mass spell icons
  src/fheroes2/agg/agg.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement, gui

#964 AI hero smooth movement
  src/fheroes2/ai/ai_hero_action.cpp
Labels: AI, gui, logic

#977 Adjust contour color change delay
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
Labels: bug, gui

#978 Add lightning flash and delay
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#982 Update camera logic for AI moving out of the fog
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: bug

#989 Fit the screen to closest resolution in SDL 2
  src/engine/display.cpp
Labels: SDL 2, bug, gui

#991 Use only screen supported resolutions for the game
  src/engine/display.cpp
Labels: enhancement, gui

#994 Try to compile OSX builds on GitHub Actions
  .github/workflows/osx_pull_request.yml
  .github/workflows/osx_release.yml
  .travis.yml
Labels: GitHub Actions, enhancement

#997 Fix Shipwreck empty battle
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#998 Correct AI movements
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, gui

#897 Optimise ListFiles::ReadDir function
  src/engine/dir.cpp
Labels: enhancement, logic

#1000 Fix enormous warning generation on Unix builds
  src/engine/display.h
  src/engine/localevent.h
  src/fheroes2/gui/interface_list.h
Labels: enhancement

#1005 Fix more warnings
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/text.h
Labels: enhancement

#999 Screen makes focus on a hero after adjusting scroll speed
  src/fheroes2/gui/interface_events.cpp
Labels: enhancement, gui, logic

#949 "Summon boat" spell shouldn't be used on a board
  src/fheroes2/heroes/heroes_spell.cpp
Labels: enhancement, logic

#1001 Update elemental storm spell
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1014 Fix irresponsive battle log
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#937 Battle hero animation refactor
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/game/game_delays.cpp
Labels: enhancement, gui

#1010 Fix Hypnotyze and Berserk spell behaviors
  src/fheroes2/ai/simple/ai_simple_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, gui

#968 Blind and morale animation should take appropriate position
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, enhancement, gui

#1018 Death wave/ripple spell effect implementation
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/agg/m82.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: enhancement, gui

#1022 Increase the amount of sound channels to 16
  src/fheroes2/game/fheroes2.cpp
Labels: enhancement, sound

#992 Pathfinding fixes: roads, move cost and display
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/route_pathfind.cpp
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, gui, logic

#1015 Holy Shout blur effect
  src/engine/surface.cpp
  src/engine/surface.h
  src/engine/tools.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: enhancement, gui

#1019 Fix troop counter position
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, gui

#1025 Fix castle initialization, shadows and drawing
  src/fheroes2/agg/agg.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/kingdom/world_loadmap.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.h
Labels: bug, gui, logic

#1046 Fix dimension door range and drawings
  src/fheroes2/game/game_interface.cpp
Labels: bug, gui

#1048 Add additional buildings to the cycling list
  src/fheroes2/castle/castle.cpp
Labels: bug, gui

#1047 Update death logic and animations
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, gui

#1049 Adjust holy shout delay and alpha mask
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1050 Add cycling animation to the battlefield
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, gui

#1062 Fix screen centering and dimension door spell
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, crash, gui

#1056 Support ogg music from GOG version
  .gitignore
  files/music/README
  script/windows/setup_packages.bat
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/system/settings.cpp
Labels: enhancement, script, sound

#1064 Add a Discord badge
  README.md
Labels: script

#1065 Fix chain lightning start point
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#1069 Fix battle pointer cursor offset
  src/fheroes2/gui/cursor.cpp
Labels: Regression, bug, gui

#1067 Reset sound only if battle is shown
  src/fheroes2/battle/battle_main.cpp
Labels: bug, sound

#1063 Add initial SMK video file support
  VisualStudio/common.props
  fheroes2.vcxproj
  src/Makefile
  src/dist/Makefile
  src/engine/Makefile
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
  src/thirdparty/libsmacker/COPYING
  src/thirdparty/libsmacker/Makefile
  src/thirdparty/libsmacker/README
  src/thirdparty/libsmacker/smacker.c
  src/thirdparty/libsmacker/smacker.h
  src/thirdparty/libsmacker/smk_bitstream.c
  src/thirdparty/libsmacker/smk_bitstream.h
  src/thirdparty/libsmacker/smk_hufftree.c
  src/thirdparty/libsmacker/smk_hufftree.h
  src/thirdparty/libsmacker/smk_malloc.h
Labels: enhancement, gui

#1071 Fix system menu OKAY button
  src/fheroes2/dialog/dialog_system.cpp
Labels: bug, gui

#1072 Add SMK audio playback
  src/engine/smk_decoder.cpp
  src/fheroes2/game/game_video.cpp
Labels: enhancement, gui, sound

#1070 Fix luck animation offset
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1074 Fix hero's level up window with single secondary skill
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: SDL 1, bug, gui

#1076 Remove some PocketPC related code
  fheroes2.vcxproj
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/pocketpc/pocketpc.h
  src/fheroes2/pocketpc/pocketpc_armyinfo.cpp
  src/fheroes2/pocketpc/pocketpc_castle.cpp
  src/fheroes2/pocketpc/pocketpc_heroes.cpp
  src/fheroes2/pocketpc/pocketpc_kingdom.cpp
  src/fheroes2/pocketpc/pocketpc_mainmenu.cpp
  src/fheroes2/pocketpc/pocketpc_meeting.cpp
  src/fheroes2/pocketpc/pocketpc_selectscenario.cpp
  src/fheroes2/pocketpc/pocketpc_thievesguild.cpp
Labels: enhancement

#1077 Fix delayed mouse click on a cell during battle
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1078 Fix incorrect popping window in tavern
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, gui

#1079 Update current cursor first before deleting old one for SDL 2
  src/fheroes2/gui/cursor.cpp
Labels: SDL 2, bug, gui

#1082 Fix cursor for empty enemy castle
  src/fheroes2/game/game_startgame.cpp
Labels: bug, gui

#1083 Remove PocketPC related code and fix some compilation warnings
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/pocketpc/pocketpc_dialog.cpp
Labels: enhancement

#1088 Don't play sounds in castle's window when restoring the application
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: bug, sound

#1089 Use correct sprite for castle's exit button
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
Labels: bug, gui

#1093 Display froth sprite only if away from the coast
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, gui

#1101 Adjust hero battle dialog to align text
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, gui

#1100 Add boat building animation
  src/fheroes2/castle/castle_dialog.cpp
Labels: bug, gui

#1092 Fix map monster attack and fade animation
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, gui

#1104 Fix wolf's low attack animation
  src/fheroes2/agg/agg.cpp
Labels: bug, gui

#1106 Add boat summoning animation
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, gui

#1107 Fix regression introduced in #1106
  src/fheroes2/gui/interface_gamearea.cpp
Labels: Regression, bug, gui

#1110 Fix fading animation on the World Map
  src/fheroes2/gui/interface_gamearea.cpp
Labels: Regression, bug, gui

#1111 Fix wolves attack animation
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/bin_info.cpp
Labels: bug, gui

#1112 Don't run useless code
  src/engine/audio_music.cpp
Labels: enhancement, sound

#1117 Add evil interface support for Dimension Door spell
  src/fheroes2/game/game_interface.cpp
Labels: enhancement, gui

#1119 Fix missing music after Dimension Door
  src/fheroes2/heroes/heroes_spell.cpp
Labels: Regression, bug, sound

#1120 Fix attacking monster sprite on the World Map
  src/fheroes2/maps/maps_tiles.cpp
Labels: Regression, bug, gui

#1122 Fix attack cursor while pointing a monster
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, gui

#1123 Fix attacking monster sprite conditions
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, gui

#1124 Fix elves lower shooting start position
  src/fheroes2/agg/bin_info.cpp
Labels: enhancement, gui

#1125 Fix flickering of status bar in castle
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/resource/artifact.h
Labels: bug, gui

#1105 AI hero fade animations
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/kingdom/world.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, gui, logic

#1127 Add resolution change in-game option
  fheroes2.vcxproj
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_resolution.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_mainmenu.cpp
Labels: enhancement, gui

#1128 Fix last shooting angle missile sprite
  src/fheroes2/agg/bin_info.cpp
Labels: bug, gui

#1130 Reset game interface when resolution changes
  src/fheroes2/game/game_mainmenu.cpp
Labels: bug, gui

#1132 Filter resolutions if they are bigger than default
  src/engine/display.cpp
Labels: enhancement, gui

#1134 Add extra conditions for SDL2 resolution retrieval
  src/engine/display.cpp
Labels: enhancement, gui

#1137 Fix infinite morale bug
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic

#1136 Resume AI music after battle that was shown
  src/fheroes2/ai/ai_hero_action.cpp
Labels: AI, bug, sound

#1133 Add swamp and necromancer cycling animations
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, gui

#1138 Fix inability to choose similar resolution
  src/fheroes2/dialog/dialog_resolution.cpp
Labels: bug, gui

#1139 Fix incorrect scrolling area for new resolution
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_mainmenu.cpp
Labels: bug, gui

#1020 Update version to 0.8
  .github/workflows/osx_release.yml
  .travis.yml
  README.md
  appveyor.yml
  changelog.txt
  files/images/screenshots/screenshot_castle.png
  src/fheroes2/system/gamedefs.h
Labels: documentation

#1143 Fix Dimension Door crash
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, gui

#1148 Add README.md into package
  .github/workflows/osx_release.yml
  .travis.yml
  appveyor.yml
Labels: deployment, enhancement

#1161 Add donation information
  README.md
Labels: documentation

#1178 Use global file inclusion for SDL files
  src/engine/audio_mixer.h
  src/engine/audio_music.cpp
  src/engine/font.h
  src/engine/sdlnet.h
  src/engine/surface.cpp
  src/engine/thread.h
Labels: Linux, bug
