Repository ihhub/fheroes2, pull requests merged in 2020-03, with the labels that each got.

#385 Human turn always first (#322)
  src/fheroes2/game/game_startgame.cpp
Labels: bug, logic

#386 Fix game freezes during animation of resources collection (#234)
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, gui

#388 Monster::Rand optimisation (#57)
  src/fheroes2/monster/monster.cpp
Labels: enhancement, logic

#390 Include libvorbis and libogg DLL in the build output
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  appveyor.yml
  script/windows/setup_packages.bat
Labels: audio, bug
