Repository ihhub/fheroes2, pull requests merged in 2020-09, with the labels that each got.

#1485 Save configuration file after resolution change
  src/fheroes2/game/game_mainmenu.cpp
Labels: enhancement, logic

#1489 Draw only current level of mage guild
  src/fheroes2/castle/castle_building.cpp
Labels: bug, gui

#1486 Fix castle mini status icon
  src/fheroes2/gui/interface_icons.cpp
Labels: bug, enhancement, gui

#1487 Set minimum Spell Power to be 1
  src/fheroes2/castle/captain.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#1488 Set focus on a hero while opening spell book
  src/fheroes2/gui/interface_events.cpp
Labels: enhancement, logic

#1502 Play video intro at the opening
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/screen.h
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: enhancement, gui

#1503 Code cleanup for SMK decoder
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
Labels: enhancement

#1510 Add different type of border
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, gui

#1504 Update version to 0.8.1
  changelog.txt
  src/fheroes2/system/gamedefs.h
  src/fheroes2/system/settings.cpp
Labels: enhancement

#1538 Fix Resurrection animation frame and moving dead units
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, gui, logic

#1539 Make Exit button disabled for popup windows in castle
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: enhancement, gui

#1540 Fix generated window position
  src/fheroes2/dialog/dialog_box.cpp
Labels: enhancement, gui

#1542 Fix sky view status
  src/fheroes2/gui/interface_status.cpp
Labels: bug, gui

#1547 Remove "castle: allow recruits special/expansion heroes" option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: logic

#1548 Fix a crash while downgrading resolution in 8-bit mode
  src/engine/screen.cpp
Labels: crash

#1549 Fix New Game window UI
  src/fheroes2/game/game_newgame.cpp
Labels: enhancement, gui

#1550 Fix map size button state selection
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: enhancement, gui

#1551 Optimise video playback
  src/fheroes2/game/game_video.cpp
Labels: enhancement, gui

#1552 Fix few UI issues
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: bug, enhancement, gui

#1553 Draw monster animation within specified ROI
  src/engine/image.cpp
  src/engine/image.h
  src/engine/math_base.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, enhancement, gui

#1554 Fix graphical issues in big text font
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg.cpp
Labels: enhancement, gui

#1555 Fix multiplayer player count window position
  src/fheroes2/game/game_newgame.cpp
Labels: enhancement, gui

#1556 Disable Next Hero button if none of heroes can move
  src/fheroes2/gui/interface_buttons.cpp
Labels: enhancement, gui

#1557 Fix game info buttons
  src/fheroes2/agg/agg.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: enhancement, gui

#1558 Make scroolbar more user friendly in battle log
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#1559 Fix few Phoenix frames
  src/fheroes2/agg/agg.cpp
Labels: enhancement, gui

#1572 Add a dot at the end of Ultimate Artifact message
  src/fheroes2/gui/interface_events.cpp
Labels: enhancement, gui

#1597 Fix missing resolutions and black screen for SDL 1
  src/engine/screen.cpp
Labels: bug, gui

#1599 Add dot at end in Cast Spell Info Window
  src/fheroes2/battle/battle_dialogs.cpp
Labels: enhancement, gui

#1541 Cache pathfinding results to speed up calculations
  VisualStudio/common.props
  fheroes2.vcxproj
  src/fheroes2/ai/simple/ai_simple_heroes.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/direction.cpp
  src/fheroes2/heroes/direction.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/heroes/route_pathfind.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: logic, optimisation

#1603 Fix Bloodlust animation
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1606 Fix `battle: show damage info` option
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: enhancement, gui

#1622 Add external music support by default
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, sound

#1623 Fix cycling colors for mirrored Genie
  src/engine/image.cpp
  src/engine/pal.cpp
Labels: enhancement, gui

#1638 Add button choice support for campaign
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: enhancement, gui

#1641 Add proper Cursor class
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_bar.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/test/test_monstersprite.cpp
Labels: enhancement

#1639 fix building tools
  src/tools/icn2img.cpp
Labels: script

#1651 Fix creature shadow contour issue
  src/engine/image.cpp
  src/fheroes2/agg/agg.cpp
Labels: enhancement, gui

#1650 I1648 added word player
  src/fheroes2/game/game_over.cpp
Labels: enhancement, gui

#1652 Center spell point text in hero's dialog
  src/fheroes2/heroes/heroes_indicator.cpp
Labels: bug, gui

#1653 Fix some icon positions in hero's dialog
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, gui

#1654 Remove extra wince animation for cold ray spell
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1655 Fix monster info shadow position
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, gui

#1658 Fix text color for joining window
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, gui

#1659 Fix File Options window position
  src/fheroes2/dialog/dialog_file.cpp
Labels: enhancement, gui

#1660 Fix victory message in battle
  src/fheroes2/battle/battle_dialogs.cpp
Labels: enhancement, gui

#1661 Fix Blind spell name
  src/fheroes2/spell/spell.cpp
Labels: bug, gui

#1663 Fix Daemon Cave incorrect window
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, gui, logic

#1664 Reset music after exiting a castle
  src/fheroes2/game/game_startgame.cpp
Labels: bug, sound

#1665 Fix a crash for Mirror image creature
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, crash, logic

#1666 Fix hero button position for joining window
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, gui

#1667 Add missing dot for a victory text
  src/fheroes2/battle/battle_dialogs.cpp
Labels: enhancement, gui

#1662 Display Liches for the City of the Dead
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#1668 Display spell points in magic book from bottom to top
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement, gui

#1669 Center Hero's Options dialog
  src/fheroes2/battle/battle_dialogs.cpp
Labels: enhancement, gui

#1670 Add proper credits
  src/fheroes2/game/game.cpp
Labels: enhancement, gui

#1672 Readme and code cleanup
  README.md
  src/engine/image.cpp
  src/engine/screen.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/gui/cursor.cpp
Labels: enhancement

#1671 Set path intro "H2XINTRO.SMK" on cross-platform manner
  src/fheroes2/game/fheroes2.cpp
Labels: enhancement

#1696 Validate and fix the path if hero was stuck
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#1702 Fix multiple UI issues in Hero's Screen
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/skill.cpp
Labels: enhancement, ui

#1657 Check magic resistance against Chain Lighting spell
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic

#1706 Focus on a new hired hero in a castle
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, logic

#1727 Reset dimissed hero's army
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#1707 Fix bottom-to-top scrolling issue by keyboard key
  src/fheroes2/gui/interface_list.h
Labels: bug, ui

#1708 Remember MP of surrendered/retreated hero
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world.cpp
Labels: enhancement, logic

#1760 Castle construction screen, add the Income information window
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
Labels: enhancement, ui

#1762 Change color for item selection
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/resource/artifact.cpp
Labels: enhancement, ui

#1763 Change unit movement speed in battle under spells
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, ui

#1766 Shift second hero's portrait in town
  src/fheroes2/castle/castle_town.cpp
Labels: enhancement, ui

#1764 Don't shift High Score background for high resolutions
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_over.cpp
Labels: enhancement, ui

#1765 Use single OKAY button for Config window
  src/fheroes2/dialog/dialog_settings.cpp
Labels: bug, ui

#1761 Added dot to the end of hero description
  src/fheroes2/castle/castle_town.cpp
Labels: ui

#1656 Implement base for battle AI
  fheroes2.vcxproj
  src/fheroes2/agg/agg.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/spell/spell_storage.cpp
  src/fheroes2/spell/spell_storage.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, enhancement, logic

#1776 Add extended campaign support
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
Labels: campaign, enhancement, ui

#1779 Fix scrollbar in Settings window
  src/fheroes2/dialog/dialog_settings.cpp
Labels: bug, ui

#1780 Fix cursor for Abandoned mine protected by monsters
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#1781 Fix popup windows for Spell Book
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement, ui

#1783 Fix some compilation warnings
  fheroes2.vcxproj
  src/engine/display.cpp
  src/engine/display.h
  src/engine/engine.h
  src/engine/localevent.cpp
  src/engine/surface.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/agg/sprite.cpp
  src/fheroes2/agg/sprite.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_resourceinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_skillinfo.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/heroes/direction.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_storage.cpp
  src/fheroes2/spell/spell_storage.h
  src/fheroes2/system/settings.cpp
Labels: enhancement

#1784 "Choose your lord" phrase before selecting campaign
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
  src/thirdparty/libsmacker/smk_hufftree.c
Labels: enhancement, ui

#1786 Add the word "Skill" for "Attack Skill" and "Defense Skill" in monster's stats dialog
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, ui

#1788 Add Information window by right click in File dialog
  src/fheroes2/dialog/dialog_file.cpp
Labels: enhancement, ui

#1789 Fix text poistion in creature recruit window
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: enhancement, ui

#1790 Fix bookmark positions in Spell Book
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement, ui

#1791 Add missing dots for messages
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: enhancement, ui

#1799 Delete executable on "make clean"
  Makefile
Labels: enhancement

#1800 Remove spaces between the damage numbers and the dash
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, ui

#1804 Remove unused diff file
  src/engine/wince/sdl-1.2.mingw32ce.hg4904.diff.gz
Labels: enhancement

#1805 Fix dialog frame drawing
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_box.cpp
Labels: bug, ui

#1803 Combat AI: improve target selection
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
Labels: AI, enhancement

#1806 Allow to open hero's dialog during meeting
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: enhancement, ui

#1808 Draw all dead troops on the battlefield
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_grave.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#1811 Fix hero's names
  src/fheroes2/heroes/heroes.cpp
Labels: bug

#1807 Combat AI: enable defensive tactics
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: AI, enhancement

#1813 Delete unused gzstream lib
  src/fheroes2/system/gamedefs.h
  src/xmlccwrap/gzstream.cpp
  src/xmlccwrap/gzstream.h
  src/xmlccwrap/xmlccwrap.h
Labels: enhancement

#1816 Remove unused file
  files/sounds/sound.txt
Labels: enhancement

#1113 Refactor map structures
  src/fheroes2/agg/m82.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/simple/ai_simple_heroes.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: enhancement, logic

#1812 Amount of creatures moved down by 1 pixel in DrawMonsterInfo
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, ui

#1821 Fix puzzle and ultimate artifact logic
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic, ui

#1822 Fix tile protection for pickup objects
  src/fheroes2/maps/maps.cpp
Labels: bug, logic

#1823 Fix castle shadows and shadow draw priority
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#1827 Reset puzzle between games
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#1825 Allow hero to make last diagonal move
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/direction.cpp
  src/fheroes2/heroes/direction.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#1830 Remove unused variables
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: enhancement

#1833 Always reduce moral for visited Graveyard and Ship Wreck
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#1835 Remove map editor boat sprite on map load
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, ui

#1836 Save neutral army after battle
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, logic

#1834 Strategic AI: handle hero movement
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: AI, enhancement

#1837 Use a proper randomizer
  src/engine/rand.cpp
  src/engine/rand.h
  src/fheroes2/game/fheroes2.cpp
Labels: enhancement

#1838 Update debug option selection
  src/fheroes2/system/settings.cpp
Labels: enhancement

#1839 Fix configuration file saving
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/system/settings.cpp
Labels: bug

#1840 Fix AI hero recruit crash
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: bug, crash, logic

#1851 Fix typo in description of "Knowledge" skill at hero screen
  src/fheroes2/heroes/skill.cpp
Labels: bug, ui
