Repository ihhub/fheroes2, pull requests merged in 2020-08, with the labels that each got.

#1169 Descriptions fixes
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/skill.cpp
Labels: enhancement, gui

#1174 Add more user friendly readme file
  .github/workflows/osx_release.yml
  .travis.yml
  appveyor.yml
  doc/README.txt
Labels: deployment, documentation

#1190 Don't draw tent images in the castle window at all
  src/fheroes2/castle/castle_building.cpp
Labels: bug, gui

#1191 Add logic to handle inability to buy monsters in well
  src/fheroes2/castle/castle_well.cpp
Labels: enhancement, gui, logic

#1193 Don't show start and end position for monster log movement
  src/fheroes2/battle/battle_interface.cpp
Labels: enhancement, gui

#1194 Remove black background over army counter
  src/fheroes2/army/army_bar.cpp
Labels: enhancement, gui

#1201 Fix AI turn crash and battle board cleanup
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: Regression, bug, crash, logic

#1202 Correct downloads badge
  README.md
Labels: documentation, enhancement

#1203 Add C++11 support
  src/Makefile
  src/fheroes2/ai/simple/ai_simple_battle.cpp
  src/fheroes2/ai/simple/ai_simple_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/world.cpp
  src/fheroes2/system/players.cpp
  src/thirdparty/libsmacker/Makefile
Labels: enhancement

#1205 Fix EXIT button position in creature window
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, gui

#1209 Skip turn of resurrected troop
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: enhancement, logic

#1208 Map pathfinding refactoring
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/simple/ai_simple_heroes.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/heroes/route_pathfind.cpp
  src/fheroes2/kingdom/world.cpp
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic, optimisation

#1177 Add a new rendering engine
  fheroes2.vcxproj
  src/engine/image.cpp
  src/engine/image.h
  src/engine/math_base.h
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: enhancement, gui

#1210 Fix ultimate artifact regression
  src/fheroes2/maps/maps_tiles.cpp
Labels: Regression, logic

#1213 Fix an ability to skip button state by using keyboard
  src/fheroes2/gui/button.cpp
Labels: bug, gui, logic

#1216 Apply Chain Lightning damage on allies as well
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/spell/spell.cpp
Labels: enhancement, logic

#1223 Don't display artifact dialog for unknown artifact
  src/fheroes2/resource/artifact.cpp
Labels: bug, gui

#1227 Show a dialog if a hero has no space for Spell Book
  src/fheroes2/castle/castle_dialog.cpp
Labels: enhancement, gui

#1248 New engine: game area integration
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/resource/artifact_ultimate.cpp
  src/fheroes2/resource/artifact_ultimate.h
Labels: gui

#1259 New engine: adventure dialogs
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_box.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_buttons.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/interface_status.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: gui

#1271 New engine: battle interface integration
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: gui

#1287 New engine: battle dialogs
  src/engine/image.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
Labels: gui

#1373 Fix marketplace text
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: enhancement, gui

#1374 Fix graveyard message
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, gui

#1375 Add missing title for graveyard message
  src/fheroes2/heroes/heroes_action.cpp
Labels: enhancement, gui

#1376 Fix Dismiss button position in Hero's dialog
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, gui

#1378 Fix lighthouse spelling
  src/fheroes2/maps/mp2.cpp
Labels: bug, gui

#1207 Show upgrade button if there's not enough money
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: enhancement, gui

#1380 Polish battle only button
  src/fheroes2/agg/agg.cpp
Labels: enhancement, gui

#1377 Modify Graveyard robber message
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
Labels: enhancement, gui

#1381 Fix Sphinx message
  src/fheroes2/heroes/heroes_action.cpp
Labels: enhancement, gui

#1379 Fix cursor position for SDL 1
  src/fheroes2/gui/cursor.cpp
Labels: Regression, SDL 1, gui

#1382 Fix file save always disabled button
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: bug, gui

#1385 Fix abandonded mine cursor
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: enhancement, gui

#1394 Don't show diplomacy even when not enough gold
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#1395 Disable Campaign button if no files present
  src/fheroes2/game/game_newgame.cpp
Labels: enhancement, gui

#1396 Make Disabled Campaign button in High Score board
  src/fheroes2/game/game_highscores.cpp
Labels: enhancement, gui

#1397 Don't refocus after exiting castle's window
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, gui

#1398 Reset interface while changing its type
  src/fheroes2/dialog/dialog_system.cpp
Labels: bug, gui

#1399 Use proper config background image
  src/fheroes2/dialog/dialog_settings.cpp
Labels: bug, gui

#1400 Fix map difficulty text and its position
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: bug, gui

#1401 Always center scenario window position
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: enhancement, gui

#1402 Add dot at the end of player's turn text
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, gui

#1403 Always show diplomacy window and fix marketplace button
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: Regression, gui, logic

#1404 Incorrect map extension crash
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: crash

#1405 Update interface after exiting hero dialog
  src/fheroes2/game/game_startgame.cpp
Labels: bug, gui

#1407 Fix Armageddon animation
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#1437 Fix shift after opening and closing system options dialog
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_radar.cpp
Labels: bug, gui

#1438 Old engine code cleanup
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/system/settings.cpp
Labels: optimisation

#1439 Add missing config button
  src/fheroes2/agg/agg.cpp
Labels: enhancement, gui

#1440 Add proper support of configuration file
  .github/workflows/osx_release.yml
  .travis.yml
  appveyor.yml
  fheroes2.cfg
  src/engine/screen.cpp
  src/engine/screen.h
  src/engine/tools.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, documentation, enhancement, gui

#1445 Fix message dialog shadow
  src/fheroes2/dialog/dialog_box.cpp
Labels: bug, gui

#1446 Remove some redundant / useless config options
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, gui, logic

#1447 Fix button drawing for no interface
  src/fheroes2/gui/interface_cpanel.cpp
Labels: bug, gui

#1448 Update configuration options
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, gui

#1449 Remove not in use code
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/agg/sprite.cpp
  src/fheroes2/agg/sprite.h
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement

#1458 Save all battle options in global configuration file
  src/engine/smk_decoder.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/kingdom/world.h
  src/fheroes2/pocketpc/pocketpc_dialog.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, logic

#1461 Remove few configuration options
  src/engine/display.cpp
  src/engine/display.h
  src/engine/pal.cpp
  src/engine/pal.h
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/sprite.cpp
  src/fheroes2/agg/sprite.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: enhancement, logic
