Repository ihhub/fheroes2, pull requests merged in 2020-01, with the labels that each got.

#298 Make 32 bit depth as default depth
  src/engine/surface.cpp
Labels: SDL 1, bug, gui

#301 Add ARM compilation support
  .travis.yml
Labels: Linux, SDL 1, SDL 2, Travis-CI

#303 Add ZIP support for ARM build
  .travis.yml
Labels: Travis-CI, bug

#302 Fix compilation warning
  src/engine/serialize.h
Labels: enhancement

#305 Static analysis fixes
  src/engine/audio.h
  src/engine/sprites.cpp
  src/engine/sprites.h
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/gui/interface_status.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_actions.h
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/system/players.h
Labels: enhancement

#306 Code cleanup
  src/engine/audio_mixer.cpp
  src/engine/audio_music.h
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/font.cpp
  src/engine/translations.cpp
  src/engine/types.h
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/m82.h
  src/fheroes2/agg/til.h
  src/fheroes2/agg/xmi.cpp
  src/fheroes2/agg/xmi.h
  src/fheroes2/ai/simple/ai_heroes.cpp
  src/fheroes2/ai/simple/ai_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_grave.h
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/world_loadmap.cpp
  src/fheroes2/pocketpc/pocketpc_castle.cpp
  src/fheroes2/system/gamedefs.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/settings.cpp
Labels: enhancement

#256 Fix crash for configuration file cases
  src/engine/serialize.cpp
  src/engine/tools.cpp
  src/fheroes2/system/settings.cpp
Labels: bug

#307 Use caching for packages
  appveyor.yml
Labels: AppVeyor, script

#308 Fix compilation of tools
  src/tools/Makefile
  src/tools/xmi2mid.cpp
Labels: Linux, bug

#310 Fix some compilation warnings
  src/engine/error.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/objects/trees.cpp
  src/fheroes2/pocketpc/pocketpc_kingdom.cpp
Labels: enhancement

#313 Compile Editor on OSX with Qt
  .travis.yml
  editor/CMakeLists.txt
  editor/dialogs.h
Labels: Map editor, Travis-CI

#314 Code style formatting
  .clang-format
  src/engine/IMG_savepng.cpp
  src/engine/audio.h
  src/engine/system.cpp
  src/engine/types.h
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/kingdom/luck.h
  src/fheroes2/kingdom/morale.cpp
  src/fheroes2/kingdom/morale.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
  src/fheroes2/kingdom/speed.cpp
  src/fheroes2/kingdom/speed.h
  src/tools/extractor.cpp
  src/tools/til2img.cpp
Labels: enhancement

#253 Fix the crash on starting a new game after loading any save
  src/engine/localevent.cpp
  src/engine/system.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/kingdom/world_loadmap.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: bug, logic

#316 Disable VS linker optimizations
  VisualStudio/Release.props
Labels: AppVeyor, Windows

#317 Update game screenshots
  README.md
  files/images/screenshots/screenshot_castle.png
  files/images/screenshots/screenshot_game1.png
  files/images/screenshots/screenshot_game2.png
  files/images/screenshots/screenshot_world_map.png
Labels: documentation, enhancement

#299 Fix signs not displaying any information
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/mp2.h
Labels: bug, gui

#319 Do not show a Tavern in Necromancer's castle
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_town.cpp
Labels: bug, gui

#320 Do not show Necromancy window for 0 skeletons
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#324 Format code style for Editor
  editor/dialogs.cpp
  editor/dialogs.h
  editor/engine.cpp
  editor/engine.h
  editor/global.cpp
  editor/global.h
  editor/mainwindow.cpp
  editor/mainwindow.h
  editor/mapdata.cpp
  editor/mapdata.h
  editor/mapwindow.cpp
  editor/mapwindow.h
  editor/program.cpp
  editor/program.h
Labels: enhancement

#326 Do not do anything for disabled spell cast button
  src/fheroes2/gui/interface_buttons.cpp
Labels: bug, gui

#328 Do not install gettext for OSX jobs
  .travis.yml
Labels: Travis-CI, enhancement

#329 Try to cache Homebrew
  .travis.yml
Labels: Travis-CI, enhancement

#334 Fix resizing of minimap in fixed interface mode
  src/fheroes2/gui/interface_radar.cpp
Labels: bug, gui

#333 Show movement arrow icons with proper colors
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/sprite.cpp
  src/fheroes2/agg/sprite.h
Labels: bug, gui

#340 Castle well ui fixes
  src/fheroes2/castle/castle_well.cpp
Labels: bug, gui
