Repository ihhub/fheroes2, pull requests merged in 2020-02, with the labels that each got.

#341 Display recruit monster window even for 0 creatures
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: enhancement, gui, logic

#342 Fix scrolling behaviour and add diagonal scrolling
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, gui

#345 Set correct animation speed
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/game/game_delays.cpp
Labels: bug, enhancement, gui

#348 Add monster animation to castle's well
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: enhancement, gui

#349 Tune parameters for scrolling
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, gui, logic

#350 Update cursor while stopping hero's movement
  src/fheroes2/game/game_startgame.cpp
Labels: bug, gui

#353 Add Bin2txt tool and fix idle animation in battles
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/tools/Makefile
  src/tools/bin2txt.cpp
  src/tools/til2img.cpp
Labels: gui, logic

#362 Fix MAX button state for monster change in recruitment window
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: bug, gui

#371 Allow file selection by double-clicking a list entry (#337)
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: enhancement, gui

#380 Dont allow to move artifacts for not hired heroes (#111)
  src/fheroes2/resource/artifact.cpp
Labels: enhancement, gui

#378 Cancel dialog by close windows button (#321)
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: enhancement, gui

#381 Add Wing32.dll download for Windows demo
  script/demo/demo_windows.bat
Labels: Windows, script

#382 Fix blurred adventure buttons (#273)
  src/fheroes2/agg/icn.cpp
Labels: SDL 2, bug, gui

#376 Don't show file save loading dialog if no saves exist
  src/engine/dir.cpp
  src/engine/dir.h
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/pocketpc/pocketpc_mainmenu.cpp
Labels: enhancement, gui, logic
