Repository ihhub/fheroes2, pull requests merged in 2020-04, with the labels that each got.

#394 Fix map object casting
  src/fheroes2/ai/ai_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, logic

#396 Fix battle grid drawings
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, gui

#397 Add hotkey N to start a new game
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: enhancement, logic

#400 Fix compilation warnings
  src/engine/system.cpp
Labels: enhancement

#401 Fix multiple compilation warnings
  src/fheroes2/agg/mus.cpp
  src/fheroes2/ai/ai_action.cpp
  src/fheroes2/ai/simple/ai_castle.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/kingdom/world_loadmap.cpp
  src/fheroes2/pocketpc/pocketpc_mainmenu.cpp
Labels: enhancement

#402 Fix incorrect scrolling in dialogs
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/interface_list.h
Labels: enhancement, gui, logic

#403 Complete hero's movement if user stops it
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: enhancement, logic

#405 Add an edge of world map
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: enhancement, gui

#406 Stop hero's movement if any button is pressed
  src/fheroes2/game/game_startgame.cpp
Labels: enhancement, logic

#413 Readme update
  README.md
  files/images/screenshots/screenshot_world_map.png
Labels: documentation

#417 Fix segfault on quit by moving SDL2 deinit code outside singleton des…
  src/engine/display.cpp
  src/engine/display.h
  src/fheroes2/game/fheroes2.cpp
Labels: bug, crash

#421 Add double quotes to surrender dialog
  src/fheroes2/battle/battle_dialogs.cpp
Labels: enhancement, gui

#422 Fix application crash at exit in SDL 1
  src/engine/display.cpp
  src/engine/display.h
  src/engine/surface.cpp
  src/engine/surface.h
  src/fheroes2/game/fheroes2.cpp
Labels: bug, crash

#423 Do not show text for hidden Dismiss button
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, gui

#420 Use O3 flag to optimize code even more
  src/Makefile
Labels: Linux, MacOS

#425 Add scalable Sprites support
  src/engine/display.cpp
  src/engine/display.h
  src/engine/rect.cpp
  src/engine/rect.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/system/settings.cpp
Labels: enhancement, gui

#426 Recruit Creature Info window has an incorrect position in higher than default resolution
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: enhancement, gui
