Repository ihhub/fheroes2, pull requests merged in 2021-01, with the labels that each got.

#2518 Fix Hydra's movement during battle
  src/fheroes2/battle/battle_board.cpp
Labels: bug, logic

#2520 Add support for pseudo-single images
  src/engine/image.cpp
  src/engine/image.h
  src/engine/screen.cpp
Labels: improvement, ui

#2521 Optimize world map rendering
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/position.cpp
  src/fheroes2/maps/position.h
Labels: improvement, ui

#2522 Speed up interface drawings for World map
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/captain.h
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: improvement, ui

#2523 Revert back changes because of regression
  src/fheroes2/gui/interface_border.cpp
Labels: Regression, ui

#2524 Explicitely define Linux package OS
  .travis.yml
Labels: Linux, Travis-CI

#2525 Fix empty enemy castle capture action
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#2526 Fix Earthquake spell animation
  src/engine/math_base.h
  src/engine/rect.cpp
  src/engine/rect.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2527 Add Gold version support for video
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
Labels: improvement, ui

#2469 Add game controller support
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#2530 Fix Player Rankings message bar
  src/fheroes2/dialog/dialog_thievesguild.cpp
Labels: bug, ui

#2531 Always display the correct monster combat speed
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, ui

#2533 Code cleanup
  src/engine/pal.cpp
  src/engine/pal.h
  src/engine/rand.cpp
  src/engine/rand.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/pocketpc/pocketpc.h
  src/tools/cdinfo.py
Labels: improvement

#2535 Fix controller support
  src/engine/localevent.cpp
  src/engine/timing.h
Labels: Regression, logic

#2536 Update CI/CD related scripts
  .travis.yml
  appveyor.yml
Labels: AppVeyor, Travis-CI, script

#2539 Fix multiple SonarCloud bugs
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/captain.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/gui/interface_cpanel.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement

#2541 Fix multiple code bugs
  src/engine/image.h
  src/engine/rand.h
  src/engine/smk_decoder.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/world/world.cpp
Labels: improvement

#2543 Fix all scan-build warnings
  .github/workflows/scan-build.yml
  src/fheroes2/agg/agg.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/thirdparty/libsmacker/smk_hufftree.c
Labels: improvement

#2482 Fix mouse cursor switching while navigating on hero or castle panel
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#2534 Meeting screen, morale and luck sprites positioning
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#2529 Add palette support for SDL2
  src/engine/screen.cpp
Labels: improvement, ui

#2546 Exclude third-party code from SonarCloud analysis
  sonar-project.properties
Labels: improvement

#2545 fix for sonar cloud warnings
  src/engine/image_tool.cpp
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/spell/spell.h
  src/fheroes2/system/bitmodes.h
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#2547 fix for errors found by sc
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/profit.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement

#2550 Add PNG image saving support for SDL2
  .github/workflows/osx_pull_request.yml
  .github/workflows/osx_release.yml
  .travis.yml
  VisualStudio/SDL2.props
  fheroes2.vcxproj
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
  src/engine/IMG_savepng.cpp
  src/engine/IMG_savepng.h
  src/engine/image_tool.cpp
Labels: ui

#2551 Remove unused key events
  fheroes2.key
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
Labels: improvement

#2555 Clang format fix
  .github/workflows/clang_format.yml
  script/tools/clang-format-diff.py
Labels: bug, script

#2558 Add -Wfloat-conversion compilation flag
  .travis.yml
  src/Makefile
  src/engine/rect.cpp
  src/engine/tools.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement

#2556 Bone Dragon morale malus shows in battle and in dialog window
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement, logic

#2557 Fix code issues found by SonarCloud
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/smk_decoder.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps_actions.cpp
  src/fheroes2/maps/maps_actions.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#2560 Make SDL2 as default option for makefile
  .github/workflows/osx_pull_request.yml
  .github/workflows/osx_release.yml
  .github/workflows/scan-build.yml
  .travis.yml
  Makefile
  README.md
  src/Makefile
  src/tools/Makefile
Labels: improvement, script

#2561 Fix object drawings on battlefield
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2562 Display battle grid for whole battlefield
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2563 Fix a log message when a tower kill one creature
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2564 Always draw troop counter at the top of monster sprites
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2565 Hide Marketplace button for Surrender window
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#2566 optimize include files (include what you use)
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/system.cpp
  src/engine/translations.cpp
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/icn.cpp
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_resourceinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/heroes/direction.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/system/gamedefs.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement

#2569 Fix castle's battlefield drawings
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2567 Fix marketplace button in Surrender window
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#2571 Do not close File Save window while cancelling file overriding
  src/fheroes2/game/game_io.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#2574 Fix animation order of creatures during combat
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2510 After AI loses to either castle or other player, center the view on them
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, logic

#2582 Fix controller cursor max position
  src/engine/localevent.cpp
Labels: Regression, ui

#2585 Fix troop counter redraw in a normal battle
  src/fheroes2/battle/battle_interface.cpp
Labels: Regression, ui

#2586 Don't update brew for MacOS
  .github/workflows/osx_pull_request.yml
  .github/workflows/osx_release.yml
Labels: script

#2587 AI: check for special objects that you can't move through
  src/fheroes2/monster/monster.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, bug

#2513 QuickInfo dialogs have fixed position when clicked from right bar
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
Labels: bug, ui

#2579 Fix joining creature logic with the lack of gold
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, logic

#2552 Add touchpad support
  src/engine/engine.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/screen.h
Labels: improvement, logic, ui

#2506 Implement Alt hotkey to unite stacks of same type, Implement CTRL split even with selected troop
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement, ui

#2592 Change highlighted cursor area for spells during battle
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2604 Remove SDL timer
  src/engine/audio_music.cpp
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/localevent.h
  src/engine/math_base.h
  src/engine/rand.h
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/smk_decoder.cpp
  src/engine/system.h
  src/engine/thread.h
  src/engine/timing.cpp
  src/engine/timing.h
  src/engine/types.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/gui/interface_status.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement

#2613 AI: avoid disembarking on empty tiles
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, bug

#2615 Add new standard window with shadow
  fheroes2.vcxproj
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#2616 Fix town portal buttons in good interface
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, ui

#2612 AI: fix path selection for hero in patrol
  src/engine/pathfinding.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: AI, bug

#2591 Display correct text when righ-clicking on map tile
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/maps/ground.cpp
Labels: bug, ui

#2617 Fix castle's object positions
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2618 Show pointer cursor most of the time during combat
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2619 Display troop counter only for static animations
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2611 optimize audio/rand/serialize include files
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/mus.cpp
  src/fheroes2/ai/ai.h
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_recruits.h
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/puzzle.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/position.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/artifact_ultimate.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/system/gamedefs.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#2581 Show Spade of Necromancy artifact bonus in Necromancy Skill window
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_skillinfo.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/skill_bar.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#2278 Fix freeze while buying hero
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
Labels: improvement, ui

#2620 Fix Kingdom overview crash
  src/fheroes2/castle/castle_heroes.h
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, crash

#2624 Do not show shadow for uneffected by spell monsters
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, logic, ui

#2623 Fix pathfinding issues and missing path display
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, improvement, logic

#2626 Correction of spell area shadow
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2631 Fix shadow for current unit during spell casting
  src/fheroes2/battle/battle_interface.cpp
Labels: Regression, ui

#2632 Multiple enhancements to rendering engine
  src/engine/image.cpp
  src/engine/image.h
  src/engine/screen.cpp
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/game/game_video.cpp
Labels: improvement, ui

#2553 Refactor campaign scenario window
  fheroes2.vcxproj
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#2633 Don't draw wall for destroyed bridge
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2634 Allow Anti-magic spell on mirror master creature
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#2635 Add empty line for visited info
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#2636 Fix castle flag drawing
  src/fheroes2/agg/icn.cpp
Labels: bug, ui

#2149 Move agg-parsing code to engine
  fheroes2.vcxproj
  src/engine/agg_file.cpp
  src/engine/agg_file.h
  src/fheroes2/agg/agg.cpp
Labels: improvement

#2343 Fix Chain lightning logic
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: bug, logic

#2644 Fix Berserk logic
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: bug, logic

#2650 Do not play dwarves' resist sound during mass spells
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, logic

#2651 Remove few experimental options
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#2568 Fix scouting bugs + make crystal ball work
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: bug, logic, ui

#2653 Fix missing music for Load Game option
  src/fheroes2/game/game_loadgame.cpp
Labels: bug, sound

#2657 Add a separate option for displaying terrain penalty.
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#2662 Cancel spell selection with ESC button in combat
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2666 Fix Transcribe Spell text
  src/fheroes2/resource/artifact.cpp
Labels: bug, ui

#2603 Fix right mouse split regression
  src/fheroes2/army/army_bar.cpp
Labels: Regression, logic

#2672 Fix issue with fading at the start of the battle
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_main.cpp
Labels: Regression, ui

#2597 Fix bugs in Kingdom View
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, logic, ui

#2673 Cap necromancy bonus to 100% instead of 90%
  src/fheroes2/heroes/skill.cpp
Labels: improvement, logic

#2663 Align dates by left in the load file dialog
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: improvement, ui

#2675 Add include/lib folders resolve relatively to props files.
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  VisualStudio/common.props
Labels: Windows, improvement

#2676 Reset hero direction when recruiting
  src/fheroes2/heroes/heroes.cpp
Labels: bug, ui

#2678 Fix application crash after compiling on some Unix systems
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/bin_info.h
Labels: Regression

#2692 Optimize CI pipelines
  .travis.yml
  appveyor.yml
Labels: improvement, script

#2695 Play music after showing New Week/Month dialog
  src/fheroes2/game/game_startgame.cpp
Labels: bug, sound

#2694 Change the text for the number of secondary skills in level up window
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: improvement, ui

#2696 Disable actions while buying a hero or during construction
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
Labels: bug, logic

#2697 Fix overlapped flag in Knight's castle
  src/fheroes2/castle/castle_building.cpp
Labels: improvement, ui

#2698 Do not block shooters with overpowered army
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: AI, improvement

#2700 Fix a crash in debug mode
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: Regression

#2701 Add more logic for AI jumping into whirlpools
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, improvement

#2703 Travis-CI hot fix
  .travis.yml
Labels: Regression, Travis-CI

#2649 [Bugfix][2646] Ability to retreat when player has no towns
  src/fheroes2/battle/battle_arena.cpp
Labels: improvement, logic

#2658 Do not show marketplace icon for joining creature dialog is none is built
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: Regression, ui

#2699 Restore cursor theme after HeroDialog or CastleDialog
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#2665 Remove dependency on the dialog.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#2669 Fix tools compilation
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  VisualStudio/common.props
  src/engine/agg_file.cpp
  src/engine/agg_file.h
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/agg/agg.cpp
  src/tools/82m2wav.cpp
  src/tools/82m2wav.vcxproj
  src/tools/bin2txt.vcxproj
  src/tools/extractor.cpp
  src/tools/extractor.vcxproj
  src/tools/icn2img.cpp
  src/tools/icn2img.vcxproj
  src/tools/til2img.cpp
  src/tools/til2img.vcxproj
  src/tools/xmi2mid.vcxproj
  src/tools/xmi2mid_cli.cpp
Labels: improvement

#2702 Fixes to whirlpool logic
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#2680 Battle screen, area-based spells vs Anti-Magic
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, logic

#2707 Fix AI castle defence mechanics
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/resource/resource.cpp
Labels: AI, bug

#2708 Don't visit useless objects by AI heroes
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, improvement
