Repository ihhub/fheroes2, pull requests merged in 2021-11, with the labels that each got.

#4533 xmi2mid: avoid possible reordering of MIDI commands with the same timestamp
  src/engine/xmi2mid.cpp
Labels: bug, sound

#4531 Do not reset music type to MUSIC_MIDI_ORIGINAL too early
  src/fheroes2/system/settings.cpp
Labels: bug, sound

#4535 Fix Marketplace messaging
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: improvement, ui

#4539 Fix rendering of Captain's Quarters in Warlock castle
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/castle/castle_building_info.cpp
Labels: improvement, ui, assets

#4532 Add buttons in castle construction window
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, ui

#4544 Fix Stonehenge building requirements
  src/fheroes2/castle/castle.cpp
Labels: bug

#4549 Fix Stonehenge gold cost
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, logic

#4547 Do not leak the hotkey state from the experimental settings dialog to the scenario info dialog
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: bug, ui

#4545 Fix interaction with Shipwreck object
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: bug, logic, regression

#4554 Version 0.9.9
  CMakeLists.txt
  Makefile.switch
  appveyor.yml
  changelog.txt
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
Labels: improvement

#4556 Always highlight the cell under the cursor in combat if the Shadow Cursor is enabled, even if this cell is not reachable by the current unit
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#4543 ResetMixer is async by default
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
Labels: improvement, sound

#4436 Shorten artifacts names to be fit for campaign UI
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: improvement, ui

#4456 Clarifying messages in battle mode
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#4551 Use OG Prerequisistes for Upgraded Jousting Arena and Upgraded Cathedral
  src/fheroes2/castle/castle.cpp
Labels: bug, logic

#4553 Allow to use mouse wheel to change system options
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: improvement, ui

#4563 Add Homebrew install instructions
  docs/INSTALL.md
Labels: improvement, deployment

#4570 Fix water object passabilities
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4558 Fix terrain music being played during battle
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/game/game_startgame.cpp
Labels: bug, sound, regression

#4571 Don't translate the proper names in Original Team's credits
  src/fheroes2/game/game_credits.cpp
Labels: bug, translation

#4577 Add runtime language generation
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/agg_image.h
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_language_selection.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
  src/fheroes2/system/settings.cpp
Labels: improvement, ui, translation

#4580 Better heuristic for AI usage of Disrupting Ray
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: improvement, AI

#4582 Kingdom::LossPostActions(): don't (indirectly) call erase() in the std::for_each() functor
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#4574 Resurect spell updates the board even in no-UI mode
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#4575 Add hotkey to Okay button in Campaign select window
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#4583 Add multiple languages from the box
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#4564 Fix sound effects when receiving artifacts from world map
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, sound

#4561 Use the path from the AI pathfinder when determining the nearest reachable cell instead of simply comparing distances
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: bug, logic

#4560 Set starting army in Archibald 7 scenario
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: logic, campaign

#4525 Add missing gettext translation calls and update POs
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/game/game_credits.cpp
Labels: improvement, translation

#4606 If a hero on the map has the custom empty army (OG editor bug/feature), give him a minimum army (one unit of level 1)
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#4600 Well : Clean up, optimize and make consistent with OG
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, ui

#4610 Allow to change Battle Speed using mouse wheel
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#4597 Don't copy data if it's unnessesary
  src/engine/system.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, ui, logic

#4620 Use correct message in marketplace for first exchange when not enough resources
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: bug, ui

#4609 Fix max music/sound volume
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#4627 Add random sign message
  src/fheroes2/maps/maps_objects.cpp
Labels: bug, ui

#4599 Fix heuristic for slow/haste spell in battle
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/kingdom/speed.cpp
  src/fheroes2/kingdom/speed.h
Labels: bug, logic

#4630 Fix monster recruit window position on World Map
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#4584 Load palette from AGG file
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/engine/image.cpp
  src/engine/image_palette.cpp
  src/engine/image_palette.h
  src/engine/image_tool.cpp
  src/engine/screen.cpp
  src/fheroes2/game/fheroes2.cpp
  src/tools/icn2img-vs2015.vcxproj
  src/tools/icn2img-vs2019.vcxproj
  src/tools/icn2img.cpp
Labels: improvement, ui, logic

#4640 AGG::LoadModifiedICN(): fix invalid Sprite::resize() call
  src/fheroes2/agg/agg_image.cpp
Labels: bug, ui, regression

#4635 Remove BUILD_RELEASE macro
  CMakeLists.txt
  Makefile
  Makefile.switch
  Makefile.vita
  VisualStudio/Release.props
  src/Makefile
  src/fheroes2/CMakeLists.txt
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/system/settings.cpp
Labels: bug, script

#4645 Fix regression with support of multiple languages
  src/fheroes2/agg/agg_image.cpp
Labels: ui, regression

#4649 Fix AI obsession with whirlpools and being always in sea
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, logic, AI

#4644 Fix logic for difficulty text, update POs and change contact, un-fuzzy Swedish translation
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: bug, translation

#4664 Interface::Basic::EventDefaultAction(): the action object can alter the status of the hero, so forcibly redraw the hero icon panel
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#4652 Make Unix script to automatically copy & extract all necessary assets from original HoMM2 distributions
  .github/workflows/make.yml
  CMakeLists.txt
  docs/INSTALL.md
  docs/README.txt
  script/demo/download_demo_version.sh
  script/homm2/extract_homm2_resources.sh
Labels: improvement, Linux, script, deployment, macOS

#4626 WorldPathfinder: implement "last move" logic, fix wrong penalty calculation algorithm
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/maps/ground.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, logic

#4670 Always mark Artesian Spring as visited, even if the hero was not able to drink from it
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#4671 Fix language names being incorrectly displayed in the list
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
Labels: bug, ui, translation

#4628 Add title for most of dialogs from map's objects
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#4688 Properly handle the day-week-month routine
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/world/world.cpp
Labels: bug, logic

#4636 Add some Italian translations
  files/lang/Makefile
  files/lang/it.po
  src/engine/translations.cpp
Labels: improvement, translation

#4702 Fix With's Hut name
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/maps/mp2.cpp
Labels: bug, ui

#4703 Show available creature count for PoL monster objects
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug

#4684 Update Norwegian translation
  files/lang/nb.po
Labels: improvement, translation

#4707 Show heroes on minimap
  src/fheroes2/gui/interface_radar.cpp
Labels: bug, improvement, ui

#4704 Add default castle's name is none is specified by editor
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, ui, crash

#4710 Make consistent campaign info dialog
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#4706 Play sounds from closest surrounding objects first
  src/engine/audio.cpp
  src/engine/audio.h
  src/fheroes2/game/game.cpp
Labels: bug, sound

#4705 Add Champion image for Stables object
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#4712 Use the OK button for the Tavern window
  src/fheroes2/castle/castle_tavern.cpp
Labels: bug, ui

#4708 Properly draw battle grid
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#4211 Troops split logic change
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, logic
