Repository ihhub/fheroes2, pull requests merged in 2021-07, with the labels that each got.

#3776 Fix passabilities for old save files
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: bug, logic, regression

#3781 Add link to code style to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: improvement

#3773 Add morale and luck normalize functions
  src/fheroes2/castle/captain.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/kingdom/luck.h
  src/fheroes2/kingdom/morale.cpp
  src/fheroes2/kingdom/morale.h
Labels: improvement

#3779 Improve AI logic
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, improvement, logic

#3783 Fix passabilities for old saves being resaved
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic, regression

#3782 getFilesFromDirectory(): FindFirstFile() searches for both long and short variants of names, so we need additional filtering
  src/engine/dir.cpp
Labels: Windows, bug, ui

#3767 Cannot summon boats close to some objects on a world map #2935
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: bug, logic

#3789 Do not show x marker for fully built castle icon
  src/fheroes2/castle/castle_ui.cpp
Labels: bug, ui

#3778 Update translation files and fix in-game translation function
  files/lang/Makefile
  files/lang/cs.po
  files/lang/es.po
  files/lang/fheroes2.pot
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/engine/translations.cpp
Labels: improvement, translation

#3790 Add an option to restart Campaign scenario
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: campaign, improvement, ui

#3791 Fix placement of creatures during Month of Monster event
  src/fheroes2/world/world.cpp
Labels: bug, logic

#3741 Implement continuous scrollbar
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/dist/fheroes2
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_base.cpp
  src/fheroes2/gui/ui_base.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui

#3759 Settings cleanup
  CMakeLists.txt
  Makefile
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  fheroes2.key
  src/Makefile.mingw
  src/Makefile.mingw32
  src/engine/CMakeLists.txt
  src/engine/audio_cdrom.cpp
  src/engine/audio_cdrom.h
  src/engine/audio_mixer.cpp
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/sdlnet.cpp
  src/engine/sdlnet.h
  src/fheroes2/CMakeLists.txt
  src/fheroes2/agg/agg.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_mode.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/tools/extractor.vcxproj
  src/tools/icn2img.vcxproj
  src/tools/music_wrapper.sh
  src/tools/til2img.vcxproj
  src/tools/xmi2mid.vcxproj
Labels: improvement

#3792 Add Bane / Alliance monster behavior for campaign scenarios
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: campaign, improvement, logic

#3784 Cleanup tools
  src/engine/screen.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/battle/battle_cell.cpp
Labels: improvement

#3793 Code cleanup and binary removal
  src/Makefile
  src/dist/fheroes2
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/agg/bin_info.h
Labels: improvement

#3794 Make AI hero task management
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: AI, high priority, improvement, logic

#3788 Version 0.9.5
  CMakeLists.txt
  appveyor.yml
  changelog.txt
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
Labels: improvement

#3798 AI heroes don't ever capture empty castles
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, bug

#3799 Removed Army::GetUniqueCount() and replaced it with AllTroopsAreSame()
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: improvement, logic

#3803 Add Alchemist Tower to the list of objects to be avoided by AI
  src/fheroes2/ai/ai_hero_action.cpp
Labels: AI, bug, logic

#3804 AI should check if an object is guarded while unveiling fog
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, bug, logic

#3810 Revert some auxiliary changes introduced in #3576
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#3806 code cleanup: Remove redundant c_str() calls
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement

#3811 DialogBattleNecromancy(): set cursor to Cursor::POINTER
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#3805 Fix town passability for some cases
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, high priority, logic

#3816 fix small font check for russian localization
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, translation

#3827 Post-release removing of unused headers and forward declarations
  src/engine/system.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_only.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/tools/extractor.cpp
  src/tools/icn2img.cpp
Labels: improvement

#3819 Clean-up normalize functions
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/kingdom/morale.cpp
Labels: improvement

#3809 If the hero's army does not have any of the original troops left alive at the end of the battle, then the hero should lose
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, logic

#3831 Fix crash in Maps::GetFreeIndexesAroundTile()
  src/fheroes2/maps/maps.cpp
Labels: bug, crash

#3820 Display translated text in campaign dialog
  src/fheroes2/campaign/campaign_data.cpp
Labels: improvement, translation

#3836 Align text evenly inside secondary skill window
  src/fheroes2/dialog/dialog_skillinfo.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui

#3835 Add additional getFilesFromDirectory() filtering on Vita
  src/engine/dir.cpp
Labels: bug, ui

#2993 Refine battle pathfinding using a recursive greedy depth-limited approach
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, logic

#3837 Add 500 EP for conquering a town regardless of defending hero existence
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
Labels: bug, logic

#3839 Fix Wizards scenario 3 with custom Ultimate Artifact
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, campaign, logic

#3817 replace System::GetEnvironment with getenv
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/system/settings.cpp
Labels: improvement

#3431 Fix next hero choose logic
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: bug, logic

#3774 Remove required spellpoints from scroll in Mage Guild
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog_spellinfo.cpp
Labels: improvement, ui

#3818 code cleanup: Replace size() for checking emptiness of a container with empty()
  src/engine/agg_file.cpp
  src/engine/audio_music.cpp
  src/engine/localevent.cpp
  src/engine/system.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_resourceinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_skillinfo.cpp
  src/fheroes2/dialog/dialog_spellinfo.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world.cpp
  src/tools/extractor.cpp
  src/tools/icn2img.cpp
  src/tools/xmi2mid_cli.cpp
Labels: improvement

#3815 Add clang-tidy integration
  .clang-tidy
  .github/workflows/clang_tidy.yml
  .github/workflows/sonarcloud.yml
Labels: improvement

#3848 Clang-Tidy workflow: use pull_request_target instead of pull_request
  .github/workflows/clang_tidy.yml
Labels: bug, script

#3847 Centering fast separation buttons
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, ui

#3826 Fix missing monster spell casting during battles
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/monster/monster_info.h
Labels: bug, logic

#3849 Clang-Tidy: disable some checks
  .clang-tidy
Labels: improvement, script

#3850 Clang-Tidy: disable cppcoreguidelines-avoid-magic-numbers, readability-braces-around-statements and readability-magic-numbers
  .clang-tidy
Labels: improvement, script

#3852 Fix inifinte loop during AI turn
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, regression

#3853 Make fog discovery by AI more efficient
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, improvement

#3854 Clang-Tidy: fix repo checkout for pull_request_target
  .github/workflows/clang_tidy.yml
Labels: bug, script

#3855 Clang-Tidy: disable cppcoreguidelines-pro-bounds-pointer-arithmetic and modernize-use-auto
  .clang-tidy
Labels: improvement, script

#3851 Group duplicated switch branches
  src/engine/localevent.cpp
  src/fheroes2/agg/m82.cpp
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/resource/artifact.cpp
Labels: improvement

#3857 Don't run the Clang-Tidy workflow on PRs from forks
  .github/workflows/clang_tidy.yml
Labels: high priority, script

#3822 Use explicit get methods instead of operator()
  src/engine/font.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_spellinfo.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/spell/spell_storage.cpp
Labels: improvement

#3838 Update ru/fr translations and the Makefile
  files/lang/Makefile
  files/lang/fr.po
  files/lang/ru.po
Labels: improvement, translation

#3856 Make AI to use Lich's ability properly
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: AI, improvement

#3769 Improve win/loss checks
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_over.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/world/world.cpp
Labels: bug, logic

#3860 Use std::chrono::steady_clock instead of std::chrono::high_resolution…
  src/engine/timing.cpp
  src/engine/timing.h
  src/fheroes2/gui/ui_tool.cpp
Labels: improvement, logic

#3861 Small performance optimizations
  src/fheroes2/army/army.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/direction.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#3864 Build .mo files in CI pipelines
  .github/workflows/make.yml
  appveyor.yml
  files/lang/Makefile
  files/lang/es.po.invalid
  files/lang/pl.po.invalid
  script/windows/fheroes2.iss
Labels: improvement, script

#3867 Implement the secure way to run clang-tidy checks from forks
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
Labels: improvement, script

#3869 Add translation support without Unicode
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement, ui

#3871 Clang-Tidy: turn off non-private-member-variables-in-classes
  .clang-tidy
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
Labels: improvement, script

#3866 Differentiate castle entrance and castle tiles
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_regions.cpp
Labels: bug, logic

#3874 Fix missing castle list
  src/fheroes2/castle/castle.cpp
  src/fheroes2/world/world.cpp
Labels: crash, regression

#3641 Implement Town Screen Hotkeys
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement, ui

#3892 Fix simultaneous activation of buttons in hero meeting screen
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#3891 Fix English phrasing and punctuation
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
Labels: bug, ui

#3893 Render on window resizing event
  src/engine/localevent.cpp
Labels: improvement, ui

#3895 Remove unused AlphaBlit overload
  src/engine/image.cpp
  src/engine/image.h
Labels: bug, logic

#3876 Implement regular win/loss conditions for multiplayer mode
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_over.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#3896 Don't run clang-tidy-pr-comments if there is no fixes.yml file
  .github/workflows/clang_tidy_comments.yml
Labels: bug, script

#3886 Remove Unicode support
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cmake.yml
  .github/workflows/make.yml
  .github/workflows/sonarcloud.yml
  CMakeLists.txt
  Makefile
  Makefile.vita
  VisualStudio/SDL2.props
  cmake/FindSDL2_ttf.cmake
  docs/INSTALL.md
  docs/README_cmake.md
  files/fonts/bigfonts.ttf
  files/fonts/dejavusans.ttf
  files/fonts/smallfonts.ttf
  files/lang/Makefile
  script/linux/install_sdl_1.sh
  script/linux/install_sdl_1_dev.sh
  script/linux/install_sdl_2.sh
  script/linux/install_sdl_2_dev.sh
  script/macos/install_sdl_1.sh
  script/macos/install_sdl_2.sh
  script/packaging/debian/control
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
  src/Makefile
  src/Makefile.all
  src/Makefile.bsd
  src/Makefile.mingw
  src/Makefile.mingw32
  src/Makefile.osx
  src/Makefile.vita
  src/engine/CMakeLists.txt
  src/engine/audio_music.cpp
  src/engine/audio_music.h
  src/engine/engine.cpp
  src/engine/font.cpp
  src/engine/font.h
  src/engine/tools.cpp
  src/fheroes2/CMakeLists.txt
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/agg_image.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#3888 clang-tidy: disable cppcoreguidelines-pro-type-union-access
  .clang-tidy
Labels: improvement, script

#3872 Use equal operator results as arguments
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#3879 Fix FHEROES2_IMAGE_SUPPORT build
  src/Makefile
  src/engine/CMakeLists.txt
  src/engine/image_tool.cpp
  src/tools/CMakeLists.txt
  src/tools/icn2img.cpp
  src/tools/til2img.cpp
Labels: bug

#3885 Add support for town hotkeys in fheroes2.key
  fheroes2.key
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement, ui

#3902 Fix incorrect cursor icon over castle
  src/fheroes2/game/game_startgame.cpp
Labels: bug, regression

#3904 Fix town fog area revealing
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game.h
Labels: bug, logic

#3910 Add font checksums for Polish / German / alt. Russian (XXI Vek) versions
  src/fheroes2/gui/ui_language.cpp
Labels: improvement, translation

#3907 Restore background music after playing short-term music effects
  .clang-tidy
  .github/workflows/clang_tidy.yml
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, sound

#3899 Improve project description in README.md and docs/README.md
  README.md
  docs/README.md
Labels: improvement

#3911 Highlight cells from where a monster will attack
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#3917 Do not draw flags for puzzle image
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, ui

#3914 Fix infinite loop after chain lightning spell
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic

#3766 Properly update artifact and resource sprites
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: bug, ui

#3918 AI: the first target of Chain Lighting can't be immune to it
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: AI, bug, logic

#3921 Fix UI defects in Kingdom castle dialog
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#3920 Fix AI archer avoid handfighting battle logic
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: AI, bug

#3922 Remove some useless experimental options
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#3925 Delete the fixes.yml existence check - it is no longer needed
  .github/workflows/clang_tidy_comments.yml
Labels: GitHub Actions, improvement, script

#3932 iconv: fix transliteration issues for certain languages
  files/lang/Makefile
  files/lang/es.po
  files/lang/pl.po
Labels: bug, translation

#3913 Add monster names, abilities and hero skills to translations
  files/lang/Makefile
  files/lang/cs.po
  files/lang/es.po
  files/lang/fheroes2.pot
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/dist/Makefile
  src/engine/translations.cpp
  src/engine/translations.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement, translation

#3931 Fix an assertion call during battle shadow rendering
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, crash, regression

#3924 Don't play ambient sounds during AI turn, move all battle sound-related stuff to Battle::Interface
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, sound

#3878 Use erase-remove idiom
  src/engine/tinyconfig.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement

#3908 Code style check workflow: use system clang-format-diff
  .github/workflows/code_style_check.yml
  script/tools/check_code_format.sh
  script/tools/clang-format-diff.py
Labels: GitHub Actions, improvement, script

#3937 Fix attacking after turning back in some cases
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic
