Repository ihhub/fheroes2, pull requests merged in 2021-03, with the labels that each got.

#2889 Fix assertion at the start of battle
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: bug, crash

#2891 Add PS Vita background image
  files/images/platform/psv/background.png
Labels: improvement, ui

#2892 Add Playstation Vita icon
  files/images/platform/psv/icon.png
Labels: improvement, ui

#2893 Update image tools
  src/engine/image_tool.cpp
  src/engine/image_tool.h
Labels: improvement, logic

#2850 Fix Split-related issues, and Implement some new ones
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, ui

#2890 AI: improve retreat condition
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: AI, improvement

#2884 Fix barrier fade
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#2887 Fix "Artifacts:" category in Oracle Screen
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: improvement, ui

#2894 engine: Fix endian.h include, absent in MinGW.
  src/engine/endian_h2.h
Labels: bug

#2897 Do not force reinitialization of castle data on redraw in Kingdom View event loop
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, logic

#2898 Do not allow the visiting hero to learn Library spells if the Library hasn't been built yet
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/spell/spell_storage.cpp
Labels: bug, logic

#2902 Preserve unit direction in battle if it moves strictly vertically
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, ui

#2895 Make MouseRelease* events one-shot to fix excessive FPS issue
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: bug, logic, ui

#2818 Cache released disabled button sprite
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement, ui

#2909 Don't give an extra day of life to a player without castles
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#2911 Fix Wildcard warnings by Visual Studio
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
Labels: Windows

#2912 Add new button sprites
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, ui

#2914 Fix MIN and MAX button drawings
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, ui

#2913 Fix the pathfinding near monsters (OG-style)
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#2908 AI: improvements for wide unit pathfinding
  src/fheroes2/battle/battle_pathfinding.cpp
Labels: AI, bug

#2903 AI: use mass damage spells in combat
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.h
Labels: AI, improvement

#2924 Still show the build window if there is not enough resources to build this building
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, ui

#2923 Fix double attack direction against large units
  src/fheroes2/battle/battle_action.cpp
Labels: bug

#2915 AI: ranged troops should move when blocked by a strong unit
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: AI, improvement

#2927 Fix missing cursor in Army Bar for SDL 1
  src/fheroes2/army/army_bar.cpp
Labels: bug, ui

#2929 Wait for user input at the end of Winning video
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
Labels: improvement, ui

#2930 Do not show external music option with an absent folder
  src/engine/system.h
  src/fheroes2/dialog/dialog_system.cpp
Labels: improvement, sound

#2933 Don't open the hero screen in readonly mode if it was opened from the meeting screen
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#2922 AI: support additional harmful combat spells
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: AI, improvement

#2937 Update no data error message
  src/fheroes2/agg/agg.cpp
  src/fheroes2/image/embedded_image.h
Labels: improvement, ui

#2938 Code cleanup and decoupling
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/font.cpp
  src/engine/font.h
  src/engine/translations.cpp
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_border.h
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_cpanel.h
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#2939 Update editor images
  editor/images/ground_beach.png
  editor/images/ground_desert.png
  editor/images/ground_dirt.png
  editor/images/ground_grass.png
  editor/images/ground_lava.png
  editor/images/ground_snow.png
  editor/images/ground_swamp.png
  editor/images/ground_wasteland.png
  editor/images/ground_water.png
Labels: improvement

#2941 Fix City of the dead incorrect monster info
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#2942 Update sound extractor tool
  src/tools/82m2wav.cpp
  src/tools/82m2wav.vcxproj
Labels: Windows, assets

#2948 Fix ArenaPathfinder backwards move logic
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#2730 Change damage description log message for few mass spells
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#2955 Fix playing background music during video playback on SDL1
  src/fheroes2/game/game_video.cpp
Labels: bug, sound

#2830 [Bugfix][2822] Sound off when minimized
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: improvement, sound

#2896 Replay auto battle manually if outcome is negative
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_main.cpp
Labels: improvement, ui

#2921 align spells in the magic book
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#2952 add some game-related objects to .gitignore
  .gitignore
Labels: improvement

#2932 Allow to place units in moat in front of the bridge
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#2949 Reset blind upon taking any damage
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, logic

#2943 AI: predict double cell attacks in combat
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.cpp
Labels: AI, improvement

#2925 more detail display for morale and luck
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
Labels: improvement, ui

#2962 Remove Interface options from the list
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_settings.cpp
Labels: bug, logic

#2963 Show full 1-pixel black border for Show Interface option
  src/fheroes2/dialog/dialog_system.cpp
Labels: improvement, ui

#2964 Show normal monster names in Visions spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, ui

#2965 Add initial implementation of View spells
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, ui

#2970 Fix multiple SonarQube code smells
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/engine/screen.h
  src/engine/xmi2mid.cpp
  src/fheroes2/castle/marketplace.h
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_radar.cpp
Labels: improvement

#2977 Fix multiple SonarQube code smells
  src/engine/localevent.cpp
  src/engine/rand.h
  src/engine/types.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/heroes/direction.h
  src/fheroes2/kingdom/payment.h
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/system/bitmodes.h
  src/fheroes2/world/world.h
Labels: improvement

#2978 Fix incorrect icon over ally's castle
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#2988 Fix last focus option
  src/fheroes2/game/game_startgame.cpp
Labels: bug, logic

#2989 Use rule of 9 for Ultimate Artifact placement
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#2960 Fix interaction with the castle bridge for flying units
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#3002 Fix missing sounds within System dialog
  src/fheroes2/agg/agg.cpp
Labels: bug, sound

#3000 Fix rendering of the Castle Captain's spell points bar
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/captain.h
Labels: bug, ui

#3005 Fix incorrect drawings for battle OKAY button
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#3010 Don't hide mouse cursor if the Skill Info dialog called from the Level Up dialog contains OK button
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: bug, ui

#2883 Fix boat drawing issue
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#3011 Fix distance calculation between cells on battlefield
  src/fheroes2/battle/battle_board.cpp
Labels: bug, logic

#3012 Fix Kingdom Overview selection drawings
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#3013 Fix logic of placing monsters for a New Month
  src/fheroes2/world/world.cpp
Labels: bug, logic

#3014 Allow to use mouse wheel anywhere for split troop dialog
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, ui

#3006 Rewrite player switching in multiplayer dialog
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/player_info.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
Labels: improvement, logic, ui

#3020 Fix game crash when trying to save/autosave a loaded game with vanquished human-controlled player
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, crash

#2991 Implement Cross army drag split
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/gui/interface_itemsbar.h
Labels: improvement, logic

#3018 Don't apply morale penalty to a hero if he wins a battle in a Graveyard, Shipwreck or Derelict Ship
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#3008 Show the surrender dialog even if there is not enough gold to surrender
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#3023 Fix Max/Min button position in monster recruit dialog
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: improvement, ui

#3022 Standartize icon position in town's dialog
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_town.cpp
Labels: improvement, ui

#3025 Fix scrollbar position in multiple places
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
Labels: bug, ui

#3024 Fix possibly incorrect arrow direction from shooters
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#3028 update positions of monster sprites and numbers on army status panel
  src/fheroes2/army/army.cpp
  src/fheroes2/gui/interface_status.cpp
Labels: bug, ui

#3029 Hypnotize spell behavior & description fix
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/spell/spell.cpp
Labels: bug, logic

#3038 Do not give additional 500 experience to the hero who won the battle if the opposing hero surrenders or flees
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic

#3033 Fix blind spell
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#3044 Fix rendering of Arm of the Martyr
  src/fheroes2/resource/artifact.cpp
Labels: bug, ui

#2219 Update Visual Studio project settings and configuration
  VisualStudio/Debug.props
  VisualStudio/Release.props
Labels: Windows, improvement

#3050 Fix VS compilation on 32-bit OSes
  VisualStudio/Debug.props
  VisualStudio/Release.props
Labels: bug

#3026 Reformat installation instruction and add Gentoo
  README.md
Labels: Linux, improvement

#3045 Reset hero spellpoints when restarting a battle
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#3021 Unneeded redraw
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, ui

#3052 Fix creature recture window UI
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: improvement, ui

#3048 Remove unused code
  src/engine/rect.cpp
  src/engine/rect.h
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/captain.h
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/castle/mageguild.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/statusbar.cpp
  src/fheroes2/gui/statusbar.h
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/pairs.h
  src/fheroes2/system/bitmodes.h
  src/fheroes2/world/world_regions.cpp
  src/fheroes2/world/world_regions.h
Labels: improvement

#3030 AI: implement missing combat spells
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
Labels: AI, improvement

#1616 Add PlayStation Vita support
  .travis.yml
  Makefile.vita
  doc/README_PSV.md
  files/images/platform/psv/sce_sys/icon0.png
  files/images/platform/psv/sce_sys/livearea/contents/bg.png
  files/images/platform/psv/sce_sys/livearea/contents/startup.png
  files/images/platform/psv/sce_sys/livearea/contents/template.xml
  src/Makefile
  src/Makefile.vita
  src/engine/dir.cpp
  src/engine/dir.h
  src/engine/engine.cpp
  src/engine/engine.h
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/logging.h
  src/engine/screen.cpp
  src/engine/system.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/system/settings.cpp
  src/thirdparty/libsmacker/smk_hufftree.c
Labels: improvement

#3056 Respect initial order of units (from top to bottom) when determining the order of unit moves in battle
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
Labels: bug, logic

#3053 Check that the hero is able to move before focusing him and starting his movement
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#3055 Archers shouldn't lose shots when attacking in melee
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#3060 Fix compilation of tools for makefile
  .github/workflows/scan-build.yml
  src/tools/Makefile
  src/tools/icn2img.cpp
  src/tools/til2img.cpp
Labels: Linux, bug

#3062 Add deployment for PSV build
  .travis.yml
Labels: improvement

#3054 Make recruitment of heroes more random
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#3064 Force units into empty slots first during merge
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: improvement, logic
