Repository ihhub/fheroes2, pull requests merged in 2021-04, with the labels that each got.

#3057 AI: estimate hero spell strength
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
Labels: AI, improvement

#3063 AI: fix defensive unit behaviour
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: AI, bug

#3077 Fix merging of the castle guardian army
  src/fheroes2/army/army.cpp
Labels: bug, ui

#3075 Prohibit the guardian hero from casting adventure spells
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: bug, logic

#3082 Fix resurrect check for units still standing
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: AI, bug

#3084 Remove the mobility index sprite info from the hero Quick Info dialog
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#3069 Fix building tools again
  VisualStudio/common.props
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/tools/icn2img.vcxproj
  src/tools/til2img.vcxproj
  src/tools/xmi2mid.vcxproj
Labels: Windows, bug

#3066 Improve castle garrison estimation
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
Labels: AI, improvement

#3086 Add an action to auto assign assignee of PR
  .github/workflows/pr_author_auto_assign.yml
Labels: improvement

#3085 Fix Choose Your Lord video sound
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
Labels: bug, sound

#3087 Fix incorrect window resolution in fullscreen mode
  src/engine/screen.cpp
Labels: SDL 2, bug, ui

#3088 Rescan heroes paths only when we have full info about players
  src/fheroes2/game/game_io.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: bug, ui

#3065 Randomize attack position choice and replace random_shuffle
  src/engine/rand.cpp
  src/engine/rand.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/puzzle.h
  src/fheroes2/world/world.cpp
Labels: logic

#3090 Fix dispell value estimation
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: AI, bug

#3089 Reset paralyze state when receiving spell damage
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#3092 Fix video playback
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_video.cpp
Labels: bug, sound

#3091 Conserve AI hero spellpoints
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: AI, improvement

#3096 Fix Sphinx missing rewards
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#3067 AI: fast units should try to get the first strike
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
Labels: AI, improvement

#3099 Add proper Large Obstacle generation for battlefields
  src/fheroes2/battle/battle_arena.cpp
Labels: improvement, ui

#3100 Display Lighthouse count in Kingdom Overview
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui

#3101 Add missing dot to sentences in few windows
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#3102 Fix full artifact bag message
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#3080 Version 0.9.2
  README.md
  appveyor.yml
  changelog.txt
  doc/README.txt
  sonar-project.properties
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/system/version.h
Labels: improvement

#3097 Fix many enumeration compilation warnings
  src/fheroes2/battle/battle.h
  src/fheroes2/castle/castle.h
Labels: improvement

#3109 Add stricter checks on VS compilation
  VisualStudio/common.props
  src/engine/engine.cpp
  src/engine/font.cpp
  src/engine/localevent.cpp
  src/engine/serialize.cpp
  src/engine/thread.cpp
  src/engine/tinyconfig.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_spriteinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#3110 Don't overwrite meaningful event processing result in Interface::Basic::HumanTurn()
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#3120 Update Display class capabilities
  src/engine/screen.cpp
  src/engine/screen.h
Labels: improvement

#3081 Make Game::ObjectFadeAnimation synchronous to perform events in the correct order
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, ui

#3126 Speed up ICN loading and remove useless image copying
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_cpanel.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement, ui

#3125 Fix ultimate artifact digging logic
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#3119 Fix for the #3117
  src/fheroes2/heroes/skill.cpp
Labels: bug, ui

#3142 Immediately hide hero's path before executing the animation of the Dimension Door spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, ui

#3144 Reset the spell on tile when AI-controlled hero has successfully captured an object
  src/fheroes2/ai/ai_hero_action.cpp
Labels: AI, bug, ui

#3130 Fix game score calculation
  src/fheroes2/game/game.cpp
Labels: bug, logic

#3146 Zero-initialize _data in Image::resize(), don't leave _data dangling in Image::operator=()
  src/engine/image.cpp
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, ui

#3148 Migrate Image::_data to std::unique_ptr
  src/engine/image.cpp
  src/engine/image.h
Labels: improvement

#3151 Remove old saves support till 0.8 version
  src/fheroes2/game/game_io.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: improvement

#3149 Fix excessive FPS issue in Dialog::ArmyJoinWithCost()
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, ui

#2986 Code cleanup
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_only.h
  src/fheroes2/heroes/heroes_indicator.h
  src/fheroes2/world/world.h
Labels: improvement

#3095 Implement the "faster monster of opposite army goes first" logic in the battle mode
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
Labels: bug, logic

#3153 Load correct video files to be played
  src/engine/dir.cpp
  src/engine/dir.h
  src/fheroes2/game/game_video.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, logic

#3161 fix dragon city guardians
  src/fheroes2/army/army.cpp
Labels: bug, logic

#3162 Recalculate hero path on focus change in Interface::Basic::EventNextHero()
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#3164 Fix Homebrew issues on macOS builds
  .github/workflows/macos_pull_request.yml
  .github/workflows/macos_release.yml
Labels: bug, macOS, script

#3163 Partially migrate Linux builds from Travis to GitHub Actions
  .github/workflows/linux_pull_request.yml
  .github/workflows/linux_release.yml
  .github/workflows/macos_release.yml
  .travis.yml
Labels: Linux, deployment, improvement, script

#3166 add message when visit Oracle
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#3168 Fix large object coverage in battles
  src/fheroes2/battle/battle_board.cpp
Labels: bug, logic

#3150 implement new necromancy window
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_main.cpp
Labels: improvement, ui

#3171 Highlight Lich's shot area
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#3174 Preserve the order of catapult shots
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic

#3061 Fix double shadow from heroes
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#3105 Hero info window, "Blood" morale shouldn't include exclamation mark
  src/fheroes2/heroes/heroes_indicator.cpp
Labels: improvement, ui

#3175 Remove cppclean workflow
  .github/workflows/static_analysis.yml
Labels: script

#3170 fix gold and exp dialog for the demon cave
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#3193 Fix mixed-up heroes in Battle::Arena::CanSurrenderOpponent()
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, ui

#3182 Fix issue with Stone Liths
  src/fheroes2/maps/maps.cpp
Labels: bug, logic

#3177 Visit artesian springs independently
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#3184 Fix saving scroll speed in the game config file
  src/fheroes2/system/settings.cpp
Labels: bug, ui

#3194 Enable builds for Linux with DEBUG on pull request
  .github/workflows/linux_pull_request.yml
Labels: improvement, script

#3173 Force the scan-build workflow to fail if any bugs found
  .github/workflows/scan-build.yml
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement, script

#3154 Enable triggering of positive morale event after soft wait
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, logic

#3196 Code cleanup and speedup
  VisualStudio/common.props
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/rect.cpp
  src/engine/rect.h
  src/engine/translations.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_only.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#3197 Fix object slicing issues
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: improvement

#3198 Update application icon
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/image/embedded_image.h
Labels: improvement, ui

#3070 Add asserts which helps me debug issues with tests
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement

#3200 Fix multiple SonarQube issues
  src/engine/image.cpp
  src/engine/image_tool.cpp
  src/engine/screen.cpp
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_only.h
  src/fheroes2/castle/captain.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#2629 Implementing CMake buildsystem for project
  .github/workflows/cmake_build.yml
  CMakeLists.txt
  README.md
  cmake/FindSDL2.cmake
  cmake/FindSDL2_image.cmake
  cmake/FindSDL2_mixer.cmake
  cmake/FindSDL2_ttf.cmake
  cmake/README.md
  cmake/README_fheroes2.md
  doc/README_cmake.md
  src/CMakeLists.txt
  src/dist/Makefile
  src/engine/CMakeLists.txt
  src/fheroes2/CMakeLists.txt
  src/thirdparty/CMakeLists.txt
  src/tools/CMakeLists.txt
Labels: improvement, script

#3208 Fix highlighting of the Lich shot area behind the castle walls
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#2476 Refactor for AllCastles
  src/engine/math_base.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#3203 set spells order as OG
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#3106 Use swap buttons in hero meeting dialog
  VisualStudio/common.props
  src/engine/image.cpp
  src/engine/image.h
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, logic, ui

#3202 Fix sphinx riddle dialogs
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_objects.cpp
Labels: bug, improvement, ui

#3220 Fix information displayed in castle quick info window
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#3221 Fix issue with incorrect rendering of spells in spellbook
  src/fheroes2/spell/spell_book.cpp
Labels: bug, regression, ui

#3223 Add proper support of other languages
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/agg_image.h
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
Labels: improvement, ui

#3228 Fix 4592 warning on Visual Studio
  VisualStudio/common.props
  src/engine/agg_file.h
Labels: bug

#3123 Don't allow the player to scroll world map while hero is moving
  src/fheroes2/game/game.h
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#3229 Run cmake_build.yml workflow only on master branch
  .github/workflows/cmake_build.yml
Labels: script

#3230 Fix cursor during video playback
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
Labels: bug, ui

#3195 aling horizontal positions of columns and flags at oracle dialog
  src/fheroes2/dialog/dialog_thievesguild.cpp
Labels: improvement, ui

#3219 Display correct message when capturing abandoned mine
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#3231 Set requested music as current only if it is actually played
  src/fheroes2/agg/agg.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, sound

#3238 Dont redraw objects under hero
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, ui

#3237 Fix the display of the army in the castle quick info window
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#3251 Don't run animation of lowering the bridge on bridge destruction if bridge is already lowered
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, ui

#3254 Fix passability for some big obstacles in battles
  src/fheroes2/battle/battle_board.cpp
Labels: bug, ui

#3259 ResizeToShortName(): properly handle filenames with dots
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: bug, ui

#3264 Fix Interface::ListBox::GetFromPosition()
  src/fheroes2/gui/interface_list.h
Labels: bug, ui

#3265 Migrate SonarCloud analysis to GitHub Actions
  .github/workflows/sonarcloud.yml
  .travis.yml
Labels: improvement, script

#3169 Add letters for World View and View spells
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement, ui

#3250 Fix bridge operation for flying units in the "no interface" mode
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic

#3267 Update Visual Studio package installation and demo setup
  .gitignore
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  VisualStudio/common.props
  appveyor.yml
  doc/README.txt
  script/demo/demo_windows.bat
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
Labels: Windows, improvement, script

#3266 Use SonarCloud cfamily cache to speed up analysis
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: improvement, script

#3268 Show correct message for hero's option dialog buttons
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#3270 Dimension door animation
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#3271 Add title to Arena dialog
  src/fheroes2/dialog/dialog_arena.cpp
Labels: improvement, ui

#3272 Add titles to Alchemist Tower and Stables dialogs
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#3274 Show Mage Guild always in center
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/castle/castle_mageguild.cpp
Labels: improvement, ui

#3258 Add initial support of russian localization
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui

#3275 Remove some unused code
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/player_info.h
  src/fheroes2/gui/statusbar.cpp
  src/fheroes2/gui/statusbar.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/gui/ui_scrollbar.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/maps/position.cpp
  src/fheroes2/maps/position.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
  src/fheroes2/system/bitmodes.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#3279 Allow the hero to retreat if, while in the castle, he attacks the hero outside the castle
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic

#3284 Fix shadows for all monster mini sprites
  src/engine/image.cpp
  src/engine/image.h
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui

#3295 Don't take Mage Guild level into account when calculating count of archers in castle towers
  src/fheroes2/battle/battle_tower.cpp
Labels: bug, logic

#3189 Fix redrawing some objects near hero
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#3249 Fix -Wextra-semi compilation warning findings
  src/Makefile
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_only.h
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_heroes.h
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/system/bitmodes.h
  src/fheroes2/system/settings.cpp
Labels: improvement

#3296 Do not generate Puzzle image on map loading
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/resource/artifact_ultimate.cpp
  src/fheroes2/resource/artifact_ultimate.h
Labels: improvement

#3298 Remove world: abandoned mine random resource option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#3306 Fix rendering of "Not enough gold" text in Dialog::ArmyJoinWithCost()
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, ui

#3307 Teleport battle spell: verify target cell passability for the correct (teleporting) unit
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic

#3288 Battle log & spell resistance fix
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, logic, ui

#3263 Allow switching heroes in hero dialog if it was opened from meeting dialog
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui
