Repository ihhub/fheroes2, pull requests merged in 2021-10, with the labels that each got.

#4296 Fix artifact selection area
  src/engine/image.cpp
  src/fheroes2/resource/artifact.cpp
Labels: improvement, ui

#4287 Correct evaluation of AI hero recruitment and meeting
  src/fheroes2/heroes/heroes.cpp
Labels: improvement, AI

#4295 Add monster double attack cell highlighting
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#4292 Add confirmation message in Alchemist Tower
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#4302 Fix well when hero has mana >= max
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#4308 Kingdom::isVisited(): return the correct result for a tile with a hero on it
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#4304 Fix rewards in the demon cave
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#4203 Fix adventure border rendering
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: bug, ui

#4310 Add headers for all Daemon Cave dialogs
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#4283 New week is only determined through current day + map seed
  src/engine/rand.h
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/kingdom/week.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, logic

#4306 Correct resource position in castle window
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
Labels: improvement, ui

#4312 Use within-loop variables in repeatPattern()
  src/fheroes2/gui/interface_border.cpp
Labels: improvement

#4309 Minor improvements to installation scripts
  appveyor.yml
  docs/README.txt
Labels: improvement, script, deployment

#4317 Fix monster position on World Map
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, ui

#4318 Before manual battle we should reset artifacts that are planned for transfer after instant battle
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#4316 Version 0.9.8
  CMakeLists.txt
  Makefile.switch
  appveyor.yml
  changelog.txt
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
Labels: improvement

#4326 Properly show the attack cursor when the attack square is located at the top of the castle sprite
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#4520 Cover more cases for shadow tile images
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, crash

#4521 Fix incorrect map loading algorithm
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/mp2_helper.cpp
Labels: crash, regression

#4522 Fix interaction passability with water objects
  src/fheroes2/maps/mp2.cpp
Labels: bug, logic

#4482 Use original alignment for Rating, Map Size in gameinfo window
  files/lang/cs.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: bug, ui

#4528 Correct original Waterfall images to remove Cave
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui

#4529 Remove extra assertion for Reefs
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, crash

#4530 Add credits to original HoMM2 team
  src/fheroes2/game/game_credits.cpp
Labels: improvement, ui
