Repository ihhub/fheroes2, pull requests merged in 2021-09, with the labels that each got.

#4110 Add short save file description
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: improvement, ui

#4058 Add monsters into High Score dialog
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/monster/monster_anim.cpp
  src/fheroes2/monster/monster_anim.h
Labels: improvement, ui

#4116 Update translation files
  files/lang/cs.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
Labels: improvement, translation

#4080 Update French translation
  files/lang/fr.po
Labels: improvement, translation

#4125 Return only unique maps (based on map file name) from PrepareMapsFileInfoList()
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/system/settings.cpp
Labels: bug, ui

#4137 Alignment fix of scenario info window
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: bug, ui

#4140 Remove flags from most of the captured objects when losing
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world.cpp
Labels: bug, ui

#4155 Fix incorrect object info when a hero stands on it
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#4159 Fix medium portrait issues
  src/fheroes2/heroes/heroes.cpp
Labels: improvement, ui

#4162 Add first German translation
  files/lang/de.po
Labels: improvement, translation

#4104 Remove redundant member initializations
  .clang-tidy
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/heroes/heroes_base.cpp
Labels: improvement

#4118 Optimize Battle Arena related code
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement

#4164 Boat boarding animation speed doesn't depend on hero speed
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#4165 Fix Faerie Ring passability
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4163 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4168 audio_music: log the reason why mixer could not be created
  src/engine/audio.cpp
Labels: improvement, sound

#4170 Add popup dialogs for some buttons
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_highscores.cpp
Labels: improvement, ui

#4158 Version 0.9.7
  CMakeLists.txt
  Makefile.switch
  appveyor.yml
  changelog.txt
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/version.h
Labels: improvement

#4161 Fix passability for tiles with shadows only
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic

#4156 Fix black edges on view world
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/kingdom/view_world.h
Labels: bug, ui

#4153 Allow hero to traverse Stone Liths and Whirlpools even if he has no movement points left
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: bug, logic

#4177 Fix ability to attack a monster through a barrier
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#4179 Code cleanup and correction
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/gui/text.h
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_recruits.cpp
  src/fheroes2/heroes/heroes_recruits.h
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/pairs.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world.cpp
Labels: improvement, logic

#4180 Fix passability of mines
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4187 Lock mouse within the window in multi-display device
  src/engine/screen.cpp
Labels: improvement, ui

#4188 Fix incrementing days spent value after reloading a campaign save
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_mainmenu.cpp
Labels: bug, logic, campaign

#4189 Fix adventure border rendering on higher resolutions
  src/fheroes2/gui/interface_border.cpp
Labels: improvement, ui

#4106 Display message about Ultimate Artifact after the battle
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_main.cpp
Labels: bug, ui

#4183 Fix Maps::getAroundIndexes()
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/world/world.cpp
Labels: bug, sound

#4193 Fix incorrect rendering for game settings window with Evil interface
  src/fheroes2/dialog/dialog_game_settings.cpp
Labels: bug, ui

#4195 Fix post battle crash
  src/fheroes2/battle/battle_main.cpp
Labels: logic, crash, regression

#4194 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4198 Remove unused translation strings
  files/lang/cs.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
Labels: improvement, translation

#4191 Use bitwise OR instead of addition in deserialization code
  src/engine/serialize.cpp
Labels: improvement

#4201 Remove bugged union experimental options
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#4202 Remove more unused functions
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/fheroes2/game/game_static.cpp
Labels: improvement

#4196 Fix some cases with Tree passabilities
  VisualStudio/common.props
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic, high priority

#4204 Add hotkey for View World dialog
  fheroes2.key
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#4184 Reset focus when hero was dismissed, use KEY_RETURN for EVENT_OPENFOCUS by default
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_list.h
Labels: bug, ui

#4205 Add Spell description window in monster info dialog
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/engine/types.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/world/world.cpp
Labels: improvement, ui, logic

#4209 align elements on artifact combat dialog
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#4210 Battle command cleanup
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement

#4213 Fix some code smells introduced in recent commits
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
Labels: improvement

#4215 Add Castle::isFortificationBuild to reduce duplication
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
Labels: improvement

#4219 Fix passabilities related to cracks
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic, high priority

#4224 Correct castle building active area
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_building_info.cpp
  src/fheroes2/castle/castle_building_info.h
Labels: improvement, ui

#4225 Fix incorrect level of Lightning Rod artifact
  src/fheroes2/resource/artifact.cpp
Labels: bug, logic

#4229 Correct battle speed change for monsters
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#4221 Fix wrong campaign award in Roland Campaign's branching scenario
  src/fheroes2/campaign/campaign_data.cpp
Labels: bug, logic, campaign

#4113 Cleanup GetKingdomStartingResources
  src/fheroes2/game/game_static.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: improvement

#4223 Add the FAQ to the repository home page.
  README.md
  docs/README.md
Labels: improvement, deployment

#4243 Fix passability for tall objects
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic, high priority

#4228 Add getBattleResult to reduce code duplication
  src/fheroes2/battle/battle_main.cpp
Labels: improvement

#4244 Fix an empty list of heroes in the Kingdom Overview after the dismissal or loss of a hero
  src/fheroes2/gui/interface_list.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#4218 Flatten HeroBase::CanCastSpell and fix result without error output
  src/fheroes2/heroes/heroes_base.cpp
Labels: improvement

#4208 Fix deterministic battle outcome
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle.cpp
Labels: bug, logic

#4235 Optimize artifacts income calculation in Kingdom::GetIncome
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement

#4252 Fix bridge animation during battle
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#4253 Tiny code speedups
  src/engine/system.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/direction.cpp
  src/fheroes2/heroes/route.cpp
Labels: improvement

#4259 Fix cmake library include directories for engine target
  CMakeLists.txt
  src/engine/CMakeLists.txt
Labels: deployment, CMake

#4222 Small Arena ctor optimization
  src/fheroes2/battle/battle_arena.cpp
Labels: improvement

#4271 Fix troop position in the Pyramid
  src/fheroes2/army/army.cpp
Labels: bug, logic

#4247 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4249 Unselect initial town in the Town Portal spell list
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, ui

#4275 Replace scrollbar in Experimental Settings dialog
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_settings.cpp
Labels: improvement, ui

#4251 Fix scrollbar rendering in select lists
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, ui

#4272 AI can visit Pyramids
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#4280 Fix active building area in castle window
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, ui

#4281 Fix application hang during AI turn while attacking an object with gu…
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, logic

#4273 Improve Week class
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/kingdom/week.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/world/world.cpp
Labels: improvement

#4009 Make Windows script to automatically copy & extract all necessary assets from original HoMM2 distributions
  .github/workflows/make.yml
  CMakeLists.txt
  appveyor.yml
  docs/DEVELOPMENT.md
  docs/INSTALL.md
  docs/README.txt
  script/demo/demo_windows.bat
  script/demo/download_demo_version.bat
  script/demo/download_demo_version.ps1
  script/demo/download_demo_version.sh
  script/homm2/README.md
  script/homm2/extract_homm2_dos_anim.bat
  script/homm2/extract_homm2_dos_anim.ps1
  script/homm2/extract_homm2_resources.bat
  script/homm2/extract_homm2_resources.ps1
  script/windows/fheroes2.iss
Labels: improvement, script, deployment

#4282 Fix passabilities of action objects
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic

#4284 Fix AI hero being stuck on Stoneliths
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, AI

#4285 Fix Altars' passabilities
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4286 Develop castle during AI hero purchase
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: logic, AI

#4289 Do not place wandering troops on OBJ_COAST tile if there are no other OBJ_COAST tiles nearby
  src/fheroes2/world/world.cpp
Labels: bug, logic

#4291 Fix Resurrection spell regression
  src/fheroes2/battle/battle_arena.h
Labels: logic, regression

#4290 Show map type icons in New Map lists
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: improvement, ui

#4294 Grey out experimental disabled option
  src/fheroes2/dialog/dialog_settings.cpp
Labels: improvement, ui

#4293 Add title to all artifact related windows
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui
