Repository ihhub/fheroes2, pull requests merged in 2021-08, with the labels that each got.

#3930 Update skill order for new heroes
  src/fheroes2/heroes/skill.cpp
Labels: improvement, ui

#3940 Fix incorrect icons for scenario information dialog
  src/fheroes2/gui/player_info.cpp
Labels: improvement, ui

#3934 Add hotkeys for Well dialog
  fheroes2.key
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement, ui

#3800 Castle Construction Screen, Tavern, one of the heroes available in the tavern changes every time the save file is loaded
  src/fheroes2/castle/castle.cpp
Labels: bug, logic

#3939 Remove sortTiles flag from Maps::GetAroundIndexes
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#3941 Fix incorrect Alliance conditions for certain maps
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: bug, logic

#3942 Use 256x256 icon for Switch, mention Switch in the Snapshots section of INSTALL.md
  docs/INSTALL.md
  files/images/platform/switch/icon.png
Labels: deployment, improvement

#3944 Fix a crash while AI uses Summon Elemental spell during battle
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
Labels: AI, bug, crash

#3947 Fix build on PSV
  src/engine/dir.cpp
Labels: bug

#3952 Remove duplicated arena size defines
  src/fheroes2/battle/battle_arena.h
Labels: improvement

#3935 Improvements for FR and RU translations
  files/lang/fr.po
  files/lang/ru.po
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/resource/artifact.cpp
Labels: improvement, translation

#3950 Battle::Board::GetPath(): minor optimization
  src/fheroes2/battle/battle_board.cpp
Labels: improvement

#3951 Make captured object event messages to contain yellow titles
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui

#3958 Update Switch icon
  files/images/platform/switch/icon.jpg
  files/images/platform/switch/icon.png
Labels: improvement, ui

#3957 Fix incorrect translation for dynamic language switching
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/kingdom/luck.h
  src/fheroes2/kingdom/morale.cpp
  src/fheroes2/kingdom/morale.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
  src/fheroes2/kingdom/speed.cpp
  src/fheroes2/kingdom/speed.h
Labels: bug, translation

#3955 Fixup .PHONY targets in makefiles
  Makefile
  Makefile.vita
  src/Makefile
  src/dist/Makefile
  src/engine/Makefile
  src/thirdparty/libsmacker/Makefile
  src/tools/Makefile
Labels: improvement, script

#3954 Clang-Tidy: disable cppcoreguidelines-pro-bounds-constant-array-index
  .clang-tidy
Labels: improvement, script

#3946 Provide issue templates for the most common issue types
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: improvement

#3964 Fix monster joining logic
  src/fheroes2/army/army.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/monster/monster.h
Labels: bug, logic

#3962 Remove extra class specifiers in static member function calls, ERROR_LOG already prints __FUNCTION__, so we shouldn't print function name once again
  src/fheroes2/battle/battle_board.cpp
Labels: improvement

#3960 Add links to README_switch.md in INSTALL.md and DEVELOPMENT.md, rename "PS Vita" to "PlayStation Vita"
  docs/DEVELOPMENT.md
  docs/INSTALL.md
Labels: deployment, improvement

#3961 Minor improvements
  .github/workflows/make.yml
  Makefile.switch
Labels: deployment, improvement, script

#3967 Add translation support for missing places
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, translation

#3966 Add titles to some dialogs
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, ui

#3968 Display the position of a hero or a castle on radar while right clicking
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
Labels: improvement, ui

#3971 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#3969 Ignore .mo files
  .gitignore
Labels: improvement

#3963 Clang-Tidy: disable cppcoreguidelines-pro-bounds-array-to-pointer-decay
  .clang-tidy
Labels: improvement, script

#3973 Add direct preview of changes in system options dialog
  data/Netlodr.dat
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/dialog/dialog_system_options.h
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#3979 Update status window in WhirlpoolTroopLooseEffect() if troops has fallen overboard
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#3980 Remove mistakenly added file
  data/Netlodr.dat
Labels: bug, regression

#3959 Version 0.9.6
  CMakeLists.txt
  Makefile.switch
  appveyor.yml
  changelog.txt
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
Labels: improvement

#3982 INSTALL.md: add download links for PS Vita and Switch
  docs/INSTALL.md
Labels: improvement, deployment

#3985 Remove unused CONFIGURE_FHEROES2_LOCALEDIR from makefiles
  CMakeLists.txt
  Makefile
  src/fheroes2/CMakeLists.txt
Labels: improvement, script

#3981 Clang-Tidy: disable cppcoreguidelines-avoid-non-const-global-variables
  .clang-tidy
Labels: improvement, script

#3976 Remove extra check: res should have no other value than END_TURN here
  src/fheroes2/game/game_startgame.cpp
Labels: improvement

#3992 Game settings dialog: reset current language to English if game resources doesn't support other languages
  src/fheroes2/dialog/dialog_game_settings.cpp
Labels: bug, logic

#3989 Fix polish encoding
  files/lang/Makefile
Labels: bug, translation

#3998 Minor documentation fixes
  CONTRIBUTING.md
  docs/DEVELOPMENT.md
Labels: improvement

#3990 Replace TinyConfig::AddEntry with simple insert
  src/engine/tinyconfig.cpp
  src/engine/tinyconfig.h
Labels: improvement

#3993 A not visited obelisk remains not visited after the UA has been found.
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, logic

#4000 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4004 Documentation fixes
  CONTRIBUTING.md
  README.md
  cmake/README.md
  cmake/README_fheroes2.md
  docs/DEVELOPMENT.md
  docs/INSTALL.md
  docs/README.md
  docs/README.txt
  docs/README_PSV.md
  docs/README_cmake.md
  docs/README_switch.md
  script/demo/README.md
  script/packaging/debian/README.Debian
  script/windows/README.md
Labels: improvement, deployment

#3975 Audio thread-safety fixes, various bugfixes
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/engine/audio.cpp
  src/engine/audio.h
  src/engine/audio_mixer.cpp
  src/engine/audio_mixer.h
  src/engine/audio_music.cpp
  src/engine/audio_music.h
  src/engine/engine.cpp
  src/engine/localevent.cpp
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/tools/extractor.vcxproj
  src/tools/icn2img.vcxproj
  src/tools/til2img.vcxproj
  src/tools/xmi2mid.vcxproj
  src/tools/xmi2mid_cli.cpp
Labels: bug, sound

#3970 Remove zoomIn flag from ViewWorld::ZoomROIs::ChangeZoom
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/kingdom/view_world.h
Labels: improvement

#3983 Move duplicated code to filterByName function
  src/engine/dir.cpp
Labels: improvement

#3933 allow player to immediately edit save file name without clicking on the input field
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: improvement, ui

#3956 Convert Kingdoms::size() method to static member
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: improvement

#3995 Deduplicate settings code
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#4013 Make sure that a random filename will not clash with the names of existing files
  script/demo/demo_windows.ps1
Labels: improvement, script

#4012 Optimize Battle Arena related code
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement

#4001 Do not let the player get a random artifact that allows him to win the game
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#3972 Properly handle cross-moat attacks
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic

#4016 Fix too many free slots in cross-army splitting
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, logic

#4022 Fix Holy Shout being applied on Dwarves
  src/fheroes2/monster/monster_info.cpp
Labels: bug, logic

#4017 Update scrollbar logic
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/gui/ui_scrollbar.h
Labels: bug, improvement, ui

#3828 Add support for h2d file format with first data file
  .github/workflows/make.yml
  VisualStudio/common.props
  appveyor.yml
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  files/data/resurrection.h2d
  script/windows/fheroes2.iss
  src/fheroes2/CMakeLists.txt
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/h2d/h2d.h
  src/fheroes2/h2d/h2d_file.cpp
  src/fheroes2/h2d/h2d_file.h
Labels: improvement, ui, assets

#4003 Update French translation
  files/lang/fr.po
Labels: improvement, translation

#4028 CMake: install h2d files to the game data directory
  CMakeLists.txt
Labels: improvement, script, CMake

#4021 Add named ObjectType enumeration
  src/engine/pathfinding.h
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/m82.h
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/visit.cpp
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/mounts.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
  src/fheroes2/world/world_regions.cpp
Labels: improvement

#3898 Remove TextInterface
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
Labels: improvement

#4029 SonarCloud: fix sonar.links.ci
  sonar-project.properties
Labels: improvement, script

#4025 Fix max ballista shots
  src/fheroes2/resource/artifact.cpp
Labels: bug, logic

#4030 Fix multiple SonarQube Smells
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/engine/image.cpp
  src/engine/image.h
  src/engine/localevent.cpp
  src/engine/screen.h
  src/engine/serialize.h
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/til.cpp
  src/fheroes2/agg/til.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/ui_base.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_actions.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/resource/artifact_ultimate.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, improvement, regression

#4034 Game::EnvironmentSoundMixer(): remove extra Audio::isValid() check that blocks the main thread
  src/fheroes2/game/game.cpp
Labels: bug, sound, regression

#4032 Place Ultimate artifact not always in the center of puzzle image
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/resource/artifact_ultimate.cpp
  src/fheroes2/resource/artifact_ultimate.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: bug, logic

#4042 make.yml: make translation generation a separate step, use make -C instead of cd && make
  .github/workflows/make.yml
Labels: improvement, script, GitHub Actions

#4018 Battle pathfinding: store passability info separately for the head and tail of wide units, improve AI pathfinding a bit
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, improvement, logic

#4039 Display same name maps in the list of available maps
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
Labels: bug, logic

#4040 Build tools as a part of VS compilation
  .github/workflows/vs2019.yml
  src/tools/82m2wav-vs2015.vcxproj
  src/tools/bin2txt-vs2015.vcxproj
  src/tools/bin2txt-vs2019.vcxproj
  src/tools/extractor-vs2015.vcxproj
  src/tools/extractor-vs2019.vcxproj
  src/tools/extractor.cpp
  src/tools/icn2img-vs2015.vcxproj
  src/tools/icn2img-vs2019.vcxproj
  src/tools/icn2img.cpp
  src/tools/til2img-vs2015.vcxproj
  src/tools/xmi2mid-vs2015.vcxproj
Labels: improvement, Windows, script

#4045 Fix SonarQube extra smells
  src/engine/math_base.h
  src/engine/screen.cpp
  src/engine/serialize.h
  src/engine/tools.cpp
  src/engine/translations.cpp
  src/engine/xmi2mid.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#4044 Audio: make valid atomic
  src/engine/audio.cpp
  src/fheroes2/agg/agg.cpp
Labels: improvement, sound

#4050 Fix incorrect rendering on fog tile
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, ui

#4054 Fix invalid reference in FilterResolutions
  src/engine/screen.cpp
Labels: bug, ui

#4056 Make check_code_format script executable
  script/tools/check_code_format.sh
Labels: improvement, script

#4036 Add popup dialogs in Kingdom Overview UI
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui

#4055 Ensure strict ordering in SortResolutions
  src/engine/screen.cpp
Labels: improvement

#4035 Remember UI position in Kingdom Overview dialog
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui

#4023 Drop duplicated enum and replace some magic numbers with its values
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_tower.cpp
Labels: improvement

#4051 Fix some issues found by clang UBSan
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/gui/interface_status.cpp
Labels: bug, improvement

#4057 clang-tidy: enable AllowSoleDefaultDtor option for cppcoreguidelines-special-member-functions check
  .clang-tidy
Labels: improvement, script

#4052 Implement CaseInsensitiveCompare for filename sorting
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement, ui

#4059 Don't ignore in<>out mismatch in Image Transpose
  src/engine/image.cpp
Labels: improvement

#4068 Properly restore captain's spell points after quick battle
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#4060 Use distinct image for the "Swap heroes" button
  src/fheroes2/castle/castle_dialog.cpp
Labels: improvement, ui

#4061 Eradicate more reinterpret_cast calls
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/tools/CMakeLists.txt
  src/tools/bin2txt.cpp
Labels: improvement

#4077 Remove unused LOSS_STARTHERO loss condition
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_over.h
Labels: improvement

#4076 Handle Escape/Enter keys in various settings dialogs
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: bug, ui

#4069 Calculate the number of stack-to-stack splitting options using the total quantity from both stacks when splitting to the stack with the same troop type
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, improvement, ui, regression

#4078 Fix AI behavior during siege
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, AI

#4038 Add object count for weekly object income message
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, ui

#4082 Rename HeroBase's HasArtifact to artifactCount for readability
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#4095 Heroes::inCastle(): respect GUARDIAN mode
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: bug, logic

#4094 Simplify passability logic a bit, clarify function descriptions
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, logic

#4102 Fix scrollbar position in Kingdom Overview dialog
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#4111 AI can capture Haunted mines
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#4107 Replace ostringstream by string
  src/engine/zzlib.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell_storage.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#4073 Fix the logic in Army::GetMoraleModificator()
  src/fheroes2/army/army.cpp
Labels: improvement

#4072 Restart of the battle should lead to the same results
  src/engine/rand.cpp
  src/engine/rand.h
  src/engine/tools.h
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#4112 Add base roles for AI heroes
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: improvement, AI
