Repository ihhub/fheroes2, pull requests merged in 2021-06, with the labels that each got.

#3583 Improvements for Windows scripts
  script/demo/demo_windows.ps1
  script/windows/install_packages.bat
Labels: Windows, improvement, script

#3584 Fix inaccurate object sorting by distance
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: bug, logic

#3586 Add popup dialogs for missing options and buttons
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game_newgame.cpp
Labels: improvement, ui

#3585 Fix crash in Roland 10 scenario
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: crash

#3218 Use XDG directories
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/system/settings.cpp
Labels: Linux, improvement

#3595 Fix missing letter when splitting text string
  src/fheroes2/gui/text.cpp
Labels: bug, ui

#3590 Adapt scripts for downloading the demo version to multi-user environment
  script/demo/demo_unix.sh
  script/demo/demo_windows.bat
  script/demo/demo_windows.ps1
Labels: improvement, script

#3582 Create Windows executable installers
  appveyor.yml
  script/windows/fheroes2.iss
Labels: Windows, improvement, script

#3600 Fix AppVeyor missing installer artifact
  appveyor.yml
Labels: Windows, bug, script

#3599 Fix Windows shortcuts
  script/windows/fheroes2.iss
Labels: Windows, improvement, script

#3596 Version 0.9.4
  CMakeLists.txt
  appveyor.yml
  changelog.txt
  script/windows/fheroes2.iss
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_logo.cpp
  src/fheroes2/system/version.h
Labels: improvement

#3606 Correct Cmake compilation flags
  .github/workflows/cmake_build.yml
  src/CMakeLists.txt
Labels: CMake, bug

#3614 Fix PoL campaign selection missing rendering
  src/fheroes2/game/game_newgame.cpp
Labels: bug, campaign, ui

#3605 Update clang-format to C++11
  .clang-format
Labels: improvement, script

#3611 Combat, when the Genie's special ability triggers (Genie destroys half the enemy troops!) if there is only one creature in the troop, the troop should be decimated
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic

#3612 Adventure map, after the teleportation the Boat should not be positioned in the Whirlpool on an already occupied square
  src/fheroes2/world/world.cpp
Labels: bug, logic

#3610 Campaign, some names of bonuses don't fit the box and should be shortened #3509
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: improvement, ui

#3617 Combat, when a troop of Dwarves resists a spell, the message should be displayed only after the animation of the spell
  src/fheroes2/battle/battle_action.cpp
Labels: bug, ui

#3629 Maps::Tiles::setBoat(): properly set unique id for pushed addon
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, ui

#3635 Dialog::Marketplace() : Fix usage of wrong kingdom during battle (if called from surrender dialog)
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: bug, ui

#3637 Code speed up and cleanup
  src/engine/pal.cpp
  src/engine/rand.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/heroes/skill_static.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/position.cpp
Labels: improvement

#3616 Fix number of choices when splitting a troop into multiple troops
  src/fheroes2/army/army_bar.cpp
Labels: bug, ui

#3576 Fix attacking monster sprite behavior
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, ui

#3591 Adventure map, it should be possible to attack a hero located on a Temple
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#3638 Add more compilation flags
  VisualStudio/common.props
  src/engine/audio_mixer.cpp
  src/engine/audio_music.cpp
  src/engine/serialize.cpp
  src/engine/tools.cpp
  src/engine/xmi2mid.cpp
  src/engine/zzlib.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/m82.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#3639 Remove XML usage
  .github/workflows/scan-build.yml
  CMakeLists.txt
  Makefile
  files/stats/animations.xml
  files/stats/artifacts.xml
  files/stats/battle.xml
  files/stats/buildings.xml
  files/stats/globals.xml
  files/stats/monsters.xml
  files/stats/payments.xml
  files/stats/profits.xml
  files/stats/skills.xml
  files/stats/spells.xml
  files/stats/stevenaus-03.7z
  src/Makefile
  src/dist/Makefile
  src/fheroes2/CMakeLists.txt
  src/fheroes2/army/army.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/payment.h
  src/fheroes2/kingdom/profit.cpp
  src/fheroes2/kingdom/profit.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/resource.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/thirdparty/CMakeLists.txt
  src/thirdparty/tinyxml/Makefile
  src/thirdparty/tinyxml/tinystr.cpp
  src/thirdparty/tinyxml/tinystr.h
  src/thirdparty/tinyxml/tinyxml.cpp
  src/thirdparty/tinyxml/tinyxml.h
  src/thirdparty/tinyxml/tinyxmlerror.cpp
  src/thirdparty/tinyxml/tinyxmlparser.cpp
Labels: improvement

#3642 Prefer per-user config file over global one
  src/engine/dir.cpp
  src/engine/dir.h
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, logic

#3646 Fix missing road identification
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#3648 fheroes2.cfg: fix typos and update comments a bit
  src/fheroes2/system/settings.cpp
Labels: improvement

#3656 Fix issue when abandoned mine becomes OBJ_ZERO when captured by AI-controlled hero
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, logic

#3618 Scenario with random players, in the original game, random opponents are generated so that all castles are present and different when possible
  src/fheroes2/system/players.cpp
Labels: improvement, logic

#3645 Adding gettext to the list of installed packages
  script/linux/install_sdl_1.sh
  script/linux/install_sdl_2.sh
Labels: Linux, improvement, script

#3624 Adventure map, Alamar can still move but there is no yellow part in the hero movement indicator in the hero list
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#3652 Use std::end instead of ARRAY_COUNT_END macro
  src/engine/types.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/objcrck.cpp
  src/fheroes2/objects/objdirt.cpp
  src/fheroes2/objects/objdsrt.cpp
  src/fheroes2/objects/objgras.cpp
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/objects/objsnow.cpp
  src/fheroes2/objects/objswmp.cpp
  src/fheroes2/objects/objwatr.cpp
  src/fheroes2/objects/objxloc.cpp
  src/fheroes2/objects/trees.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement

#3654 Fix title background for recruit dialog
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: ui

#3657 Fix incorrect text position insertion while saving a save
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
Labels: bug, ui

#3651 Implement build versioning for AppVeyor Windows builds
  VisualStudio/common.props
  appveyor.yml
  src/fheroes2/system/version.h
  src/resources/fheroes2.rc
Labels: AppVeyor, Windows, improvement, script

#2953 Add Debian package creation script
  script/packaging/common/fheroes2.desktop
  script/packaging/debian/README.Debian
  script/packaging/debian/changelog
  script/packaging/debian/compat
  script/packaging/debian/control
  script/packaging/debian/copyright
  script/packaging/debian/docs
  script/packaging/debian/install
  script/packaging/debian/rules
  script/packaging/debian/source/format
  src/resources/fheroes2.png
Labels: Linux, improvement

#3659 Don't let nearby monsters automatically attack hero if he moved to this tile using Stone Lith, Whirlpool or Dimension Door
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: bug, logic

#3664 Remove unused code related to cursor
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
Labels: improvement, ui

#3627 Fixed the displayed text in the army bar
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_bar.cpp
Labels: improvement, ui

#3650 More gamepad hotkeys added
  doc/README_PSV.md
  src/engine/localevent.cpp
Labels: improvement

#3660 Center quickinfo dialog under mouse cursor.
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#3670 Fix typo in AIToMagellanMaps()
  src/fheroes2/ai/ai_hero_action.cpp
Labels: AI, bug

#3669 CMake: install LICENSE into ${CMAKE_INSTALL_DOCDIR}, paraphrase some sentences in README.txt
  CMakeLists.txt
  doc/README.txt
  script/packaging/debian/README.Debian
Labels: CMake, improvement

#3676 Make proper rendering of some of disabled buttons
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui

#3677 Fix build with older Xcode versions
  src/engine/image.cpp
  src/engine/localevent.cpp
  src/engine/tools.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, macOS

#3686 Heroes::setVisitedForAllies(): set object as visited for this hero's kingdom as well, not just for allied kingdoms
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#3685 Adventure map, Alchemist's Tower, Sphere of Negation should not be considered a cursed artifact
  src/fheroes2/resource/artifact.cpp
Labels: bug, logic

#3690 Fix AI spellcasting and army estimates
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
Labels: AI, bug

#3692 AI improvements
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, improvement

#3688 CMake: install demo version installation scripts into ${CMAKE_INSTALL_DOCDIR}/demo
  CMakeLists.txt
Labels: CMake, improvement

#3494 Fix summoning boat logic in relation to AI
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: bug, logic

#3675 Allow right click on captured artifact graphic to get information about the artifact (Issue #1513)
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#3644 Remove Travis-CI usage from the project
  .travis.yml
  README.md
Labels: Travis-CI, improvement

#3695 Remove WITHOUT_ZLIB build option
  CMakeLists.txt
  Makefile
  VisualStudio/common.props
  src/Makefile
  src/Makefile.vita
  src/engine/CMakeLists.txt
  src/engine/serialize.h
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/CMakeLists.txt
  src/fheroes2/agg/agg.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/image/embedded_image.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug

#3543 Visit artesian spring once a week
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: bug, logic

#3655 Install non-dev SDL packages by default
  README.md
  script/linux/install_sdl_1.sh
  script/linux/install_sdl_1_dev.sh
  script/linux/install_sdl_2.sh
  script/linux/install_sdl_2_dev.sh
Labels: improvement, script

#3699 Rework on monster related code and added monster description
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_recrut.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/monster/monster_anim.cpp
  src/fheroes2/monster/monster_anim.h
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/monster/monster_info.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: improvement, logic, ui

#3694 CMake: Add WITH_DEBUG flag for Debug build type
  src/CMakeLists.txt
Labels: CMake, improvement

#3711 Add -Wextra-semi compilation warning flag for makefile compilation
  src/Makefile
Labels: improvement

#3628 Castle screen, Creature separation window, the sentence "Fast separation into slots:" and the graphic "2" are not displayed when there are only 2 creatures in the starting slot during the distribution between the hero's army and the garrison
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, ui

#3712 Small AI improvements
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
Labels: AI, improvement, logic

#3714 Remove "battle: skip increase +2 defense" option
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/monster/monster_info.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#3715 Remove "world: use unique artifacts for morale/luck" option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#3710 Combine the functions Settings::GetListFiles() and Settings::FindFiles() into one, use the exact filename match in Settings::GetLastFile()
  src/fheroes2/agg/agg.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, logic

#3702 Set app version from AppVeyor
  appveyor.yml
  script/windows/fheroes2.iss
Labels: improvement, script

#3729 Fix Bone Dragons' description
  src/fheroes2/monster/monster_info.cpp
Labels: bug, ui

#3727 Remove static game data from save files
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#3730 code cleanup: Replace find_if with more suitable functions
  src/engine/tools.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#3726 Remove unused MapMonster, MapArtifact and MapResource structs
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/world/world.cpp
Labels: improvement

#3733 Fix black screen for loading a campaign map without files
  src/fheroes2/game/game_campaign.cpp
Labels: bug, campaign

#3697 Make the separate page for installation instructions, improve README.md
  README.md
  doc/INSTALL.md
  script/macos/README.md
Labels: deployment, improvement

#3740 Fix the tileId calculation in Maps::GetAroundIndexes()
  src/fheroes2/maps/maps.cpp
Labels: bug, logic, regression

#3626 Adventure map, AI behavior, red AI player's hero Thundax does not capture a defenseless castle (0.9.4 3612)
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/castle/castle.cpp
Labels: AI, improvement

#3724 Maps::FileInfo: don't save the full path to the map file, save only the basename
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, logic

#3744 Fix rendering priorities of map's objects
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic, ui

#3752 Fix incorrect object sorting logic
  src/fheroes2/maps/maps_tiles.cpp
Labels: logic, regression

#3743 Cache campaign map data in Campaign::tryGetMatchingFile() to speed it up
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: improvement, ui

#3753 Fix missing update in hero meeting dialog
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#3755 Use spacebar only for activating object
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#3760 Fix blocking way AI heroes
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: AI, improvement

#3698 CMake: Implementing optional deploy of demo data
  CMakeLists.txt
  doc/README_cmake.md
  src/Makefile.switch
  src/fheroes2/CMakeLists.txt
  src/fheroes2/system/settings.cpp
Labels: CMake, improvement

#3758 Make AI to use Hut of Magi and Jail objects
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: AI, improvement

#3762 Add extra conditions for object visiting by AI
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, improvement

#3735 Remove ARRAY_COUNT macro
  src/engine/tools.cpp
  src/engine/types.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/spell/spell.cpp
Labels: improvement

#3754 Adventure map, Haunted and Abandoned Mines, the information about the number of ghosts is not indicated in the mine information window
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#3553 Fix disembarkation on coast during diagonal move
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#3768 Fix multiple issues with castle music
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_focus.cpp
Labels: bug, sound

#3771 Don't reset mixer on each focus update
  src/fheroes2/gui/interface_focus.cpp
Labels: regression, sound

#3756 Fix passabilities of objects on map
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#3757 Fix displayed object info in popup dialogs
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui
