Repository ihhub/fheroes2, pull requests merged in 2021-05, with the labels that each got.

#3313 Fix ability to retreat for a hero defending a town
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic, regression

#2926 Implement Campaign Awards
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: campaign, improvement

#3317 Add special Victory conditions for campaign scenarios
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/world/world.cpp
Labels: campaign, improvement

#3289 Display empty indicator when hero has less than 3 spell points
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: bug, ui

#3321 Speed up World Map drawings
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, ui

#2826 Fix magic book behavior in inventory (#761)
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: improvement, ui

#3320 Fix catapult miss animation: show this animation near the actual target object
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#3278 Remove incorrect background for Graveyard
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#3323 Partial unused code cleanup
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/world/world_regions.h
Labels: improvement

#3332 Remove unused file
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/resource/maps_text.cpp
Labels: improvement

#3217 Drop support of saves older than 0.9 version
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#3315 Save Completed Campaign Scenario to file
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
Labels: campaign, improvement

#3322 Retain position of the Adventure Map view after the Ultimate Artifact puzzle is viewed
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, regression, ui

#3335 Remove "world: new version WeekOf (+growth)" option
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: bug, logic

#3339 Check that unit is (im)movable after each unit action
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, logic

#3324 Add additional info for oracle dialog
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: bug, ui

#3333 Version 0.9.3
  CMakeLists.txt
  appveyor.yml
  changelog.txt
  sonar-project.properties
  src/fheroes2/system/version.h
Labels: improvement

#3353 Disable controller for any OS except gaming consoles
  src/engine/localevent.cpp
Labels: bug, logic

#3356 Disable controller on non console platforms
  src/engine/localevent.cpp
  src/fheroes2/game/fheroes2.cpp
Labels: bug, logic

#3360 Do not offer to exchange artifact with spell book
  src/fheroes2/resource/artifact.cpp
Labels: bug, ui

#3358 Print more verbose info about -d option in the app's command-line help message
  src/fheroes2/game/fheroes2.cpp
Labels: bug, logic

#3369 Fix broken behavior of scrollbars
  src/fheroes2/gui/interface_list.h
Labels: regression, ui

#3372 Fix non-standard dialog rendering
  src/engine/math_base.h
  src/fheroes2/dialog/dialog_frameborder.cpp
Labels: bug, ui

#3377 Fix View spells rendering
  src/fheroes2/kingdom/view_world.cpp
Labels: bug, regression, ui

#3378 Fix idling monster animation during battle
  src/fheroes2/battle/battle_animation.cpp
Labels: bug, regression, ui

#3362 Reset current music from the previous turn in the beginning of a new human turn
  src/fheroes2/game/game_startgame.cpp
Labels: bug, sound

#3379 Fix some compilation warnings and SonarQube code smells
  src/engine/image_tool.cpp
  src/engine/timing.h
  src/engine/tools.cpp
  src/engine/translations.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/world/world.cpp
Labels: improvement

#3222 Simulate level-ups for campaign-specific heroes that start at a higher level
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: campaign, improvement, logic

#3373 Fix issue when troop info window isn't shown after moving a single unit between army bars using drag&drop
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_bar.h
Labels: bug, ui

#3334 Fix Mix-up in Roland's Campaign Scenarios
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/game/game_campaign.cpp
Labels: bug, ui

#3388 Reduce CPU usage for video playback and puzzle revealing
  VisualStudio/common.props
  src/engine/image.cpp
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#3400 Fix the "world: use unique artifacts for resource affecting" option
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#3402 Fix bug with mouse cursor not visible after left-clicking on hero's secondary skill in Kingdom Overview
  src/fheroes2/dialog/dialog_skillinfo.cpp
Labels: bug, ui

#3406 Speed up MIDI loading
  src/engine/serialize.cpp
Labels: improvement

#3370 Reset MOUSE_RELEASED mode along with MOUSE_CLICKED on successful mouse click processing
  src/engine/localevent.cpp
Labels: bug, ui

#3405 Add correct support of The Price of Loyalty add-on
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/icn.cpp
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/system/players.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#3389 Use non-plural name for 1 creature while viewing with Crystal Ball
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#3382 Generate obstacles on battlefield based on the battle tile index
  src/engine/rand.cpp
  src/engine/rand.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: bug, logic

#3414 Code speed up and cleanup
  VisualStudio/common.props
  src/engine/image.cpp
  src/engine/image.h
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/math_base.h
  src/engine/pal.h
  src/engine/serialize.cpp
  src/engine/timing.h
  src/engine/tools.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_delays.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/image/embedded_image.h
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/system/settings.h
  src/tools/bin2txt.cpp
Labels: improvement

#3419 Fix many Visual Studio compilation warnings
  VisualStudio/common.props
  src/engine/image.cpp
  src/engine/image.h
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/thirdparty/libsmacker/smacker.c
  src/thirdparty/libsmacker/smacker.h
  src/thirdparty/libsmacker/smk_bitstream.c
  src/thirdparty/libsmacker/smk_bitstream.h
  src/thirdparty/libsmacker/smk_hufftree.c
  src/thirdparty/libsmacker/smk_hufftree.h
Labels: improvement

#3341 Fix elements layout for oracle/thieves dialog
  src/fheroes2/dialog/dialog_thievesguild.cpp
Labels: improvement, ui

#3420 Add Home and End button support for save naming
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: improvement, logic

#3422 Fix build on OpenBSD
  src/engine/endian_h2.h
Labels: improvement

#3429 Fix a crash while loading a new save
  src/fheroes2/system/settings.cpp
Labels: bug, crash, regression

#3427 Fix sound mute in background on MacOS with SDL1
  src/engine/localevent.cpp
Labels: SDL 1, bug, sound

#3430 Fix flags in Oracle/Thieves' Guild dialog
  src/fheroes2/dialog/dialog_thievesguild.cpp
Labels: improvement, ui

#3404 Implement Lose Sorceress Village Condition for The Succession Wars campaign
  src/fheroes2/army/army.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: campaign, improvement

#3433 Fix incorrect rendering of View World image
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#3436 Fix crash on non-PoL maps because the heroes vector isn't full
  src/fheroes2/heroes/heroes.cpp
Labels: crash, regression

#3437 Fix UI defect of selected creature appearing after closing meeting di…
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/skill_bar.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#3432 Add extended cursor icons from 4+ to 7+
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/heroes/heroes.cpp
Labels: improvement, ui

#3443 Fix lightning spell rendering
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, regression, ui

#3211 More double shadow
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, ui

#3445 Unveil the fog at the start of hero's movement
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, ui

#3446 Add shadow for Spell Book
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#3449 Unveil the fog on instant hero's movement (for example, via Stone Lith)
  src/fheroes2/heroes/heroes.cpp
Labels: bug, regression

#3441 Implement dismiss and upgrade hotkeys in unit dialog info
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement, ui

#3176 Do not draw objects under the fog if they are far from a revealed area
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement

#3453 Add an option to hide AI movements
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/dialog/dialog_system.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement, ui

#3457 Remove assert as it doesn't cover all cases
  src/fheroes2/game/game_mainmenu.cpp
Labels: bug, regression

#3458 Remove configuration file created at first failed run
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, ui

#3459 Speed up AI hero movement
  src/fheroes2/ai/ai_hero_action.cpp
Labels: improvement

#3461 Fix campaign save files not loading in the latest version
  src/fheroes2/game/game_io.cpp
Labels: bug, logic, regression

#3462 Fix heroes blocked in front of player's castle for Debug Mode
  src/fheroes2/heroes/heroes.cpp
Labels: bug, regression

#3428 Mute sound by setting music & effects volume to zero instead of pausing them
  .github/workflows/cmake_build.yml
  CMakeLists.txt
  Makefile
  VisualStudio/common.props
  doc/README_cmake.md
  src/Makefile
  src/Makefile.mingw32
  src/Makefile.vita
  src/engine/CMakeLists.txt
  src/engine/audio_mixer.cpp
  src/engine/audio_mixer.h
  src/engine/audio_music.cpp
  src/engine/audio_music.h
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/CMakeLists.txt
  src/fheroes2/agg/agg.cpp
Labels: bug, sound

#3465 Do not count monsters under fog for Visions spell
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, logic

#3467 Build Mage Guild before Special building for AI
  src/fheroes2/ai/normal/ai_normal_castle.cpp
Labels: AI, improvement

#3442 Fix Tower shooting logic during castle's siege
  src/fheroes2/battle/battle_troop.cpp
Labels: AI, improvement, logic

#3471 Cache Vita SDK to avoid build failures on SDK installation issues
  .github/workflows/linux_pull_request.yml
  .github/workflows/linux_release.yml
Labels: improvement, script

#3479 Fix Roland, chapter 9 map conditions
  VisualStudio/common.props
  src/engine/serialize.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/system/gamedefs.h
  src/fheroes2/system/settings.cpp
Labels: bug, campaign, logic

#3483 Don't reset hero mana points to maximum in the beginning of a new week if they are above maximum
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#3469 Modernize & secure demo version installation scripts
  .github/workflows/linux_release.yml
  .github/workflows/macos_release.yml
  .travis.yml
  README.md
  appveyor.yml
  doc/README.txt
  script/demo/demo_linux.sh
  script/demo/demo_macos.sh
  script/demo/demo_unix.sh
  script/demo/demo_windows.bat
  script/demo/demo_windows.ps1
  script/windows/install_packages.bat
Labels: improvement, script

#3490 Fix tools compilation
  src/tools/extractor.vcxproj
  src/tools/icn2img.cpp
  src/tools/icn2img.vcxproj
Labels: bug

#3500 Directly show next campaign scenario for end of scenario save
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
  src/fheroes2/game/game_loadgame.cpp
Labels: campaign, improvement, ui

#3502 Set proper difficulty level for campaign scenario
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game.cpp
Labels: bug, campaign, logic

#3495 Fix move points and spell points replenishment logic for heroes from hero pool
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/world/world.cpp
Labels: bug, logic

#3503 Add an option to open Hero Screen within battle
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#3504 Fix well's max button hiring logic
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, logic

#3507 Troops::JoinTroop(): make sure that the candidate slot not only contains the same troops, but also that troops are valid
  src/fheroes2/army/army.cpp
Labels: bug, ui

#3510 Fix incorrect hero receiving a spell bonus
  src/fheroes2/game/game_campaign.cpp
Labels: bug, campaign, logic

#3512 Make Ultimate Crown artifact for campaign scenarios
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, campaign, logic

#3514 Play hero's vanishing sound after AI vs human battle
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, sound

#3515 Return to load screen after cancelling loaded campaign scenario
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_mode.h
Labels: campaign, improvement, ui

#3401 Combat, AI behavior, AI hero Hector casts the Blind spell which does not give any benefit because the hero has only 1 point of Spell Power
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: AI

#3517 Fix puzzle drawings
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, ui

#3521 Fix Stables and Alchemist's Tower passabilities
  src/fheroes2/maps/mp2.cpp
Labels: bug, logic

#3522 Fix WaterWheel passability
  src/fheroes2/maps/mp2.cpp
Labels: bug, logic

#3523 Force display rendering on app activation
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: bug, ui

#3468 Remove "dynamic interface" experimental setting
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, ui

#3527 Add an option to replay Intro video for campaign
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, video

#3454 Mark executable as Language Neutral, UTF-8
  src/resources/fheroes2.rc
Labels: Windows, improvement

#3201 Code cleanup
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
  src/fheroes2/world/world_regions.cpp
  src/fheroes2/world/world_regions.h
Labels: improvement

#3518 Fix cheating AI behavior for dwellings with defenders
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: AI, bug

#3519 Recruit an AI hero if none exists
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, improvement

#3529 Highlight the door in Main Menu for mouse over event
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, ui

#3530 Make Cursor and CursorRestorer non-copyable and non-assignable
  src/fheroes2/gui/cursor.h
Labels: improvement

#3531 Fix a few SonarCloud code smells in Mixer
  src/engine/audio_mixer.cpp
  src/engine/audio_mixer.h
Labels: improvement

#3511 Implement PoL campaign Data
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_newgame.cpp
Labels: campaign, improvement

#3533 Don't clear morale modifiers too early
  src/fheroes2/heroes/heroes_base.cpp
Labels: bug, ui

#3534 Fix incorrect hero position facing left
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, ui

#3535 Draw correct castle icon in popup window
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/castle/castle_ui.cpp
  src/fheroes2/castle/castle_ui.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/gui/interface_icons.cpp
Labels: improvement, ui

#3536 Fix moving AI hero out of hero drawings
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, regression, ui

#3538 Fix graphics regression for new ICNs
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
Labels: regression, ui

#3539 Add most of PoL campaign drawings
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#3545 Fix shadows for random resources and artifacts
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#3546 Fix cursor apprearance between videos and fix corrupted last frame
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
Labels: improvement, ui

#3547 Hide cursor for popup windows
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#3451 Implement hiding & showing cursor with SDL2
  src/engine/screen.cpp
  src/engine/screen.h
Labels: improvement, ui

#3550 Fix inaccessible beach tiles
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#3549 Support PoL heroes & artifacts in "battle only" mode
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/world/world.cpp
Labels: bug, ui

#3551 Add configuration option for first game run
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#3552 Add The Price of Loyaty campaign selection
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
Labels: improvement, ui

#3554 Do not show gray flag over Haunted mine
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui

#3556 Show extended shadow for 2-hex monsters in battle
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#3557 Fix incorrect game ending during time loss condition
  src/fheroes2/game/game_startgame.cpp
Labels: bug, logic

#3558 Fix incorrect cell shadowing for 2-hex monster
  src/fheroes2/battle/battle_interface.cpp
Labels: logic, regression

#3560 Mark resource generator objects as visited for allies
  VisualStudio/common.props
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, logic

#3566 Clear the hidden mode for the hero's path after moving through Whirlpool
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#3559 Fix AI obsession over Observation Towers
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: AI, bug

#3567 Don't show fading AI hero animation with hidden movement option
  src/fheroes2/ai/ai_hero_action.cpp
Labels: improvement, ui

#3568 Make fog uncovering task for AI more efficient
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, improvement

#3569 Read campaign files in non-case sensitive manner
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: campaign, improvement

#3571 Fix game freezing during AI movements
  src/fheroes2/world/world_pathfinding.cpp
Labels: AI, bug, regression

#3573 Fix 2-hex unit shadow movement
  src/fheroes2/battle/battle_interface.cpp
Labels: regression, ui

#3574 Remove "world: only the first monster will attack (H2 bug)" option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#3578 Fix flickering effect for SDL1 cursor on Windows 10
  src/engine/screen.cpp
Labels: SDL 1, bug, ui

#3579 Fix multiple issues with AI and spell logic using distance evaluation
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: AI, bug, logic

#3580 Do not render full screen on button event
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement, ui
