Repository ihhub/fheroes2, pull requests merged in 2021-12, with the labels that each got.

#4727 Fix passability for Dimension Door spell
  src/fheroes2/game/game_interface.cpp
Labels: bug, logic

#4729 Show credits at the end of campaign
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#4722 Fix Enter button pressed state in gift dialog
  src/fheroes2/dialog/dialog_giftresources.cpp
Labels: bug, ui

#4735 Play campaign music in campaign scenario selection screen
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, sound

#4736 Add popup window to OK button in game settings
  src/fheroes2/dialog/dialog_game_settings.cpp
Labels: improvement, ui

#4739 Fix vertical position of building construction name
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, ui

#4741 Add sound for visiting Observation Tower
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, sound

#4742 Add video playback in PoL campaign selection window
  src/engine/smk_decoder.h
  src/fheroes2/game/game_newgame.cpp
Labels: improvement, campaign, video

#4728 Fix Summon Boat logic
  src/fheroes2/heroes/heroes_spell.cpp
Labels: bug, logic

#4743 Fix vertical text position in skill icon
  src/fheroes2/dialog/dialog_skillinfo.cpp
Labels: bug, ui

#4631 Improve marketplace gift button placement
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: improvement, ui

#4744 Adjust monster recruit position for some dialogs
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, ui

#4745 Fix horizontal position of town name and town icon in construction dialog
  src/fheroes2/castle/castle_town.cpp
Labels: bug, ui

#4740 Update background music on the fly
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: improvement, sound

#4752 Version 0.9.10
  CMakeLists.txt
  Makefile.switch
  appveyor.yml
  changelog.txt
  docs/images/screenshots/screenshot_battle.png
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
Labels: improvement

#4756 Always mark the entrance to the castle/town as a road, do not automatically mark the tile south of the entrance as a road
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4757 Fix extractor tools compilation on Visual Studio
  src/tools/extractor-vs2015.vcxproj
  src/tools/extractor-vs2019.vcxproj
Labels: Windows, script

#4768 Fix regression in campaign bonuses logic
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: campaign, crash

#4769 Fix image Copy function
  src/engine/image.cpp
Labels: bug, ui

#4761 Add additional spell info for spells owned by a hero
  fheroes2-vs2015.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_spellinfo.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/spell/spell_info.h
Labels: improvement, ui

#4720 Allow to select player class using mouse wheel
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
Labels: improvement, ui

#4448 Fix River being considered as a Road
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4778 Don't reset the hero's path in SLEEPER mode, reset the SLEEPER mode only with the beginning of the hero's movement
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, ui, logic

#4777 Add hotkey for settings in main menu
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, ui

#4779 Fix performance drop in rendering
  src/engine/image.cpp
  src/engine/screen.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_button.cpp
Labels: improvement, ui, regression

#4774 Fix crash due to out of memory boundary access during resolution change
  src/engine/screen.cpp
Labels: bug, ui, crash

#4518 Fix heroes meeting swap arrows
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#4790 Updated Settings description to cover all actions
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
Labels: improvement, ui

#4734 Generate correct letters for French language
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#4798 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4786 Generate Russian letters by default
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#4807 Windows: Try to set the console codepage to the system codepage
  src/engine/logging.cpp
Labels: improvement, Windows, ui

#4811 Audio: replace SDL_GetError() by Mix_GetError()
  src/engine/audio.cpp
Labels: bug, sound

#4820 Improve AI behavior during castle defense
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: bug, AI

#4802 Fix handling of national symbols in the paths to music files on Windows
  src/engine/audio.cpp
  src/engine/audio.h
  src/engine/system.cpp
  src/engine/system.h
Labels: bug, Windows, sound

#4812 Build system improvements
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cmake.yml
  .github/workflows/make.yml
  .github/workflows/sonarcloud.yml
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
Labels: improvement, script, deployment

#4825 Show languages in vertical order rather than horizonal
  src/fheroes2/dialog/dialog_language_selection.cpp
Labels: improvement, ui

#4454 Consider the protected tile as an obstacle when recalculating the hero's path
  src/fheroes2/heroes/route.cpp
Labels: bug, logic

#4828 Add popup dialog for map information
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
Labels: improvement, ui

#4829 Version 0.9.11
  CMakeLists.txt
  Makefile.switch
  appveyor.yml
  changelog.txt
  script/packaging/debian/changelog
  sonar-project.properties
  src/fheroes2/system/version.h
Labels: improvement

#4831 Revert back SDL version for Windows
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
Labels: bug, Windows, high priority

#4841 Fix a crash during AI turn
  src/fheroes2/army/army.cpp
Labels: AI, crash

#4801 Introduce asio lib
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cmake.yml
  .github/workflows/make.yml
  CMakeLists.txt
  VisualStudio/common.props
  cmake/Findasio.cmake
  fheroes2-vs2019.vcxproj
  script/linux/install_asio.sh
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
  src/Makefile.switch
  src/Makefile.vita
  src/dist/Makefile
  src/fheroes2/CMakeLists.txt
  src/fheroes2/network/test.cpp
Labels: improvement

#4853 Moved trading resources slightly to the left
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: bug, ui

#4852 Fixed sprite position in marketplace
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: bug, ui

#4861 Allow translation for "cost per troop:" text
  src/fheroes2/dialog/dialog_recrut.cpp
Labels: improvement, ui

#4862 Generate proper russian E with 2 dots on top
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#4864 Always enable Autosave
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#4863 Add support of Buka Anim2 directory
  src/fheroes2/game/game_video.cpp
Labels: bug, video

#4846 Rework the logic of re-calculating the paths of heroes on the adventure map
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: bug, logic, regression
