Repository ihhub/fheroes2, pull requests merged in 2022-01, with the labels that each got.

#4858 Fix use of plural/singular translation
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/resource/artifact.cpp
Labels: bug, translation

#4857 The game does not display tooltips and popups for the Cast, Retreat, …
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#4870 Fix a possible crash in French letters generation
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui

#4872 Add a spell title when no enough SP window appears
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#4873 Show proper language name for mismatched by language save files
  src/fheroes2/game/game_io.cpp
Labels: improvement, ui

#4874 Fix CPU player icon's extra color column
  src/fheroes2/agg/agg_image.cpp
Labels: bug, assets

#4871 Improve AI behavior during castle defence
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, AI

#4879 Fix glowing red pixel in Warlock's Red Tower
  src/fheroes2/agg/agg_image.cpp
Labels: bug, assets

#4878 Minor Route::Path cleanup
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
Labels: improvement, logic

#4880 Show only in-game players for Gift marketplace option
  src/fheroes2/dialog/dialog_giftresources.cpp
Labels: bug, ui

#4851 Update French translation
  files/lang/cs.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/dist/Makefile
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, translation

#4881 Route::Path::GetFrontDirection(): return Direction::UNKNOWN if path is empty and path destination is not valid
  src/fheroes2/heroes/route.cpp
Labels: improvement, logic

#4889 Fix water tiles with OBJ_COAST
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#4885 Adds missing "pourcent" in description of Golden Bow
  files/lang/fr.po
Labels: improvement, translation

#4884 fix `make clean` to correctly remove fheroes2.res file
  src/dist/Makefile
Labels: improvement, script

#4866 Changed captain's name
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#4891 added missing casts to unsigned char for isspace, isdigit, and tolower
  src/engine/tools.cpp
Labels: bug, ui

#4897 MusicRestorer: prevent attempts to play the old music by new instances while the music being restored is starting in the background
  src/fheroes2/game/game.h
Labels: bug, sound

#4902 Fix the Whirlpools
  src/fheroes2/heroes/route.cpp
Labels: bug, logic, regression

#4886 Update documentation related to MacOS
  docs/INSTALL.md
Labels: improvement, deployment

#4844 Centered Knowledge sprite
  src/fheroes2/dialog/dialog_arena.cpp
Labels: improvement, ui

#4697 Add translation context for color and syntax flexibility to Traveller's Tent and Barrier
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
Labels: improvement, translation

#4607 Make multiple methods to be inlined
  src/engine/image.cpp
  src/engine/image.h
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/system.cpp
  src/engine/tinyconfig.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/engine/translations.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_border.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#4903 INSTALL.md: make the link to the section of the DEVELOPMENT.md universal
  docs/DEVELOPMENT.md
  docs/INSTALL.md
Labels: improvement, deployment

#4894 AIWorldPathfinder: encourage the AI-controlled heroes to overcome water obstacles using boats
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, logic, AI, high priority

#4890 Fix sed -i behavior on some systems
  files/lang/Makefile
  src/dist/Makefile
Labels: bug, script, macOS

#4912 Fix Russian small k per in both fonts and expand campaign scenario startup choice text area
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/game/game_campaign.cpp
Labels: bug, ui

#4910 CMake improvements
  .github/workflows/cmake.yml
  .gitignore
  CMakeLists.txt
  src/dist/Makefile
Labels: improvement, script, deployment, CMake

#4909 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4918 Fix Mass Dispel usage during battle
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#4922 Display dead monster information during battle
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, ui

#4920 PlayerWorldPathfinder::processCurrentNode(): always check that the candidate tile is not blocked, even if it is guarded by a nearby monster
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, logic

#4923 Fix position of Russian e with 2 dots on top
  src/fheroes2/agg/agg_image.cpp
Labels: bug, ui, translation

#4904 AIWorldPathfinder: add support for paving the way through Whirlpools
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
  src/fheroes2/world/world_regions.cpp
  src/fheroes2/world/world_regions.h
Labels: improvement, logic, AI

#4927 Improve the AI fog discovery logic
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement, logic, AI

#4908 Fix translation of saved default player names
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: bug, ui

#4925 Reduce SDL dependency and the amount of warnings in Visual Studio
  src/engine/image.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/serialize.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement

#4905 German translation
  files/lang/Makefile
  files/lang/de.po
Labels: improvement, translation

#4929 Scenario selection dialog: fix the display of properties for maps from the list
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
Labels: bug, ui, regression

#4932 Fix most of still existing cases with passabilities
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic, high priority

#4933 Fix small font for Polish GoG version
  src/fheroes2/agg/agg_image.cpp
Labels: bug, ui, assets

#4935 AI: apply the "anti-stuck" heuristics even to the last available hero
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, AI

#4942 Show monster info on right click in castle's well
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, ui

#4950 Fix a few code smells detected by the SonarCloud
  src/engine/dir.cpp
  src/engine/logging.cpp
  src/engine/pathfinding.h
  src/engine/screen.cpp
  src/engine/serialize.cpp
  src/engine/system.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/monster/monster_anim.h
  src/fheroes2/system/players.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.h
  src/tools/bin2txt.cpp
  src/tools/extractor.cpp
Labels: improvement

#4907 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#4931 Redesign the hero recruitment process
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_recruits.cpp
  src/fheroes2/heroes/heroes_recruits.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#4952 Fix a few recent code smells
  src/fheroes2/heroes/heroes_recruits.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/players.cpp
Labels: improvement

#4937 German font generation (support Umlaut & Eszett)
  files/lang/Makefile
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#4947 Modify army order setting
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#4956 Fix campaign text translation
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
Labels: bug, translation

#4957 Made language area and campaign choice selection to cover text too
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#4955 Fix some SonarQube bugs
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
Labels: improvement

#4958 Fix race condition on initialization of paletteHolder
  src/engine/image_palette.cpp
Labels: bug, ui

#4959 Fix crashes due to assertions while rendering a text
  src/fheroes2/gui/ui_text.cpp
Labels: bug, ui

#4938 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#4930 Fixes in English translatable strings
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, translation

#4962 Fix some SonarQube smells
  src/engine/image_tool.cpp
  src/engine/serialize.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world.cpp
Labels: improvement

#4948 Fix the "week of monsters" and a few other issues
  src/engine/rand.h
  src/fheroes2/heroes/heroes_recruits.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: bug, logic, regression

#4960 Fix attack cursor during battle
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui
