Repository ihhub/fheroes2, pull requests merged in 2022-12, with the labels that each got.

#6274 Remove LGTM badge and minor adjustments to the frontpage
  README.md
  docs/README.md
Labels: documentation

#6275 MSVC: do not define _DEBUG by hand
  VisualStudio/Debug.props
Labels: improvement, Windows

#6280 Do not translate companies' names
  src/fheroes2/game/game_credits.cpp
Labels: improvement, translation

#6265 Hexagon shading improvement (Battlefield)
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#6285 Update the dependency package hash for Windows
  script/windows/install_packages.bat
Labels: improvement, Windows

#5983 Scenario Window UI Items position fix
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
Labels: bug, ui

#6257 An attempt to recreate the original rainbow animation (battlefield)
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#6282 Make an option to toggle screen scaling type
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#6283 Fix incorrect cursor shadow position at the creature's turn start
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#6278 Install the latest Microsoft Visual C++ Redistributable package using Inno Setup
  .github/workflows/msvc.yml
  docs/README.txt
  script/windows/fheroes2.iss
Labels: improvement, Windows, deployment

#6269 Fix position of left barbarian's captain quarters part
  src/fheroes2/castle/castle_building.cpp
Labels: bug, ui, regression

#6292 Change Danish abbreviation to dk from da
  src/engine/translations.cpp
  src/fheroes2/gui/ui_language.cpp
Labels: improvement, translation

#6296 ScenarioInfo window: all difficulty texts remain after difficulty is …
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: bug, ui, regression

#6294 Remove the redundant cast
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement

#6293 Fix multiline word splitting for short phrases with a long first word
  src/fheroes2/gui/ui_text.cpp
Labels: bug, ui

#6303 Avoid using memory on heap for rendering methods
  src/engine/image.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, ui

#6306 Revert back regression changes in Blit function
  src/engine/image.cpp
Labels: bug, regression

#6248 Add more Cyrillic button letters
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui, translation

#6298 Fix the smoke animation when demolishing a castle building (Battlefield).
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#6308 Android: do not backup fheroes2.bin
  .gitignore
  android/app/src/main/res/xml/data_extraction_rules.xml
  android/app/src/main/res/xml/full_backup_content.xml
Labels: improvement, Android

#6312 The Cancel button, in the Recruid dialog, remains its translated text…
  src/fheroes2/dialog/dialog_recruit.cpp
Labels: bug, ui, translation

#6309 Do not draw multiple frames of Adventure Map
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
Labels: improvement, ui

#6318 Fix Dwarves death animation
  src/fheroes2/agg/bin_info.cpp
Labels: improvement, assets

#6325 Display the amount of gold in the diplomacy dialog
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, ui, regression

#6194 Make the Main Menu's dialog buttons translatable
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
Labels: improvement, ui, translation

#6287 Add double-lined class name translations
  files/lang/be.po
  files/lang/bg.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/nb.po
  files/lang/pl.po
  files/lang/ru.po
  files/lang/sv.po
Labels: improvement, translation

#6329 Fix a few code smells and "bugs" detected by SonarCloud
  src/fheroes2/game/game_io.cpp
  src/fheroes2/resource/resource.cpp
Labels: improvement

#6307 Rework the right mouse button simulation with touch events
  docs/README_android.md
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_itemsbar.h
Labels: improvement, ui, Android

#6330 Adjust several button font characters
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui

#6332 Fix incorrect battlefield image restoration in the place of the previous damage popup
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#6289 Add the ability to set the maximum text width for each icon in settings dialogs
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/gui/ui_option_item.cpp
  src/fheroes2/gui/ui_option_item.h
Labels: improvement, ui

#6165 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#6319 Do not stop object animation during AI turn
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/interface_status.h
Labels: improvement, ui

#6336 Fix a few recently introduced code smells
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/interface_itemsbar.h
Labels: improvement

#6341 The newly allocated channels have a default volume of MIX_MAX_VOLUME
  src/engine/audio.cpp
Labels: bug, audio

#6331 Make File Dialog and Adventure Dialog buttons translatable
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_file.cpp
Labels: improvement, ui, translation

#6349 Reduce priority for bottles in sea for AI
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#6345 Fix rainbow endpoint calculation (Battlefield)
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui, regression

#6348 Fix black area not being rendering during video playback
  src/engine/screen.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
Labels: bug, video

#6297 Optimize defensive strategy for AI castles
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, AI

#6342 Tidy up hotkeys constants a bit, make separate hotkeys to cast battle & adventure spells, add the "Quit game" hotkey, handle hotkeys in the Adventure Map's File dialog
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#6262 Enable touch support for all devices
  src/engine/localevent.cpp
Labels: improvement

#6242 Use logarithmic scale of sound volume
  src/engine/audio.cpp
  src/engine/audio.h
Labels: improvement, audio

#6354 Remove the leftovers of the "Continue after victory" experimental setting
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_over.h
  src/fheroes2/system/save_format_version.h
Labels: improvement

#6358 Fix a recently introduced code smell
  src/fheroes2/army/army.cpp
Labels: improvement

#6359 Fix rendering an extra empty line for specific texts
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui

#6356 Do not mirror corpses of defeated troops (Battlefield)
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#6344 Death Wave spell animation fix (Battlefield)
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/monster/monster_anim.h
Labels: bug, ui

#6352 Implement the infrastructure to apply campaign bonuses and awards to a specific hero, multiple campaign-related fixes
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/ui_campaign.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, campaign

#6355 Fix animation of slowed flying creatures (Battlefield)
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/monster/monster_anim.h
Labels: bug, ui

#6157 Drop support of old save versions
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/save_format_version.h
Labels: improvement

#6374 Fix extra frame rendering for status update during AI turn
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, ui

#5756 Fix possible crash while calculating points for a straight line
  src/engine/tools.cpp
Labels: bug, logic, high priority

#6376 Add popup windows for monster recruit dialog buttons
  src/fheroes2/dialog/dialog_recruit.cpp
Labels: improvement, ui

#6371 Disable Trade button in Marketplace when appropriate
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: bug, ui

#6387 Remove obsolete IWYU pragmas
  src/fheroes2/agg/bin_info.h
  src/fheroes2/monster/monster_info.h
Labels: improvement

#6337 Make the regular small buttons translatable
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui, translation

#6384 Fix wrong usage of std::isspace() in TinyConfig
  src/engine/tinyconfig.cpp
Labels: improvement

#6382 Add global hotkey to toggle the text support mode, fix the toggling of fullscreen mode a bit
  src/engine/image.h
  src/engine/screen.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/system/settings.cpp
Labels: improvement, ui

#6383 Update the Norwegian translation
  files/lang/nb.po
Labels: improvement, translation

#6390 Add a link to demo version within Android documentation
  docs/README_android.md
Labels: improvement, documentation, Android

#6375 Optimize rendering in multiple places
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog_box.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/statusbar.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#6392 Enable the instant battle (without the auto spell casting) by default
  src/fheroes2/system/settings.cpp
Labels: improvement

#6372 Fix bridge logic after morale event, simplify Bridge class, minor code cleanup
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, improvement, logic

#6394 Add French and German to use original assets for buttons
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#6385 [#5240] Adjusted "Battlefield Casualties" vertical position of MonsterLines.
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#6395 Fix incorrect resource placements on certain maps
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#6301 Bulgarian Translation 18
  files/lang/bg.po
Labels: improvement, translation

#6368 Update the French translation
  files/lang/fr.po
Labels: improvement, translation

#6360 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#6246 Add cross building for Ubuntu ARM64
  .github/workflows/make.yml
  src/Makefile.all
Labels: improvement, Linux, script

#6380 Version 1.0
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#6401 Add links to download the ARM64 Linux build, distinguish the archive names between x86-64 and ARM64
  .github/workflows/make.yml
  docs/INSTALL.md
Labels: improvement, deployment

#6402 INSTALL.md: remove SDL1 links
  docs/INSTALL.md
Labels: deployment, high priority

#6396 Add button font full stop and A and E with accents for CP1252
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui, translation

#6363 Fix multiple MSVC warnings, implement a few additional checks
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: improvement

#6405 GitHub Actions: use ubuntu-20.04 image to build Linux x86-64 images using the Make workflow
  .github/workflows/cmake.yml
  .github/workflows/make.yml
Labels: deployment

#6412 Fix controller support for PS Vita
  src/engine/core.cpp
  src/engine/localevent.cpp
Labels: bug, logic

#6409 Add dev name to Flatpak package info
  script/packaging/common/fheroes2.appdata.xml
Labels: improvement, documentation

#6408 Automatically assemble artifacts sets if their parts were captured in the battle
  VisualStudio/fheroes2/sources.props
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_artifact.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: bug, logic

#6417 Update SDL 2 rendering code
  src/engine/screen.cpp
Labels: improvement, ui

#6413 Optimize Death Wave spell effect rendering. Battlefield.
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#6424 GitHub issue template: add Android to the list of platforms
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: improvement

#6423 Fix screen flickering in SDL2
  src/engine/screen.cpp
Labels: bug, ui

#6425 update man page
  docs/fheroes2.6.in
Labels: improvement, documentation

#6428 Better support of commandline arguments to check_copyright_headers
  script/tools/check_copyright_headers.py
Labels: improvement, script

#6400 Fix forced IDLE animation after switching to STATIC animation. (Battlefield)
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, ui

#6379 Don't lowercase creature name (or other string) when it is put first in phrase
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, translation

#6112 Update German translation
  files/lang/de.po
Labels: improvement, translation

#6431 Fix incorrect logic for monster placement on Adventure Map
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#6436 Update docs and appdata (for flatpak)
  docs/INSTALL.md
  script/packaging/common/fheroes2.appdata.xml
Labels: improvement, documentation

#6435 System::GetCaseInsensitivePath(): remove the addition of an extra "./" for relative paths
  src/engine/system.cpp
Labels: bug
