Repository ihhub/fheroes2, pull requests merged in 2022-06, with the labels that each got.

#5486 Cleanup of Audio related code
  src/engine/audio.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, audio

#5489 Fix the invalid behavior of "no interface" mode
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/system/settings.h
Labels: bug, ui

#5436 ukrainian translation (skills)
  files/lang/uk.po
Labels: improvement, translation

#5494 Add sound for rocks in water
  src/fheroes2/agg/m82.h
  src/fheroes2/game/game.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, audio

#5406 ukrainian translation (places)
  files/lang/Makefile
  files/lang/uk.po
Labels: improvement, translation

#5498 simplify lang/Makefile
  files/lang/Makefile
Labels: improvement, script

#5500 Fix Puzzle window exit button rendering
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, assets

#5502 Do not auto-save at the end of a turn if the player has been vanquished on that turn
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, logic

#5506 Clang-Tidy: disable the modernize-use-nodiscard
  .clang-tidy
Labels: improvement, GitHub Actions

#5504 Improve loop sound playback logic
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
Labels: improvement, audio

#5487 Update Polish translation: added polish descriptions of all campaign …
  files/lang/pl.po
Labels: improvement, translation

#5490 Make the "no interface" mode more usable
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_border.h
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_buttons.h
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_cpanel.h
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/interface_status.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/system/settings.cpp
Labels: bug, improvement, ui

#5516 Fix a case when overall sound volume did not change sound effects
  src/fheroes2/audio/audio_manager.cpp
Labels: bug, audio

#5517 Fix missing looping sounds after stopping mixer
  src/fheroes2/audio/audio_manager.cpp
Labels: bug, audio

#5519 Reset the interface when changing the UI theme, just redraw it is not enough
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: bug, ui, regression

#5518 Minor fixes for the music continuation feature
  src/engine/audio.cpp
  src/engine/audio.h
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/interface_focus.cpp
Labels: bug, improvement, audio

#5521 Swap spell icons for Death Wave and Death Ripple
  src/fheroes2/spell/spell.cpp
Labels: bug, ui

#5522 Rework the music resume logic, replace std::lock_guard by std::scoped_lock
  src/engine/audio.cpp
  src/engine/audio.h
  src/engine/thread.cpp
  src/engine/thread.h
  src/fheroes2/audio/audio_manager.cpp
Labels: improvement, audio

#5434 Flatpak Documentation
  docs/INSTALL.md
Labels: improvement, deployment, documentation

#5526 Rework settings and introduce 3D audio UI option
  fheroes2-vs2017.vcxproj
  fheroes2-vs2019.vcxproj
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_audio.h
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: improvement, ui, high priority

#5527 Multiple fixes for the AsyncManager, make it ready for use to restart the music in the RESUME_AND_PLAY_INFINITE mode
  src/engine/audio.cpp
  src/engine/thread.cpp
  src/engine/thread.h
  src/fheroes2/audio/audio_manager.cpp
Labels: bug, improvement, audio

#5524 Version 0.9.16
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
Labels: improvement

#5534 appdata.xml should be updated like this
  script/packaging/common/fheroes2.appdata.xml
Labels: improvement, documentation

#5535 Fix a delay in game while crossing a terrain and playing MIDI music
  src/engine/audio.cpp
  src/engine/audio.h
  src/fheroes2/game/game.cpp
Labels: bug, audio

#5525 Nintendo Switch: protect the logfile with mutex
  src/engine/logging.cpp
  src/engine/logging.h
Labels: bug

#5539 Don't waste time playing the pre-battle sound if the game sounds are turned off
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, audio

#5540 Fix a few recent code smells
  src/engine/agg_file.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/h2d/h2d_file.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#5546 Initial implementation of true "Evil" interface in the game
  src/engine/pal.cpp
  src/engine/pal.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
Labels: improvement, ui

#5548 Update audio related logic
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/m82.h
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/agg/xmi.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, audio

#5545 Fix multiple issues with RadarUpdater from the quick info window
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#5551 Fix typo: "silder" -> "slider"
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_cpanel.h
  src/fheroes2/gui/ui_scrollbar.h
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement

#5549 Rework extended game options a bit
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#5513 fixed ghosts bug on abandoned mines, caption on abandoned mine dialog
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#5555 Keep the object type and placeholder sprite index in sync on tiles with random monsters
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#5557 Add and update a few comments in the audio module
  src/engine/audio.cpp
  src/engine/audio.h
Labels: improvement

#5476 add fheroes2 man page
  docs/Makefile
  docs/fheroes2.6.in
Labels: improvement, documentation

#5556 Reset sounds through Audio Manager
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: bug, audio

#5562 align hero button vertically
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: bug, ui

#5570 Fix the castle well build logic
  src/fheroes2/ai/normal/ai_normal_castle.cpp
Labels: bug, AI

#5550 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#5564 Respect the Ultimate Artifact's radius specified by the map creator
  src/fheroes2/maps/maps.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#5574 Fix AI hero recruiment limit
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, regression

#5561 Fix displaying of negative resources in dialog
  src/fheroes2/gui/ui_dialog.cpp
Labels: bug, ui

#5568 Add individual Spell strategic value for AI
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
Labels: improvement, AI

#5573 Improving AI castle defenses
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#5559 Multiple AudioManager fixes
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, improvement, audio, regression

#5552 Add extra information for XMI to MID conversion
  src/engine/xmi2mid.cpp
Labels: improvement, audio

#5075 Remember the last open page in Spell Book during battle
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_book.h
Labels: improvement, ui

#5576 Update Genie special ability
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/monster/monster_info.cpp
Labels: improvement, ui, logic

#5553 Update Norwegian translation
  files/lang/nb.po
Labels: improvement, translation

#5497 ukrainian translation, part 3
  files/lang/uk.po
Labels: improvement, translation

#5571 AI should keep some creatures in reserve for castle defense
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: improvement, AI
