Repository ihhub/fheroes2, pull requests merged in 2022-11, with the labels that each got.

#6053 Bulgarian Translation 14
  files/lang/bg.po
Labels: improvement, translation

#6073 Campaign difficulty window, text alignment
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#5970 Update the Russian translation
  files/lang/ru.po
Labels: improvement, translation

#6077 Fix catapult's boulder animation
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#6083 Bulgarian Translation 15
  files/lang/bg.po
Labels: improvement, translation

#6080 Rework the troops arrangement mechanics for the castle defense
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
Labels: improvement, logic

#6087 Draw the correct arrows for the paths on the adventure map
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, ui

#6081 Correcting text errors
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, ui

#6090 Change language selection window to support many languages
  src/fheroes2/dialog/dialog_language_selection.cpp
Labels: improvement, ui

#6051 Don't overwrite focus on game load
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_focus.cpp
Labels: bug, ui

#6101 Fix recently introduced code smell
  src/fheroes2/gui/interface_focus.cpp
Labels: improvement

#6099 Remove redundant PS Vita-specific code from the Settings::Save()
  src/fheroes2/system/settings.cpp
Labels: improvement

#6022 More contrast for player objects on the minimap
  src/fheroes2/gui/interface_radar.cpp
Labels: improvement, ui

#6100 Reset the MOUSE_WHEEL in LocalEvent::GetClean() and LocalEvent::HandleEvents(), add a few comments regarding event modes
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: improvement

#6111 Add a separate graphics options window
  fheroes2-vs2017.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/ui_option_item.cpp
  src/fheroes2/gui/ui_option_item.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#5826 Luck / Morale related objects are now reset after meeting / battle
  src/fheroes2/ai/ai_base.cpp
Labels: improvement, AI

#6094 Fix possible assertion hit for campaign scenario info dialog
  src/fheroes2/game/game_campaign.cpp
Labels: ui, crash

#6107 Add right click quick info in more dialogs for hero and castle captain
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#6125 Fix handicap income calculation
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement, logic

#6126 Fix incorrect evaluation of army strength where hero's abilities should not be taken into account
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/monster/monster.cpp
Labels: bug, logic

#6130 Adventure map pathfinding: minor optimizations
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, logic

#6127 Add missing alliance conditions for SW last scenarios
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, logic, campaign

#5969 Update Belarusian translation
  files/lang/be.po
Labels: improvement, translation

#6133 Drop support for save file formats older than 0.9.19
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: improvement

#6131 Reset hero meeting flag every time if hero's strength has changed
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: bug, AI

#6134 Fix monster upgrade cost formula
  src/fheroes2/monster/monster.cpp
Labels: improvement, logic

#6129 Update the Norwegian translation
  files/lang/nb.po
Labels: improvement, translation

#6061 Changed "Manual" string to "autoBattle|Manual" to separate it from game credits "Manual".
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_credits.cpp
Labels: improvement, translation

#6151 Fix Android filesystem related logic
  src/engine/system.cpp
Labels: bug, Android

#6152 IWYU: add <cmath> as another alias for std::abs()'s internal header
  iwyu.map
Labels: improvement

#6153 Fix bugs in the execution flow detected by SonarCloud
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/monster/monster.cpp
Labels: bug

#5484 update debian packaging script
  script/packaging/common/fheroes2.desktop
  script/packaging/debian/README.txt
  script/packaging/debian/compat
  script/packaging/debian/control
  script/packaging/debian/copyright
  script/packaging/debian/docs
  script/packaging/debian/install
  script/packaging/debian/manpages
  script/packaging/debian/rules
  script/packaging/debian/upstream/metadata
Labels: improvement, script

#6150 Do not show any hero status for AI heroes
  src/fheroes2/heroes/heroes.cpp
Labels: improvement, ui

#6143 Version 0.9.21
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
Labels: improvement

#6158 Fix download links after 0.9.21
  docs/INSTALL.md
Labels: improvement, deployment, high priority

#6167 Correctly reflect the change of fullscreen mode in the graphics settings dialog when it was toggled using a hotkey
  src/fheroes2/dialog/dialog_graphics_settings.cpp
Labels: bug, ui

#6173 Tower::GetInfo(): correctly reflect the fact that the tower was destroyed during the battle
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_tower.h
Labels: bug, ui

#6172 Make battle: deterministic events option by default
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#6171 Fix UI elements for an unhired hero popup window
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui, regression

#6177 Tower::GetInfo(): add const
  src/fheroes2/battle/battle_tower.cpp
Labels: improvement

#6181 Clang-Tidy: disable the bugprone-easily-swappable-parameters check
  .clang-tidy
Labels: improvement, GitHub Actions

#6168 Always center text when a maximum width is provided
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
Labels: improvement, ui

#6196 Make the heroes: remember movement points when retreating or surrendering option by default
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#6164 Update captain's mana on map load and when building the Captain's Quarters
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/castle.cpp
Labels: bug, ui

#6184 Always show the Ultimate Artifact behind one of the last four central pieces of the puzzle
  src/fheroes2/resource/artifact_ultimate.cpp
Labels: bug, logic

#6190 Remove the castle: allow guardians option
  fheroes2-vs2017.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_heroes.h
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, ui, logic

#6191 Remove the game: offer to continue the game after victory option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui, logic

#6200 Fix recent code smells
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/gui/ui_castle.h
Labels: improvement

#6199 Rework credits page
  src/fheroes2/game/game_credits.cpp
Labels: improvement, ui

#6166 Reference project affiliated donation and social network links
  .github/FUNDING.yml
  README.md
  docs/README.md
  docs/README.txt
  files/lang/ru.po
  src/fheroes2/game/game_credits.cpp
Labels: documentation

#6201 Remove the world: Scouting skill shows extended content info option
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_ui_helper.cpp
  src/fheroes2/army/army_ui_helper.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#6206 Add SDLCALL to callbacks used by SDL, remove the SDL_SetEventFilter()
  iwyu.map
  src/engine/audio.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: bug, improvement

#6209 Fix some recently introduced code smells
  src/engine/localevent.cpp
  src/fheroes2/castle/castle.cpp
Labels: improvement

#6205 Remove the world: allow to set guardian to objects option
  fheroes2-vs2017.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, logic

#6179 Use parabolic catapult projectile flight trajectory
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#5878 Map scroll with left button
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
Labels: improvement, ui, high priority

#6193 Implement all troops transfer to castle dialog
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle_dialog.cpp
Labels: improvement, ui

#6215 Remove the heroes: allow buy a spellbook from Shrines option
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#6219 Remove the world: Windmills, Water Wheels and Magic Gardens can be captured option
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, logic

#6217 Make fullscreen mode as a default state for Android devices
  src/engine/core.cpp
  src/engine/core.h
  src/fheroes2/system/settings.cpp
Labels: improvement, Android

#6216 Change battlefield hexagon generation to match the original
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#6213 Rework SDL events handling
  src/engine/core.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement

#6210 Integrate "battle: show damage info" into the game
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#6220 Remove CONFIG button from scenario info dialog
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: improvement, ui

#6225 Fix recent code smells
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/pairs.h
Labels: improvement

#6223 Rework key modifiers logic
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement

#6224 Disable Adventure Map scrolling for handheld devices by default
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui, Android

#6102 Fix cursor software rendering mode on SDL 2 builds
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/system/settings.cpp
Labels: bug, ui

#6092 Add mouse right click simulation on touchscreen devices
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: improvement, ui

#6227 Do not show resolution dialog on handheld devices on the first startup
  src/fheroes2/game/game_mainmenu.cpp
Labels: ui, translation

#6233 Style nits
  src/engine/core.cpp
  src/engine/core.h
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement

#6234 Fix inability to toggle V-Sync dynamically
  src/engine/screen.cpp
Labels: bug, ui

#6232 Remove experimental options dialog
  fheroes2-vs2017.vcxproj
  fheroes2-vs2019.vcxproj
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#6240 Clean up translation files
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/uk.po
Labels: improvement, translation

#6235 Fix multiple issues with auxiliary functions from the engine
  src/engine/dir.cpp
  src/engine/logging.cpp
  src/engine/logging.h
  src/engine/rand.cpp
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/tools/extractor.cpp
  src/tools/icn2img.cpp
  src/tools/til2img.cpp
Labels: bug, improvement

#6238 Remove the heroes: allow to choose any primary skill in Arena option
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#6244 iwyu.map: add new private header mappings for newer Ubuntu image version, speed up IWYU workflow a bit
  .github/workflows/iwyu.yml
  iwyu.map
  src/fheroes2/agg/bin_info.h
  src/fheroes2/monster/monster_info.h
  src/fheroes2/resource/artifact_info.cpp
  src/fheroes2/resource/artifact_info.h
Labels: improvement

#6247 Fix a few recent code smells
  src/engine/rand.cpp
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/dialog/dialog.h
Labels: improvement

#6169 Generate resizable buttons for both interfaces
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
Labels: improvement, ui

#6245 Fix the scenario info dialog position
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: bug, ui

#6250 Java: use final where appropriate
  android/app/src/main/java/org/fheroes2/MainActivity.java
Labels: improvement, Android

#6239 Remove the battle: allow soft wait for troops option
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/system/settings.h
Labels: improvement, logic

#6192 Integrate the game: autosave will be made at the beginning of the day option
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#6243 Add Android installation and usage documentation
  .github/workflows/android.yml
  docs/INSTALL.md
  docs/README_android.md
Labels: documentation, Android

#6163 Bulgarian Translation 17
  files/lang/bg.po
Labels: improvement, translation

#6229 Fix multiple issues with fullscreen mode on Windows
  src/engine/screen.cpp
  src/fheroes2/system/settings.cpp
Labels: bug, Windows, ui

#6251 Store everything in the fheroes2.cfg, remove the binary config file support
  src/engine/tinyconfig.cpp
  src/engine/tinyconfig.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_box.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#6176 Introduce AI Scout role
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#6256 Add shadowing for fog in debug build
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, ui

#6261 Set the minimum supported version to Android 6.0
  android/app/build.gradle
Labels: bug, improvement, Android

#6264 Remove some leftovers of support for visiting the allied castles
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement

#6266 Use explicit shell: bash in GitHub Actions scripts
  .github/workflows/android.yml
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
  .github/workflows/cmake.yml
  .github/workflows/code_style_check.yml
  .github/workflows/iwyu.yml
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  .github/workflows/pr_author_auto_assign.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/translation_update.yml
Labels: improvement, script, GitHub Actions

#6249 Fix French and Italian characters not being shown with their assets
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#6270 Update the dependency package hashes for Android & Windows
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#6268 Improve rendering speed with software cursor rendering
  src/engine/audio.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/screen.h
  src/engine/timing.cpp
  src/engine/timing.h
  src/engine/tools.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
Labels: improvement

#6271 Add Danish language option and font
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
Labels: improvement, translation
