Repository ihhub/fheroes2, pull requests merged in 2022-07, with the labels that each got.

#5584 Add logging for Ultimate Artifact placement
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#5585 Fix build order regression for AI towns
  src/fheroes2/ai/normal/ai_normal_castle.cpp
Labels: AI, regression

#5582 Fix multiple audio issues
  src/engine/audio.cpp
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_audio.h
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, audio

#5587 Remove unused field move_point_scale from the Heroes class
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
Labels: improvement

#5583 Implement AI courier hero role for better logistics
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#5040 Allow different translations of "Red Tower"
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  src/fheroes2/castle/castle_building_info.cpp
Labels: improvement, translation

#5586 Update debug mode logging to include hero role
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, low priority

#5554 Update French translation
  files/lang/fr.po
Labels: improvement, translation

#5577 Update Polish translation - "Red Tower" #5040
  files/lang/pl.po
Labels: improvement, translation

#5588 Mixer::SetChannels(): don't call the Mix_ReserveChannels()
  src/engine/audio.cpp
Labels: improvement, audio

#5439 Fixed missing column of pixels
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui

#5592 Fix Campaign Window button flickering
  src/fheroes2/agg/agg_image.cpp
Labels: bug

#5591 Fix incorrect animation effect for castle's window
  src/fheroes2/castle/castle_dialog.cpp
Labels: ui, regression

#5589 Align File Options dialog position
  src/fheroes2/dialog/dialog_file.cpp
Labels: improvement, ui

#5590 Fix extra shadow being drawn for Hero Screen
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, ui

#5595 Fix the class of a hero named Joseph
  src/fheroes2/heroes/heroes.cpp
Labels: bug, campaign

#5596 Fix campaign button change regression
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/game/game_campaign.cpp
Labels: ui, regression

#5597 Show a window stating about missing video files for campaigns
  src/fheroes2/game/game_newgame.cpp
Labels: improvement, ui

#5599 Add The Price of Loyalty team to credits
  src/fheroes2/game/game_credits.cpp
Labels: improvement, ui

#5604 Remove the redundant cast
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement

#5601 Remove some usage of old Text classes
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/maps/maps_actions.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/resource/artifact.cpp
Labels: improvement

#5609 Preparations for Adventure Map rendering
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.h
Labels: bug, logic

#5605 When scouting, use a straight line distance instead of an approximate distance, rework the neutral monsters counting logic for the extended scouting
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_ui_helper.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/world/world_regions.cpp
Labels: bug, logic

#5611 Allow to remap HotKeys within the game
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement, ui

#5615 Always ask about rewriting an existing save file
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#5614 Fix a crash when no AI heroes exist
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: AI, crash, regression, high priority

#5608 Do not call SDL_Mixer functions from the callback set by the Mix_ChannelFinished()
  src/engine/audio.cpp
Labels: bug, audio, crash

#5617 Version 0.9.17
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
Labels: improvement

#5593 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#5630 Fix redrawing of the status window in cases when the hero's army or the castle garrison change without changing focus
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui, regression

#5623 Update main page screenshots
  README.md
  VisualStudio/common.props
  docs/images/screenshots/screenshot_battle.png
  docs/images/screenshots/screenshot_castle.png
  docs/images/screenshots/screenshot_world_map.png
  src/engine/image_tool.cpp
Labels: improvement, documentation

#5638 Remove unused variable
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement

#5636 Use right graphic for create upgrades at adventure objects
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#5635 Add support for loading of MIDI sound fonts
  .github/workflows/cmake.yml
  src/engine/audio.cpp
  src/engine/audio.h
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, audio

#5619 Color cycling code cleanup
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_logo.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement

#5639 fix typos in ru.po and hu.po
  files/lang/hu.po
  files/lang/ru.po
Labels: improvement, translation

#5637 When adding a custom spellbook while loading a hero from MP2, check that the hero does not have it yet
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic

#5644 Add auto-calculated resolutions
  src/engine/screen.cpp
Labels: improvement, ui

#5642 Small code cleanup
  src/engine/core.cpp
  src/engine/xmi2mid.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_grave.h
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
Labels: improvement

#5640 Update image sizes on the published web page
  docs/README.md
Labels: bug, documentation

#5649 Revert resolution changes and add checks for rendering
  src/engine/screen.cpp
Labels: bug, ui, regression

#5655 Remove virtual from Troop::GetCount()
  src/fheroes2/army/army_troop.h
Labels: improvement

#5658 Update treasure chest AI decision logic
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#5661 Update SDL to 2.0.22 version for Windows
  script/windows/install_packages.bat
  script/windows/setup_packages.bat
  src/engine/audio.cpp
  src/engine/screen.cpp
Labels: improvement, ui

#5632 Bulgarian Translation
  files/lang/bg.po
Labels: improvement, translation

#5668 Fix number of ghosts and splitting for Shipwreck, Haunt and Abandoned Mine cases
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: bug, logic

#5673 Add missing window frame for hero's dialog during level up
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: ui, regression

#5675 Fix incorrect castle's area leading to wrong castle's info
  src/fheroes2/castle/castle.cpp
Labels: bug

#5682 Fix an assertion crash for Shipwreck guardians
  src/fheroes2/army/army.cpp
Labels: bug, crash, regression

#5680 Remove cryptic quantity3 member from Tiles class
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_recruits.cpp
  src/fheroes2/heroes/heroes_recruits.h
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/system/save_format_version.h
Labels: improvement

#5659 Yet another Makefile improvement
  src/Makefile
  src/dist/Makefile
  src/tools/Makefile
Labels: improvement, deployment

#5683 Replace macos-10.15 by macos-11
  .github/workflows/make.yml
Labels: deployment, macOS, GitHub Actions

#5687 Update comments and logging for XMI conversion
  src/engine/xmi2mid.cpp
Labels: improvement, audio

#5689 Update the dependency package hash for Windows
  script/windows/install_packages.bat
Labels: improvement

#5686 Cleanup hero rendering code as a part of Adventure Map rendering
  src/engine/image.cpp
  src/engine/image.h
  src/engine/image_tool.cpp
  src/engine/screen.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, ui

#5674 Fix missing retaliation delay after last animation frame
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#5704 MSVC workflow: use 7zip instead of Info-ZIP
  .github/workflows/msvc.yml
Labels: bug, deployment, GitHub Actions

#5705 Fix build with earlier Windows SDKs, copy soundfonts and *.mo files (if they exist) to the $(OutDir)
  VisualStudio/SDL1.props
  VisualStudio/SDL2.props
  VisualStudio/common.props
  src/engine/audio.cpp
  src/engine/dir.cpp
  src/engine/logging.cpp
  src/engine/system.cpp
Labels: improvement, Windows

#5697 Fix experience from Tree of Knowledge
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#5685 Bulgarian Translation second PR
  files/lang/bg.po
Labels: improvement, translation

#5698 fix starting xp
  src/fheroes2/heroes/heroes.cpp
Labels: bug, logic
