Repository ihhub/fheroes2, pull requests merged in 2022-03, with the labels that each got.

#5059 Fix directory and file detection on Windows
  src/engine/dir.cpp
  src/engine/system.cpp
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, Windows

#5057 Fix some french translations
  files/lang/fr.po
Labels: improvement, translation

#5066 Add missing artifact discovery event description
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: improvement, ui

#5069 Fix Sirens action dialogs
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#5065 Add dynamic generation of scrollbar slider
  src/engine/screen.cpp
  src/engine/zzlib.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/gui/ui_scrollbar.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/system/gamedefs.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement, ui

#5072 Increase the fetch-depth for clang_tidy.yml and code_style_check.yml workflows
  .github/workflows/clang_tidy.yml
  .github/workflows/code_style_check.yml
  script/tools/check_copyright_headers.py
Labels: bug, script, regression, GitHub Actions

#5073 Show missing last frame of wince animation
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#5071 Fix Sirens logic, AI interaction and UI
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, improvement, ui, AI

#5006 Add base support for text mode
  src/engine/logging.cpp
  src/engine/logging.h
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/system/settings.cpp
Labels: improvement

#5068 Display the correct size of player-owned objects on mini-map
  src/fheroes2/gui/interface_radar.cpp
Labels: improvement, ui

#5062 Use move constructor instead of copying strings by value
  src/fheroes2/game/game_logo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#5067 Allow selecting options while restarting a campaign scenario
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#5076 Fix a crash caused by a broken object being rendered on mini-map
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: crash, regression

#5074 Remove H3 related option
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/skill_bar.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/monster/monster_info.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui, logic

#5078 Remember map size selection
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement, ui

#5080 Add popup windows for campaign scenario dialog buttons
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui, campaign

#5079 Remove Map loading screen
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement, ui

#5081 Add popup windows for campaign awards and bonuses
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui, campaign

#5083 Check for the git failures in pipelines
  .github/workflows/clang_tidy.yml
  script/tools/check_code_format.sh
  script/tools/check_copyright_headers.sh
Labels: improvement, script, GitHub Actions

#5077 Show captain quick info dialog
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui

#5105 Add popup dialogs for Arena's skill choices
  src/fheroes2/dialog/dialog_arena.cpp
Labels: improvement, ui

#5095 Added search for FLAC files if Ogg files aren't found
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/agg/agg.cpp
Labels: improvement, sound

#5104 Fix some issues with UI windows
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, improvement, ui

#5103 Code cleanup
  src/engine/image.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/xmi2mid.cpp
  src/engine/zzlib.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/payment.h
  src/fheroes2/maps/maps_actions.h
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/artifact_ultimate.cpp
  src/fheroes2/resource/artifact_ultimate.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#5106 Fix rare case of Shipwreck having no battle
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#5108 Let the hero surrender to the captain during the siege
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, logic

#5110 Increase the number of sound channels to 32
  src/fheroes2/game/fheroes2.cpp
Labels: bug, sound

#5111 Use Okay over OK
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement, ui

#5109 Add MP3 file support
  src/engine/agg_file.cpp
  src/engine/agg_file.h
  src/engine/audio.cpp
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
Labels: bug, improvement, sound

#5117 Fix a few recent code smells
  src/fheroes2/agg/mus.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: improvement

#5113 Fix translation and UI in Tavern dialog
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/engine/timing.h
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/resource/artifact_ultimate.cpp
  src/fheroes2/resource/artifact_ultimate.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui

#5118 Do not show experience value in popup window
  src/fheroes2/gui/ui_dialog.cpp
Labels: improvement, ui

#5119 Dynamically update Game Language dialog
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, ui

#5116 Properly center the first sentence in the battle surrender dialog
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#5112 Do not render extra frame while playing an audio only video file
  src/fheroes2/game/game_video.cpp
Labels: improvement, video

#5124 Greatly speedup heavy video loading
  src/engine/smk_decoder.cpp
Labels: improvement, video

#5123 Another round of code cleanup
  src/engine/audio.cpp
  src/engine/localevent.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#5125 More performance improvements
  src/engine/screen.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_language_selection.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement

#5128 Fix incorrect popup monster window in Well
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_well.cpp
Labels: bug, ui, regression

#5129 Set the direction for attacking and defending units in battle in a more OG-like way
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: improvement, ui, logic

#4711 Fix position of armies for quick info window for both castle and enemy hero
  fheroes2-vs2019.vcxproj
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_ui_helper.cpp
  src/fheroes2/army/army_ui_helper.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#5132 Fix incorrect logic for palette application function
  src/engine/image.cpp
Labels: bug, ui

#5134 Add libFLAC DLL into Windows packages
  script/windows/setup_packages.bat
Labels: bug, Windows, sound

#5137 Add libmpg DLL into Windows packages
  script/windows/setup_packages.bat
Labels: improvement, Windows, sound

#5135 Add mandatory requirement of h2d file being present
  VisualStudio/common.props
  src/fheroes2/agg/agg.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/h2d/h2d.h
Labels: improvement, logic

#5138 Add a popup window for battle log
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#5142 Combat: calculate the position of the wide attacking unit based on the direction of attack
  src/fheroes2/battle/battle_action.cpp
Labels: improvement, ui, logic

#5087 Update Norwegian translation with new strings
  files/lang/nb.po
Labels: improvement, translation

#5150 Remove memory copy while reading data from AGG file
  src/fheroes2/agg/agg.cpp
Labels: improvement

#5148 Build player influence map to inform AI kingdom development decisions
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement, AI

#5094 Updated macOS paths to OS-canonical paths
  CMakeLists.txt
  Makefile
  docs/INSTALL.md
  script/demo/download_demo_version.sh
  script/demo/download_demo_version_for_app_bundle.sh
  script/homm2/extract_homm2_resources.sh
  script/homm2/extract_homm2_resources_for_app_bundle.sh
  src/Makefile.osx
  src/dist/Makefile
  src/engine/CMakeLists.txt
  src/engine/logging.cpp
  src/engine/logging.h
  src/engine/system.cpp
  src/fheroes2/CMakeLists.txt
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/image/embedded_image.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/resources/Info.plist.in
  src/resources/fheroes2.icns
Labels: improvement, macOS

#5155 Optimize fighter hero priorities
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#5159 Update minimap colors
  src/fheroes2/gui/interface_radar.cpp
Labels: ui

#5156 Take the weekly growth into account when calculating monthly population growth bonuses and fines
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
Labels: bug, logic

#5158 GitHub Actions: build the macOS App Bundle
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cmake.yml
  .github/workflows/make.yml
  .github/workflows/sonarcloud.yml
  CMakeLists.txt
  Makefile
  VisualStudio/SDL2.props
  docs/DEVELOPMENT.md
  docs/INSTALL.md
  script/demo/download_demo_version_for_app_bundle.sh
  script/homm2/extract_homm2_resources_for_app_bundle.sh
  script/packaging/debian/rules
  src/CMakeLists.txt
  src/Makefile
  src/Makefile.osx
  src/dist/Makefile
  src/engine/CMakeLists.txt
  src/engine/image_tool.cpp
  src/fheroes2/CMakeLists.txt
  src/fheroes2/system/settings.cpp
  src/resources/fheroes2.icns
  src/thirdparty/CMakeLists.txt
  src/tools/CMakeLists.txt
  src/tools/Makefile
  src/tools/icn2img.cpp
  src/tools/til2img.cpp
Labels: improvement, script, deployment, macOS, GitHub Actions

#5154 Prioritize AI castles further from enemy territory
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#5160 Fix typo in CMakeLists
  CMakeLists.txt
Labels: bug, CMake

#5120 Fix Town Gate spell logic
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_info.cpp
Labels: improvement, ui

#5161 Optimize GitHub Actions workflows
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
  .github/workflows/cmake.yml
  .github/workflows/code_style_check.yml
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  .github/workflows/pr_author_auto_assign.yml
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
  .github/workflows/sonarcloud.yml
Labels: improvement, script, GitHub Actions

#5169 Avoid extra memory copy during video loading
  src/engine/smk_decoder.cpp
Labels: improvement, video

#5157 Reduce the number of storage I/O calls while searching for data
  VisualStudio/common.props
  src/engine/dir.cpp
  src/engine/dir.h
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#5170 Fix the calculation of the cost of surrender
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: bug, logic

#5171 Remove unnecessary call to play VICTORY music during Campaign intro
  src/fheroes2/game/game_newgame.cpp
Labels: bug, sound

#5151 Combat: implement the infrastructure to change the unit's "main" cell when positioning it on the battlefield
  src/engine/tools.cpp
  src/engine/tools.h
  src/engine/xmi2mid.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_bridge.h
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_grave.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_only.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/gui/ui_language.h
  src/fheroes2/world/world.h
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, logic

#5136 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#5177 Avoid extra memory reallocations while handling stream buffers
  src/engine/serialize.cpp
Labels: improvement

#5178 Use move operators for Stream Buffer
  src/engine/serialize.cpp
  src/engine/serialize.h
Labels: improvement

#5179 GitHub Actions: use shallow clone for VDPM, fix broken PSV build, improve Makefiles
  .github/workflows/make.yml
  CMakeLists.txt
  Makefile
  files/lang/Makefile
  src/CMakeLists.txt
  src/Makefile
  src/Makefile.all
  src/Makefile.bsd
  src/Makefile.mingw
  src/Makefile.mingw32
  src/Makefile.osx
  src/Makefile.switch
  src/Makefile.vita
  src/dist/Makefile
  src/engine/CMakeLists.txt
  src/engine/Makefile
  src/fheroes2/CMakeLists.txt
  src/thirdparty/CMakeLists.txt
  src/thirdparty/libsmacker/Makefile
  src/tools/CMakeLists.txt
  src/tools/Makefile
Labels: improvement, script, GitHub Actions

#5181 Fix rendering of bottom bar in Well dialog
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, assets

#5182 Fix a few recent code smells
  src/engine/rand.h
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/resource/artifact.h
Labels: improvement

#4913 Adjust AI spell estimates
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
Labels: improvement, AI

#5174 Fix High Score Music after winning scenario
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, sound

#5176 Fix army order option related crash
  src/engine/image.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui, crash

#5183 Fix the build for PSV, add multiple warning-related compiler flags to the Makefile, remove useless -Weffc++ from the waiting list
  src/Makefile
  src/Makefile.vita
  src/fheroes2/army/army_bar.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
  src/fheroes2/dialog/dialog_settings.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/objects/objcrck.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/spell/spell.cpp
  src/tools/82m2wav.cpp
Labels: improvement, high priority

#5185 Clang-Tidy: disable the cppcoreguidelines-pro-type-reinterpret-cast check
  .clang-tidy
Labels: improvement

#5186 Fix regression for AGG file search
  src/fheroes2/agg/agg.cpp
Labels: bug, logic, regression
