Repository ihhub/fheroes2, pull requests merged in 2022-09, with the labels that each got.

#5782 UI elements code cleanup
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_bar.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog_guardian.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: improvement, ui

#5802 Fix start resources for AI players
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic, AI

#5774 Bulgarian Translation update
  files/lang/bg.po
Labels: improvement, translation

#4865 Fixed messages displayed with captains
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#5798 Show intro videos like in the original game
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/game/fheroes2.cpp
Labels: bug, video

#5813 Fix refresh of campaign window after choosing difficulty
  src/fheroes2/game/game_campaign.cpp
Labels: bug, ui

#5799 UI cleanup (part 2)
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/gui/ui_base.cpp
  src/fheroes2/gui/ui_base.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement, ui

#5785 Implement some improvements when exchanging an army between heroes
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#5811 Polish translation - Artifacts' little stories
  files/lang/pl.po
Labels: improvement, translation

#5760 Fix constantly moving AI heroes when they have nothing to do
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, AI

#5815 Generate MIN button based on newly added font
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui

#5816 Add popup dialogs for Well's buttons
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, ui

#5821 Version 0.9.19
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
Labels: improvement

#5805 Update French translation
  files/lang/fr.po
Labels: improvement, translation

#5828 Fix incorrectly rendered monochrome cursor for campaign selection window
  src/fheroes2/gui/cursor.cpp
Labels: bug, ui

#5832 Include rating calculation for Campaign's high score
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/highscores.cpp
  src/fheroes2/game/highscores.h
Labels: improvement, ui, campaign

#5829 Use sound volume when playing music for map objects
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, audio

#5837 Fix incorrect rendering calls being done by scrollbars
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: bug, ui

#5844 Fix crosshair rendering on Mini-map and missing selection in Marketplace
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/gui/interface_radar.cpp
Labels: bug, ui, regression

#5836 Generate new default Gift button, move Difficulty button generation, fix pressed evil buttons
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui, translation

#5839 Add Handicap feature present in the OG
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/player_info.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/system/save_format_version.h
Labels: bug, improvement, ui

#5855 Update the dependency package hash for Windows
  script/windows/install_packages.bat
Labels: improvement, Windows, deployment

#5854 Before setting a handicap for a player, make sure that this player cannot be controlled by AI
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/system/players.cpp
Labels: bug, ui, crash

#5845 Bulgarian Translation Update 5
  files/lang/bg.po
Labels: improvement, translation

#5846 Fix switching of terrain music in case of hero loss
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, audio

#5864 Fix incorrect current save format
  src/fheroes2/system/save_format_version.h
Labels: bug, regression

#5853 Generate button letters A, B, E, H, P, R, S and new Battle Only button
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui, translation

#5866 Add enhancements link to frontpage
  README.md
  docs/README.md
Labels: documentation

#5871 Generate J, Q, V, W, X, Z, -
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui

#5860 Bulgarian Translation Update 8
  files/lang/bg.po
Labels: improvement, translation

#5875 Restructure button font generation code to support future code pages
  src/engine/image.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_font.h
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui

#5874 Make creature names lowercased
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: ui, translation

#5879 Add a feature to give human player control to AI (debug build only)
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/world/world.cpp
Labels: improvement, logic, AI

#5889 Fix incorrect object evaluation for AI heroes on boats
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, AI

#5891 AI battle pathfinder: fix logic of processing cells containing units available for possible attack
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
Labels: bug, logic, AI

#5873 Bulgarian Translation Update 10
  files/lang/bg.po
Labels: improvement, translation

#5868 UI improvements of the Settings dialog
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: improvement, ui, translation

#5876 Make logging for monster movement in battle more user-friendly
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#5900 Decrease monster growth bonus for AI
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: improvement, AI

#5901 Apply usual rules for unit growth in neutral towns/castles with custom troops
  src/fheroes2/castle/castle.cpp
Labels: bug, logic

#5886 Generate button fonts for different code pages
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_font.h
Labels: improvement, ui, translation

#5902 install_packages.bat: return nonzero value on error, update package hash
  script/windows/install_packages.bat
Labels: improvement, Windows, script

#5897 Take into consideration a case with full artifact bag while checking …
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, AI
