Repository ihhub/fheroes2, pull requests merged in 2023-08, with the labels that each got.

#7504 Add an extra check for AI Gold income bonus
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement, AI

#7509 Update the Norwegian Translation
  files/lang/nb.po
Labels: improvement, translation

#7507 Rephrase various game dialogs
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/heroes/heroes_base.cpp
Labels: improvement, ui

#7479 Add Summon Boat spell support for AI
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, AI

#7505 Update danish 1.0.7
  files/lang/dk.po
Labels: improvement, translation

#7495 german translation update
  files/lang/de.po
Labels: improvement, translation

#7513 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#7499 Upd Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#7519 Fix Army info button in level up dialog
  src/fheroes2/agg/agg_image.cpp
Labels: bug, ui, regression

#7515 Make various EXIT, the well's MAX and some leftover buttons translatable and fix the castle EXIT button
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, improvement, ui, regression, translation

#7465 Update of the Slovak Translation
  files/lang/sk.po
Labels: improvement, translation

#7525 Update danish translation (v.1.0.7)
  files/lang/dk.po
Labels: improvement, translation

#7510 Android Toolset: add the ability to export and import save files (as a ZIP archive)
  android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/app/src/main/res/drawable-hdpi/btn_export.png
  android/app/src/main/res/drawable-hdpi/btn_import.png
  android/app/src/main/res/drawable-mdpi/btn_export.png
  android/app/src/main/res/drawable-mdpi/btn_import.png
  android/app/src/main/res/drawable-night-hdpi/btn_export.png
  android/app/src/main/res/drawable-night-hdpi/btn_import.png
  android/app/src/main/res/drawable-night-mdpi/btn_export.png
  android/app/src/main/res/drawable-night-mdpi/btn_import.png
  android/app/src/main/res/drawable-night-xhdpi/btn_export.png
  android/app/src/main/res/drawable-night-xhdpi/btn_import.png
  android/app/src/main/res/drawable-night-xxhdpi/btn_export.png
  android/app/src/main/res/drawable-night-xxhdpi/btn_import.png
  android/app/src/main/res/drawable-night-xxxhdpi/btn_export.png
  android/app/src/main/res/drawable-night-xxxhdpi/btn_import.png
  android/app/src/main/res/drawable-xhdpi/btn_export.png
  android/app/src/main/res/drawable-xhdpi/btn_import.png
  android/app/src/main/res/drawable-xxhdpi/btn_export.png
  android/app/src/main/res/drawable-xxhdpi/btn_import.png
  android/app/src/main/res/drawable-xxxhdpi/btn_export.png
  android/app/src/main/res/drawable-xxxhdpi/btn_import.png
  android/app/src/main/res/layout/activity_save_file_manager.xml
  android/app/src/main/res/layout/activity_toolset.xml
  android/app/src/main/res/values-ru/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: improvement, Android

#7533 SonarCloud: fix the warning about the Java 11 deprecation
  .github/workflows/sonarcloud.yml
Labels: bug, GitHub Actions

#7532 Fix a few recently introduced code smells, fix GitHub Actions build with ASAN & TSAN
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/code_style_check.yml
  .github/workflows/iwyu.yml
  .github/workflows/make.yml
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
Labels: bug, improvement, GitHub Actions

#7530 Update danish translation v.1.0.7 (1295)
  files/lang/dk.po
Labels: improvement, translation

#7531 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7537 Battle AI should switch to offense instead of passing
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: improvement, AI

#7506 Prepare the code for the future AI resource trading logic
  VisualStudio/fheroes2/sources.props
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/kingdom/resource_trading.cpp
  src/fheroes2/kingdom/resource_trading.h
Labels: improvement, AI

#7536 Update danish translation (1133)
  files/lang/dk.po
Labels: improvement, translation

#7538 Update the Norwegian translation
  files/lang/nb.po
Labels: improvement, translation

#7522 Rework the "select from list" dialogs used in Battle only mode to use them in Editor in future
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/ui_scrollbar.h
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui, editor

#7500 Fix estimation of the castle garrison strength for priority tasks
  src/engine/image.cpp
  src/engine/system.cpp
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, AI

#7550 Fix marketplace assertion if one of the resources is not selected
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/kingdom/resource_trading.cpp
Labels: bug, high priority

#7549 Don't handle an event on the map twice
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#7471 Do not play simultaneous walk/fly sounds for battle speed 9 and 10
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, audio

#7544 Fix some recently introduced code smells
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement

#7542 AI heroes shouldn't know what exactly a Treasure or Sea Chest contains
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#7552 Fix issue when AI hero "jumps back" during the fog discovery, various fixes & improvements
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/system/save_format_version.h
Labels: bug, AI, high priority

#7559 Fix some recent code smells
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: improvement

#7561 Version 1.0.7
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#7521 Implement basic terrain draw in Map Editor (currently without terrain connections)
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/gui/interface_base.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, editor

#7563 Update Android & Windows dependencies
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, deployment, Android

#7553 AI should decline battles if passing by
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement, AI

#7566 Swe. Translation Update
  files/lang/sv.po
Labels: improvement, translation

#7567 Fix the regression and minor issue in the AI pathfinder, fix crash in the priority task management due to an assertion failure, improve the distance estimation when an AI-controlled hero passes through objects on the map
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, AI

#7572 Fix some of the recently introduced code smells
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#7490 Remember map filter selection until you quit the game
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: improvement, ui

#7487 Allow early exit from puzzle map during reveal animation
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#7571 Update ukrainian translate
  files/lang/uk.po
Labels: improvement, translation

#7569 Swe. Translation Update
  files/lang/sv.po
Labels: improvement, translation

#7540 Update danish translation (955)
  files/lang/dk.po
Labels: improvement, translation

#7589 Add "Victory!" title to victory dialog
  src/fheroes2/game/game_over.cpp
Labels: improvement, ui

#7587 Add "New Month!" title for new month
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, ui

#7597 Improve Mage guild status message for learnt spells
  src/fheroes2/castle/castle_mageguild.cpp
Labels: improvement, ui

#7595 Fix size of the button letter Æ
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui, translation

#7592 Swedish Translation Update
  files/lang/sv.po
Labels: improvement, translation

#7598 Add A and O with diaereses to CP1252 button font
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui, translation

#7603 Update Contributing file
  CONTRIBUTING.md
Labels: improvement, documentation

#7588 Ukrainian Translate upd 08.21.23
  files/lang/uk.po
Labels: improvement, translation

#7606 Center text in hero battle info window
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#7614 Use "Redmean" color distance calculation for GetPALColorId()
  src/engine/image.cpp
Labels: improvement, ui

#7615 Adjust text for Quick Info dialogs
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#7621 Kingdom Overview: fix update of Army Bar in Towns/Castles, fix render of extra dialog shadow after recruiting/dismissing a hero
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, improvement, ui

#7613 Update Danish Translation (76% / 644)
  files/lang/dk.po
Labels: improvement, translation

#7612 Ukrainian Update 23.08.23
  files/lang/uk.po
Labels: improvement, translation

#7625 Avoid extra image copy while constructing specific buttons
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement

#7620 Multiple CMake-related improvements
  CMakeLists.txt
  Makefile
  cmake/FindSDL2.cmake
  cmake/FindSDL2_image.cmake
  cmake/FindSDL2_mixer.cmake
  cmake/LICENSE.md
  cmake/README.md
  cmake/README_fheroes2.md
  cmake/README_findsdl2.md
  iwyu.map
  src/engine/CMakeLists.txt
  src/fheroes2/CMakeLists.txt
  src/thirdparty/CMakeLists.txt
Labels: improvement, CMake

#7622 Fix monster name in monster info dialog
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, ui

#7624 Show ... in Load/Save File dialog for long names
  src/fheroes2/army/army_ui_helper.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
Labels: improvement, ui

#7641 Shift text in Surrender window
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#7637 Expand clickable area for settings in the Main Menu
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, ui

#7638 Change Shipyard construction message
  src/fheroes2/castle/buildinginfo.cpp
Labels: improvement, ui

#7632 Fix Load/Save file title position and color
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: improvement, ui

#7644 Fix missing hero and town name in dialogs
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui

#7642 Speed up map, translation and save files loading
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/tinyconfig.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/engine/translations.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
Labels: improvement

#7649 Fix the weird logic of MP2::isWaterActionObject()
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/maps/mp2.cpp
Labels: bug, logic, crash

#7640 Add small skill icons for Xanadu visit dialog
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#7661 Fix a few minor code issues
  src/engine/tinyconfig.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement

#7657 Show the "You have been eliminated from the game" message in the multiplayer game
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_over.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_gamearea.h
Labels: bug, ui

#7639 Cancel Hut of Magi reveal area animation when a player clicks any button
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#7653 Update Danish Translation (85% / 400)
  files/lang/dk.po
Labels: improvement, translation

#7658 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7667 Do not try to scout the area if the hero is in jail and gets an artifact assigned using the map editor
  src/fheroes2/agg/icn.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic, crash

#7659 Fix foreign pixels on snow battlefield objects
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui
