Repository ihhub/fheroes2, pull requests merged in 2023-12, with the labels that each got.

#8094 Swedish translation update (#10)
  files/lang/sv.po
Labels: improvement, translation

#8090 Add missing AI team alliance to Evil campaign's 6th scenario
  src/fheroes2/campaign/campaign_data.cpp
Labels: bug, campaign

#8092 Castle building info dialog: do not show quick info for hidden buttons
  src/fheroes2/castle/buildinginfo.cpp
Labels: bug, ui

#8101 Add text rendering within a given ROI
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
Labels: improvement, ui

#8096 Add basic logic to load and save maps through UI
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_building_info.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: improvement, editor

#8107 Don't include local headers as system headers
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#8104 Fix a crash with castle overlapping inside a map
  src/fheroes2/castle/castle.cpp
Labels: logic, crash

#8110 Speed up OG map format reading
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement, logic

#8095 Update Danish Language (v.1.0.11)
  files/lang/dk.po
Labels: improvement, translation

#8100 Hungarian language update #08
  files/lang/hu.po
Labels: improvement, translation

#8121 Fix invalid focus update after AI hero battle
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, ui

#8116 Update Vietnamese Translation P10
  files/lang/vi.po
Labels: improvement, translation

#8122 Update Spanish translation and add Spanish and Portuguese button font letters
  files/lang/es.po
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, translation

#8118 Battle pathfinder: replace std::bitset by std::array<bool>
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
Labels: improvement

#8124 Update Vietnamese Translation P11
  files/lang/vi.po
Labels: improvement, translation

#8114 Make speed of fade-in & fade-out animations for AI-controlled heroes dependent on the AI speed setting
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, ui, AI

#8111 Increased width and height of the Campaign Difficulty selection dialog
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui, campaign

#7951 Bulgarian Translation
  files/lang/bg.po
Labels: improvement, translation

#8119 Hungarian language update #09
  files/lang/hu.po
Labels: improvement, translation

#8128 Update Vietnamese Translation P12
  files/lang/vi.po
Labels: improvement, translation

#8127 Update the French translation, add missing offset for an A with accent
  files/lang/fr.po
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, translation

#8129 Update the Spanish translation
  files/lang/es.po
Labels: improvement, translation

#8139 Hungarian language update #10
  files/lang/hu.po
Labels: improvement, translation

#8135 Update Vietnamese Translation 13
  files/lang/vi.po
Labels: improvement, translation

#8103 Implement town and castle placing in the Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/gui/ui_map_object.cpp
  src/fheroes2/gui/ui_map_object.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/mp2.cpp
Labels: improvement, high priority, editor

#8138 Code cleanup for Maps::FileInfo structure
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement, logic

#8146 Set object ID for all object parts of town / castle
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, logic, editor

#8143 Add a different object popup window logic for the Editor
  VisualStudio/fheroes2/sources.props
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_object_popup_window.cpp
  src/fheroes2/editor/editor_object_popup_window.h
  src/fheroes2/gui/ui_map_interface.cpp
  src/fheroes2/gui/ui_map_interface.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: improvement, ui, editor

#8142 Update Vietnamese Translation P14
  files/lang/vi.po
Labels: improvement, translation

#8144 Hungarian language update #11
  files/lang/hu.po
Labels: improvement, translation

#8147 Add Tree of Knowledge claimed and cost info to quick info dialog
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#8047 Improve the logic of AI defensive tactics
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement, AI, high priority

#8155 Update Vietnamese Translation P15
  files/lang/vi.po
Labels: improvement, translation

#8156 Hungarian language update #12
  files/lang/hu.po
Labels: improvement, translation

#8158 Version 1.0.11
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#8134 StreamFile: improve I/O error handling
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/agg/bin_info.cpp
  src/tools/icn2img.cpp
Labels: improvement

#8132 Update the French translation
  files/lang/fr.po
Labels: improvement, translation

#8160 Fix multiple spellbook-related issues in the Battle Only mode
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_only.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: bug, ui, logic

#8150 Rework editor instrument groups: add new buttons, rework instrument panel, add evil inerface
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_base.h
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
Labels: improvement, ui, high priority, editor

#8165 Fix the AI spell damage estimation logic for units immune to the given spell
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: bug, AI

#8159 Radar rendering optimization
  src/fheroes2/editor/editor_object_popup_window.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#8169 Take into an account SHIFT and CAPS LOCK being used at the same time
  src/engine/localevent.cpp
Labels: improvement, ui

#8171 Add Campfire object in the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, editor

#8109 Update some descriptions
  src/fheroes2/army/army.cpp
  src/fheroes2/castle/castle_building_info.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/kingdom/luck.cpp
  src/fheroes2/kingdom/morale.cpp
Labels: improvement, ui

#8174 Hide swap army/artifact buttons in the Battle Only
  src/fheroes2/battle/battle_only.cpp
Labels: improvement, ui, pixel-precision

#8175 Fix too wide text in quick hero info box
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#8058 Shifted the name of the Necromancy skill in the secondary skill bar l…
  src/fheroes2/gui/skill_bar.cpp
Labels: improvement, ui

#8172 Add missing rules for the plural in Hungarian
  src/engine/translations.cpp
Labels: bug, translation

#8180 Store Map Format within Editor to allow any changes to be done directly within the format
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/editor/history_manager.cpp
  src/fheroes2/editor/history_manager.h
  src/fheroes2/maps/map_format_helper.cpp
Labels: improvement, editor

#8184 Fix inaccurate Jail removal
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: bug, logic, crash

#8187 Use singular Mine form for the corresponding object
  src/fheroes2/agg/m82.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#8167 Add base code to load new map format files
  src/engine/dir.cpp
  src/engine/dir.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/system/players.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#8195 Fix heroes with no names
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/system/save_format_version.h
Labels: bug, logic

#8181 Swedish Translation Update (#12)
  files/lang/sv.po
Labels: improvement, translation

#8188 Modify the logic to calculate owned mines
  src/fheroes2/world/world.cpp
Labels: improvement

#8176 AI: use the "cautious offensive" tactics only against melee-only armies without the distant attack potential (including damage spells)
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: bug, improvement, AI

#8198 Remove old unused object related functions
  src/fheroes2/objects/objcrck.cpp
  src/fheroes2/objects/objcrck.h
  src/fheroes2/objects/objdirt.cpp
  src/fheroes2/objects/objdirt.h
  src/fheroes2/objects/objdsrt.cpp
  src/fheroes2/objects/objdsrt.h
  src/fheroes2/objects/objgras.cpp
  src/fheroes2/objects/objgras.h
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objlava.h
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/objects/objmult.h
  src/fheroes2/objects/objsnow.cpp
  src/fheroes2/objects/objsnow.h
  src/fheroes2/objects/objswmp.cpp
  src/fheroes2/objects/objswmp.h
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/objects/objtown.h
  src/fheroes2/objects/objwatr.cpp
  src/fheroes2/objects/objwatr.h
  src/fheroes2/objects/objxloc.cpp
  src/fheroes2/objects/objxloc.h
  src/fheroes2/objects/trees.cpp
  src/fheroes2/objects/trees.h
Labels: improvement

#8191 Update buttons and add popup windows for them in Battle Only mode
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_only.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#8185 Expand the map format
  src/fheroes2/agg/agg_image.h
  src/fheroes2/gui/ui_language.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
Labels: improvement, editor

#8201 Remove more unused functions
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/mounts.h
Labels: improvement

#8178 AI: improve the heuristics of covering shooters when using defensive tactics
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#8203 Improve the AI logic for pay to hire dwellings on Adventure Map
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#8204 Small memory optimizations
  src/engine/render_processor.h
  src/engine/serialize.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, logic

#8202 Reset object UID while creating a new map in the Editor
  src/fheroes2/editor/editor_mainmenu.cpp
Labels: improvement, editor

#8197 Implement makeShadow() to work with single-layer images
  src/engine/image.cpp
Labels: improvement

#8210 Fix several SonarQube smells
  src/engine/screen.cpp
  src/engine/translations.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/system/gamedefs.h
  src/fheroes2/system/settings.cpp
Labels: improvement
