Repository ihhub/fheroes2, pull requests merged in 2023-02, with the labels that each got.

#6531 Fix scroll bar bottom position when dragging and fix high FPS rate when dragging scroll bar by mouse
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_scrollbar.cpp
Labels: bug, ui

#6539 Android Save File Manager: implement filtering of save files by type
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/res/layout/activity_save_file_manager.xml
  android/app/src/main/res/layout/activity_toolset.xml
  android/app/src/main/res/values-de/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: improvement, ui, Android

#6533 Update German in Android-Toolset
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/res/values-de/strings.xml
  android/app/src/main/res/values/strings.xml
Labels: improvement, translation, Android

#6544 Android Toolset: add Russian translation
  android/app/src/main/res/values-ru/strings.xml
Labels: improvement, translation, Android

#6537 Update Czech translation cs.po
  files/lang/cs.po
Labels: improvement, translation

#6561 Fix incorrect status bar update call
  src/fheroes2/gui/statusbar.cpp
Labels: bug, ui

#6559 Fix invalid Kingdom income calculation
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#6573 Instantly update status bar in battle for hero's dialog options
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/gui/statusbar.cpp
  src/fheroes2/gui/statusbar.h
Labels: bug, ui

#6567 Fix possibly corrupted save format
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic, high priority

#6516 Add support for scaled resolutions
  src/engine/screen.cpp
  src/engine/screen.h
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui, high priority

#6577 Update team members in credits page
  src/fheroes2/game/game_credits.cpp
Labels: improvement, ui

#6581 Update Android & Windows dependencies, bump target Android API level to 33 (Android 13)
  android/app/build.gradle
  android/app/lint.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#6585 Fix saving of Maps::Tiles and Maps::TilesAddon enums
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, regression, high priority

#6564 icn2img tool: handle multiple ICN files
  src/engine/system.cpp
  src/engine/system.h
  src/tools/icn2img.cpp
Labels: improvement

#6584 Add the ambient sound for Abandoned Mine
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/m82.h
Labels: bug, audio

#6583 Version 1.0.1
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#6591 clang-format: force reordering of header groups
  .clang-format
Labels: improvement

#6596 Fix the "unused parameter" warnings in release builds, remove unused variable
  src/engine/screen.cpp
  src/fheroes2/game/game_over.cpp
Labels: improvement

#6595 Improve installation documentation
  docs/INSTALL.md
Labels: improvement, documentation

#6606 Generate & display the current status of translations
  .github/workflows/translation_update.yml
  docs/TRANSLATION.md
Labels: improvement, translation

#6608 Move TIL image decoding to a common place
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/agg/agg_image.cpp
Labels: improvement

#6493 Combat, Adding tooltip damage info for single target attack spells
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement, ui

#6562 Optimize View World rendering
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/kingdom/view_world.h
Labels: improvement, ui

#6609 Fix title in German translation
  files/lang/de.po
Labels: improvement, translation

#6615 Translation update workflow: hotfix for handling of partial msgfmt output
  .github/workflows/translation_update.yml
Labels: bug, script, GitHub Actions

#6611 SonarCloud: use newer syntax for the cfamily cache
  .github/workflows/sonarcloud.yml
Labels: improvement, script, GitHub Actions

#6610 Fix headers of PO files, fix typo in TRANSLATION.md
  docs/TRANSLATION.md
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/dk.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
Labels: improvement, translation

#6620 Add proper hotkeys option icon
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
Labels: improvement, ui, assets

#6582 Update Czech translation
  files/lang/cs.po
Labels: improvement, translation

#6627 Make ICNHeader::offsetX and ICNHeader::offsetY signed
  src/engine/agg_file.h
  src/fheroes2/agg/agg_image.cpp
  src/tools/icn2img.cpp
Labels: improvement

#6626 extractor tool: extract each AGG file to a separate subdir
  script/agg/extract_agg.bat
  script/agg/extract_agg.sh
  src/tools/extractor.cpp
Labels: bug

#6621 Add a tool to generate an image from a palette file
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  VisualStudio/tools/pal2img/common.props
  VisualStudio/tools/pal2img/sources.props
  src/tools/CMakeLists.txt
  src/tools/Makefile
  src/tools/README
  src/tools/pal2img-vs2017.vcxproj
  src/tools/pal2img-vs2019.vcxproj
  src/tools/pal2img.cpp
Labels: improvement, ui

#6514 Optimize mini-map rendering
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement, ui

#6639 Fix an invalid option for scenario 1 of Roland Campaign
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: bug, campaign

#6632 Run pal2img tool in extract_agg scripts, minor code cleanup
  script/agg/extract_agg.bat
  script/agg/extract_agg.sh
  script/android/install_packages.sh
  script/demo/download_demo_version.sh
  script/homm2/extract_homm2_resources.sh
  src/engine/image_tool.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
  src/tools/extractor.cpp
  src/tools/pal2img.cpp
Labels: improvement, script

#6590 feature: Add lighthouse information popup in kingdom overview
  src/fheroes2/gui/ui_kingdom.cpp
  src/fheroes2/gui/ui_kingdom.h
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/mp2.cpp
Labels: improvement, ui

#6636 Add an ability to load 8-bit images
  src/engine/image_tool.cpp
Labels: improvement, ui

#6653 Tune MSVC dependencies for xmi2midi tool
  VisualStudio/tools/xmi2midi/sources.props
Labels: improvement

#6652 Add sound related tools to tool package
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  script/agg/extract_agg.bat
  script/agg/extract_agg.sh
  src/tools/extractor.cpp
  src/tools/icn2img.cpp
Labels: improvement, audio

#6646 fix stereo audio playing in SMK files
  src/engine/smk_decoder.cpp
Labels: bug, audio

#6641 Fix musical effects for various objects, move auxiliary functions to the anonymous namespace
  src/fheroes2/agg/mus.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, audio

#6656 Fix issue with the puzzle rendering
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, ui

#6654 Fix Mini-map reset of enemy object colors after enemy vanquish
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#6662 extract_agg.sh: fix copy+paste typo in copyright header
  script/agg/extract_agg.sh
Labels: bug

#6625 Add a guide for graphical artists
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  README.md
  docs/GRAPHICAL_ASSETS.md
  docs/README.md
Labels: improvement, documentation

#6335 Update Russian translation (main menu and dialog buttons)
  files/lang/ru.po
Labels: improvement, translation

#6666 Fix volcano sounds
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/m82.h
  src/fheroes2/game/game.cpp
Labels: bug, audio

#6664 Fix remaining MSVC warnings
  VisualStudio/common.props
  src/CMakeLists.txt
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/thirdparty/libsmacker/smacker.c
  src/tools/82m2wav.cpp
  src/tools/bin2txt.cpp
  src/tools/xmi2midi.cpp
Labels: improvement

#6661 Fix a few code smells, remove unused code
  VisualStudio/fheroes2/sources.props
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_actions.cpp
  src/fheroes2/maps/maps_actions.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#6665 Fix line breaks in Graphical Artist Guide
  docs/GRAPHICAL_ASSETS.md
Labels: improvement, documentation

#6651 Bulgarian translation - last changes and some small fixes
  files/lang/bg.po
Labels: improvement, translation

#6605 Rewrite standard window generation code
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#6673 MSVC: enable link-time optimization in release mode
  VisualStudio/Release.props
Labels: improvement, Windows

#6672 Fix multiple issues in the Dialog::ArmyInfo()
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: bug, ui

#6669 Track the board status while caching the battle pathfinder graph
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
Labels: bug, logic

#6640 Memorize zoom level of the View World screen
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/kingdom/view_world.h
  src/fheroes2/system/settings.h
Labels: bug, ui

#6624 Fix View World default adventure map position
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement, ui

#6671 Puzzle map window is not centered on the screen
  src/fheroes2/kingdom/puzzle.cpp
Labels: bug, ui

#6674 Fix recently introduced code smells
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/ui_kingdom.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#6677 Fix the "unused variable" warning on builds where NDEBUG is defined
  src/fheroes2/gui/interface_radar.cpp
Labels: improvement

#6678 Fix the spell id calculation for a spell scroll
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, logic

#6682 Speed up the creation of a file list in Windows
  src/engine/dir.cpp
Labels: improvement, Windows

#6680 Avoid overflow on manipulations with number of monsters on tile, remove static_cast
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: improvement

#6688 Make tiles with allied heroes or castles inaccessible at the pathfinder level
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/payment.h
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#6660 Update Czech translation
  files/lang/cs.po
Labels: improvement, translation

#6684 Show kingdom income when gold per day income is clicked
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#6694 Fix adding an element of a vector to the same vector (golem animation frames copy issue)
  src/engine/screen.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui, regression

#6700 Render background between HEROES and TOWSN/CASTLES buttons in Kingdom Overview window
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui, regression

#6703 Properly restore the screen after closing the hero dialog during combat
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#6300 Do not copy images while rendering Adventure Map
  VisualStudio/fheroes2/sources.props
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/ui_object_rendering.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, ui

#6718 Battle pathfinder: auto-fix the cropped paths for AI-controlled wide units
  src/fheroes2/battle/battle_pathfinding.cpp
Labels: bug, logic, regression

#6722 Use an '^' operator for radar ROI with world intersection
  src/fheroes2/gui/interface_radar.cpp
Labels: bug, regression

#6713 Fix fog rendering horizontal offset. Adventure map.
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, ui

#6679 Add Graphics option icon and update Hotkeys icon
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/h2d/h2d_file.cpp
Labels: improvement, ui

#6704 Fix Right clicking on empty hero or castle shows Adventure Map inform…
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, ui

#6389 Rework AI hero task priority logic
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/mp2.cpp
Labels: bug, improvement, AI

#6731 Battle::Board::GetDistanceIndexes(): results should not include the center
  src/fheroes2/battle/battle_board.cpp
Labels: bug, logic, regression

#6723 CMake to copy executable to project root
  src/fheroes2/CMakeLists.txt
Labels: improvement, CMake

#6714 Display the world date for save files, refactor the game I/O a bit
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/highscores.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: improvement, ui

#6721 Fix musical effects for various objects, fix the Tree of Knowledge window
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, ui, audio

#6629 add a frame for a hero portrait on the quickinfo dialog
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui
