Repository ihhub/fheroes2, pull requests merged in 2023-10, with the labels that each got.

#7847 Reduce old Text class usage within the code
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/resource/resource.cpp
Labels: improvement, ui

#7839 Adjust AI combat spell heuristics
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: improvement, AI

#7851 Implement streams placing in Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, editor

#7845 Teach battle AI to use shield spells
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: improvement, AI

#7862 Add a mirror image check during spell evaluation
  src/fheroes2/ai/normal/ai_normal_spell.cpp
Labels: improvement, AI

#7861 Fix archer evaluation regression
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, AI

#7852 Add functionality to place monsters in the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: improvement, ui, editor

#7874 Remove hardcoded values for monster battle statuses
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement

#7846 AI should avoid splitting troops on easy difficulty
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: improvement, AI

#7856 Restrict heroes meetings and army merging on Easy difficulty
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: improvement, AI

#7887 Fix the correct default monster count in the Editor by default
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, logic, editor

#7888 Make Grass as a default terrain for new maps in the Editor
  src/fheroes2/editor/editor_interface_panel.h
Labels: improvement, ui, editor

#7886 Remember monster selection in the Editor
  src/fheroes2/editor/editor_interface_panel.cpp
Labels: logic, editor

#7866 Fix German translation No.1
  files/lang/de.po
Labels: improvement, translation

#7893 Disable Random Map option in the Editor
  src/fheroes2/editor/editor_mainmenu.cpp
Labels: improvement, ui, editor

#7838 Hungarian translation update part 04
  files/lang/hu.po
Labels: improvement, translation

#7863 Ukrainian_Translation_Update
  files/lang/uk.po
Labels: improvement, translation

#7867 Fix German translation No.2
  files/lang/de.po
Labels: improvement, translation

#7864 Completely remove old Text classes
  VisualStudio/fheroes2/sources.props
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/agg_image.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#7891 Add an ability to place Random Monsters in the Editor
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: improvement, logic, editor

#7897 Build the Editor for release but allow only with a specific config flag
  src/fheroes2/editor/editor.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, editor

#7892 Allow to open the Editor only if The PoL version is used
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, editor

#7903 Remove extra space in dialog phrases
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/dk.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sk.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  files/lang/vi.po
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/spell/spell_info.cpp
Labels: improvement, ui

#7901 Fix empty lines at the end of the luck/morale description
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
Labels: bug, ui, regression

#7899 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7896 Add an ability to place heroes in the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_base.cpp
  src/fheroes2/gui/interface_base.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/maps_tiles_render.h
Labels: improvement, editor

#7868 Fix German translation No.3
  files/lang/de.po
Labels: improvement, translation

#7912 Town Gate and Town Portal spells: use depersonalized wording
  src/fheroes2/heroes/heroes_base.cpp
Labels: improvement, ui

#7859 Combat victory window creature position
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_ui_helper.cpp
  src/fheroes2/army/army_ui_helper.h
Labels: improvement, ui

#7909 Rework Hot Keys dialog to support flexible size and Evil interface
  src/fheroes2/dialog/dialog_hotkeys.cpp
Labels: improvement, ui

#7748 Update Vietnamese Translation P5
  files/lang/vi.po
Labels: improvement, translation

#7918 Add "tent visited" info to barrier quick info dialog
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: improvement, ui

#7921 Use prefix decrement
  src/fheroes2/army/army_ui_helper.cpp
Labels: improvement

#7869 Fix German translation No.4
  files/lang/de.po
Labels: improvement, translation

#7916 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7923 Version 1.0.9
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#7890 Prioritize when hiring those heroes whose portraits are not used by customized heroes
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/skill.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#7928 Fix troops sprites overlap in quick info
  src/fheroes2/army/army_ui_helper.cpp
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui, regression, high priority

#7932 Show proper Quick Info window for a hero during battle, reorganize the functions related to the Quick Info display
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#7934 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#7940 Fix recruit dialog MIN/MAX button when switching creature upgrades
  src/fheroes2/dialog/dialog_recruit.cpp
Labels: bug, ui

#7931 Remove support for pre-1.0.5 save files
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#7902 Implement erase tool in Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, editor

#7870 Fix German translation No.5
  files/lang/de.po
Labels: improvement, translation

#7955 Update hashes for Android & Windows dependency packages
  android/build.gradle
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, high priority, Android

#7907 Standartise Maps::Tiles class members
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: improvement, editor

#7959 Fix summon boat spell assertion
  src/fheroes2/maps/maps_tiles.cpp
Labels: logic, crash, regression

#7871 Fix German translation No.6
  files/lang/de.po
Labels: improvement, translation

#7939 Teach AI to use the marketplace to accelerate the development of their castles
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/payment.h
  src/fheroes2/kingdom/profit.cpp
  src/fheroes2/kingdom/profit.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/resource/resource.h
Labels: improvement, AI

#7877 Home screen, Adjustement of window text on first game launch (#4789)
  src/fheroes2/game/game_mainmenu.cpp
Labels: improvement, ui

#7967 Fix the random generator usage by the non-Arena code
  src/engine/rand.cpp
  src/engine/rand.h
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle.cpp
Labels: bug, logic

#7974 Remove unused function
  src/engine/rand.h
Labels: improvement

#7978 Fix the impossibility of actions in hero's army after recruitment
  src/fheroes2/castle/castle_dialog.cpp
Labels: bug, regression

#7976 Display 0 shots during battle for archers
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, ui

#7980 Fix description text in Wizard's Isle 3rd scenario.
  src/fheroes2/campaign/campaign_data.cpp
Labels: bug, ui

#7979 Add hero action button image
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement, ui

#7963 AI-controlled battle: increase the priority of those enemy units that have not yet got their turn
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement, AI

#7983 Move the barrier color constants to the anonymous namespace and fix the patrol zone for imprisoned heroes
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
Labels: improvement

#7985 Eliminate redundant headers that were detected as required by IWYU with older compilers
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
Labels: bug

#7975 Fix the logic of purchasing a boat in shipyard
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#7872 Fix German translation No.7
  files/lang/de.po
Labels: improvement, translation

#7982 Remove special case for castle passability
  src/fheroes2/maps/mp2.cpp
Labels: improvement, logic

#7958 Add support for the future new heroes
  src/fheroes2/agg/icn.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_recruits.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic, editor

#7991 Clang-Tidy workflow: use head ref instead of the ref of virtual merge commit
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
Labels: improvement, GitHub Actions

#7984 Move scrollbar background and button rendering code to 'ui_window'
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
Labels: improvement, low priority

#7990 Fix several issues with loading ICN resources
  src/fheroes2/agg/agg_image.cpp
Labels: bug, ui

#7873 Fix German translation No.8
  files/lang/de.po
Labels: improvement, translation

#7920 Update Vietnamese Translation P6
  files/lang/vi.po
Labels: improvement, translation

#7986 Use the battle pathfinder's distance estimation when finding an optimal position for attack during the next turn
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
Labels: bug, AI

#7994 Simplify passability rules
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, logic
