Repository ihhub/fheroes2, pull requests merged in 2023-01, with the labels that each got.

#6440 fheroes2.rc: update the copyright year
  src/resources/fheroes2.rc
Labels: improvement

#6441 extract_homm2_resources.sh: detect multiple Python versions
  .github/workflows/translation_update.yml
  script/android/install_packages.sh
  script/demo/download_demo_version.sh
  script/homm2/extract_homm2_resources.sh
Labels: improvement, script

#6447 Reduce CPU usage in Select Language dialog
  src/fheroes2/dialog/dialog_language_selection.cpp
Labels: bug

#6439 Changelog in appdata.xml
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/tools/changelog_update_appdata.py
Labels: improvement, script

#6451 extract_homm2_resources.sh: add the innoextract support
  script/homm2/extract_homm2_resources.ps1
  script/homm2/extract_homm2_resources.sh
  script/homm2/extract_homm2_resources_for_app_bundle.sh
Labels: improvement, script, deployment

#6418 Improvements to the French translation
  files/lang/fr.po
Labels: improvement, translation

#6450 Streamlining MacOS installation instructions
  docs/INSTALL.md
Labels: improvement, macOS, documentation

#6421 Android: add the basic toolset activity with functionality that allows to unpack the files of the original game to the fheroes2 external data directory
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/fheroes2/GameActivity.java
  android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/app/src/main/res/layout/activity_toolset.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher_toolset.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_toolset.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_toolset.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_toolset.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_toolset.png
  android/app/src/main/res/values/strings.xml
  android/gradle.properties
  docs/README_android.md
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, Android

#6455 Set audio frequency to 44100 on Windows
  src/engine/audio.cpp
Labels: bug, Windows, audio

#6437 Prepare code for the future Editor
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#6432 Revert the unit counter display while Death Wave or Holy Shout spell effect animation. Battlefield.
  src/fheroes2/battle/battle_interface.cpp
Labels: ui, regression

#6411 Optimize multiple places for rendering
  src/engine/timing.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_logo.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/ui_tool.cpp
Labels: improvement, ui

#6457 Update PL translation - fix wrong brackets
  files/lang/pl.po
Labels: bug, translation

#6459 Exclude Java files from SonarCloud analysis
  sonar-project.properties
Labels: bug, GitHub Actions

#6446 Rework tile main object types
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/mus.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/objcrck.cpp
  src/fheroes2/objects/objdirt.cpp
  src/fheroes2/objects/objdsrt.cpp
  src/fheroes2/objects/objgras.cpp
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/objects/objsnow.cpp
  src/fheroes2/objects/objswmp.cpp
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/objects/objwatr.cpp
  src/fheroes2/objects/objxloc.cpp
  src/fheroes2/objects/trees.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement, logic

#6467 Battle::Interface::GetBattleCursor(): add the extra assertion
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement

#6452 Optimize Holy Shout spell effect rendering. Battlefield.
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#6414 Fix creature wince animation for low morale and lich cloud cases. Battlefield.
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#6472 Fix the bridge operation when a wide friendly unit steps on it from the moat
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_bridge.h
Labels: bug, logic

#6398 Modification of walking units movement animation algorithm. Battlefield.
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
Labels: improvement, ui

#6473 Removed redundant redraws when dragging an adventure map with the mouse
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
Labels: improvement, ui

#6461 Finalize object tile types
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#6469 Fix few PL translations
  files/lang/pl.po
Labels: bug, improvement, translation

#6458 Android Toolset Translation (German)
  android/app/src/main/res/values-de/strings.xml
Labels: improvement, translation, Android

#6483 Fix an infinite loop in the RedrawActionWincesKills() on Lich attack
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui, regression

#6479 Rework the battle pathfinding
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.h
Labels: improvement, logic

#6496 Fix the Dimension Door shadow on resolutions 640+x480 & 640x480+, temporarily hide auxiliary panels in "no interface" mode
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: bug, improvement, ui

#6500 Code cleanup for terrain tile types
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/mp2_helper.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: improvement, logic

#6501 Remove unused methods
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: improvement

#6494 Fix the AI resurrect spell logic
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_grave.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, AI

#6503 SonarCloud: use the compile_commands.json instead of build wrapper
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: improvement, GitHub Actions

#6442 Render spell effect animation so as not to cover the front troops. Battlefield.
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#6506 Remove 0.9.21 save format support
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: improvement

#6507 Add checks to identify MX2 being loaded as MP2
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#6512 [Fix] Appdata: correct & extend donation link
  script/packaging/common/fheroes2.appdata.xml
Labels: bug, deployment

#6510 BattlePathfinder::evaluateForUnit(): minor polishing
  src/fheroes2/battle/battle_pathfinding.cpp
Labels: improvement

#6509 Do not allow to dig for Ultimate Artifact second time
  src/fheroes2/gui/interface_events.cpp
Labels: bug, logic

#6521 Uncover the fog during the hero's instantaneous movement only if the hero is actually moving
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, logic

#6519 Update spell points for campaign heroes at the start of a scenario
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, logic, campaign

#6508 Fix loss of the first frame in the after attack unit animation. Battlefield.
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#6502 Rework the way how object ICN types are used
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#6529 Rebuild the battle pathfinding cache dynamically if necessary
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/maps/maps.h
Labels: improvement, logic

#6520 Do not allow to load saves from a PoL map if PoL expansion isn't present
  src/fheroes2/game/game_io.cpp
Labels: improvement, logic

#6511 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#6536 Reduce dependencies from old Text class
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/resource/artifact.cpp
Labels: improvement, ui

#6491 Fix shooters projectile position. Battlefield.
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#6237 Add a danish translation
  files/lang/Makefile
  files/lang/dk.po
Labels: improvement, translation

#6478 PS Vita fixes and gamepad mapping improvements
  docs/README_PSV.md
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/screen.cpp
Labels: bug, improvement

#6540 Fix Druid projectile start position for shooting up (Battlefield)
  src/fheroes2/agg/bin_info.cpp
Labels: improvement, ui

#6504 Make a narrower button font for cp-1251 (Cyrillic) characters
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui
