Repository ihhub/fheroes2, pull requests merged in 2023-11, with the labels that each got.

#8004 Minor code clean in 'maps_tiles'
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
Labels: improvement, low priority

#7929 Hungarian language update 05
  files/lang/hu.po
Labels: improvement, translation

#7997 Update Vietnamese Translation P7
  files/lang/vi.po
Labels: improvement, translation

#7999 AI: take into account the spell immunity when calculating the effectiveness of mass damage spells
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, AI

#8002 Rename .appdata.xml file to .metainfo.xml and add <launchable/> tag
  CMakeLists.txt
  script/packaging/common/fheroes2.metainfo.xml
  script/packaging/debian/copyright
  script/tools/changelog_update_appdata.py
  script/tools/changelog_update_metainfo.py
Labels: improvement, deployment

#8010 Add support for right SHIFT, CTRL and ALT hot keys
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/game/game_hotkeys.cpp
Labels: improvement, logic

#8003 Remove the END_TURN battle command, improve command argument checks, fix a few issues found thanks to improved checks
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, logic

#8017 Speed up monochrome cursors loading
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, logic

#8000 Fix items list update after deleting an item: fix dismissing a hero from the Kingdom Overview dialog
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#8006 Rework the Thieves Guild (Oracle) dialog code and minor fixes to Hero dialog rendering
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, improvement, ui

#8018 Reset hero path after digging and update hero buttons
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#8020 Fix a few recently introduced code smells
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/resource/artifact_info.h
Labels: improvement

#8016 Add treasure placement in the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/mp2.cpp
Labels: improvement, editor

#8024 Make Oracle dialog use selected interface mode (Good/Evil)
  src/fheroes2/dialog/dialog_thievesguild.cpp
Labels: improvement, ui

#7969 Implement artifacts placing in Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/artifact_info.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, editor

#8022 Town Portal dialog: use the same dialog code as for the select dialogs in Battle Only mode (dialog_selectitems).
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, ui

#8033 Fix dialog borders generation regression for StandardWindow()
  src/fheroes2/gui/ui_window.cpp
Labels: ui, regression

#7948 Small swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#8032 Focus on the hero when he starts to move by the Move button press
  src/fheroes2/game/game_interface.h
  src/fheroes2/gui/interface_events.cpp
Labels: ui, regression

#8035 Swedish translation update (#8)
  files/lang/sv.po
Labels: improvement, translation

#8038 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#8023 Hungarian language update #06
  files/lang/hu.po
Labels: improvement, translation

#8040 Shipyard: Treat water with an object's shadow as water free of objects
  src/fheroes2/castle/castle.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic, regression, high priority

#8048 Version 1.0.10
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#8019 Add ability to place Ocean Objects within the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/gui/ui_map_object.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/mp2.h
Labels: improvement, editor

#8052 Make the touch device ID part of the finger ID
  src/engine/localevent.cpp
  src/engine/localevent.h
Labels: improvement

#8036 Properly evaluate potential attack positions for wide units
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
Labels: bug, AI

#8059 Enable Dependabot for actions from the GitHub Marketplace
  .github/dependabot.yml
Labels: improvement, GitHub Actions

#8066 Group objects for the Editor into logical buckets
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: improvement, editor

#8074 Fix multi-font text offset calculation
  src/fheroes2/gui/ui_text.cpp
Labels: bug, ui, crash

#8076 Allow application closure by close button if no resources available
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, ui

#8075 Speed up map loading for New Game
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement

#8080 Add cell selection in Details mode for the Editor
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
Labels: improvement, editor

#8082 Update hashes for Android & Windows dependency packages
  android/app/build.gradle
  android/build.gradle
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, high priority, Android

#8077 Rework Battle Only mode
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_only.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, ui, logic

#8071 fix scroll location on file deletion
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: bug, ui

#8079 Add Hotkeys categories for the future UI improvements
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement, ui

#8084 Add base map file format
  VisualStudio/fheroes2/sources.props
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, editor

#8011 Update Vietnamese Translation P8
  files/lang/vi.po
Labels: improvement, translation

#8060 Swedish translation update (#9)
  files/lang/sv.po
Labels: improvement, translation
