Repository ihhub/fheroes2, pull requests merged in 2023-09, with the labels that each got.

#7671 Do not show second brackets when hero can learn secondary skill from witch hut
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui, regression

#7669 File options menu disappears on cancelling load game dialog
  src/fheroes2/dialog/dialog_file.cpp
Labels: improvement, ui

#7516 Add Czech to original resource exceptions
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#7672 Update Danish Translation (88% / 312)
  files/lang/dk.po
Labels: improvement, translation

#7674 Update Swedish Translation
  files/lang/sv.po
Labels: improvement, translation

#7645 Update the Hungarian translation
  files/lang/hu.po
Labels: improvement, translation

#7677 Fix SonarQube bugs and blocker issues
  src/engine/screen.h
  src/engine/translations.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
Labels: regression

#7676 Change Army Order to Turn Order
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#7679 Remove extra checks while setting cursor type
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: improvement

#7681 Fix some SonarQube smells
  src/fheroes2/dialog/dialog_artifact.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: improvement

#7684 Fix several code smells
  src/engine/core.cpp
  src/engine/localevent.h
  src/fheroes2/castle/castle.h
Labels: improvement

#7662 Rework the Save/Load game dialog to allow variable dialog size and support Evil interface
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_scrollbar.cpp
Labels: improvement, ui, high priority

#7596 Implement terrain transitions in Editor.
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
Labels: improvement, high priority, editor

#7678 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7683 Update Danish Translation (93% / 181)
  files/lang/dk.po
Labels: improvement, translation

#7686 Swedish Translation Update
  files/lang/sv.po
Labels: improvement, translation

#7582 Make vertical buttons translatable
  files/lang/nb.po
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_font.h
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui, translation

#7673 Ukrainian upd 31.08.23
  files/lang/uk.po
Labels: improvement, translation

#7691 Update Swedish Translation (small fixes)
  files/lang/sv.po
Labels: improvement, translation

#7698 Translate disabled buttons and reset them when changing languages
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
Labels: improvement, ui, translation

#7703 Bump actions/checkout to v4
  .github/workflows/android.yml
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
  .github/workflows/cmake.yml
  .github/workflows/code_style_check.yml
  .github/workflows/iwyu.yml
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/translation_update.yml
Labels: bug, GitHub Actions

#7700 Fix regressions after #7662: cursor position setting in text input field and display restoration after closing the virtual keyboard
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: bug, regression

#7699 Swedish Translation Update
  files/lang/sv.po
Labels: improvement, translation

#7688 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7705 Fix empty space between diagonal lines in button font.
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui

#7715 Adjust the description of the Eagle Eye skill
  src/fheroes2/heroes/skill.cpp
Labels: improvement, ui

#7707 Ukrainian_Upd_05.09.23_base
  files/lang/uk.po
Labels: improvement, translation

#7710 Slovak translation
  files/lang/sk.po
Labels: improvement, translation

#7701 Hungarian Translation 02. part
  files/lang/hu.po
Labels: improvement, translation

#7695 Update Vietnamese Translation P4
  files/lang/vi.po
Labels: improvement, translation

#7690 Improve the logic of kiting enemies with archers
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
Labels: improvement, AI, high priority

#7711 Show highscores after multiplayer game
  src/fheroes2/game/game_over.cpp
Labels: bug, ui, regression, high priority

#7722 Fix some recently introduced code smells
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: improvement

#7725 Optimize `getAroundIndexes()` function
  src/fheroes2/maps/maps.cpp
Labels: improvement, logic

#7720 Show only skills that the hero doesn't already have in battle only skill selection list;
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/gui/skill_bar.cpp
Labels: bug, ui

#7727 Display missing resource dialog not less than 5 seconds
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, ui

#7731 Bump the timeout for SonarCloud Analyzer workflow to 60 minutes
  .github/workflows/sonarcloud.yml
Labels: improvement, GitHub Actions

#7714 Generate vertical high scores buttons
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui, translation

#7724 Fix ? symbols appearing in single-line texts
  src/fheroes2/gui/ui_text.cpp
Labels: bug, ui

#7726 Fix spell rendering issues when words are divided in the middle
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#7734 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7712 Update danish translation (97% / 71)
  files/lang/dk.po
Labels: improvement, translation

#7713 Fix number placeholders not being replaced in campaign spell bonus texts
  src/fheroes2/gui/ui_campaign.cpp
Labels: bug, ui

#7736 Version 1.0.8
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#7741 Wand of Negation should grant immunity against the Mass Dispel spell
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/resource/artifact_info.cpp
Labels: bug, logic

#7745 ActionToStables(): remove redundant check
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#7747 Update Windows & Android dependencies
  android/app/build.gradle
  android/build.gradle
  android/isotools/build.gradle
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, high priority, Android

#7739 Improve path calculations by AIWorldPathfinder in planning mode
  VisualStudio/fheroes2/sources.props
  src/engine/pathfinding.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/route.cpp
  src/fheroes2/heroes/route.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, AI

#7717 Berserker spell: always use the nearest cell to attack the nearby unit
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
Labels: bug, logic

#7752 Use Home and End hotkeys to navigate among items within a list
  src/fheroes2/gui/interface_list.h
Labels: improvement, ui

#7742 Update danish translation (100%)
  files/lang/dk.po
Labels: improvement, translation

#7744 Czech and Slovak translation updates
  files/lang/cs.po
  files/lang/sk.po
Labels: improvement, translation

#7750 Bulgarian Translation Update
  files/lang/bg.po
Labels: improvement, translation

#7753 Remove old Dialog::Message usage from the code
  VisualStudio/fheroes2/sources.props
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_message.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: bug, ui

#7755 Remove double spaces in translatable texts
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/resource/artifact_info.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/world/world.cpp
Labels: improvement, translation

#7761 Remove unused texts from translations
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/dk.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/it.po
  files/lang/nb.po
  files/lang/pl.po
  files/lang/ru.po
  files/lang/sk.po
  files/lang/sv.po
  files/lang/vi.po
Labels: translation

#7762 Code cleanup for Maps::Tiles
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#7763 Hero related code cleanup
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: improvement

#7735 Do not force display render for software cursor restorer: fix render of incorrect frames after closing game dialogs with software cursor enabled
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: bug, ui

#7758 Swedish Translation Update
  files/lang/sv.po
Labels: improvement, translation

#7776 Fix Editor Main Menu hotkeys
  src/fheroes2/editor/editor_mainmenu.cpp
Labels: bug, ui, editor

#7760 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7766 Improve AI behavior for Ghosts during battle
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, AI

#7785 Revert Ghost estimation for the AI
  src/fheroes2/battle/battle_troop.cpp
Labels: AI, regression

#7767 Add the ability to confirm actions in battle for touch devices
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#7779 Add historical changes support for the Editor
  VisualStudio/fheroes2/sources.props
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/editor/history_manager.cpp
  src/fheroes2/editor/history_manager.h
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, improvement, editor

#7787 Describe the mechanics of confirming combat actions on touch devices
  docs/README_android.md
Labels: improvement, documentation

#7788 Fix the logic of MonsterAbilityType::ALWAYS_RETALIATE in regard to paralyzed units
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: bug, logic

#7796 Clean up the code for Maps::Tiles
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/mp2_helper.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: improvement, logic

#7811 Update followers window to support text mode
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, ui

#7810 Prepare the code for the future cursor updates within the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_base.h
  src/fheroes2/gui/interface_gamearea.cpp
Labels: improvement, editor

#7809 Adjusted the position of luck and morale icons
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, ui

#7815 Fix memorizing the position in the map list when changing the map size filter
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: bug, ui, regression

#7813 Properly display player name in the New Game window
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
Labels: improvement, ui

#7817 Fix battle AI protecting paralyzed archers
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement, AI

#7721 Hungarian translation update part 03
  files/lang/hu.po
Labels: improvement, translation

#7771 Slovak and Czech translation update
  files/lang/cs.po
  files/lang/sk.po
Labels: improvement, translation

#7770 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#7827 Fix the AI first strike logic
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, improvement, AI

#7772 Implement roads placing in map editor.
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, editor

#7746 Ukrainian_Translate_08.09.23_base
  files/lang/uk.po
Labels: improvement, translation

#7819 Another Maps::Tiles code cleanup as preparations for the Editor
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/world/world.cpp
Labels: improvement
