Repository ihhub/fheroes2, pull requests merged in 2023-06, with the labels that each got.

#7260 Reduce unit growth bonus for AI
  src/fheroes2/game/difficulty.cpp
Labels: improvement, AI

#7254 Fix missing logic for AI heroes to meet each other in the middle of a turn
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/world/world.cpp
Labels: bug, AI

#7261 Fix AI heroes behavior ignoring empty castles with commanders
  src/fheroes2/army/army.cpp
Labels: bug, AI

#7259 Do not recalculate the hero path on focus change if player is controlled by AI
  src/fheroes2/gui/interface_focus.cpp
Labels: bug, logic

#7258 Do not check whether a hero can cast a spell if spellcasting is prohibited in principle
  src/fheroes2/army/army.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/system/players.cpp
Labels: bug, logic

#7256 Fix extra fade when switching heroes by interface buttons, fix hero dismiss UI bugs
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, ui, regression

#7263 Fix monster upgrade logic when AI was wasting resources for nothing
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
Labels: bug, logic, AI

#7267 Fix a few recently introduced code smells detected by SonarCloud
  src/engine/tools.cpp
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement

#7265 Move jobless AI heroes into castles on a last day of a week
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#7251 Make the text input cursor blink and add the ability to set the cursor position anywhere in the edited string
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#7273 Fix assertion in the Interface::Basic::SetFocus( Castle * )
  src/fheroes2/gui/interface_focus.cpp
Labels: bug, logic

#7278 Improve army distribution in castles for AI players
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
Labels: improvement, AI

#7280 Fix okay button not being redrawn in battle options dialog
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#7262 Add shadows for the Virtual Keyboard buttons
  src/engine/image.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui

#7232 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#7277 Campaign scenario UI: show the currently selected bonus if the campaign scenario is already in progress
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: bug, ui, campaign

#7249 Update danish translation - 1.0.5
  files/lang/dk.po
Labels: improvement, translation

#7286 Fix rating in campaign congratulations text in win video
  src/fheroes2/game/game_campaign.cpp
Labels: bug, ui

#7279 Improve AI heroes interaction with castles and heroes in dangerous areas
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.h
Labels: improvement, AI

#7284 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#7294 Bulgarian Translation Update
  files/lang/bg.po
Labels: improvement, translation

#7301 Fix invalid AI castle reinforcement issue
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: bug, AI, regression

#7299 Explicitly call static function 'GetStrength()' to resolve the ambiguity between 'Army::GetStrength()' and 'Troops::GetStrength()'
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: bug, AI

#7221 Update the translation documentation
  docs/TRANSLATION.md
Labels: improvement, translation, documentation

#7293 Version 1.0.5
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#7306 extract_homm2_resources.ps1: add support for the Ubisoft digital HoMM2 version
  script/homm2/extract_homm2_resources.ps1
Labels: improvement, Windows, script

#7300 Fixes to button text placements and smaller fixes
  src/fheroes2/agg/agg_image.cpp
Labels: bug, ui, pixel-precision

#7020 6952: Improve Summon Boat spell grayed out messages
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/spell/spell_info.h
Labels: improvement, ui

#7315 Fix various recently appeared code smells detected by SonarCloud
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/gui/text.cpp
  src/fheroes2/gui/text.h
  src/fheroes2/spell/spell_info.cpp
Labels: improvement

#7308 Android: put the AAB file to a separate ZIP archive
  .github/workflows/android.yml
Labels: improvement, deployment, GitHub Actions, Android

#7313 Rework game credits to keep aspect ratio
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_credits.h
Labels: improvement, ui

#7334 Fix display of false symbols afer the blinking cursor
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: ui, regression

#7333 Properly restore environment sounds and terrain music after opening a castle dialog from the Kingdom Overview screen
  src/fheroes2/game/game_startgame.cpp
Labels: bug, audio, regression

#7331 h2dmgr: extract images as BMP/PNG files, fix color format of images loaded from BMP/PNG files (SDL2 only)
  src/engine/image_tool.cpp
  src/tools/h2dmgr.cpp
  src/tools/pal2img.cpp
Labels: improvement, tools

#7337 Fix the fade effect on the "View World" screen
  src/fheroes2/kingdom/view_world.cpp
Labels: bug, ui, regression

#7339 Do Main Menu fade-in before showing first game run messages, not after
  src/fheroes2/game/game_mainmenu.cpp
Labels: bug, ui, regression

#7342 Add instructions for installing Gentoo packages
  docs/INSTALL.md
Labels: improvement, documentation

#7348 Reduce the number of calls to get a singleton instance
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement

#7351 Fix Abandoned Mine right sprite update
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, ui

#7347 Make an AI hero to stop moving when a new action object is discovered
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world.cpp
Labels: improvement, AI

#7191 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation
