Repository ihhub/fheroes2, pull requests merged in 2023-05, with the labels that each got.

#7068 Fix calculation of castle towers strength for AI
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, AI

#7054 Adust spell info message when hero has zero (0) mana
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/spell/spell_book.cpp
Labels: improvement, ui

#7080 Fix adventure map fog reveal on campaign scenario restart and when loading a Hot Seat save made in the first game day.
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/system/settings.h
Labels: bug, ui, regression

#7104 Add instructions for building the fheroes2 project for Android to DEVELOPMENT.md
  docs/DEVELOPMENT.md
Labels: improvement, documentation

#7084 Standartize metadata for all objects on Adventure Map
  src/engine/serialize.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, improvement, logic, high priority, editor

#7111 Fix loading campaign save made at the end of scenario
  src/fheroes2/system/players.cpp
Labels: bug, regression

#7109 Fix not returning to load menu while switching between campaign scenarios
  src/fheroes2/game/game_mainmenu.cpp
Labels: ui, logic

#7119 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#7120 Fill main menu with background when we do not stretch the main menu main image
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_mainmenu_ui.cpp
  src/fheroes2/game/game_mainmenu_ui.h
  src/fheroes2/game/game_newgame.cpp
Labels: improvement, ui, high priority

#7113 Remove duplicate line in translations.cpp
  src/engine/translations.cpp
Labels: improvement

#7130 Add popup windows for monster dialog buttons
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement

#7061 Fix Battlefield animations freeze while waiting for Good Luck sound to end
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#7123 Move Tiles rendering code to a separate place
  VisualStudio/fheroes2/sources.props
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/maps_tiles_render.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui

#7056 Do not make an empty text line at the end of phrase and fix text rendering in a wider area than given maximum width.
  src/fheroes2/gui/ui_text.cpp
Labels: bug, ui

#6911 Create small and large obstacles on the battlefield at the same time.
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: bug, logic

#7121 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#7096 Czech translation update
  files/lang/cs.po
Labels: improvement, translation

#7131 Fix missing metadata conversion from old saves when a hero stands on an object
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: bug, regression

#7137 Fix typo in Russian translation
  files/lang/ru.po
Labels: regression, translation

#7136 Android: limit visibility of inner class members
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
Labels: improvement, Android

#7086 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7097 Update danish translation
  files/lang/dk.po
Labels: improvement, translation

#7067 Add the ability to cancel waiting for the end of the pre-battle sound
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, logic

#7088 Update Vietnamese Translation - Part 3
  files/lang/vi.po
Labels: improvement, translation

#7112 Fix logic & reward of Daemon Cave object for AI, improve the resource value estimation algorithm for AI
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/resource/resource.h
Labels: improvement, AI

#7110 Avoid pirated translation which are applied on English version of the game
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, logic

#7143 Fix an issue that caused an AI-controlled hero standing next to Stone Liths to block the path of another AI-controlled hero standing on these Stone Liths
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, AI

#7147 Fix creature idle animation freeze during Blind / Paralyze spell. Battlefield.
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#7149 Fix idle animation lag while casting a spell on the Battlefield
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#7108 Do not stop hero's movement after the first Dimension Door jump
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#7151 Fix absence of delay after creature wincing animation. Battlefield.
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#7156 Extra virtual keyboard language support for Russian
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui, translation

#7165 Remove unused translation texts
  files/lang/bg.po
  files/lang/de.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/nb.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ru.po
  files/lang/sv.po
Labels: improvement, translation

#7166 Add Polish to Virtual Keyboard
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui, high priority, translation

#7158 Version 1.0.4
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#7170 Fix incorrect changelog date
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
Labels: bug, documentation

#7169 Fix infinite loop while using Dimension Door spell by AI hero
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, AI, crash

#7171 Bump Android version
  version_code.txt
Labels: bug, Android

#7160 Android Toolset: minor cleanup
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
Labels: improvement, Android

#7053 Do not reset castle or heroes scrollbars when hero moves
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#7179 Fix some recently introduced code smells
  src/fheroes2/kingdom/kingdom.h
Labels: improvement

#7185 Update Windows dependencies
  script/windows/install_packages.bat
Labels: improvement, Windows

#7175 Fix java.nio desugaring on Android 7 and below
  android/app/build.gradle
  android/build.gradle
Labels: bug, Android

#7049 Update Ukrainian translation
  files/lang/uk.po
Labels: improvement, translation

#7145 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7173 Add diacritic signs to CP-1250 button font
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui

#7184 Update CP1250 font support - Slovak characters
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui

#7200 Fix some critical issues detected by SonarQube
  src/engine/agg_file.h
  src/engine/serialize.cpp
Labels: improvement

#7196 Utilize zlib optimized impl of CRC32 checksum algorithm instead of reinventing the wheel.
  src/engine/tools.cpp
Labels: improvement

#7202 Use 22050 sound sample rate for PS Vita to fix high CPU load
  src/engine/audio.cpp
Labels: regression

#7212 Fix cases when AI ignores some objects during path evaluation
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#7216 Use an older version of the Android Gradle Plugin
  android/app/build.gradle
  android/build.gradle
Labels: bug, Android

#7126 Restructure the code to allow adding new artifacts
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/artifact_info.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#7154 Remove obsolete parameter of Heroes::Action()
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, logic

#7183 MusicalEffectPlayer: do not change music volume if there is no music file for the corresponding effect, reduce I/O when searching for music files
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, audio

#7209 Fix some Clang-Tidy issues and code style improvements (battle_interface.cpp)
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, low priority

#7223 Use try_emplace() from C++17 instead of emplace()
  src/fheroes2/audio/audio_manager.cpp
Labels: improvement

#7215 Resurrection spells are not a subset of restoration spells
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/spell/spell.cpp
Labels: bug, ui, logic

#7208 Optimize CPU load while Battlefield rendering
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#7206 Translation ru: Correct the translation of `halfling` as `полурослик`, not `hobbit` (`хоббит`).
  files/lang/ru.po
Labels: improvement, translation

#7225 Fix the rendering of the number of units during the castle siege
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui, regression

#7062 Add screen fade effect when changing display image
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_mainmenu_ui.cpp
  src/fheroes2/game/game_mainmenu_ui.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#7201 Update of Bulgarian translation
  files/lang/bg.po
Labels: improvement, translation

#7192 Add button shadow generation, rework Recruit dialog, add Evil interface to Recruit dialog.
  src/engine/image.cpp
  src/engine/image.h
  src/engine/pal.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#7228 Always recalculate the hero's path when setting the focus on this hero, if the hero is not moving at the moment
  src/engine/pathfinding.h
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
Labels: bug, logic

#7220 Fix the logic of recognizing objects guarded by neighboring monsters
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/mp2.cpp
Labels: bug, ui, logic

#7239 Fix logic for defeated heroes in campaign scenarios
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic, campaign

#7235 Do not use fade effect when switching campaign scenario
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/interface_events.cpp
Labels: bug, ui

#7250 Add zlib1.dll to the tools package on Windows
  .github/workflows/msvc.yml
Labels: bug, deployment

#7237 Fix not rendering big objects on the Battlefield
  src/fheroes2/battle/battle_interface.cpp
Labels: ui, regression

#7243 Fix the Skeleton passability
  src/fheroes2/maps/mp2.cpp
Labels: bug, logic

#7246 Fix AI capturing a dwelling protected by monsters
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: bug, logic

#7247 Remove extra fade-in and redundant Castle row 'Init()' in Kingdom Overview
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui, regression

#7248 Do not play same kill/wince sounds simultaneously
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, audio
