Repository ihhub/fheroes2, pull requests merged in 2023-04, with the labels that each got.

#6919 Make hotkey names translatable
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement, ui, translation

#6918 Show mirrored monster image in army order
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#6916 Added missing gold in Dungeon description
  src/fheroes2/castle/castle_building_info.cpp
Labels: improvement, ui

#6930 Remove path icon after a hero/boat makes a turn, not before
  src/fheroes2/gui/interface_gamearea.cpp
Labels: improvement, ui

#6821 Add Vietnamese translation
  files/lang/vi.po
Labels: improvement, translation

#6935 Cleanup MP2 object loading code
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#6934 Consider object type while calculating object value over distances for AI heroes
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#6927 Reduce AI obsession with Wells
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: improvement, AI

#6933 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#6931 Fix projectile render position when hitting the target creature. Battlefiled.
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#6940 Cleanup MP2 format and Maps::Tiles class
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement, logic

#6929 Czech translation update
  files/lang/cs.po
Labels: improvement, translation

#6854 Adjusted number of resources subtracted in event messages.
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: bug, ui

#6882 Update Slovak translation
  files/lang/sk.po
Labels: improvement, translation

#6949 Show approximate information about the mine guardians to a non-owner player
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#6909 Added count to Morale and Luck artifacts desc.
  src/fheroes2/resource/artifact_info.cpp
Labels: improvement, ui

#6881 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#6943 Add Virtual Keyboard open button to Save Game and Player Name dialogs
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui

#6966 Do not allow to access overprotected tiles using the Dimension Door spell
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, AI

#6948 Add more translatable buttons
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui, translation

#6946 Improve the destination indication for Teleport spell
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement, ui

#6861 Hero info window frame is missing when checking through hero meeting window
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: bug, ui

#6954 Update Russian translation
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/dk.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sk.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  files/lang/vi.po
  src/fheroes2/resource/artifact_info.cpp
Labels: improvement, translation

#6976 Android: remove non-translatable string from Polish localization
  android/app/src/main/res/values-pl/strings.xml
Labels: translation, Android

#6975 Android: build AAB in addition to APK
  .github/workflows/android.yml
Labels: improvement, deployment, GitHub Actions, Android

#6980 Fix the "unused variable" warning on release builds
  src/engine/audio.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#6979 Norwegian translation update
  files/lang/nb.po
Labels: improvement, translation

#6977 Update German Translation
  files/lang/de.po
Labels: improvement, translation

#6391 Add missing generated small buttons and adjust some others
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: improvement, ui

#6973 Add a document for privacy policy for the project
  docs/PRIVACY_POLICY.md
Labels: documentation, Android

#6978 Flatpak Appdata update
  script/packaging/common/fheroes2.appdata.xml
Labels: documentation

#6955 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#6972 Version 1.0.3
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#6959 Expand AI control debugging functionalities
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: bug, AI

#6982 Add "New week!" title to dialog showing start of a new week
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, ui

#6997 Do not render hero/boat over the bottom map border. Adventure map.
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, ui, regression

#7003 Add Google Play link to the INSTALL.md
  docs/INSTALL.md
Labels: improvement, documentation

#7004 Redraw the status window after the amount of kingdom resources has changed at the beginning of the day, fix recurring events
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/world/world.cpp
Labels: bug, ui

#7001 Update ukrainian translation
  files/lang/uk.po
Labels: improvement, translation

#6993 Update Slovak translation
  files/lang/sk.po
Labels: improvement, translation

#7010 Czech translation update
  files/lang/cs.po
Labels: improvement, translation

#7006 Fix a crash on deleting last save file
  src/fheroes2/dialog/dialog_selectfile.cpp
Labels: bug

#7019 Reset battlefield grid cursor position after using the Spell Book
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic

#6985 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#6990 Move all quantity related auxiliary functions out of Maps::Tiles class
  VisualStudio/fheroes2/sources.props
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#6868 Update the Danish translation
  files/lang/dk.po
Labels: improvement, translation

#7015 Modernize the Android Toolset
  .github/workflows/android.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/app/src/main/res/values-de/strings.xml
  android/app/src/main/res/values-pl/strings.xml
  android/app/src/main/res/values-ru/strings.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
Labels: improvement, Android

#6992 extract_homm2_resources.ps1: properly handle absolute and relative paths in the CDDrive registry key
  script/homm2/extract_homm2_resources.ps1
Labels: bug, script, deployment

#7022 Expand wide screen support
  src/engine/screen.cpp
  src/engine/screen.h
  src/engine/tinyconfig.cpp
  src/engine/tinyconfig.h
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement, ui

#7033 Add language support for highscores
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/highscores.cpp
  src/fheroes2/game/highscores.h
Labels: improvement, ui

#7041 Update hashes for Windows and Android pre-built library packages
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#7040 Fix the behavior of Berserk and Hypnotize spells
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#7007 Update the Vietnamese translation
  files/lang/vi.po
Labels: improvement, translation

#7047 Catapult and castle towers should still act, even if there are no troops in the respective armies capable of taking any action
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, logic

#7026 Add "End Turn" title to dialog when heroes can move and you are ending your turn
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#7052 Add extra checks to prevent loading renamed MX2 maps on demo version
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#7029 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7025 Show map ratings in victory video, add subtitles, add color fade
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/dk.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sk.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  files/lang/vi.po
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_over.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui, video

#7051 Rework the search algorithm for available scaled resolutions
  src/engine/screen.cpp
Labels: improvement, ui

#7023 Update swedish translation
  files/lang/sv.po
Labels: improvement, translation

#7060 Handle events during fade animations, sync rendering by "CustomAnimationDelay"
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#7065 AI should check for castles and funds before retreat
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: improvement, AI

#6756 Strategic AI economy update
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: improvement, AI

#7055 Android Toolset: implement animation extraction from HOMM2.GOG
  .clang-format
  .github/workflows/android.yml
  android/app/build.gradle
  android/app/src/main/java/org/fheroes2/GameActivity.java
  android/app/src/main/java/org/fheroes2/HoMM2AssetManagement.java
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/isotools/LICENSE
  android/isotools/build.gradle
  android/isotools/src/main/AndroidManifest.xml
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/api/FileEntry.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/api/FileSystem.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/api/LoopFileSystemException.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Constants.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/EntryInputStream.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/EntryIterator.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Iso9660FileEntry.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Iso9660FileSystem.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Iso9660VolumeDescriptorSet.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/Util.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/AbstractBlockFileSystem.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/AbstractFileSystem.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/SeekableInput.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/SeekableInputFile.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/VolumeDescriptorSet.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/util/LittleEndian.java
  android/settings.gradle
Labels: improvement, Android

#7057 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7030 Czech translation update
  files/lang/cs.po
Labels: improvement, translation

#7075 Fix/suppress some of recently introduced code smells
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/EntryInputStream.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/iso9660/EntryIterator.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/spi/AbstractBlockFileSystem.java
  android/isotools/src/main/java/com/github/stephenc/javaisotools/loopfs/util/LittleEndian.java
Labels: improvement

#7076 Add Vietnamese percentage icon to translation guide
  docs/TRANSLATION.md
Labels: improvement, translation, documentation

#7077 Slovak translation update
  files/lang/sk.po
Labels: improvement, translation

#7079 Print more detailed information about the hero patrol settings in debug mode
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement

#7066 Bulgarian translation Update
  files/lang/bg.po
Labels: improvement, translation

#7024 Improve dialog titles related to losing the game
  src/fheroes2/game/game.h
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, ui

#7050 Slovak translation string pointing change
  src/engine/translations.cpp
Labels: bug, translation

#7044 Update Vietnamese Translation.
  files/lang/vi.po
Labels: improvement, translation
