Repository ihhub/fheroes2, pull requests merged in 2023-03, with the labels that each got.

#6738 Remove unused functions
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: improvement

#6739 Tree of Knowledge: fix the experience calculation for AI-controlled heroes
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes.cpp
Labels: bug, AI

#6736 Reset the world pathfinder(s) on fog reveal operations
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, logic

#6743 Fix battle AI tactics estimation
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: bug, AI

#6749 Cleanup the SDL Mixer initialization
  src/engine/audio.cpp
Labels: improvement, audio

#6754 Fix zero delays for Battlefield animations to reduce CPU usage at 10th battle speed
  src/fheroes2/game/game_delays.cpp
Labels: bug, ui

#6719 Update Polish translation
  files/lang/pl.po
Labels: improvement, translation

#6758 Fix AI being stuck on watering hole
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, regression

#6753 Add symbols to button font (ASCII)
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui

#6744 AI using town portal
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, AI

#6752 Rework the radar (mini-map) update calls for AI auto controlled player
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#6742 Tune sounds for guarded creature dwellings and streamline the logic
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, audio

#6745 Clean up AI priority tasks if attacker was killed
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
Labels: improvement, AI

#6764 zzlib.cpp: avoid extra reinterpret_cast conversions, check the results of static_cast conversions
  src/engine/zzlib.cpp
Labels: improvement

#6767 zzlib.cpp: avoid potential unsigned overflow when calculating the initial buffer size
  src/engine/zzlib.cpp
Labels: improvement

#6710 Czech translation Update
  files/lang/cs.po
Labels: improvement, translation

#6729 Gray out summon boat, town gate and town portal spells
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/spell/spell_info.h
Labels: bug, ui

#6770 Rename "scoute"
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#6766 Fix crash at the start of every map
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: crash, regression, high priority

#6750 Add virtual keyboard support for touch devices
  VisualStudio/fheroes2/sources.props
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_keyboard.h
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
Labels: improvement, ui, Android

#6791 Add max lines of translations for new languages
  docs/TRANSLATION.md
Labels: improvement, translation, documentation

#6737 Allow the player to refuse to level up in the Tree of Knowledge even if this level up is for free
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui, logic

#6741 Change the logic of reinforcement of the guest hero's army during the castle defense
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: improvement, logic

#6786 Make dwellings act like in OG: fight the guardians only once per map
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, logic

#6788 Redraw hero icons to display movement bar change before action dialog…
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#6793 Handle tasks removed by another hero
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: AI, crash, high priority

#6790 Fix the battle casualty report when non-true Resurrect spell was used during battle
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, logic

#6789 Allow to resurrect Elementals
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
Labels: bug, logic

#6775 Add missing part of Captain's Quarter in Sorceress Town
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/castle_building.cpp
Labels: improvement, ui, assets

#6787 Allow resurrected units to act on the current turn if they have not yet had their turn
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#6778 Czech translation Update
  files/lang/cs.po
Labels: improvement, translation

#6813 Remove unneeded translations
  src/fheroes2/dialog/dialog_game_settings.cpp
Labels: improvement, translation

#6819 Update the Norwegian translation
  files/lang/nb.po
Labels: improvement, translation

#6815 Drop pre-1.0 save file support
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
Labels: improvement

#6780 Fix mini-map update when interacting with map objects (Teleport, Artifact, Mine, Resource, Hero)
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, ui, regression

#6811 Fix display of Haunted Mines on mini-map and in View World
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: bug, ui

#6820 Version 1.0.2
  changelog.txt
  script/packaging/common/fheroes2.appdata.xml
  script/packaging/debian/changelog
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#6833 Update package hashes
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, script, Android

#6825 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#6836 Update Czech translation
  files/lang/cs.po
Labels: improvement, translation

#6832 Update documentation about Android
  docs/README_android.md
Labels: improvement, documentation, Android

#6839 Keep only Patreon link for FlatPak
  script/packaging/common/fheroes2.appdata.xml
Labels: bug, documentation

#6805 Properly track the Mirror Image spell duration, fix necromancy and calculation of casualties with mirrors
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, logic

#6846 Clang Analyzer & Clang-Tidy: migrate to Clang 15
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
Labels: improvement, GitHub Actions

#6841 Swedish translation update
  files/lang/sv.po
Labels: improvement, translation

#6844 SP now calculated with SPR after mouse click on icon
  src/fheroes2/gui/ui_dialog.cpp
Labels: bug, ui

#6859 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#6831 Fix Hero shadow render on Adventure Map
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, ui

#6858 Preserve existing object sprite Layer Type on monster spawning. Adventure map.
  src/fheroes2/maps/maps_tiles_quantity.cpp
Labels: bug, ui

#6818 Chain lightning blocked, if first target unit resists spell.
  src/fheroes2/battle/battle_action.cpp
Labels: bug, logic

#6855 Fix quick info for non-action objects when their action tile is under the fog. Adventure map.
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#6716 Added numeric speed of monsters to hero dialog fix #6526
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/kingdom/speed.cpp
  src/fheroes2/kingdom/speed.h
Labels: improvement, ui

#6864 Add cycling animation information into artist documentation
  docs/GRAPHICAL_ASSETS.md
  src/engine/pal.cpp
  src/tools/pal2img.cpp
Labels: improvement, documentation

#6602 Update Belarusian translation
  files/lang/be.po
Labels: improvement, translation

#6353 Small hero movement code cleanup
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement

#6779 Remove the MSVC 2017 support
  docs/DEVELOPMENT.md
  fheroes2-vs2017.vcxproj
  src/fheroes2/gui/ui_keyboard.cpp
  src/tools/82m2wav-vs2017.vcxproj
  src/tools/bin2txt-vs2017.vcxproj
  src/tools/extractor-vs2017.vcxproj
  src/tools/icn2img-vs2017.vcxproj
  src/tools/pal2img-vs2017.vcxproj
  src/tools/til2img-vs2017.vcxproj
  src/tools/xmi2midi-vs2017.vcxproj
Labels: improvement, Windows

#6863 Properly handle the situation when wandering monsters and a hero controlled by AI eliminate each other
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic, AI, high priority

#6867 Add Slovak translation and language option
  files/lang/Makefile
  files/lang/sk.po
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
Labels: improvement, translation

#6851 Update swedish translation
  files/lang/sv.po
Labels: improvement, translation

#6875 Separate Abandoned and Haunted mines
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_quantity.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: bug, logic

#6852 Update Polish translation
  android/app/src/main/res/values-pl/strings.xml
  files/lang/pl.po
Labels: improvement, high priority, translation

#6874 correct rounding of raising skeletons count
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic

#6884 Flatpak info translation page
  docs/TRANSLATION.md
Labels: improvement, documentation

#6894 Fix some recently introduced code smells
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement

#6709 Adjust recruitment window position on castle well and kingdom overview
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_bar.h
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: improvement, ui

#6809 Optimize Adventure Map: cache fog directions, do not render objects under fog, minor optimizations and fixes
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, ui

#6902 Fix clicks in Android MIDI music, use 44100 Hz sample frequency for all systems.
  android/app/src/main/assets/instruments/harp.pat
  android/app/src/main/assets/instruments/piccolo.pat
  android/app/src/main/assets/instruments/timpani.pat
  src/engine/audio.cpp
Labels: bug, improvement, audio, assets

#6901 Legacy game detection on x64
  script/homm2/extract_homm2_resources.ps1
Labels: improvement, script, deployment

#6896 Fix a few more code smells
  src/fheroes2/army/army_bar.cpp
Labels: improvement

#6899 Focus on the AI hero before he disappears due to boarding a boat or using a Dimension Door or Town Portal spell
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/mp2.cpp
Labels: bug, ui, AI

#6905 Fix the number of regenerated spell points with the Mysticism skill
  src/fheroes2/game/game_static.cpp
  src/fheroes2/heroes/skill.cpp
Labels: bug, logic

#6893 Update Czech translation
  files/lang/cs.po
Labels: improvement, translation

#6830 Add Vietnamese to the makefile, language option and initial font support
  files/lang/Makefile
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
Labels: improvement, translation

#6907 Fix typos
  cmake/FindSDL2.cmake
  cmake/README.md
  docs/TRANSLATION.md
  files/lang/be.po
  files/lang/bg.po
  files/lang/cs.po
  files/lang/de.po
  files/lang/dk.po
  files/lang/es.po
  files/lang/fr.po
  files/lang/hu.po
  files/lang/it.po
  files/lang/lt.po
  files/lang/nb.po
  files/lang/nl.po
  files/lang/pl.po
  files/lang/pt.po
  files/lang/ro.po
  files/lang/ru.po
  files/lang/sk.po
  files/lang/sv.po
  files/lang/tr.po
  files/lang/uk.po
  src/engine/localevent.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, ui

#6908 Added gold missing in statue building description
  src/fheroes2/castle/castle_building_info.cpp
Labels: improvement, ui

#6912 Fix multiple typos
  cmake/FindSDL2.cmake
  cmake/README.md
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_mode.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/gui/ui_scrollbar.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement

#6913 Improve AI fog discovery logic
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, AI
