Repository ihhub/fheroes2, pull requests merged in 2024-08, with the labels that each got.

#9014 Update of Ukrainian translation
  files/lang/uk.po
Labels: improvement, translation

#9001 Disable mouse popup for empty space in map selection window
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: improvement, ui

#9011 Update Earthquake spell animation and improve its logic to allow bridge and nearby towers demolition (Battlefield)
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_tower.h
Labels: bug, ui, logic

#9027 Rename cost_t to Cost
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/profit.cpp
  src/fheroes2/monster/monster_info.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: improvement

#9032 Tune the set of C/C++ compiler warnings
  android/app/jni/Android.mk
  src/CMakeLists.txt
  src/Makefile
Labels: improvement

#8996 Fix Cliff Nest glowing pixel
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, assets, pixel-precision

#9030 Extractor tool: use unsigned arithmetic to calculate the hash
  src/tools/extractor.cpp
Labels: improvement

#9033 Fix the audio playback and distance calculation in the 3D Audio mode
  src/engine/audio.cpp
  src/engine/audio.h
  src/fheroes2/agg/mus.cpp
  src/fheroes2/agg/mus.h
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_video.cpp
  src/fheroes2/resource/resource.h
Labels: bug, audio

#8962 Swedish Translation Update (#20)
  files/lang/sv.po
Labels: improvement, translation

#9026 Rework the castle buildings construction logic
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_common.h
  src/fheroes2/ai/ai_planner_castle.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_building_info.cpp
  src/fheroes2/castle/castle_building_info.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: bug, ui, regression

#9018 Ukrainian translation update
  files/lang/uk.po
Labels: improvement, translation

#9002 Minor code clean in battle_interface.cpp/.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, low priority

#9038 Fix the recently introduced code smell
  .clang-tidy
  src/fheroes2/audio/audio_manager.cpp
Labels: improvement

#9041 Fix the rendering of the Mage Guild upgrade animation
  src/fheroes2/castle/castle_building.cpp
Labels: bug, ui, regression

#9043 Transform the single-iteration loop into the lambda
  src/fheroes2/castle/castle_building.cpp
Labels: improvement

#9047 Replace reinterpret_cast with static_cast
  src/engine/image_tool.cpp
Labels: improvement

#9040 Render mirrored troop in dialog properly
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: improvement, ui

#9045 Use the castle owner's point of view for the threat assessment algorithm for castles
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/castle/castle.cpp
Labels: bug, AI

#9029 Fix multiple file-related bugs
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/fheroes2/world/world.cpp
Labels: bug, ui

#9037 Fix multiple issues with action creation in the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_format_info.h
Labels: bug, logic, editor

#9042 Update of Ukrainian Translations
  files/lang/uk.po
Labels: improvement, translation

#9048 Turn on the -Wmissing-declarations warning and move all detected global functions to the anonymous namespace
  android/app/jni/Android.mk
  src/CMakeLists.txt
  src/Makefile
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/resource/resource.cpp
  src/fheroes2/system/players.h
Labels: bug, improvement, ui

#8991 Limit the use of the Summon Boat by AI
  src/fheroes2/spell/spell_info.cpp
Labels: improvement, AI

#9051 Enable a few more compiler warnings, add more RAII for C-style "alloc()/free(), open()/close()"-like function pairs
  android/app/jni/Android.mk
  src/CMakeLists.txt
  src/Makefile
  src/engine/audio.cpp
  src/engine/core.cpp
  src/engine/image_tool.cpp
  src/engine/localevent.cpp
  src/engine/screen.cpp
  src/engine/serialize.h
  src/engine/smk_decoder.cpp
  src/engine/system.cpp
  src/engine/zzlib.cpp
  src/fheroes2/game/fheroes2.cpp
Labels: improvement

#9052 Swedish Translation Update (#21)
  files/lang/sv.po
Labels: improvement, translation

#9060 Hungarian language small update 06
  files/lang/hu.po
Labels: improvement, translation

#9064 Update of Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#9062 Add filename hash check in AGG files
  VisualStudio/tools/extractor/sources.props
  src/engine/agg_file.cpp
  src/engine/agg_file.h
  src/tools/extractor.cpp
Labels: improvement, assets

#9074 Move skill amount info up
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: improvement, ui, pixel-precision
