Repository ihhub/fheroes2, pull requests merged in 2024-03, with the labels that each got.

#8442 Fix the recently introduced code smell
  src/fheroes2/castle/buildinginfo.h
Labels: improvement

#8443 Update the Ukrainian translation
  files/lang/uk.po
Labels: improvement, translation

#8419 Fix the troops carry over mechanics for campaign
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/save_format_version.h
Labels: bug, campaign

#8444 Hungarian language update #16
  files/lang/hu.po
Labels: improvement, translation

#8445 Update the Ukrainian translation
  files/lang/uk.po
Labels: improvement, translation

#8447 Ukrainian translate update2
  files/lang/uk.po
Labels: improvement, translation

#8450 Fix a crash with AI hero animation
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
Labels: ui, crash

#8448 Update danish language (v1.1+)
  files/lang/dk.po
Labels: improvement, translation

#8454 Update DK translation (v1)
  files/lang/dk.po
Labels: improvement, translation

#8449 Fix multiple objects and add missing ones in the Editor
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, editor

#7956 Fix army split dialog text overflowing the dialog and add troops name
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, ui

#8408 Convenient list scrolling for touch screens
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/gui/ui_scrollbar.h
Labels: improvement, ui

#8395 Update editor's erasure tool
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, editor

#8400 Fix delayed cursor in campaign briefing dialog
  src/fheroes2/game/game_campaign.cpp
Labels: bug, ui, campaign

#8426 Update the French translation
  files/lang/fr.po
Labels: improvement, translation

#8462 Fix crash when selecting mines in the map editor
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: bug, editor

#8463 Fix rendering flaws of battle journal when using scroll bar
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#8459 fixed double daily resources award
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#8464 added possibility to "draw" the attack angle between two hexes
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#8467 Add a window telling about demo version being used
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
Labels: improvement, ui

#8471 Fix sphinx title offset
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, ui

#8466 Update the Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8474 Update the Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8478 Update to the Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8481 Update credits page
  src/fheroes2/game/game_credits.cpp
Labels: improvement, ui

#8485 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#8477 Update the French translation
  files/lang/fr.po
Labels: improvement, translation

#8482 Version 1.0.13
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#8456 Update the Spanish translation
  files/lang/es.po
Labels: improvement, translation

#8469 Add Editor related options
  VisualStudio/fheroes2/sources.props
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/editor/editor_options.h
  src/fheroes2/gui/interface_base.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui, editor

#8475 Make the default left and right hotkeys select skills in the level up dialog
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: improvement, ui

#8480 Fix hero battle info text X offset
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui

#8491 Hungarian language update #17
  files/lang/hu.po
Labels: improvement, translation

#8468 Use the AI pathfinder to assess the threat of enemy heroes instead of relying on the region database
  VisualStudio/fheroes2/sources.props
  src/engine/rand.h
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_personality.cpp
  src/fheroes2/ai/ai_personality.h
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/players.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, AI

#8488 Update to Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8497 Update Windows & Android dependencies
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, high priority, Android

#8496 Update the Romanian translations
  files/lang/ro.po
Labels: improvement, translation

#8502 Fix wrong name for Neutral race troops
  src/fheroes2/army/army.cpp
Labels: improvement, ui

#8501 Update the Ukrainian translation
  files/lang/uk.po
Labels: improvement, translation

#8499 Expand MapObjectType enumeration
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/system/save_format_version.h
Labels: improvement, editor

#8509 Make Funds as structure
  src/fheroes2/ai/ai.h
  src/fheroes2/castle/castle.h
  src/fheroes2/gui/ui_castle.h
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/resource/resource.h
Labels: improvement

#8500 Add more ISO8859-16 characters
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, translation

#8512 add info about install from Debian repository
  docs/INSTALL.md
Labels: improvement, Linux, documentation

#8511 Update to Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8516 Add all required metadata structures for Adventure Map objects
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: improvement, editor

#8523 Fix the typo in the Funds class constructor
  src/fheroes2/resource/resource.cpp
Labels: bug, regression

#8517 Update to Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8508 Small change of phrasing of creature seperation
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, ui

#8518 Hungarian language small update #01
  files/lang/hu.po
Labels: improvement, translation

#8525 Update CMakeLists.txt for a nicer fheroes2.exe
  src/fheroes2/CMakeLists.txt
Labels: improvement, deployment

#8527 add option FHEROES2_WITH_SYSTEM_SMACKER
  Makefile
  src/Makefile
  src/dist/Makefile
  src/engine/Makefile
Labels: improvement, deployment

#8503 added saveConfiguration boolean to openGraphicsSettingsDialog()
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_audio.h
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.h
  src/fheroes2/dialog/dialog_interface_settings.cpp
  src/fheroes2/dialog/dialog_interface_settings.h
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/editor/editor_options.cpp
Labels: improvement, ui

#8519 Improve Romanian translations #2
  files/lang/ro.po
Labels: improvement, translation

#8524 Improve Romanian translations #3
  files/lang/ro.po
Labels: improvement, translation
