Repository ihhub/fheroes2, pull requests merged in 2024-07, with the labels that each got.

#8898 Add Find Artifact victory condition in Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_sphinx_window.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/resource/artifact_info.cpp
Labels: improvement, editor

#8894 Allow to disable any building in castles and towns
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
Labels: improvement, ui, logic, editor

#8908 Show date description for daily events
  src/fheroes2/editor/editor_daily_event_spec_window.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_ui_helper.cpp
  src/fheroes2/editor/editor_ui_helper.h
Labels: improvement, ui

#8915 Fix the logic of processing the castle construction ban for MP2/MX2 maps
  src/fheroes2/castle/castle.cpp
Labels: bug, logic, regression

#8913 Fix the unused variable warning in release builds
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement

#8917 Add support for double click within Sphinx, Daily Events and Rumors lists
  src/fheroes2/editor/editor_daily_events_window.cpp
  src/fheroes2/editor/editor_rumor_window.cpp
  src/fheroes2/editor/editor_sphinx_window.cpp
Labels: improvement, ui, editor

#8916 Swedish Translation Update (#19)
  files/lang/sv.po
Labels: improvement, translation

#8802 Update of Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8925 Remove the unused extra ICNs
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
Labels: improvement

#8929 Fix UIDs restoration after Redo operation in Editor
  src/fheroes2/editor/history_manager.cpp
Labels: bug, crash, editor

#8934 Fix an assertion when pressing an unknown mouse button
  src/engine/localevent.cpp
Labels: bug, crash

#8805 Update of Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#8938 Remove unused ICN resources being generated by the engine
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
Labels: improvement

#8923 Add Evil theme for ADD, EDIT and DELETE buttons in Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/editor/editor_daily_events_window.cpp
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_rumor_window.cpp
  src/fheroes2/editor/editor_sphinx_window.cpp
  src/fheroes2/editor/editor_ui_helper.cpp
Labels: improvement, editor

#8905 Implement special victory and loss conditions for heroes and towns
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/gui/ui_castle.cpp
  src/fheroes2/gui/ui_castle.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, high priority, editor

#8822 Hungarian language small update 05
  files/lang/hu.po
Labels: improvement, translation

#8936 Fix swap of the main tile addon if a top object already exists in that tile
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: bug, high priority, editor

#8944 Fix "Accumulate gold" condition logic
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: bug, logic, high priority

#8940 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#8945 Add extra checks for verify objects' information
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, logic

#8947 Address recently added SonarQube issues
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement

#8928 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#8950 Update of Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8927 Version 1.1.1
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#8952 AI: properly evaluate the enemy heroes defending the castles
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, AI

#8939 Fix some SonarQube code smells
  src/engine/screen.cpp
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/spell/spell.cpp
Labels: improvement

#8912 Handle the SDL events strictly in turn
  src/engine/localevent.cpp
  src/engine/screen.cpp
Labels: bug, SDL2

#8957 Kingdoms::AddCastles(): bring the const back
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
Labels: improvement

#8956 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#8961 Add new River Deltas objects
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, ui, editor

#8964 Allow to type "/", "*", "-", "+" and "." from the keypad
  src/engine/localevent.cpp
Labels: improvement

#8958 Fix several SonarQube code smells
  src/engine/localevent.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/mp2_helper.cpp
  src/fheroes2/maps/mp2_helper.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#8967 Update hashes for Android & Windows dependency packages
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#8965 Fix diacritical marks remove in mine selection dialog in the editor
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: bug, ui, editor

#8970 Remove scouting & movement bonuses for AI-controlled players
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: improvement, AI

#8955 Use showStandardTextMessage() instead of showMessage() where possible and reduce string copying by using std::move()
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_artifact.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_sphinx_window.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/ui_campaign.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/gui/ui_kingdom.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement

#8973 Remove all object shadow related files
  VisualStudio/fheroes2/sources.props
  src/fheroes2/CMakeLists.txt
  src/fheroes2/agg/agg_image.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/objects/mounts.cpp
  src/fheroes2/objects/mounts.h
  src/fheroes2/objects/objcrck.cpp
  src/fheroes2/objects/objcrck.h
  src/fheroes2/objects/objdirt.cpp
  src/fheroes2/objects/objdirt.h
  src/fheroes2/objects/objdsrt.cpp
  src/fheroes2/objects/objdsrt.h
  src/fheroes2/objects/objgras.cpp
  src/fheroes2/objects/objgras.h
  src/fheroes2/objects/objlava.cpp
  src/fheroes2/objects/objlava.h
  src/fheroes2/objects/objmult.cpp
  src/fheroes2/objects/objmult.h
  src/fheroes2/objects/objsnow.cpp
  src/fheroes2/objects/objsnow.h
  src/fheroes2/objects/objswmp.cpp
  src/fheroes2/objects/objswmp.h
  src/fheroes2/objects/objtown.cpp
  src/fheroes2/objects/objtown.h
  src/fheroes2/objects/objwatr.cpp
  src/fheroes2/objects/objwatr.h
  src/fheroes2/objects/objxloc.cpp
  src/fheroes2/objects/objxloc.h
  src/fheroes2/objects/trees.cpp
  src/fheroes2/objects/trees.h
Labels: improvement

#8949 Fix object picking up animation, fix object remove from map and fix restoration of the object type for the tile
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, ui, high priority

#8976 Change the All maps button translation
  files/lang/pl.po
Labels: bug, translation

#8975 Android Toolset: add Russian translation for FH2M file manager
  android/app/src/main/res/values-ru/strings.xml
Labels: improvement, translation, Android

#8974 fix Anti-Magic spell description #8968
  src/fheroes2/spell/spell.cpp
Labels: improvement, ui

#8960 Add monster stats inside editor count dialog
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
Labels: improvement, ui, editor

#8981 Editor: take into account the arbitrary case of the map directory name
  src/fheroes2/editor/editor_interface.cpp
Labels: bug, Linux, editor

#8983 Add Ukrainian language virtual keyboard
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui, translation

#8986 AI code refactoring
  VisualStudio/fheroes2/sources.props
  src/dist/Makefile
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_base.cpp
  src/fheroes2/ai/ai_battle.cpp
  src/fheroes2/ai/ai_battle.h
  src/fheroes2/ai/ai_battle_spell.cpp
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_common.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_hero_action.h
  src/fheroes2/ai/ai_planner.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_castle.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_internals.h
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/ai/normal/ai_normal_spell.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world.cpp
Labels: improvement, AI

#8987 Fix some recently introduced code smells
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement

#8989 Add missed Small Cliff (Dirt terrain) to the Landscape Miscellaneous objects in Editor
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: bug, editor

#8977 Fix original maps bottom layer (hacky) placed resources and artifacts
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: bug, ui, logic

#8988 Implement alliances in editor
  src/fheroes2/editor/editor_daily_event_spec_window.cpp
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_ui_helper.cpp
  src/fheroes2/editor/editor_ui_helper.h
  src/fheroes2/maps/map_format_helper.cpp
Labels: improvement, editor

#8993 Fix map special conditions render after drop list is closed
  src/fheroes2/editor/editor_map_specs_window.cpp
Labels: ui, regression, editor

#9005 Do not immediately handle the intermediate events of some types
  src/engine/localevent.cpp
Labels: bug, SDL2, regression

#9013 Mark the appropriate headers with IWYU pragma: associated
  src/fheroes2/ai/ai_battle_spell.cpp
  src/fheroes2/ai/ai_planner_castle.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/battle/battle.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_catapult.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_artifact.cpp
  src/fheroes2/dialog/dialog_box.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_frameborder.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement

#9000 Update hero spell points indicator after the battle and before performing defeated opponent fade animation
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/gui/interface_base.cpp
  src/fheroes2/gui/interface_base.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#8591 AI should determine best skill when leveling up heroes
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_regions.cpp
Labels: improvement, AI

#9016 Handle the AI hero's patrol mode in the AI pathfinder
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, AI
