Repository ihhub/fheroes2, pull requests merged in 2024-10, with the labels that each got.

#9151 Improve the I/O error handling
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/fheroes2/army/army.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#9116 Rework the text rendering code
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui

#9162 Add the temporary workaround to fix the Windows CMake build
  .github/workflows/cmake.yml
Labels: bug, high priority, GitHub Actions

#9161 Fix a few recently introduced code smells
  src/fheroes2/world/world.cpp
Labels: improvement

#9120 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#9159 Clean-up battle interface Status class
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, low priority

#9153 Migrate AllCastles and AllHeroes to std::unique_ptr
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building_info.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#9171 Add an additional assertion
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#9173 Migrate the build from macOS 12 to macOS 13
  .github/workflows/make.yml
Labels: GitHub Actions

#9176 Fix the order in which events are handled by various UI elements in the "no interface" mode
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_status.cpp
Labels: bug, ui, regression

#9174 Improve vertical dismiss button translations for French and Spanish
  files/lang/es.po
  files/lang/fr.po
Labels: improvement, translation

#9170 Specify the pointer part of the type outside of auto
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes.h
Labels: improvement

#9160 Clean battle interface TurnOrder class
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, low priority

#9155 Battle Graveyard: allow to resurrect overlapped corpses
  src/fheroes2/ai/ai_battle_spell.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_bridge.cpp
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_grave.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, logic

#9063 Add monochrome ICN decode code and use original hexagon sprite for the battlefield
  src/engine/agg_file.h
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/tools/icn2img.cpp
Labels: improvement, ui, assets

#9166 Small code clean in Castle class
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
Labels: improvement, low priority

#9175 Make hourglass animation during AI turn more smooth
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/interface_status.h
  src/fheroes2/heroes/heroes_move.cpp
Labels: improvement, ui

#9182 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#9125 Add language support for fh2m map format
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/castle_tavern.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_language_selection.h
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_castle_details_window.h
  src/fheroes2/editor/editor_daily_event_spec_window.cpp
  src/fheroes2/editor/editor_daily_event_spec_window.h
  src/fheroes2/editor/editor_daily_events_window.cpp
  src/fheroes2/editor/editor_daily_events_window.h
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_event_details_window.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/editor/editor_rumor_window.cpp
  src/fheroes2/editor/editor_rumor_window.h
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/editor/editor_save_map_window.h
  src/fheroes2/editor/editor_sphinx_window.cpp
  src/fheroes2/editor/editor_sphinx_window.h
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, ui, translation, editor

#9179 Fix map titles not being cleared when changing map
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: bug, ui

#9167 Fix Sorceress Statue construction fade-in animation
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_dialog.cpp
Labels: bug, ui

#9178 Refactor & streamline the event handling logic for adventure map and map editor UI elements
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_interface_settings.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/cursor.cpp
  src/fheroes2/gui/cursor.h
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_border.h
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_buttons.h
  src/fheroes2/gui/interface_cpanel.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/interface_status.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#9190 Fix some recently introduced code smells
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_buttons.h
Labels: improvement

#9186 Swedish Translation Update (#22)
  files/lang/sv.po
Labels: improvement, translation

#9191 Cache translation file loading operations
  src/engine/translations.cpp
  src/engine/translations.h
  src/fheroes2/system/settings.cpp
Labels: improvement, translation

#9195 Hungarian language small update 07
  files/lang/hu.po
Labels: improvement, translation

#9156 Do not mark captured castle objects by Color::UNUSED
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/kingdom/color.cpp
  src/fheroes2/kingdom/color.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#9209 Remove the temporary workaround intended to fix the Windows CMake build
  .github/workflows/cmake.yml
Labels: improvement, GitHub Actions

#9200 Fix debug build crash with French and Italian assets
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, crash, translation

#9199 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#9198 Fix a few code smells
  script/tools/changelog_update_metainfo.py
  script/tools/check_copyright_headers.py
  src/engine/translations.h
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/system/settings.cpp
Labels: improvement

#9194 Add missing popup dialogs to buttons within View World mode
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement, ui

#9207 Shorten map title when too long in several places
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement, ui

#9201 Fix render of overlapped UI elements
  src/fheroes2/castle/captain.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_buttons.cpp
  src/fheroes2/gui/interface_buttons.h
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_icons.cpp
  src/fheroes2/gui/interface_icons.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_scrollbar.cpp
  src/fheroes2/gui/ui_scrollbar.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, ui

#9211 Remove the unused function
  src/fheroes2/game/game_interface.h
Labels: improvement

#9203 Added Czech Virtual Keyboard
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui, translation

#9213 Fix incorrect Scrollbar position after it is upscaled
  src/fheroes2/gui/ui_scrollbar.cpp
Labels: bug, ui, regression

#9205 Fix French smallfont i with circumflex
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, translation

#9217 Fix invalid behavior and crash while interacting with whirlpools by heroes on boats
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: bug, crash, high priority

#9215 Version 1.1.3
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9206 ui_button.cpp/.h code clean
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement

#9219 Add u with two dots to buttons and translate and improve German buttons
  files/lang/de.po
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, ui, translation

#9222 Do not download the wing32.dll for HoMM2 demo version
  script/demo/download_demo_version.ps1
Labels: improvement, script

#9226 Rename Addon into Object Part
  src/fheroes2/castle/castle.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/maps_tiles_render.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#9218 Various minor improvements
  src/engine/rand.cpp
  src/engine/rand.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army.h
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_tower.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: improvement, logic

#9231 Fix some recently introduced code smells
  src/engine/rand.cpp
  src/fheroes2/army/army_troop.h
Labels: improvement

#9232 Fix some code smells related to the resource management
  src/engine/image.h
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/captain.h
  src/fheroes2/castle/castle.h
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_recruits.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom.h
Labels: improvement

#9227 Use proper serialization logic for the tile's main object part
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/save_format_version.h
Labels: improvement

#9230 Reduce code duplication in ICN decode and a little speed-up for transform decode
  src/engine/image_tool.cpp
Labels: improvement

#9228 Rename Object into Object Type for tiles
  src/fheroes2/agg/m82.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_object_popup_window.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement

#9235 Rename all members of ObjectPart structure
  src/fheroes2/agg/m82.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#9236 Use singular form of Tile in the code
  src/fheroes2/agg/m82.cpp
  src/fheroes2/agg/m82.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_castle.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_object_popup_window.cpp
  src/fheroes2/editor/editor_object_popup_window.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/gui/interface_focus.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_move.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/heroes/route.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/ground.cpp
  src/fheroes2/maps/ground.h
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/maps_tiles_render.h
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_regions.cpp
Labels: improvement

#9238 SonarCloud: Ignore cpp:S106 (Standard outputs should not be used directly to log anything) for command-line tools
  sonar-project.properties
Labels: improvement

#9240 Fix reef passability
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, logic

#9244 Center Magic Book artifact on the Adventure Map
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, editor

#9241 Standartize code to update POL objects
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: improvement, logic

#9246 Update hashes for Android & Windows dependency packages
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#9239 Remove all objects marked as shadow from top layer
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, logic
