Repository ihhub/fheroes2, pull requests merged in 2024-12, with the labels that each got.

#9307 Update PS Vita touchpad ID after it has changed in SDL2 v2.30.7
  src/engine/localevent.cpp
Labels: bug

#9310 Speed up getting a list of files on PS Vita
  Makefile.vita
  src/engine/dir.cpp
  src/engine/dir.h
  src/engine/system.cpp
Labels: improvement, regression

#9281 Synchronize maximum allowed number of characters for input and Virtual Keyboard
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_keyboard.h
Labels: improvement, ui

#9312 AI::Planner::reinforceCastle() : paraphrase a few comments
  src/fheroes2/ai/ai_planner_castle.cpp
Labels: improvement

#9308 Updated Turkish Translation.
  files/lang/tr.po
Labels: improvement, translation

#9299 Updated Czech translation
  files/lang/cs.po
Labels: improvement, translation

#9204 Fix French and German ultimate staff sprite with PoL assets
  src/fheroes2/agg/agg.cpp
  src/fheroes2/agg/agg.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/bin_info.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/gui/ui_language.cpp
Labels: improvement, assets

#9315 Add missing CP1254 button letters for Turkish
  src/fheroes2/gui/ui_font.cpp
Labels: improvement, translation

#9316 Move the Battle::Unit::isUnderSpellEffect() with the AI-only logic to the AI code
  src/fheroes2/ai/ai_battle_spell.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: improvement

#9223 Use drawOnState() for buttons precessing and cache buttons' position for event handler loop
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_arena.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/dialog/dialog_chest.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_interface_settings.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/dialog/dialog_thievesguild.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_highscores.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement

#9318 Add range values for default experience
  src/fheroes2/heroes/heroes_indicator.cpp
Labels: improvement, ui, editor

#9321 Hungarian language small update 08
  files/lang/hu.po
Labels: improvement, translation

#8816 Use monster abilities instead of hardcoded monster IDs
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster.h
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/monster/monster_info.h
  src/fheroes2/spell/spell.h
Labels: improvement, logic

#9332 Limit the use of VPATH for GNU Make
  src/dist/engine/Makefile
  src/dist/fheroes2/Makefile
  src/dist/thirdparty/libsmacker/Makefile
  src/dist/tools/Makefile
Labels: improvement

#9326 Fix a bug when picking up an object whose type does not match its sprite on the map
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: bug

#9340 Reset the damage info popup when the spell cast has been cancelled
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#9319 Fix text input cursor setting for multi-line text input with many spaces at the line end
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: bug, ui

#9343 Fix spell randomization logic for Artifacts and the Adventure Map objects
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
Labels: improvement, logic

#9278 Show a warning dialog upon a map file loading failure
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement, ui

#9341 Document the mechanics of "drawing the angle of attack" in the README_android.md
  docs/README_android.md
Labels: improvement, documentation

#9327 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#9335 Add a new variant of Stone Liths object
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, assets

#9347 Add ability to set spells in Shrine in the Editor
  VisualStudio/fheroes2/sources.props
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_spell_selection.cpp
  src/fheroes2/editor/editor_spell_selection.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui, logic, editor

#9344 Add ability to set the amount in Resource object on the Adventure Map
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_object_popup_window.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui, logic, editor

#9350 Add ability to edit spells in Pyramid inside the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui, logic, editor

#9356 Editor: Reset the "tile under cursor" value, stored from a previously edited map
  src/fheroes2/editor/editor_interface.cpp
Labels: bug, editor

#9355 Fix cursor positioning with non-English characters and improve positioning at the end of the line
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: bug, ui

#9359 Fix the Linux ARM64 build
  .github/workflows/make.yml
Labels: bug, deployment, GitHub Actions

#9357 Fix the mouse interaction in the Editor's spell selection and castle properties windows
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_spell_selection.cpp
Labels: bug, ui

#9351 Add ability to setup Secondary Skills in Witch's Hut inside the Editor
  VisualStudio/fheroes2/sources.props
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_secondary_skill_selection.cpp
  src/fheroes2/editor/editor_secondary_skill_selection.h
  src/fheroes2/editor/editor_spell_selection.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/gui/ui_campaign.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui, logic, editor

#9367 Fix the spell cost displayed in the quick info window when hero has artifact that reduces this cost
  src/fheroes2/gui/ui_dialog.cpp
Labels: bug, ui

#9362 Swedish Translation Update (#24)
  files/lang/sv.po
Labels: improvement, translation

#9373 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#9363 Updated Czech translation
  files/lang/cs.po
Labels: improvement, translation

#9375 Speed up GitHub Actions
  .github/workflows/android.yml
  .github/workflows/cmake.yml
  .github/workflows/codechecker.yml
  .github/workflows/iwyu.yml
  .github/workflows/make.yml
  .github/workflows/translation_update.yml
  sonar-project.properties
Labels: improvement, GitHub Actions

#9381 Fix Spell Scroll artifact X position on the Adventure Map
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, original assets

#9383 Show '-' sign for numeric keypad only if a range allows to use negative values
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui

#9380 Show Monster and Artifact names in the popup dialog of the Editor
  src/fheroes2/editor/editor_object_popup_window.cpp
Labels: improvement, ui, editor

#9379 Add 3 new variants of Observation Tower object
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, ui, logic, editor

#9386 Hungarian language small update 09
  files/lang/hu.po
Labels: improvement, translation

#9364 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#9391 Version 1.1.5
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9384 Expand Text Support mode for New Map selection dialogs
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
Labels: improvement, ui

#9387 Add swap army and swap artifacts to the heroes meeting screen
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#9395 Fix some recent code smells
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement

#9394 Code style check: check the syntax of markdown files
  .github/workflows/code_style_check.yml
  .markdownlint-cli2.jsonc
  CONTRIBUTING.md
  README.md
  cmake/LICENSE
  docs/DEVELOPMENT.md
  docs/GRAPHICAL_ASSETS.md
  docs/INSTALL.md
  docs/PRIVACY_POLICY.md
  docs/README.md
  docs/README_PSV.md
  docs/README_android.md
  docs/README_cmake.md
  docs/README_switch.md
  docs/TRANSLATION.md
  script/README.md
  script/agg/README.md
  script/android/README.md
  script/demo/README.md
  script/homm2/README.md
  script/linux/README.md
  script/macos/README.md
  script/windows/README.md
Labels: improvement, GitHub Actions, documentation
