Repository ihhub/fheroes2, pull requests merged in 2024-04, with the labels that each got.

#8535 Do not add scaled resolutions for PS Vita
  src/engine/screen.cpp
Labels: bug, ui

#8531 Add compression step for the map format
  src/engine/h2d_file.cpp
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/highscores.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
Labels: improvement, editor

#8528 Update to Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8513 Implement hero details dialog in Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/army/army_bar.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_only.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/skill_bar.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom_overview.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_storage.cpp
  src/fheroes2/spell/spell_storage.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#8547 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#8551 Fix primary skill display in Hero dialog
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, ui, regression, high priority

#8546 Hungarian language small update #02
  files/lang/hu.po
Labels: improvement, translation

#8540 Add the jailed hero details dialog in Editor
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#8539 Add a window to change Monster properties
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/monster/monster.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#8560 Fix metadata handling and object loading for new map format
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#8559 Update Portuguese translation
  files/lang/pt.po
Labels: improvement, translation

#8545 Update of Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#8569 Expand map format to support daily events
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, high priority, editor

#8570 Fix Artifact Spell Scroll read from hero metadata
  src/fheroes2/heroes/heroes.cpp
Labels: bug, editor

#8573 Add logic to handle victory and loss conditions for maps
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#8576 Expand logic for artifact placement in the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, high priority, editor

#8582 Allow river deltas to be placed anywhere
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, editor

#8583 Add code to modify Spell Scroll artifact
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, editor

#8577 Fix radar rendering for heroes and castles
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/world/world.h
Labels: bug, editor

#8581 Add a shortcut to go to the Main Menu from the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement, editor

#8590 Fix some unused variable cases
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: bug
