Repository ihhub/fheroes2, pull requests merged in 2024-06, with the labels that each got.

#8770 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#8790 Code cleanup for event types to avoid having everything in 1 pile
  src/engine/localevent.cpp
Labels: improvement

#8782 Limit the minimum slider length by 15 pixels
  src/fheroes2/gui/ui_scrollbar.cpp
Labels: ui, regression

#8402 Remove the AI unit growth bonuses and tune the income bonuses for different difficulty levels
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, AI

#8788 Put the Graveyard object to the correct category, "hide" the ugly versions of Graveyard sprites
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: bug, editor

#8794 Fix some recently introduced code smells
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/kingdom/kingdom.cpp
Labels: improvement

#8751 Code cleanup for the future changes of map loading with more functionality
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic

#8787 Swedish translation update (#18)
  files/lang/sv.po
Labels: improvement, translation

#8669 Differentiate Random Castle and Town names
  src/fheroes2/editor/editor_castle_details_window.cpp
Labels: improvement, ui, editor

#8798 Abstract event processing code to be able to use any other library for this purpose
  src/engine/core.cpp
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_levelup.cpp
  src/fheroes2/gui/interface_gamearea.cpp
Labels: improvement, logic

#8811 Prevent a crash when a hero is killed defending a castle
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: bug, AI, crash

#8810 Code cleanup for LocalEvent class
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_mageguild.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_interface_settings.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_logo.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/gui/interface_border.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/interface_list.h
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_map_interface.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/kingdom/view_world.cpp
Labels: improvement, logic

#8814 Generate a random hero portrait for the Editor
  src/engine/pal.cpp
  src/engine/pal.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui, editor

#8806 Move an existing object in front while trying to place an exact one on the same tile
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
Labels: improvement, logic, editor

#8819 Add checks to verify object layer type
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, logic

#8829 Avoid hardcoded values for Magellans' Maps visit object
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/payment.cpp
  src/fheroes2/kingdom/payment.h
Labels: improvement, logic

#8827 Properly check the PoL resources in order to enable the Editor
  src/fheroes2/game/game_mainmenu.cpp
Labels: bug, ui

#8824 Add '?' symbol to Virtual Keyboard
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui

#8821 Speed up save file loading and saving operations
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/highscores.cpp
Labels: improvement, logic

#8818 Add more checks for SDL functions
  src/engine/localevent.cpp
  src/engine/screen.cpp
Labels: improvement

#8828 Fix Magic Garden being shown without animation within the Editor
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: improvement, ui

#8825 Fix castle and hero radar rendering in the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
Labels: bug, ui

#8831 AI: fix the assertion failure when visiting an object that is impossible to stand on
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, AI

#8820 Remove unused code related to shadow part verification
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement

#8835 Bring the logic of the Summon Boat spell for the human player in line with its logic of operation in the case of AI
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/spell/spell_info.cpp
  src/fheroes2/spell/spell_info.h
Labels: bug, logic

#8838 Update hashes for Android & Windows dependency packages
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#8823 Add an ability to edit Rumors for maps
  VisualStudio/fheroes2/sources.props
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_rumor_window.cpp
  src/fheroes2/editor/editor_rumor_window.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui, editor

#8832 Update hero selection dialog in the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: ui, editor

#8847 Add a new variation of Cave object on the Adventure Map
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, assets, editor

#8853 Fix radar rendering within the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/maps/map_format_helper.cpp
Labels: bug, ui, editor

#8859 Update development instructions
  docs/DEVELOPMENT.md
Labels: improvement, documentation

#8866 Update map type popup message by right click to include Resurrection maps
  src/fheroes2/dialog/dialog_selectscenario.cpp
Labels: improvement, ui

#8864 Reduce castle ROI for mouse right clicking inside Editor's castle selection window
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: improvement, ui

#8867 Add color names to Traveller's Tent and Barrier objects within object selection window
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, ui

#8865 Add hotkey for passability within the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement, ui

#8872 Show pressed monster button on Editor panel while clicking on it
  src/fheroes2/editor/editor_interface_panel.cpp
Labels: bug, ui, editor

#8879 Add first special map conditions within the Editor
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement, ui, editor

#8857 Magic Book window: show the maximum number of spell points
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/gui/interface_events.cpp
  src/fheroes2/heroes/heroes_base.cpp
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/spell/spell_book.cpp
  src/fheroes2/spell/spell_book.h
Labels: improvement, ui

#8845 Fix the display of identical artifacts captured in battle
  src/fheroes2/battle/battle_dialogs.cpp
Labels: bug, ui, regression

#8883 Allow normal victory for "Accumulate gold" condition
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_fileinfo.cpp
Labels: improvement, ui, editor

#8874 Set the space width as a maximum word width if the text contains only spaces
  src/fheroes2/gui/ui_text.cpp
Labels: bug, ui, high priority

#8876 Update logic related to human player selection for maps
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/game/game_mode.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, logic

#8889 Show Day, Week and Month for Out of time loss condition
  src/fheroes2/editor/editor_map_specs_window.cpp
Labels: improvement, ui, editor

#8891 Restrict obelisk placement to 48 objects
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, logic, editor

#8895 Add popup messages for right clicking on special map conditions
  src/fheroes2/editor/editor_map_specs_window.cpp
Labels: improvement, ui, editor
