Repository ihhub/fheroes2, pull requests merged in 2024-11, with the labels that each got.

#9229 Fix the penalty calculation for enemy units that can evade the engagement during battle
  src/fheroes2/ai/ai_battle.cpp
  src/fheroes2/battle/battle_troop.cpp
Labels: improvement, AI

#9193 Add support of Evil interface for Scenario Information dialog
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_gameinfo.cpp
Labels: improvement, ui

#9243 Fix overlapping text in the High Scores dialog
  src/fheroes2/game/game_highscores.cpp
Labels: bug, ui

#9248 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#9251 Update hash for Android dependency package
  script/android/install_packages.bat
  script/android/install_packages.sh
Labels: bug, improvement, Android

#9255 Fix the attack value estimation for a Hypnotized unit with the ALL_ADJACENT_CELL_MELEE_ATTACK ability
  src/fheroes2/ai/ai_battle.cpp
Labels: bug, AI

#9252 Update initial tile passability calculations
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: improvement, logic

#9256 Rename or remove some more reserved type/enum names (ending in _t)
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/game/game_over.h
  src/fheroes2/game/highscores.cpp
  src/fheroes2/game/highscores.h
  src/fheroes2/kingdom/week.cpp
  src/fheroes2/kingdom/week.h
  src/fheroes2/maps/maps.h
  src/fheroes2/monster/monster.h
Labels: improvement

#9258 Code cleanup for tile passability calculations
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, logic

#9270 Android: update the desugar_jdk_libs_nio dependency to 2.1.3
  android/app/build.gradle
Labels: improvement, Android

#9268 Swedish Translation Update (#23)
  files/lang/sv.po
Labels: improvement, translation

#9259 Update German translations related to the Price of Loyalty Campaign
  files/lang/de.po
Labels: improvement, translation

#9265 Improve & speed up the translation-related code a bit
  src/engine/agg_file.cpp
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/tinyconfig.cpp
  src/engine/tools.cpp
  src/engine/translations.cpp
  src/engine/translations.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/world/world.cpp
  src/tools/82m2wav.cpp
  src/tools/extractor.cpp
  src/tools/h2dmgr.cpp
  src/tools/xmi2midi.cpp
Labels: improvement

#9264 Move Streams handling in Editor from "world" tiles to "Map_Format"
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, editor

#9282 Add Belarusian language support for Virtual Keyboard
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui, translation

#9189 Update the Czech translation
  files/lang/cs.po
Labels: improvement, translation

#9291 Fix LANDSCAPE_MISCELLANEOUS objects erasure in editor
  src/fheroes2/editor/editor_interface.cpp
Labels: crash, regression, editor

#9290 Add new Lean-To object variant
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, ui, editor

#9293 Replace the clang-analyzer workflow with CodeChecker workflow
  .codechecker-ignore
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/codechecker.yml
  .github/workflows/iwyu.yml
  .github/workflows/pull_request.yml
  .github/workflows/sonarcloud.yml
  src/engine/audio_xmi2mid.cpp
Labels: improvement, GitHub Actions

#9287 Add Virtual Numpad support
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_keyboard.h
Labels: improvement, ui

#9280 Version 1.1.4
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9297 Use the platform-dependent byte order for the SDL audio format
  src/engine/audio.cpp
Labels: improvement, audio

#9300 Enable the number input dialog for the recruitment window
  src/fheroes2/dialog/dialog_recruit.cpp
Labels: improvement, ui

#9279 Fix a few more code smells
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: improvement

#9288 AudioManager: simplify the code for playing ambient sounds, evaluate & remove the old TODO comment
  src/fheroes2/audio/audio_manager.cpp
Labels: improvement, audio

#9296 Use the std::filesystem and support non-quite-POSIX-compliant filesystems (such as Amiga FS)
  src/engine/logging.cpp
  src/engine/system.cpp
  src/engine/system.h
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/game/game_io.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
  src/tools/82m2wav.cpp
  src/tools/bin2txt.cpp
  src/tools/extractor.cpp
  src/tools/h2dmgr.cpp
  src/tools/icn2img.cpp
  src/tools/pal2img.cpp
  src/tools/til2img.cpp
  src/tools/xmi2midi.cpp
Labels: improvement
