Repository ihhub/fheroes2, pull requests merged in 2024-09, with the labels that each got.

#9077 Fix visited info when hero has visited a tree under another player's control
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#9078 Shorten German DIFFICULTY translation
  files/lang/de.po
Labels: improvement, translation

#9055 Fix some code smells
  src/engine/screen.cpp
  src/engine/serialize.h
  src/engine/smk_decoder.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/agg/icn.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/castle/captain.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_base.h
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/heroes/skill_static.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/visit.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
  src/fheroes2/spell/spell.cpp
  src/fheroes2/spell/spell.h
Labels: improvement

#9083 Generalize the zzlib functions
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/zzlib.cpp
  src/engine/zzlib.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/highscores.cpp
  src/fheroes2/maps/map_format_info.cpp
Labels: improvement

#9061 Optimize XMI to MID decode code
  src/engine/audio_xmi2mid.cpp
  src/engine/serialize.h
Labels: improvement, audio

#9090 Fix the recently introduced code smell
  src/engine/audio_xmi2mid.cpp
Labels: improvement

#9086 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#9088 Speed up Map Specification Window closure if no changes are being done
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, editor

#9097 Add const in multiple places
  src/tools/82m2wav.cpp
  src/tools/bin2txt.cpp
  src/tools/extractor.cpp
  src/tools/h2dmgr.cpp
  src/tools/icn2img.cpp
  src/tools/pal2img.cpp
  src/tools/til2img.cpp
  src/tools/xmi2midi.cpp
Labels: improvement

#9096 Preserve the order of artifacts when adding the Spell Book to the artifacts bag
  src/fheroes2/resource/artifact.cpp
Labels: improvement, logic

#9099 Version 1.1.2
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9102 Prevent redistribution of hero's last unit
  src/fheroes2/army/army_bar.cpp
Labels: bug, logic

#9101 Minor code clean-up in icn.h/.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/captain.cpp
  src/fheroes2/castle/castle_building.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/game/game_mainmenu.cpp
  src/fheroes2/gui/ui_campaign.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
Labels: improvement, low priority

#9092 Remove all remaining const_cast conversions
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/heroes/heroes_meeting.cpp
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact.h
Labels: improvement

#9035 Rework main object part access from Tiles
  src/fheroes2/agg/m82.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement

#9089 Do not discard area selection while moving mouse out of map
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
Labels: improvement, ui

#9108 Update Windows & Android dependencies
  android/app/build.gradle
  android/build.gradle
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#9103 Center sprites and text in adventure map treasure chest dialog
  src/fheroes2/dialog/dialog_chest.cpp
Labels: bug, ui

#8562 Extend button resizing to include height
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui, translation

#9111 Fix a few recently introduced (or updated) code smells
  src/engine/dir.cpp
  src/engine/system.cpp
  src/engine/translations.cpp
Labels: improvement

#9105 Add a popup dialog to the list of resolutions
  src/fheroes2/dialog/dialog_resolution.cpp
Labels: improvement, ui

#8262 Add vertical gradient fonts
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_font.h
  src/fheroes2/gui/ui_text.h
Labels: improvement, ui

#8994 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#9119 getHeroAnimation() function minor code clean-up
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, low priority

#9117 Fix the UTF-16 -> CP_ACP conversion issues on Windows
  src/engine/audio.cpp
  src/engine/dir.cpp
  src/engine/image_tool.cpp
  src/engine/screen.cpp
  src/engine/system.cpp
  src/engine/system.h
Labels: bug, Windows

#9124 Set UID counter to the maximum object's UID value after loading a saved game
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, crash, high priority

#9128 Remove the misleading TODO comment
  src/fheroes2/agg/m82.cpp
Labels: improvement

#9135 Fix a few code smells
  src/fheroes2/battle/battle_army.h
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/gui/interface_itemsbar.h
  src/fheroes2/gui/skill_bar.h
Labels: improvement

#9139 Properly handle radar dragging in Editor when area select brush is used
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui, editor

#9133 Fix the triggering of invalid drag events for the game area in certain cases
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
Labels: bug, ui

#9134 Editor and fh2m maps: set OBJECT_LAYER when placing a monster on the map
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: bug, editor

#8813 Make default knowledge value for random hero as 1
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
Labels: improvement, logic, editor

#9126 Battlefield: optimize Damage Info pop-up dialog rendering
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#9143 Fix blinking arrow cursor during scrolling in Editor
  src/fheroes2/editor/editor_interface.cpp
Labels: bug, ui, editor

#9118 Battle log: split long phrases into two lines
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#9150 Some code optimizations
  src/engine/pal.cpp
  src/engine/smk_decoder.cpp
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/maps/map_object_info.h
Labels: improvement

#9144 Do not take into account top layer when selecting objects to erase.
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: bug, editor

#9140 Simplify the AI Dimension Door operations and improve the overall speed of AI calculations
  src/engine/localevent.cpp
  src/engine/rand.h
  src/engine/serialize.h
  src/engine/system.cpp
  src/engine/tinyconfig.cpp
  src/engine/tools.h
  src/engine/translations.cpp
  src/fheroes2/ai/ai_battle.cpp
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_personality.h
  src/fheroes2/ai/ai_planner.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_pathfinding.h
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/gui/ui_map_object.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/pairs.h
  src/fheroes2/resource/resource.h
  src/fheroes2/system/players.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: bug, improvement, AI

#9154 Fix the recently introduced code smells
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/visit.cpp
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#9145 Status Window: update army info after the battle, add sand grains to the hourglass animation and code clean
  src/fheroes2/gui/interface_status.cpp
  src/fheroes2/gui/interface_status.h
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, improvement, ui

#8877 Increase most of object selection windows by 50 pixels
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: improvement, ui
