Repository ihhub/fheroes2, pull requests merged in 2024-01, with the labels that each got.

#8215 Small improvements over image loading
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/resources/fheroes2.rc
Labels: improvement, ui

#8214 Implement warning message in the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
Labels: improvement, ui, editor

#8222 Allow AI heroes to surrender if the conditions of retreat have been met, but it is impossible to retreat
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_arena.cpp
Labels: bug, improvement, logic, AI

#8224 Update Android dependencies
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
Labels: improvement, Android

#8226 Remove redundant return type
  src/fheroes2/editor/editor_interface_panel.cpp
Labels: improvement

#8228 Fix fog sprite selection for several conditions
  src/fheroes2/maps/maps_tiles_render.cpp
Labels: bug, ui

#8213 Add dwellings into the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, editor

#8183 Hungarian language update #13
  files/lang/hu.po
Labels: improvement, translation

#8230 Handle Low Memory event for Android and iOS
  src/engine/localevent.cpp
Labels: improvement, Android

#8154 Add text width-adapted CANCEL button, change to StandardWindow for Resolution, Language, Adventure, File and Scenario Info dialogs
  files/lang/de.po
  files/lang/fr.po
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_adventure.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/player_info.cpp
  src/fheroes2/gui/ui_button.cpp
Labels: improvement, ui

#8236 Fix a SonarQube smell
  src/fheroes2/gui/player_info.cpp
Labels: improvement

#8227 Allow the AI-controlled hero to surrender if his kingdom has sufficient gold reserves
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_army.h
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/resource/resource.cpp
  src/fheroes2/resource/resource.h
Labels: improvement, AI

#8238 Remove unused macro
  src/fheroes2/resource/resource.h
Labels: improvement

#8008 Delete script/packaging/debian directory
  script/packaging/debian/README.txt
  script/packaging/debian/changelog
  script/packaging/debian/control
  script/packaging/debian/copyright
  script/packaging/debian/docs
  script/packaging/debian/install
  script/packaging/debian/manpages
  script/packaging/debian/rules
  script/packaging/debian/source/format
  script/packaging/debian/upstream/metadata
Labels: improvement, Linux, deployment

#8242 Reduce object info structure size
  src/fheroes2/maps/map_object_info.h
Labels: improvement, editor

#8239 Improve AI heroes interaction with Witch's Hut object
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/battle/battle_main.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
Labels: improvement, AI

#8251 Update Windows & Android dependencies
  android/build.gradle
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#8233 Implement Mines placing in Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/gui/ui_map_object.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
Labels: improvement, high priority, editor

#8240 Adjust text in the skill popup dialog
  src/fheroes2/gui/ui_dialog.cpp
Labels: improvement, ui

#8235 Improve AI heroes behavior on the Adventure Map
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_pathfinding.cpp
  src/fheroes2/world/world_pathfinding.h
Labels: improvement, AI

#8245 Allow units that ignore retaliatory strikes to attack neighboring enemy units while covering archers
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_grave.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_pathfinding.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/monster/monster.h
Labels: improvement, AI

#8247 Implement Power-ups object placement in the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, editor

#8259 Rename OBJ_HERO object
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/ai/normal/ai_normal_kingdom.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement

#8255 Optimize the AIPathfinder::getFogDiscoveryTile()
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
  src/fheroes2/world/world_pathfinding.cpp
Labels: improvement, AI

#8256 Make AI to attack human heroes with higher chance than AI heroes
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#8258 Make AI heroes do not know which spell a shrine has before visiting it
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#8250 Implement Mountains, Rocks and Trees placing in Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, editor

#8266 Offer the Wisdom skill to the heroes of "magic" classes on a mandatory basis at least once every three level-ups
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
Labels: bug, logic

#8271 Fix some recent code smells
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement

#8278 Use CP1257 for Lithaunian
  files/lang/Makefile
Labels: bug, improvement, macOS, translation

#8277 Use proper name for PoL campaign in High Scores
  src/fheroes2/campaign/campaign_scenariodata.cpp
Labels: bug, ui

#8272 Defensive tactics in battle: allow units covering archers with the AREA_SHOT capability to attack neighboring units on their own
  src/fheroes2/ai/normal/ai_normal_battle.cpp
Labels: improvement, AI

#8286 Do not do operations with pointer to nullptr in image.cpp
  src/engine/image.cpp
Labels: bug, high priority

#8296 Fix SonarQube issues in image.cpp
  src/engine/image.cpp
Labels: improvement

#8294 Army::Reset(): the case of a hero without a race can sometimes be legitimate
  src/fheroes2/army/army.cpp
Labels: bug, logic

#8299 Add infos on the cost of surrender
  src/fheroes2/battle/battle_army.cpp
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
Labels: improvement, ui

#8211 Update spell points, formations and artifacts descriptions
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/resource/artifact_info.cpp
Labels: improvement, ui

#8276 Single layer image processing improvements
  src/engine/h2d_file.cpp
  src/engine/image.cpp
  src/engine/image.h
  src/engine/image_tool.cpp
  src/engine/localevent.cpp
  src/engine/screen.cpp
  src/engine/zzlib.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_radar.cpp
  src/fheroes2/gui/interface_radar.h
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#8244 Add surrender cost to battle result dialog
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
Labels: improvement, ui

#8310 Revert changes for Resize() function
  src/engine/image.cpp
Labels: bug, regression

#8273 Tune the AI performance at different difficulty levels
  src/fheroes2/ai/normal/ai_normal_castle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, AI

#8311 Improve image Resize() function to properly work with single-layer images and split it to Resize() and SubpixelResize() functions
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/game/game_credits.cpp
Labels: improvement, ui

#8287 Implement Adventure (action) Miscellaneous objects placing in Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/maps/map_object_info.cpp
Labels: improvement, editor

#8307 Swedish translation update (#13)
  files/lang/sv.po
Labels: improvement, translation

#8284 Fix issue when Blind or Paralyze has been applied to a hypnotized unit during its turn
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, logic

#8275 Make the AI not to know what objects contain
  src/fheroes2/ai/normal/ai_normal.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_hero.cpp
Labels: improvement, AI

#8317 Fix OKAY button translation for Interface Settings dialog after any setting change
  src/fheroes2/dialog/dialog_interface_settings.cpp
Labels: bug, ui

#8280 Implement Landscape Miscellaneous (non action) objects placing in Editor
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
Labels: improvement, high priority, editor

#8313 Puzzle dialog rendering improvement
  src/fheroes2/kingdom/puzzle.cpp
  src/fheroes2/kingdom/puzzle.h
Labels: improvement, ui

#8316 View World rendering improvement
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/kingdom/view_world.h
Labels: improvement, ui

#8319 Fix editor_interface.cpp compilation issues
  src/fheroes2/editor/editor_interface.cpp
Labels: regression, high priority

#8304 Always offer one native hero at the beginning of a new week
  src/fheroes2/heroes/heroes_recruits.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#8318 Fix Oasis passability
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#8325 Use the same name for terrain objects within the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: improvement, ui, editor

#8338 Clang-Tidy comments workflow: junk the paths while unzipping the user-provided ZIP archive
  .github/workflows/clang_tidy_comments.yml
Labels: improvement, GitHub Actions

#8336 Added missing "the" to one of the dialogs.
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, ui

#8326 Expand castle metadata and add hero metadata for the map format
  src/engine/serialize.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, logic, editor

#8297 Make rules for AI surrender and retreat more unified
  src/fheroes2/ai/ai.h
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/normal/ai_normal.h
  src/fheroes2/ai/normal/ai_normal_battle.cpp
  src/fheroes2/ai/normal/ai_normal_hero.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/world/world_pathfinding.cpp
Labels: bug, improvement, logic, AI

#8344 Limit the number of heroes being placed on map
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
Labels: logic, editor

#8342 Change the logic to handle the future map loading
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/history_manager.cpp
  src/fheroes2/editor/history_manager.h
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/world/world_loadmap.cpp
Labels: logic, editor

#8243 Hungarian language update #14
  files/lang/hu.po
Labels: improvement, translation

#8350 GitHub Actions: Request only the minimum necessary permissions for workflows
  .github/workflows/android.yml
  .github/workflows/clang_analyzer.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/clang_tidy_comments.yml
  .github/workflows/cmake.yml
  .github/workflows/code_style_check.yml
  .github/workflows/iwyu.yml
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  .github/workflows/pr_author_auto_assign.yml
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/translation_update.yml
Labels: improvement, GitHub Actions

#8357 Migrate the build workflow from macOS 11 to 12
  .github/workflows/make.yml
Labels: improvement, macOS, GitHub Actions

#8356 Fix some minor code issues
  src/engine/image.cpp
  src/engine/serialize.cpp
  src/engine/serialize.h
  src/engine/zzlib.h
  src/fheroes2/agg/bin_info.h
  src/fheroes2/battle/battle_animation.cpp
  src/fheroes2/battle/battle_animation.h
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/kingdom/puzzle.h
  src/fheroes2/monster/monster_anim.h
  src/fheroes2/resource/resource.h
Labels: improvement
