Repository ihhub/fheroes2, pull requests merged in 2025-10, with the labels that each got.

#10155 Add support for simultaneous playback of multiple videos
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/campaign/campaign_data.cpp
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/game/fheroes2.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_over.cpp
  src/fheroes2/game/game_video.cpp
  src/fheroes2/game/game_video.h
  src/fheroes2/game/game_video_type.h
Labels: bug, campaign, video

#10226 Set a limit on multi-line text input to avoid going beyond the dialog
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/ui_tool.h
Labels: bug, ui, editor

#10239 Add missing popup dialog for Exit button in the Puzzle dialog
  src/fheroes2/kingdom/puzzle.cpp
Labels: improvement, ui

#10237 Add missing popups for all buttons in the Hero Meeting dialog
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#10225 Show Turn Order dialog above the arena if there is enough space
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#10227 Add a new resolution icon
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/h2d/h2d.cpp
Labels: improvement, ui, new assets

#10238 Allow to hold a button to repeat an action in the Virtual Keyboard
  src/engine/localevent.h
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui

#10235 Remove dangling shadow part of the Ultimate Artifact
  src/fheroes2/world/world_loadmap.cpp
Labels: bug, logic

#10251 Add startup text mode message
  src/fheroes2/game/game_logo.cpp
Labels: improvement, ui

#10222 Update the Danish translation
  files/lang/dk.po
Labels: improvement, translation

#10252 Do not cancel Marketplace resource selection if no gift was made
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
Labels: improvement, ui, logic

#10232 Make Adventure Options button resizable for better translation support
  files/lang/ru.po
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/dialog/dialog_adventure.cpp
Labels: improvement, ui

#10234 Add Restart and Quick Save buttons in File Options dialog
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/campaign/campaign_scenariodata.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/game/game_io.cpp
  src/fheroes2/game/game_io.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/maps/maps_fileinfo.cpp
  src/fheroes2/maps/maps_fileinfo.h
Labels: improvement, ui, logic

#10247 Add a button to toggle on/off all spells in the Shrines and Castles for the Editor
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/editor/editor_spell_selection.cpp
  src/fheroes2/h2d/h2d.cpp
Labels: improvement, ui, editor
