Repository ihhub/fheroes2, pull requests merged in 2025-01, with the labels that each got.

#9399 Android: gracefully handle errors when the system chooser does not start for some reason
  android/app/build.gradle
  android/app/src/main/java/org/fheroes2/MapFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/app/src/main/res/values-ru/strings.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: bug, Android

#9385 Modified Button Layout to be similar to OG
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/dialog/dialog_buyboat.cpp
  src/fheroes2/gui/ui_button.cpp
Labels: improvement, ui, pixel-precision

#9402 Improve side tile passability logic
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, logic

#9410 Remove additional passability marks on the bottom part of tiles
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement, logic

#9412 Fix a few recently introduced code smells
  src/dist/Makefile.emscripten
  src/engine/serialize.cpp
  src/engine/thread.cpp
Labels: improvement

#9414 Fix some of the HTML errors reported by SonarQube
  files/emscripten/index.html
Labels: bug, WASM

#9415 Display spell name in dialog for spell casting error
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#9416 Update the sources.props for tools
  VisualStudio/tools/h2dmgr/sources.props
  VisualStudio/tools/pal2img/sources.props
  VisualStudio/tools/til2img/sources.props
Labels: improvement

#9418 Update background image for PSV version of the engine
  files/images/platform/psv/background.png
  files/images/platform/psv/sce_sys/livearea/contents/bg.png
Labels: bug

#9424 Update hashes for Android & Windows dependency packages
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#9420 Remove the logic to update Troll's Bridge passability after visiting it
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
Labels: bug, improvement

#9417 Unify the Emscripten and non-Emscripten builds
  .gitignore
  Makefile
  Makefile.emscripten
  Makefile.switch
  Makefile.vita
  docs/Makefile
  files/lang/Makefile
  src/dist/Makefile
  src/dist/Makefile.emscripten
  src/dist/engine/Makefile
  src/dist/fheroes2-ems/Makefile
  src/dist/fheroes2/Makefile
  src/dist/thirdparty/libsmacker/Makefile
  src/dist/tools/Makefile
Labels: improvement, WASM

#9398 Improved morale ui when all troops are undead
  src/fheroes2/army/army.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
Labels: improvement, ui

#9426 Emscripten: re-enable the -pthread compiler flag
  .github/workflows/make.yml
  src/dist/Makefile.emscripten
  src/engine/thread.cpp
Labels: improvement, Wasm

#9430 Add the basic developer's documentation for the Wasm port
  docs/DEVELOPMENT.md
  docs/README_emscripten.md
Labels: improvement, documentation, Wasm

#9434 Fix the issue with the status of the pressed buttons on the battle screen
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#9446 Fix the Hideous Mask behavior when neutral units never flee
  src/fheroes2/army/army.cpp
  src/fheroes2/army/army.h
Labels: bug, logic

#9419 Update debug info being shown for tiles
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#9444 Further fixes and improvements related to WebAssembly
  .github/workflows/make.yml
  Makefile.emscripten
  docs/README_emscripten.md
  src/dist/Makefile
  src/dist/Makefile.emscripten
  src/engine/audio.cpp
  src/engine/localevent.cpp
  src/engine/screen.h
  src/engine/thread.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/gui/interface_status.cpp
Labels: improvement, Wasm

#9452 Fix selected Ore mine reset in Mine placing dialog (Editor)
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: bug, editor

#9451 Simplify passability logic when a bottom tile is a true action object
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/maps/maps_tiles.cpp
Labels: improvement

#9449 WebAssembly: improve the logging
  src/engine/logging.h
Labels: improvement, Wasm

#9454 Fix overlap of FPS info and popup message in the Editor
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, editor

#9457 Use the github-hosted arm64 runners to build for arm64
  .github/workflows/make.yml
Labels: improvement, deployment

#9455 Add a button to toggle developer mode in debug build
  src/engine/localevent.cpp
  src/engine/localevent.h
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
Labels: improvement, low priority

#9423 Set the PROJECT_VERSION for PSV in XX.YY format
  Makefile.vita
Labels: bug, deployment, PlayStation Vita

#9180 Add dialog to choose between Auto Combat and Quick Combat
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/ai/ai_battle.cpp
  src/fheroes2/ai/ai_battle.h
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_arena.h
  src/fheroes2/battle/battle_command.cpp
  src/fheroes2/battle/battle_command.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/gui/ui_button.cpp
Labels: improvement, ui

#9462 WebAssembly: build both the multithreaded and non-multithreaded versions in parallel, optimize the workflows a bit
  .github/workflows/cmake.yml
  .github/workflows/make.yml
  .github/workflows/msvc.yml
Labels: improvement, GitHub Actions

#9463 Do full image copy with one 'memcpy()' call
  src/engine/image.cpp
Labels: improvement

#9465 Remove temporary FindSDL2_* CMake scripts
  CMakeLists.txt
  cmake/FindSDL2_image.cmake
  cmake/FindSDL2_mixer.cmake
  cmake/LICENSE
  cmake/README.md
  cmake/README_findsdl2.md
Labels: improvement, CMake

#9469 Fix the build with NDEBUG
  src/fheroes2/agg/agg_image.cpp
Labels: bug

#9468 Fix a crash in View World mode for the Editor
  src/fheroes2/kingdom/view_world.cpp
  src/fheroes2/kingdom/view_world.h
Labels: bug, ui, editor

#9456 Fix mine flag rendering and don't crop its sprite, remove unused flag setting logic
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
Labels: improvement, ui

#9085 Update Hero Movement button
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/gui/interface_buttons.cpp
Labels: improvement, ui

#9482 Add description about 50% retaliation damage to the Blind spell
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/spell/spell.cpp
Labels: improvement, ui

#9480 Show Artifact description window for clicking on it in the Editor
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, ui, editor

#9470 Add undo and redo icons
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
Labels: improvement, ui, editor

#9485 Shorten hero name if name plus level is too long
  src/fheroes2/dialog/dialog_quickinfo.cpp
Labels: bug, ui

#9471 Add button shine to more buttons
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_dialogs.cpp
  src/fheroes2/dialog/dialog_audio.cpp
  src/fheroes2/dialog/dialog_game_settings.cpp
  src/fheroes2/dialog/dialog_graphics_settings.cpp
  src/fheroes2/dialog/dialog_system_options.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_option_item.cpp
Labels: improvement, ui

#9486 Add a dialog pop up when pressing standing horse
  src/fheroes2/gui/interface_events.cpp
Labels: improvement, ui

#9496 Render the main menu after calling settings dialog from new game dialog
  src/fheroes2/dialog/dialog_game_settings.cpp
Labels: bug, ui

#9487 CMake: use the CMAKE_COMPILE_WARNING_AS_ERROR instead of ENABLE_STRICT_COMPILATION
  .github/workflows/clang_tidy.yml
  .github/workflows/cmake.yml
  .github/workflows/codechecker.yml
  .github/workflows/iwyu.yml
  .github/workflows/sonarcloud.yml
  CMakeLists.txt
  src/engine/CMakeLists.txt
  src/fheroes2/CMakeLists.txt
  src/tools/CMakeLists.txt
Labels: improvement, CMake

#9497 Display resource count if set for right click popup info in the Editor
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_object_popup_window.cpp
  src/fheroes2/editor/editor_object_popup_window.h
Labels: improvement, ui, editor

#9479 Fix text rendering for the level up dialog
  src/fheroes2/dialog/dialog_levelup.cpp
Labels: bug, ui

#9499 Use a single button to switch between castle and town in the Editor dialog
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/gui/ui_button.cpp
Labels: improvement, ui

#9503 Small code restructure for agg_image.cpp|h files
  src/engine/image_tool.cpp
  src/engine/image_tool.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/agg_image.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/gui/ui_text.cpp
Labels: improvement

#9506 Add more game options for the Editor
  src/fheroes2/dialog/dialog_interface_settings.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/gui/ui_option_item.cpp
  src/fheroes2/gui/ui_option_item.h
Labels: improvement, ui, editor

#9464 Hungarian language small update 10
  files/lang/hu.po
Labels: improvement, translation

#9507 Display monster count for monster object for the Editor
  src/fheroes2/editor/editor_object_popup_window.cpp
Labels: improvement, ui, editor
