Repository ihhub/fheroes2, pull requests merged in 2025-09, with the labels that each got.

#10153 Fix Hero Dialog EXIT button flickering
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, ui

#10142 Fix invalid cursor while choosing an object in the Editor
  src/fheroes2/editor/editor_interface_panel.cpp
Labels: bug, ui, editor

#10159 Update Portuguese Translation
  files/lang/pt.po
Labels: improvement, translation

#8407 Add initial iOS Support
  .gitignore
  ios/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Assets.xcassets/ColorMap.textureset/Contents.json
  ios/Assets.xcassets/ColorMap.textureset/Universal.mipmapset/ColorMap.png
  ios/Assets.xcassets/ColorMap.textureset/Universal.mipmapset/Contents.json
  ios/Assets.xcassets/Contents.json
  ios/Base.lproj/LaunchScreen.storyboard
  ios/SDL_uikit_main.c
  ios/ShaderTypes.h
  ios/Shaders.metal
  ios/fheroes2.xcodeproj/project.pbxproj
  ios/fheroes2.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/fheroes2.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/fheroes2.xcodeproj/project.xcworkspace/xcuserdata/drewbratcher.xcuserdatad/UserInterfaceState.xcuserstate
  ios/fheroes2.xcodeproj/xcuserdata/drewbratcher.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  ios/fheroes2.xcodeproj/xcuserdata/drewbratcher.xcuserdatad/xcschemes/xcschememanagement.plist
  script/tools/check_code_format.sh
  script/tools/check_copyright_headers.sh
  src/engine/audio.cpp
  src/engine/screen.cpp
  src/fheroes2/system/settings.cpp
Labels: improvement, high priority, iOS

#10200 Grammar fix for winning condition
  src/fheroes2/editor/editor_map_specs_window.cpp
Labels: improvement, ui

#10199 Update of Ukrainian Translation September
  files/lang/uk.po
Labels: improvement, translation

#10213 Remove unused method
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
Labels: improvement

#10209 Do not show cell selection frame when no monster is selected for a brush in the Editor
  src/fheroes2/editor/editor_interface_panel.cpp
Labels: improvement, ui, editor

#10195 Add ability to delete maps from the map lists
  src/fheroes2/dialog/dialog_hotkeys.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/dialog/dialog_resolution.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/dialog/dialog_selectscenario.cpp
  src/fheroes2/dialog/dialog_selectscenario.h
  src/fheroes2/editor/editor_daily_events_window.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/editor/editor_rumor_window.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/editor/editor_sphinx_window.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/interface_list.h
Labels: improvement, ui

#10180 Code cleanup for map loading
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement
