Repository ihhub/fheroes2, pull requests merged in 2025-08, with the labels that each got.

#10054 Add popup messages for button in the Count Selection dialog
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, ui

#10049 Save days spent value for each scenario of campaign
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/system/save_format_version.h
Labels: improvement, logic

#10058 Set default initialization values for many members of classes and structures
  src/fheroes2/army/army.h
  src/fheroes2/army/army_bar.h
  src/fheroes2/battle/battle_catapult.h
  src/fheroes2/battle/battle_cell.h
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/battle/battle_only.h
  src/fheroes2/battle/battle_tower.h
  src/fheroes2/campaign/campaign_data.h
  src/fheroes2/campaign/campaign_scenariodata.h
  src/fheroes2/castle/buildinginfo.h
  src/fheroes2/system/bitmodes.h
Labels: improvement

#10057 Fix incorrect boat setting logic on a map tile
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#10059 Improve video processing logic
  .codechecker-review-status-config
  src/engine/smk_decoder.cpp
  src/engine/smk_decoder.h
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/game/game_video.cpp
Labels: improvement, video

#10062 Fix Wagon object evaluation for the AI when it contains resources
  src/fheroes2/ai/ai_planner_hero.cpp
Labels: improvement, AI

#10063 Rename strings in the Editor to use "class" instead of "race"
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: improvement, ui, translation

#10064 Add a popup window for clicking on scenario title in the campaign window
  src/fheroes2/game/game_campaign.cpp
Labels: improvement, ui

#10068 Fix a few recently introduced code smells
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement

#9323 Limit all resolutions to a currently selected resolution in the system
  src/engine/screen.cpp
Labels: improvement, ui

#10071 Android: support 16 KB page sizes
  android/app/build.gradle
  android/app/jni/Application.mk
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  script/android/install_packages.bat
  script/android/install_packages.sh
Labels: improvement, deployment, Android

#10050 Fix shifted by 16 pixels position of a map for the first opening in the Editor
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, ui

#10080 Code cleanup for the save handling code
  src/fheroes2/game/game_io.cpp
Labels: improvement

#10082 Add support for single-layer images for H2D files
  files/data/resurrection.h2d
  src/engine/h2d_file.cpp
Labels: improvement

#10069 Hungarian language updates
  files/lang/hu.po
Labels: improvement, translation

#10086 Show the creature image in the "Week of..." and "Month of..." dialog windows
  src/fheroes2/dialog/dialog_armyinfo.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, ui

#10088 Make the Toolset activities compatible with Android 15 edge-to-edge enforcements
  android/app/src/main/java/org/fheroes2/MapFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/SaveFileManagerActivity.java
  android/app/src/main/java/org/fheroes2/ToolsetActivity.java
  android/app/src/main/res/layout/activity_map_file_manager.xml
  android/app/src/main/res/layout/activity_save_file_manager.xml
  android/app/src/main/res/layout/activity_toolset.xml
Labels: improvement, ui, Android

#10125 Fix logic for hero selection window in the Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: ui, logic, editor

#10126 Small Hungarian language update
  files/lang/hu.po
Labels: improvement, translation

#10137 GitHub Actions: fix the SonarCloud workflow
  .github/workflows/sonarcloud.yml
Labels: bug, GitHub Actions

#10143 Fix incorrect sentence for Mines and Observation Tower popup message for OKAY button
  src/fheroes2/dialog/dialog_selectitems.cpp
Labels: bug, ui, editor
