Repository ihhub/fheroes2, pull requests merged in 2025-04, with the labels that each got.

#9710 CodeChecker: use the new recently introduced config format
  .codechecker-ignore
  .codechecker-review-status-config
  .github/workflows/codechecker.yml
Labels: improvement, GitHub Actions

#9712 Swedish Translation Update (#27)
  files/lang/sv.po
Labels: improvement, translation

#9718 Fix: fix install script permissions for macos
  .github/workflows/make.yml
  docs/DEVELOPMENT.md
  docs/INSTALL.md
  script/macos/Brewfile
  script/macos/install_sdl2.sh
Labels: improvement, script

#9719 Improve the input of numbers from the hardware keyboard
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#9723 Remove alert to fix github pages rendering
  docs/INSTALL.md
Labels: bug, documentation

#9722 Improve macOS Native App Build and Setup Tooling
  docs/INSTALL.md
  script/homm2/extract_homm2_resources.sh
  script/homm2/extract_homm2_resources_for_app_bundle.sh
  script/macos/Brewfile.app_bundle
  script/macos/README.md
  script/macos/cleanup_app_bundle_files.sh
Labels: improvement, script, macOS, documentation

#9725 INSTALL.md: properly align the tables and text
  docs/INSTALL.md
Labels: bug, documentation

#9720 Fix status bar offset to prevent text from overlapping status bar bottom border
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/castle_town.cpp
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/gui/statusbar.cpp
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: bug, ui, pixel-precision

#9732 Allow to move the virtual keyboard cursor using the hardware keyboard buttons
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui

#9733 Virtual keyboard: remove unused actions
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement

#9734 Replace switch statement by if statement
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement

#9608 Add German language support for Virtual Keyboard
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui, translation

#9713 Android: set the application category to "game"
  android/app/src/main/AndroidManifest.xml
Labels: improvement, Android

#9739 Clang-Tidy comments workflow: simplify the logic a bit
  .github/workflows/clang_tidy_comments.yml
Labels: improvement, GitHub Actions

#9738 GitHub Actions: run the CodeChecker and IWYU workflows only if some C/C++ files were changed
  .github/workflows/codechecker.yml
  .github/workflows/iwyu.yml
  .github/workflows/pull_request.yml
Labels: improvement, GitHub Actions

#9740 Add OGG audio format support for Emscripten build
  src/dist/Makefile.emscripten
Labels: improvement, Wasm

#9741 Fix the resumption of music playback for Emscripten builds
  src/engine/audio.cpp
Labels: improvement, audio, Wasm

#9727 Updated Czech translation
  files/lang/cs.po
Labels: improvement, translation

#9735 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#9744 MIDI: allow to pick up custom timidity.cfg
  android/app/build.gradle
  src/dist/Makefile.emscripten
  src/engine/audio.cpp
  src/engine/audio.h
  src/fheroes2/audio/audio_manager.cpp
  src/fheroes2/audio/audio_manager.h
  src/fheroes2/game/fheroes2.cpp
Labels: improvement, audio

#9729 Fix clearing diacritic signs in movable text used in status bar
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: bug, ui

#9736 Implement documentation site with dark/light theme support
  .clang-format
  .github/workflows/code_style_check.yml
  README.md
  docs/.gitignore
  docs/DEVELOPMENT.md
  docs/GRAPHICAL_ASSETS.md
  docs/Gemfile.dev
  docs/INSTALL.md
  docs/PRIVACY_POLICY.md
  docs/README.md
  docs/README_PSV.md
  docs/README_android.md
  docs/README_cmake.md
  docs/README_emscripten.md
  docs/README_switch.md
  docs/TRANSLATION.md
  docs/WEBSITE_LOCAL_DEV.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/_sass/_dark-theme.scss
  docs/_sass/_layout.scss
  docs/_sass/_light-theme.scss
  docs/assets/css/style.scss
  docs/assets/js/accessibility.js
  docs/assets/js/code-copy.js
  docs/assets/js/heading-copy.js
  docs/assets/js/templates.js
  docs/assets/js/theme-toggle.js
  docs/images/favicon.ico
  docs/package-lock.json
  docs/package.json
  script/macos/Brewfile.dev_tools
  script/tools/check_code_format.sh
  script/tools/check_copyright_headers.sh
Labels: improvement, documentation

#9746 Update Hungarian translation
  files/lang/hu.po
Labels: improvement, translation

#9749 Update Windows & Android dependencies
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, high priority, Android

#9285 Update German translations related to artifacts
  files/lang/de.po
Labels: improvement, translation

#9750 Windows: use the TiMidity backend instead of Fluidsynth for MIDI playback
  .github/workflows/msvc.yml
  VisualStudio/fheroes2/common.props
  script/windows/fheroes2.iss
  src/engine/audio.cpp
Labels: bug, improvement, Windows, audio

#9753 Windows: remove fluidsynth from dependencies
  script/windows/install_packages.bat
Labels: improvement, Windows, high priority

#9756 Windows: remove DLLs related to wavpack library
  script/windows/install_packages.bat
Labels: improvement, Windows

#9757 Android: silence the "Attribute unused on older versions" warning in regard to android:appCategory
  android/app/src/main/AndroidManifest.xml
Labels: improvement, Android

#9752 Update the fheroes2 manual page
  docs/.gitignore
  docs/fheroes2.6.in
Labels: improvement, Linux, documentation

#9731 Text input cursor change from '_' to '|' (with zero width)
  src/engine/localevent.cpp
  src/engine/tools.cpp
  src/engine/tools.h
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#9759 Fix a few recently introduced code smells
  src/fheroes2/gui/ui_text.h
Labels: improvement

#9745 Update Danish language (v.1.1.8)
  files/lang/dk.po
Labels: improvement, translation

#9755 Update the CountBits() algorithm
  src/engine/tools.h
Labels: improvement

#9607 Replace "gold only" chest dialog with "gold or exp" one in case when hero has no space for an artifact
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui
