Repository ihhub/fheroes2, pull requests merged in 2025-03, with the labels that each got.

#9591 Update portuguese translation
  files/lang/pt.po
Labels: improvement, translation

#9602 Do not center on the defeated hero after an instant movement
  src/fheroes2/heroes/heroes_move.cpp
Labels: bug, ui

#9610 Allow activate Czech virtual keyboard
  src/fheroes2/gui/ui_keyboard.cpp
Labels: bug, ui

#9612 Add proper translation support for Sign objects
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, ui, translation

#9596 Update the Hungarian translation
  files/lang/hu.po
Labels: improvement, translation

#9615 Remove unused logic for monthly castle visited status
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/kingdom/kingdom.cpp
  src/fheroes2/kingdom/kingdom.h
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
  src/fheroes2/maps/visit.cpp
  src/fheroes2/maps/visit.h
  src/fheroes2/world/world.cpp
Labels: improvement, logic

#9590 Move road placement logic directly to the map format
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/world/world.cpp
Labels: improvement, editor

#9599 Fix rendering of tall objects and extra objects (ghosts and flags) over the top map edge
  src/fheroes2/gui/interface_gamearea.cpp
  src/fheroes2/gui/interface_gamearea.h
  src/fheroes2/maps/maps_tiles_render.cpp
  src/fheroes2/maps/maps_tiles_render.h
Labels: bug, ui

#9611 Swedish Translation Update (#26)
  files/lang/sv.po
Labels: improvement, translation

#9617 Fix visited status for certain Adventure Map objects for AI
  src/fheroes2/ai/ai_hero_action.cpp
Labels: improvement, logic

#9613 Fix object visiting marking logic
  src/engine/math_base.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/map_object_info.h
Labels: improvement, logic

#8542 Fixing Golden bow sprite glowing pixels
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/game/game_credits.cpp
Labels: improvement, original assets, pixel-precision

#9620 Make the AI use Guardian spells
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: improvement, AI

#9622 Fix a delay during battle after showing a monster info dialog by right clicking
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#9623 Allow the AI to cast Guardian spell after capturing an Abandoned Mine
  src/fheroes2/ai/ai_hero_action.cpp
Labels: improvement, AI

#9626 Make the AI share visit info about some objects
  src/fheroes2/ai/ai_common.cpp
  src/fheroes2/ai/ai_common.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/difficulty.cpp
  src/fheroes2/game/difficulty.h
Labels: improvement, AI

#9618 Implement Dragon Slayer spell selection for the AI
  src/fheroes2/ai/ai_battle.h
  src/fheroes2/ai/ai_battle_spell.cpp
Labels: improvement, AI

#9624 Fix creature info dialog shadow draw on right click
  src/fheroes2/dialog/dialog_armyinfo.cpp
Labels: bug, ui

#9628 Do not apply dynamic interface if the player is not ingame
  src/fheroes2/system/settings.cpp
Labels: bug, logic, regression

#9630 Do not set visited state if genie lamp is removed from the map
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, crash, regression

#9636 Fix an assertion crash for hacked mines on old saves
  src/fheroes2/maps/maps_tiles.cpp
Labels: bug, logic

#9644 SonarCloud: use the new SonarSource actions instead of the deprecated one
  .github/workflows/sonarcloud.yml
Labels: improvement, GitHub Actions

#9642 Fix reseting heroes icons focus after oppening Castle (#9522)
  src/fheroes2/game/game_startgame.cpp
Labels: bug, logic

#9645 Add disable/enable logic for Editor's undo/redo buttons (#9450)
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
  src/fheroes2/editor/history_manager.h
Labels: improvement, editor

#9650 AI heroes should buy spellbook if there isn't one
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle.h
  src/fheroes2/castle/castle_dialog.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/castle/mageguild.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_spell.cpp
Labels: improvement, AI

#9652 Add shadow to Battle::PopupDamageInfo
  src/fheroes2/battle/battle_interface.cpp
Labels: improvement, ui

#9597 Add feature to generate symmetric buttons
  files/lang/de.po
  files/lang/es.po
  files/lang/nb.po
  files/lang/ru.po
  files/lang/sk.po
  files/lang/sv.po
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
Labels: improvement, ui, translation, pixel-precision

#9655 Campaign: allow to raise the game difficulty during the campaign
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/campaign/campaign_savedata.h
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/system/save_format_version.h
Labels: improvement, campaign

#9663 Silence the CodeChecker false positives
  .github/workflows/codechecker.yml
  src/engine/serialize.cpp
Labels: bug, GitHub Actions

#9664 CMake (Windows SDL2) job: auto-update vcpkg to the latest version
  .github/workflows/cmake.yml
Labels: improvement, GitHub Actions

#9651 Update Russian translation
  files/lang/ru.po
Labels: improvement, translation

#9660 Fix broken tiles with mines
  src/fheroes2/campaign/campaign_savedata.cpp
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/system/save_format_version.h
Labels: bug, logic, crash

#9662 Add French virtual keyboard
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_language.cpp
Labels: improvement, ui, translation

#9671 vcpkg update: don't pull the feature branches
  .github/workflows/cmake.yml
Labels: improvement, GitHub Actions

#9643 Version 1.1.7
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9677 Modernize some parts of the interface event handling code
  src/fheroes2/gui/interface_events.cpp
Labels: improvement

#9668 Add defense penalty to moat building info and adjust wording
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/castle/buildinginfo.cpp
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/castle_building_info.cpp
Labels: improvement, ui

#9393 Implement scrollable text input
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_text.cpp
  src/fheroes2/gui/ui_text.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: improvement, ui

#9674 List item selection moves along with navigation keys
  src/fheroes2/gui/interface_list.h
Labels: improvement, ui

#9691 Fix close of the caller dialg when closing the Virtual keyboard dialog by a hotkey
  src/fheroes2/gui/ui_keyboard.cpp
Labels: bug, ui

#9692 Allow to close a dialog with a single OK or CANCEL button in a button group by OK and CANCEL hotkeys
  src/fheroes2/gui/ui_button.cpp
Labels: improvement, ui

#9694 If the hero was moved to the castle when loading the map, then train him in the Mage Guild
  src/fheroes2/castle/castle.cpp
  src/fheroes2/castle/mageguild.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/kingdom/kingdom.cpp
Labels: bug, logic

#9700 Fix gap between buttons in symmetric button dialog
  src/fheroes2/gui/ui_window.cpp
Labels: bug, ui, pixel-precision

#9666 Add shadow for Heroes Meeting dialog
  src/engine/image.cpp
  src/engine/image.h
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/heroes/heroes_meeting.cpp
Labels: improvement, ui

#9704 Cache the truncation symbol width ("...")
  src/fheroes2/gui/ui_text.cpp
Labels: improvement, ui

#9705 Add color name to Traveler Tent's popup message
  src/fheroes2/heroes/heroes_action.cpp
Labels: improvement, ui

#9690 Allow to use the hardware keyboard when virtual numpad is opened
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/game/game_hotkeys.cpp
  src/fheroes2/game/game_hotkeys.h
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_keyboard.h
Labels: improvement, ui

#9696 Fix the scroll bar behavior after visiting a castle
  src/fheroes2/game/game_startgame.cpp
Labels: bug, ui

#9708 Do not ask for additional confirmation if Auto Combat or Quick Combat have been started from the GUI dialog
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: improvement, ui

#9702 Add stat bonus values to Battle Garb of Anduran info
  src/fheroes2/resource/artifact_info.cpp
Labels: improvement, ui
