Repository ihhub/fheroes2, pull requests merged in 2025-05, with the labels that each got.

#9593 Update the Belarusian Translation
  files/lang/be.po
Labels: improvement, translation

#9765 End game immediately during AI turn if there are changes in game
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_hero_action.h
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/ai/ai_planner_kingdom.cpp
  src/fheroes2/game/game_startgame.cpp
Labels: improvement, logic

#9754 Update social sharing features of documentation site and self-host fonts
  docs/README.md
  docs/_layouts/default.html
  docs/_sass/_fonts.scss
  docs/_sass/_layout.scss
  docs/assets/css/style.scss
  docs/assets/fonts/Asul/Asul-Bold.ttf
  docs/assets/fonts/Asul/Asul-Regular.ttf
  docs/assets/fonts/Asul/OFL.txt
  docs/assets/fonts/Jacquard_24/Jacquard24-Regular.ttf
  docs/assets/fonts/Jacquard_24/OFL.txt
  docs/assets/fonts/Lancelot/Lancelot-Regular.ttf
  docs/assets/fonts/Lancelot/OFL.txt
  docs/assets/js/accessibility-manager.js
  docs/assets/js/code-copy-manager.js
  docs/assets/js/heading-copy-manager.js
  docs/assets/js/templates.js
  docs/assets/js/theme-manager.js
  docs/images/screenshots/screenshot_battle.png
  docs/images/screenshots/screenshot_castle.png
  docs/images/screenshots/screenshot_world_map.png
  sonar-project.properties
Labels: improvement, deployment, regression

#9763 Version 1.1.8
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9780 Windows CMake workflow: use $VCPKG_INSTALLATION_ROOT instead of the hardcoded path
  .github/workflows/cmake.yml
Labels: improvement, GitHub Actions

#9781 Add sections to differentiate website from the game engine
  README.md
  docs/README.md
Labels: bug, documentation

#9776 Remove SonarCloud badges from the main website page
  docs/README.md
Labels: improvement, documentation

#9771 Minor "battle_cell" optimizations
  src/fheroes2/battle/battle_cell.cpp
  src/fheroes2/battle/battle_cell.h
Labels: improvement

#9768 Make the scouting area consistent with the original game
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/game/game_static.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/maps/maps.cpp
  src/fheroes2/maps/maps.h
Labels: improvement, ui, logic

#9777 convert to woff2 to reduce jacquard font size
  docs/_sass/_fonts.scss
  docs/assets/fonts/Jacquard_24/Jacquard24-Regular.ttf
  docs/assets/fonts/Jacquard_24/Jacquard24-Regular.woff2
Labels: improvement, documentation

#9773 Some code clean: battle_troop, army_troop, speed
  src/fheroes2/ai/ai_battle_spell.cpp
  src/fheroes2/army/army_troop.cpp
  src/fheroes2/army/army_troop.h
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/kingdom/speed.cpp
  src/fheroes2/kingdom/speed.h
Labels: improvement

#9785 Android: optimize the asset extraction process
  android/app/build.gradle
  android/app/src/main/java/org/fheroes2/GameActivity.java
Labels: improvement, Android

#9783 Update of Ukrainian Translation
  files/lang/uk.po
Labels: improvement, translation

#9787 Allow to use Up and Down hotkeys to change the value in value input dialogs
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
Labels: improvement, ui

#9799 Optimize rendering and timers
  src/engine/localevent.cpp
  src/engine/render_processor.cpp
  src/engine/render_processor.h
  src/engine/timing.cpp
  src/engine/timing.h
  src/fheroes2/game/game.cpp
  src/fheroes2/game/game_delays.cpp
  src/fheroes2/game/game_delays.h
Labels: improvement, ui

#9798 Significantly speed up language switching operation
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/dialog/dialog_language_selection.cpp
  src/fheroes2/game/game_language.h
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_language.cpp
  src/fheroes2/gui/ui_language.h
Labels: improvement, ui, logic

#9801 Fix a minor typo in the localevent.h
  src/engine/localevent.h
Labels: improvement

#9779 Fix skip of render end of hero's move before interacting with action object
  src/fheroes2/heroes/heroes_action.cpp
Labels: bug, ui

#9784 Battlefield: make Disrupting Ray and Teleport spells animation closer to the original game
  src/fheroes2/battle/battle_action.cpp
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
Labels: bug, improvement, ui

#9809 Update hashes for Android & Windows dependency packages
  android/build.gradle
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#9802 Website Performance Optimization - sub 220ms load times
  README.md
  docs/README.md
  docs/_layouts/default.html
  docs/_sass/_fonts.scss
  docs/_sass/_layout.scss
  docs/assets/css/fonts.scss
  docs/assets/css/style.scss
  docs/assets/fonts/Asul/Asul-Bold.ttf
  docs/assets/fonts/Asul/Asul-Bold.woff2
  docs/assets/fonts/Asul/Asul-Regular.ttf
  docs/assets/fonts/Asul/Asul-Regular.woff2
  docs/assets/fonts/Jacquard_24/Jacquard24-Regular-latin-only.woff2
  docs/assets/fonts/Lancelot/Lancelot-Regular.ttf
  docs/assets/fonts/Lancelot/Lancelot-Regular.woff2
  docs/images/screenshots/screenshot_battle.png
  docs/images/screenshots/screenshot_battle.webp
  docs/images/screenshots/screenshot_castle.png
  docs/images/screenshots/screenshot_castle.webp
  docs/images/screenshots/screenshot_world_map.png
  docs/images/screenshots/screenshot_world_map.webp
Labels: improvement, documentation

#9808 Battlefield. Fix Bad Luck animation to be closer to the original game
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#9794 Battle Interface: drawing troop count after (moving) monster
  src/fheroes2/battle/battle_interface.cpp
Labels: bug, ui

#9811 Add Danish language to virtual keyboard
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_keyboard.cpp
Labels: improvement, ui, translation

#9820 Cache resource language calculations to improve the performance
  src/fheroes2/gui/ui_language.cpp
Labels: improvement, logic

#9766 Add ability to set owner color for capturable objects in Editor
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, high priority, editor

#9814 Add an optional field for map creator's notes
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
Labels: improvement, ui, editor

#9806 Implement the infrastructure for bundling FH2M maps
  .github/workflows/make.yml
  .github/workflows/msvc.yml
  CMakeLists.txt
  Makefile
  Makefile.vita
  VisualStudio/fheroes2/common.props
  android/app/build.gradle
  android/app/src/main/java/org/fheroes2/GameActivity.java
  maps/empty.fh2m
  script/windows/fheroes2.iss
  src/dist/Makefile.emscripten
Labels: improvement, deployment

#9826 Fix Capturable Objects related regression
  src/fheroes2/world/world.cpp
Labels: crash, regression

#9819 Do not allow units to cause zero damage in case of bad luck event
  src/engine/tools.h
  src/fheroes2/battle/battle_troop.cpp
Labels: bug, logic

#9804 Update the German translation
  files/lang/de.po
Labels: improvement, translation

#9824 Clean Editor-related code: remove the unused mine color property
  src/fheroes2/dialog/dialog_selectitems.cpp
  src/fheroes2/dialog/dialog_selectitems.h
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface_panel.cpp
  src/fheroes2/editor/editor_interface_panel.h
Labels: improvement

#9818 Add Play Online Feature to Website
  .github/workflows/make.yml
  .github/workflows/pages.yml
  .github/workflows/push.yml
  docs/deployments/WEB_DEPLOYMENT.md
Labels: improvement, Wasm

#9831 Fix Sonar Cloud "cpp:S3923" issue
  src/fheroes2/editor/editor_interface_panel.cpp
Labels: improvement

#9829 Fix some recently introduced code smells
  src/engine/tools.h
  src/fheroes2/world/world.cpp
Labels: improvement

#9830 Only run GitHub Pages workflow in the base repo
  .github/workflows/pages.yml
  .github/workflows/push.yml
Labels: bug, GitHub Actions

#9813 Add Greek translation
  files/lang/Makefile
  files/lang/gr.po
  src/engine/translations.cpp
  src/fheroes2/game/game_language.h
  src/fheroes2/gui/ui_font.cpp
  src/fheroes2/gui/ui_language.cpp
Labels: improvement, translation

#9834 Minor battlefield cell related code speed-up
  src/fheroes2/battle/battle_board.cpp
  src/fheroes2/battle/battle_board.h
Labels: improvement

#9833 Battlefield. Fix rendering of high obstacles
  src/fheroes2/battle/battle_interface.cpp
  src/fheroes2/battle/battle_interface.h
Labels: bug, ui

#9815 Render hero's "current / max" Spell Points in two lines if they don't fit in one line
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/heroes_indicator.h
Labels: bug, ui

#9836 Use the double-precision floating-point values for unit threat evaluation
  src/fheroes2/ai/ai_battle.cpp
  src/fheroes2/ai/ai_battle.h
  src/fheroes2/battle/battle_arena.cpp
  src/fheroes2/battle/battle_troop.cpp
  src/fheroes2/battle/battle_troop.h
Labels: bug, logic

#9838 AI: move the guardian spell cast logic from the AI planner to the anonymous namespace
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner.h
  src/fheroes2/ai/ai_planner_hero.cpp
Labels: improvement

#9837 Fix (restore) ASCII characters for French assets
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/gui/ui_font.cpp
Labels: bug, ui, original assets

#9778 Fix map center positioning when AI interacts with action object
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, ui, pixel-precision

#9842 Compilation fix
  src/fheroes2/ai/ai_hero_action.cpp
Labels: bug, regression, high priority

#9845 Editor: move terrain placing code to `Map_Format`
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_interface.h
  src/fheroes2/editor/editor_mainmenu.cpp
  src/fheroes2/editor/history_manager.cpp
  src/fheroes2/maps/map_format_helper.cpp
  src/fheroes2/maps/map_format_helper.h
  src/fheroes2/maps/map_format_info.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_tiles.cpp
  src/fheroes2/maps/maps_tiles.h
  src/fheroes2/maps/maps_tiles_helper.cpp
  src/fheroes2/maps/maps_tiles_helper.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, editor

#9849 Remove the unused method
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement

#9848 Add the Black Cat object
  files/data/resurrection.h2d
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/ai/ai_planner_hero.cpp
  src/fheroes2/dialog/dialog_quickinfo.cpp
  src/fheroes2/game/game_static.cpp
  src/fheroes2/h2d/h2d.cpp
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_indicator.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/mp2.cpp
  src/fheroes2/maps/mp2.h
Labels: new assets

#9857 MSVC workflow: migrate to the windows-2022 runner
  .github/workflows/msvc.yml
Labels: improvement, Windows, GitHub Actions
