Repository ihhub/fheroes2, pull requests merged in 2025-02, with the labels that each got.

#9516 MonthOfMonstersAction(): make the generator dependent not just on the map seed, but also on the current month
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
Labels: improvement, logic

#9517 Impose checkbox text width limit
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_ui_helper.cpp
  src/fheroes2/editor/editor_ui_helper.h
Labels: bug, ui, editor

#9521 Add script to extract resources from CD images
  script/homm2/extract_homm2_resources_from_cd_image.sh
Labels: improvement, script, deployment

#9422 Spanish translation update
  files/lang/es.po
Labels: improvement, translation

#9378 Update documentation for pixel artists
  docs/GRAPHICAL_ASSETS.md
Labels: improvement, documentation

#9530 Show total obelisk number while clicking on the corresponding Adventure Map object
  src/fheroes2/editor/editor_interface.cpp
Labels: improvement, ui, editor

#9533 Show a range of available values for an input value dialog
  src/fheroes2/gui/ui_dialog.cpp
Labels: improvement, ui

#9498 Increase maximum allowed map name length from the original 17 characters to 50
  src/fheroes2/dialog/dialog_gameinfo.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_map_specs_window.h
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/editor/editor_save_map_window.h
  src/fheroes2/game/game_scenarioinfo.cpp
Labels: improvement, ui, editor

#9505 Rework rendering of experience indicator
  src/fheroes2/heroes/heroes_indicator.cpp
Labels: improvement, ui

#9534 Extract resources from Gold CD CAB
  script/homm2/extract_homm2_resources_from_cd_image.sh
Labels: improvement, script

#9529 Show an appropriate icon for music and audio settings when they are off
  src/fheroes2/dialog/dialog_audio.cpp
Labels: improvement, ui

#9538 Swedish Translation Update (#25)
  files/lang/sv.po
Labels: improvement, translation

#9525 Rework button code
  src/engine/pal.cpp
  src/engine/pal.h
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/agg/icn.h
  src/fheroes2/castle/castle_well.cpp
  src/fheroes2/dialog/dialog_marketplace.cpp
  src/fheroes2/dialog/dialog_recruit.cpp
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/dialog/dialog_selectfile.cpp
  src/fheroes2/editor/editor_save_map_window.cpp
  src/fheroes2/game/game_loadgame.cpp
  src/fheroes2/game/game_newgame.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_keyboard.cpp
  src/fheroes2/gui/ui_window.cpp
  src/fheroes2/gui/ui_window.h
  src/fheroes2/kingdom/kingdom_overview.cpp
Labels: bug, improvement, ui, translation

#9514 Expand the functionality of the Adventure map event
  src/engine/image.h
  src/fheroes2/ai/ai_hero_action.cpp
  src/fheroes2/army/army_bar.cpp
  src/fheroes2/dialog/dialog.h
  src/fheroes2/dialog/dialog_box.cpp
  src/fheroes2/dialog/dialog_giftresources.cpp
  src/fheroes2/editor/editor_daily_event_spec_window.cpp
  src/fheroes2/editor/editor_event_details_window.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/editor/editor_sphinx_window.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/gui/ui_dialog.cpp
  src/fheroes2/gui/ui_dialog.h
  src/fheroes2/heroes/heroes.cpp
  src/fheroes2/heroes/heroes.h
  src/fheroes2/heroes/heroes_action.cpp
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/maps/map_format_info.h
  src/fheroes2/maps/maps_objects.cpp
  src/fheroes2/maps/maps_objects.h
  src/fheroes2/system/save_format_version.h
  src/fheroes2/world/world.cpp
  src/fheroes2/world/world.h
  src/fheroes2/world/world_loadmap.cpp
Labels: improvement, logic, editor

#9518 Check Loss conditions before Victory conditions
  src/fheroes2/game/game_over.cpp
Labels: improvement, logic

#9536 Replace "max" text with MIN and MAX buttons for integer input dialog
  src/fheroes2/dialog/dialog_selectcount.cpp
Labels: improvement, ui

#9512 Add return to main menu and play map buttons to the editor
  src/fheroes2/dialog/dialog_file.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/game/game_scenarioinfo.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_window.h
Labels: improvement, ui, high priority, editor

#9545 Fix marketplace resource type string replace
  src/fheroes2/dialog/dialog_giftresources.cpp
Labels: bug, ui

#9551 Invalid serialization for save files
  src/fheroes2/maps/maps_objects.cpp
Labels: bug, crash, regression, high priority

#9547 Czech translation update and improvements
  files/lang/cs.po
Labels: improvement, translation

#9556 Fix assertion for a maximum spell points
  src/fheroes2/heroes/heroes_dialog.cpp
Labels: logic, crash

#9557 Fix Editor buttons not being translated
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/editor/editor_interface.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
Labels: improvement, ui

#9562 Fix Ultimate Artifact being erased for any action done on a map
  src/fheroes2/editor/editor_interface.cpp
Labels: bug, logic, editor

#9563 Fix invalid undead army check for an empty army
  src/fheroes2/army/army.cpp
Labels: bug, logic, regression

#9567 Fix German original assets MIN button
  src/fheroes2/agg/agg_image.cpp
Labels: regression, translation

#9570 Version 1.1.6
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/game/game_credits.cpp
  src/fheroes2/system/version.h
  version.txt
  version_code.txt
Labels: improvement

#9573 Remove assertion for passability checks
  changelog.txt
  script/packaging/common/fheroes2.metainfo.xml
  src/fheroes2/maps/maps_tiles.cpp
Labels: logic, crash, high priority

#9453 WebAssembly: fix the mouse issues when toggling the vsync mode and switching to full screen mode
  .github/workflows/make.yml
  files/emscripten/index.html
  src/dist/Makefile.emscripten
  src/engine/image_tool.cpp
  src/engine/localevent.cpp
  src/engine/screen.cpp
Labels: improvement, Wasm

#9569 Fix Russian resources' max button and empty guild/well button
  src/fheroes2/agg/agg_image.cpp
Labels: improvement, ui, translation

#9574 Fix the operation of MIN/MAX buttons in various dialogs
  src/fheroes2/dialog/dialog_selectcount.cpp
  src/fheroes2/gui/skill_bar.cpp
  src/fheroes2/heroes/skill.cpp
  src/fheroes2/heroes/skill.h
Labels: bug, ui

#9576 Swedish Translation Update (#26)
  files/lang/sv.po
Labels: improvement, translation

#9565 Avoid stacking units when defending archers
  src/fheroes2/ai/ai_battle.cpp
  src/fheroes2/ai/ai_battle.h
Labels: improvement, AI

#9583 Use Adventure Map object animation information from a correct place
  src/fheroes2/maps/map_object_info.cpp
  src/fheroes2/maps/maps_tiles_render.cpp
Labels: improvement, ui

#9413 Add dynamic interface option
  src/fheroes2/dialog/dialog_interface_settings.cpp
  src/fheroes2/editor/editor_options.cpp
  src/fheroes2/game/game_campaign.cpp
  src/fheroes2/game/game_interface.cpp
  src/fheroes2/game/game_interface.h
  src/fheroes2/game/game_startgame.cpp
  src/fheroes2/gui/ui_option_item.cpp
  src/fheroes2/gui/ui_option_item.h
  src/fheroes2/gui/ui_tool.cpp
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/kingdom/race.cpp
  src/fheroes2/kingdom/race.h
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement, ui

#9587 Fix few SonarCloud code smells
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_option_item.cpp
  src/fheroes2/gui/ui_option_item.h
  src/fheroes2/gui/ui_tool.h
  src/fheroes2/heroes/heroes_dialog.cpp
  src/fheroes2/system/settings.cpp
  src/fheroes2/system/settings.h
Labels: improvement

#9584 Check the contents of the resurrection.h2d file for correctness
  src/fheroes2/h2d/h2d.cpp
Labels: improvement, logic

#9589 Update hashes for Android & Windows dependency packages
  script/android/install_packages.bat
  script/android/install_packages.sh
  script/windows/install_packages.bat
Labels: improvement, Windows, Android

#9588 Standardize translation related code
  src/fheroes2/agg/agg_image.cpp
  src/fheroes2/editor/editor_castle_details_window.cpp
  src/fheroes2/editor/editor_map_specs_window.cpp
  src/fheroes2/gui/ui_button.cpp
  src/fheroes2/gui/ui_button.h
  src/fheroes2/gui/ui_text.h
  src/fheroes2/monster/monster.cpp
  src/fheroes2/monster/monster_info.cpp
  src/fheroes2/monster/monster_info.h
  src/fheroes2/resource/artifact.cpp
  src/fheroes2/resource/artifact_info.cpp
  src/fheroes2/resource/artifact_info.h
Labels: improvement, ui, translation

#9594 Fix the logic of transferring artifacts after a battle
  src/fheroes2/battle/battle_main.cpp
Labels: bug, logic
